### ISSUE TITLE
RuntimeException: Unable to instantiate service

### ISSUE THREAD

**Issue by anlalalu** [vanilla-music/vanilla#1004]
1. Please take a moment to check if the same Bug has already been reported.
2. Please use our subreddit for general questions: https://www.reddit.com/r/vanillamusic/
3. Please provide all relevant information below.

**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About):1.0.84
- Android Version:4.4.4
- Phone vendor / model:emulator
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

###### Reproduction Steps
This crash is triggered by an automatic testing tool with this shell instruction:

adb shell am startservice ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.MirrorLinkMediaBrowserService

###### Stack Trace

E/AndroidRuntime(18248): FATAL EXCEPTION: main
E/AndroidRuntime(18248): Process: ch.blinkenlights.android.vanilla, PID: 18248
E/AndroidRuntime(18248): java.lang.RuntimeException: Unable to instantiate service ch.blinkenlights.android.vanilla.MirrorLinkMediaBrowserService: java.lang.ClassNotFoundException: Didn't find class "ch.blinkenlights.android.vanilla.MirrorLinkMediaBrowserService" on path: DexPathList[[zip file "/data/app/ch.blinkenlights.android.vanilla-1.apk", zip file "/data/app/ch.blinkenlights.android.vanilla-1.apk"],nativeLibraryDirectories=[/data/app-lib/ch.blinkenlights.android.vanilla-1, /data/app-lib/ch.blinkenlights.android.vanilla-1, /system/lib]]
E/AndroidRuntime(18248): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2556)
E/AndroidRuntime(18248): 	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
E/AndroidRuntime(18248): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime(18248): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18248): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(18248): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime(18248): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(18248): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(18248): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime(18248): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime(18248): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(18248): Caused by: java.lang.ClassNotFoundException: Didn't find class "ch.blinkenlights.android.vanilla.MirrorLinkMediaBrowserService" on path: DexPathList[[zip file "/data/app/ch.blinkenlights.android.vanilla-1.apk", zip file "/data/app/ch.blinkenlights.android.vanilla-1.apk"],nativeLibraryDirectories=[/data/app-lib/ch.blinkenlights.android.vanilla-1, /data/app-lib/ch.blinkenlights.android.vanilla-1, /system/lib]]
E/AndroidRuntime(18248): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(18248): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/AndroidRuntime(18248): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/AndroidRuntime(18248): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2553)
E/AndroidRuntime(18248): 	... 10 more

**Comment by adrian-bl** [comment]
As it says in the error: the class does not exist: we dont export the service in the Manifest.
