### ISSUE TITLE
Cannot empty the queue

### ISSUE THREAD

**Issue by madduck** [vanilla-music/vanilla#1006]
- Vanilla Music Version (Settings -> About): 1.0.84 Released Sep. 9 2019
- Android Version: 8.0
- Phone vendor / model: Galaxy S7 Edge
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
When I select "Empty Queue", the current items get removed, but immediately, two random entries are created.

Possibly related is that when I just play one song, when it's over, the player plays a random other title 
from my library. If I try to remove the second entry in the queue, a random one gets added in place.

## Screenshot / Video (If applicable)

https://scratch.madduck.net/sync__7__dcim-int__Video%20screenshots__SM-G935F_20200112151612.mp4

...

**Comment by adrian-bl** [comment]
You have random mode enabled (the dice icon on the right).

This mode keeps the queue populated with random songs.

Switching to a different mode will turn this behavior off.

**Comment by madduck** [comment]
I am so sorry, I totally missed that...
