### ISSUE TITLE
MPD support

### ISSUE THREAD

**Issue by swedneck** [vanilla-music/vanilla#1014]
I recently started using MPD on my devices, and seeing as the existing mpd clients for android lack a lot of vanilla's features, it would be amazing to have MPD support in vanilla music.

**Comment by lennyhans** [comment]
Maybe that could be a plugin like the tag editor

**Comment by adrian-bl** [comment]
Sorry, but i think this feature is out of scope for vanilla music:

We are a local music player and streaming remote music (or controlling media servers) isn't what the app is supposed to do.

**Comment by swedneck** [comment]
MPD can be used locally, in fact that's the only way i use it.
