### ISSUE TITLE
Remove DOS endlines from files 

### ISSUE THREAD

**Issue by licaon-kter** [vanilla-music/vanilla#1021]
...like [gradle.properties](https://github.com/vanilla-music/vanilla/blob/master/gradle/wrapper/gradle-wrapper.properties) (and others) so that F-Droid can build.

**Comment by adrian-bl** [comment]
Done in commit b68ca35af7f58a32e87decf368094da7c8a92ae1

Are there any others?
How did that break f-droid? The file hasn't been touched since 2018
