### ISSUE TITLE
Lyrics plugin kills m4a files

### ISSUE THREAD

**Issue by bege10** [vanilla-music/vanilla#1025]
- Vanilla Music Version (Settings -> About): 1.0.84
- Android Version: LineageOS for microG 16 (Android 9)
- Phone vendor / model: Samsung Galaxy S5 Plus (SM-G901F)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

Saving lyrics with the plugin makes m4a files unusable

## Steps to reproduce the issue

open m4a file, search for lyrics with plugin, save - file is not usable any more (vanishes completely in Vanilla, still displayed in other players but cannot be played any more.

## Screenshot / Video (If applicable)

...

**Comment by Kaned1as** [comment]
This was fixed by https://github.com/vanilla-music/vanilla-music-tag-editor/issues/34

**Comment by bege10** [comment]
I don't have Vanilla Music installed currently because I still set up a new phone. So I cannot test this but as this has been fixed several month ago I close this comment. Thank you.
