### ISSUE TITLE
[Feature Request] Support for WebP cover art

### ISSUE THREAD

**Issue by opusforlife2** [vanilla-music/vanilla#1044]
Would it be possible to add WebP to the list of supported cover art formats? Unless it is an Android limitation, in which case, feel free to close this.

**Comment by adrian-bl** [comment]
that should be fixed by b8e41ab4f46cc1d36c617b1b2d0f62452d285598

**Comment by opusforlife2** [comment]
Woohoo! Can't wait to try it out. Thank you. :)

**Comment by opusforlife2** [comment]
Tested this just now. Works! Thanks.
