### ISSUE TITLE
Vanilla do not play .ogg files

### ISSUE THREAD

**Issue by Npa972** [vanilla-music/vanilla#1046]
- Vanilla Music Version (Settings -> About): the last one
- Android Version: 6.0.1
- Phone vendor / model: samsung xcover 3
- Application was downloaded from (use `[x]`):
  - [* ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [* ] NA / Don't know.

## Description
ogg files are not playing
....

## Steps to reproduce the issue
play ogg file
...

## Screenshot / Video (If applicable)

...
Great app thank you

**Comment by andiandi13** [comment]
Vanilla plays what your phone model plays since it uses Android Framework.

I guess your phone doesn't play ogg files as well.

**Comment by Npa972** [comment]
I just redownload Vanilla to try again :
.ogg files do not play (ogg vorbis)
.oga files play (ogg vorbis too).
If i rename .ogg in .oga = not playing

For the moment i use Aimp (i'd prefer to use Vanilla) and all the format are playing on my phone ?
Thanks

**Comment by adrian-bl** [comment]
As andiandi13 pointed out, vanilla uses the android framework to play media.

There is unfortunately nothing we can do since this is a bug in the firmware you are using.
