### ISSUE TITLE
BUG - When taping on a song from the playlist window, only that single song is added to the queue instead of the whole playlist

### ISSUE THREAD

**Issue by nkosi23** [vanilla-music/vanilla#1050]
- Vanilla Music Version (Settings -> About): 1.0.85
- Android Version: 9
- Phone vendor / model: Samsung Galaxy S9
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
I am new to Vanilla Music and this is the first time I see a music player having this behavior, this is a real nuisance. When one has a playlist, it is common to want to listen to a particular song first (morning mood etc...), so no matter what the music player is, the universal expected behavior is that when clicking/taping on a song from a playlist page/context, the song is played, and the whole playlist is added to the queue (or the song is played and the existing queue is entirely replaced by the playlist in some players - instead of appending to it).

Instead of this, the behavior of Vanilla Music is that the song is played, and then the music stops because the queue only contains that single song. If one goes through the playlist window to tap on a song, one can reasonably assume that the person wants to add the playlist to his queue by default. Especially since there is a context menu allowing the person to add the single song to the queue. This is a bug.

Currently, the only way to play a whole playlist is to hold the playlist name in the playlists tab, and select the Play option in the context menu. Therefore if one wants to play a playlist by starting by a particular song, he has to play the song first and then go one screen back and hold the playlist name to Add it to the queue from the context menu (and the song currently playing will have a duplicate in the queue). Alternatively the user has to play the playlist, another song will start playing and then the user will have to go to the Queue window and tap on the song he actually wants to listen. 

This is not ideal but more importantly this is very unintuitive and gets in the way. And this is frustrating behavior, especially for a new user since this is a very common use case.

I would not say this is a feature request, this is a bug because this is clearly not what one would expect from the music player.

## Steps to reproduce the issue

- Create a playlist containing 2 or more songs
- Go to the playlist tab
- Enter the playlist
- Tap on a song
- Only that single song is added to the queue and not the whole playlist

**Comment by grubelic** [comment]
Does choosing the option _Settings/Library Screen/Default playlist action/Play all_ fix your issue?

**Comment by nkosi23** [comment]
Yes this fixes it thank you, would it be possible to make it the default behavior? Most people will never imagine that such a setting exists (and this is the behavior that people usually expect)

**Comment by adrian-bl** [comment]
That is indeed confusing: changed the default in commit https://github.com/vanilla-music/vanilla/commit/8963ed500b16deaea1aed8b97ab8167282dbfe84
