### ISSUE TITLE
Loop latency

### ISSUE THREAD

**Issue by fynngodau** [vanilla-music/vanilla#1055]
- Vanilla Music Version (Settings -> About): 1.0.85

- Android Version: 9

- Phone vendor / model: huawei-kiwi

- Application was downloaded from (use `[x]`):

- [x] Play Store

- [ ] F-Droid

- [ ] Other (Nightly Build)

- Did this work in a previous version?

- [ ] Yes

- [ ] No

- [x] NA / Don't know.

## Description

When looping a song with "Repeat current track", there is some latency between two loops.

## Steps to reproduce the issue

* Download a perfectly looping file.
* Play it with Vanilla.
* Set to "Repeat". The file loops perfectly.
* Set to "Repeat current track". The file does not loop perfectly anymore.

**Comment by adrian-bl** [comment]
that's most likely an issue with your phone not supporting gapless or playing a format (like MP3) which doesn't support gapless.

**Comment by fynngodau** [comment]
I'd argue it is neither an issue with the file nor with my phone, as it does work as expected when set to "Repeat" (as opposed to "Repeat current track").
