### ISSUE TITLE
Vanilla music apps runs as background service, gets terminated, should run in forground

### ISSUE THREAD

**Issue by eggsgent** [vanilla-music/vanilla#1056]
- Vanilla Music Version (Settings -> About):
- Android Version: 10
- Phone vendor / model: Samsung Galaxy S9 SM-G960F 
- Application was downloaded from (use `[x]`):
  - [x ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x ] No
  - [ ] NA / Don't know.

## Description

quoting Bluetooth earbuds developer: "Under Android policy, services running are not available in the background. For service execution for playback, the status of the app should be foreground. If you look at the attached log, the status of the app is background, and in idle state, the background executed service is terminated.

21771 08-25 15:15:43.171  1000  4971  5379 I MediaFocusControl: requestAudioFocus() from uid/pid 10202/26948 clientId=android.media.AudioManager@1ab728dch.blinkenlights.android.vanilla.PlaybackService@50ebad2 callingPack=ch.blinkenlights.android.vanilla req=1 flags=0x0 sdk=29
121818 08-25 15:15:43.249 u0_a3  5360  5360 D FaceWidgetMusicController_LOCK: onPlaybackStateChanged() /   playing  -->  playing
129847 08-25 15:16:41.864  1000  4971  4971 D MediaSessionStack: updateMediaButtonSessionIfNeeded, callers=com.android.server.media.MediaSessionService.lambda$onStart$0$MediaSessionService:208 com.android.server.media.-$$Lambda$MediaSessionService$za_9dlUSlnaiZw6eCdPVEZq0XLw.onAudioPlayerActiveStateChanged:2 
......
158577 08-25 15:16:41.629  1000  4971  5042 I am_uid_idle: 10202
158578 08-25 15:16:41.632  1000  4971  5042 I am_stop_idle_service: [10202,ch.blinkenlights.android.vanilla/.PlaybackService]
129843 08-25 15:16:41.632  1000  4971  5042 W ActivityManager: Stopping service due to app idle: u0a202 -14m47s443ms ch.blinkenlights.android.vanilla/.PlaybackService
129983 08-25 15:16:41.943  1000  4971  7221 D MediaSessionService: Destroying ch.blinkenlights.android.vanilla/Vanilla Music (userId=0)
129984 08-25 15:16:41.944  1000  4971  7221 D MediaSessionService: Media button session is changed to null

## Steps to reproduce the issue

1. Start music playback, when testing i was using a pair of Bluetooth earbuds
2. Put phone in pocket and don't touch it for a while

Expected result: music to keep playing till the end of album / playlist / dir
Actual result: often music stops playing in the middle of a song, app process is being terminated

**Comment by adrian-bl** [comment]
I'm pretty sure we run as foreground service, see:

https://github.com/vanilla-music/vanilla/blob/master/app/src/main/java/ch/blinkenlights/android/vanilla/PlaybackService.java#L1050

Who is this 'bluetooth earbuds developer' and where in the log does it show that we run in the background?

**Comment by eggsgent** [comment]
According to the engineer analysing the terminal logs, it is an app problem, not phone nor earbuds connection problem.
Happens only with the Vanilla music app, no other apps that I have tested, including Foobar2000, Black player, Samsung Music.

This issue is not resolved.

**Comment by thomassross** [comment]
@adrian-bl I am seeing the same issue recently. When it happens (let's say the phone is off), I unlock my phone, launch Vanilla Music from my homescreen, and it crashes initially, with the following logs:
```
10-25 19:22:05.396  6734  6734 E AndroidRuntime: FATAL EXCEPTION: main
10-25 19:22:05.396  6734  6734 E AndroidRuntime: Process: ch.blinkenlights.android.vanilla, PID: 6734
10-25 19:22:05.396  6734  6734 E AndroidRuntime: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ch.blinkenlights.android.vanilla/.PlaybackService }: app is in background uid UidRecord{3d90370 u0a214 CAC  bg:+1m53s172ms idle change:cached procs:1 proclist:6734, seq(0,0,0)}
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1688)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1633)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at ch.blinkenlights.android.vanilla.PlaybackActivity.onStart(PlaybackActivity.java:127)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at ch.blinkenlights.android.vanilla.LibraryActivity.onStart(LibraryActivity.java:211)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7980)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3655)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:183)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:132)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2270)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8125)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
10-25 19:22:05.396  6734  6734 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

I'm using Vanilla 1.0.85, from F-Droid, running Android 10 on a Samsung S9+ (SM-G965W).
