### ISSUE TITLE
 Replaygain tags case handling ?

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#1075]
[This is not an issue but a simple question]

Reading through [loudgain](https://github.com/Moonbase59/loudgain)'s documentation, I came across this remark : https://github.com/Moonbase59/loudgain#uppercase-or-lowercase-replaygain_-tags

> File bug reports for any player you use that doesn’t handle ReplayGain tags at all or in a case-sensitive manner!

And this got me thinking : how does Vanilla Music handle Replaygain tags (for the concerned formats, namely mp3) ? Upper-case (as it should be) ? Lower case (as it's often encountered) ? Or case-insensitively ?

**Comment by adrian-bl** [comment]
I think we should be fine:

Vanillas tag parser calls `.toUpperCase()` on keys before putting them into the hashmap.

Example for the vorbiscomment (ogg/flac) parser:
https://github.com/adrian-bl/bastp/blob/master/ch/blinkenlights/bastp/Common.java#L111

We are a more strict on ID3v2 frames (T....) which must match the case:
https://github.com/adrian-bl/bastp/blob/master/ch/blinkenlights/bastp/ID3v2File.java#L204

..but we do handle freestyle (TXXX) fields case insenstivie:
https://github.com/adrian-bl/bastp/blob/master/ch/blinkenlights/bastp/ID3v2File.java#L214

**Comment by breversa** [comment]
Alright then, I'll trust your word. Thank you !
