### ISSUE TITLE
Android 11 - Unable to navigate into SD card in Media library

### ISSUE THREAD

**Issue by SavkovAlexander** [vanilla-music/vanilla#1077]
- Vanilla Music Version (Settings -> About): 1.0.91 (00dbdc7156ba81e296d3d070f9266af510619e72)
- Android Version: Android 11 
- Phone vendor / model: Android Emulator (Pixel 4 API 30), Mi A2 Lite with LineageOS 18.1
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [X] NA / Don't know.

## Description
'SD card' folder isn't displayed in folders dialog in the Edit mode of the Media library.
It is impossible to navigate inside to add folders from SD card.

## Steps to reproduce the issue
Preconditions: Android 11 with SD card, added as a Portable storage

1. Install Vanilla and give it "Files and media" permission
2. Open "Settings" -> "Media Library"
3. In indexed directories both Vanilla app directories - on internal storage and on the SD card - are marked as "Included"
4. Open Edit menu
5. Navigate upwards the folders tree to mark some folder on SD card as "Included"

Actual result:
Folders from path "/storage" and above are empty. It is impossible to move inside SD card folders.

Expected result:
SD card folder should be shown like in Android 10.

Some Tech info:
Folder list is empty because when variable 'path' equals "/storage" the call of path.listFiles() returns null in FolderPickerAdapter - refresh()
Same situation when Files tab is opened - 'readdir = file.listFiles(mFileFilter)' and it is null in FileSystemAdapter - query()

## Screenshot / Video (If applicable)
![1 Storage settings](https://user-images.githubusercontent.com/25170383/111041281-25b00c80-8440-11eb-9546-53b82c644b25.png)
![2 Permitions](https://user-images.githubusercontent.com/25170383/111041285-2a74c080-8440-11eb-8389-f01a7635c95a.png)
![3 Media library](https://user-images.githubusercontent.com/25170383/111041288-306aa180-8440-11eb-9cc5-291619b41290.png)
![4.1 File system navigation](https://user-images.githubusercontent.com/25170383/111041295-41b3ae00-8440-11eb-918c-abf3ab8a7291.png)
![4.2 File system navigation](https://user-images.githubusercontent.com/25170383/111041300-4c6e4300-8440-11eb-9997-bb3fd82f3223.png)
![4.3 File system navigation](https://user-images.githubusercontent.com/25170383/111041303-53955100-8440-11eb-9db0-013e6dd2db9d.png)

**Comment by Ammako** [comment]
Correct me if I'm wrong, but  I'm thinking it may be necessary to add `android.permission.MANAGE_EXTERNAL_STORAGE`, and perhaps use the `ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION` intent to let users grant access to manage all files. Neither one of these are in use currently.

`READ_EXTERNAL_STORAGE` and `WRITE_EXTERNAL_STORAGE` are cool and all, but with Android 11 scoped storage I'm not sure that's enough anymore.

https://developer.android.com/training/data-storage/manage-all-files#all-files-access

**Comment by adrian-bl** [comment]
Android 11 allows direct access to media files, which is all we need:
https://developer.android.com/about/versions/11/privacy/storage#media-direct-file-native

The problem here is that android doesn't (and never did since 5.x) allow to list directories in / and /storage


This should be fixed in https://github.com/vanilla-music/vanilla/commit/6de0d0626234ae87c3489c38eac1178cd13747b4 which simulates the existence of the reported external storage directories.
