### ISSUE TITLE
Mp3 songs stop playing after 1 min andriod 11

### ISSUE THREAD

**Issue by snostormjp** [vanilla-music/vanilla#1079]
- Vanilla Music Version (Settings -> About):
- Android Version:
- Phone vendor / model:
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description
Playing any song mp3 format on Samsung s20 ultra android 11 , song stops playing after about 1 min.
....

## Steps to reproduce the issue
Alys with current f driod on android 11 with s20 ultra. 
...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
Do you have any logs?

I'm pretty sure that's an issue with your ROM. Maybe try disabling battery optimizations?

**Comment by adrian-bl** [comment]
closing due to lack of reply
