### ISSUE TITLE
Disabling 'Show artwork on lockscreen' doesn't do anything

### ISSUE THREAD

**Issue by neodyne** [vanilla-music/vanilla#1081]
- Vanilla Music Version: 1.0.91
- Android Version: LineageOS 16.0
- Phone vendor / model: Xiaomi Redmi 5A
- Application was downloaded from:
  - [x] F-Droid
- Did this work in a previous version?
  - [X] Yes ≤1.0.90
## Description

Unticking `Settings > Cover art > Show artwork on lockscreen` results in the same behavior as if it was ticked (visualisation and cover art if applicable is shown on lockscreen). Wiping application data / reinstalling has no effect. This is a regression in the latest version, since it works both in 1.0.90 and 1.0.85 from F-Droid (previous available versions).

## Steps to reproduce the issue

1. untick `Settings > Cover art > Show artwork on lockscreen`
2. play a song, lock the device
2.  Instead of a plain notification on lockscreen, background cover art and visualisation is shown as well.

**Comment by adrian-bl** [comment]
Good catch: this broke during the migration to the new media session api.

Commit 4ac3bd6f17ad3d5e6b9e8dc7c541d221bfdb15f2 should fix the issue.
