### ISSUE TITLE
Plugin button no longer showing in playback screen

### ISSUE THREAD

**Issue by yekteniya** [vanilla-music/vanilla#1083]
- Vanilla Music Version (Settings -> About): 1.0.91
- Android Version: 11
- Phone vendor / model: Xiaomi Mi9T
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes (1.0.90)
  - [ ] No
  - [ ] NA / Don't know.

## Description
Plugin icon is no longer showing in the playback screen after updating the player to v1.0.91 from version v1.0.90.
Versions of the plugins being used are the latest versions on F-Droid (Tag Editor v1.4.11 and Lyrics Search v.1.3.3)

## Steps to reproduce the issue
Update from v.1.0.90 to v1.0.91

## Screenshot / Video (If applicable)
v1.0.90
![Screenshot_20210405-231743_Trebuchet_1](https://user-images.githubusercontent.com/52610846/113628505-46e1d280-9665-11eb-82c7-46e3cbbca670.png)
v1.0.91
![Screenshot_20210405-231438_Trebuchet_1](https://user-images.githubusercontent.com/52610846/113628485-40535b00-9665-11eb-8b57-629ddab17317.png)

**Comment by adrian-bl** [comment]
Thanks for reporting this: looks like API 30 now requires us to declare what (kind of) packages we are going to query.

11200eed8b955547ac9a39c41c7a7d3aeef0dce0 should fix the issue
