### ISSUE TITLE
Issues with playing .wav files from player

### ISSUE THREAD

**Issue by Xym2JZ** [vanilla-music/vanilla#1085]
.wav files aren't opening when tapped on the files directory in player, instead it will play the very next non wav format file. But wav files would play if forced open by long pressing on the song and selecting play from the menu, but still the playback screen won't show any info or thumbnail of the track being played. 'Play all' option aren't working for wav files too.

Love the player so much. Hope the issues will be rectified by the devs.

**Comment by adrian-bl** [comment]
Closing as a duplciate of issue #1052

**Comment by Xym2JZ** [comment]
Oh already reported. Ok.
