### ISSUE TITLE
Notification disappears after a while if paused

### ISSUE THREAD

**Issue by opusforlife2** [vanilla-music/vanilla#1089]
- Vanilla Music Version (Settings -> About): 1.1.0 (used to happen on previous versions as well)
- Android Version: LOS 17.1 (used to happen on 16 as well)
- Phone vendor / model: Xiaomi Mi 5
- Application was downloaded from (use `[x]`):
  - [x] F-Droid
- Did this work in a previous version?
  - [x] No

## Description

This does not happen to Poweramp, or Newpipe, for example. The notifications stay paused where they are, even hours later.

## Steps to reproduce the issue

Pause a song from the notification. Wait for some time. The notification will vanish.

No need to use other apps or anything. Just need to wait.

**Comment by opusforlife2** [comment]
@adrian-bl This might even be the cause of #1086.

**Comment by aldogithuber** [comment]
There's a option in the settings to solve this issue: Go to the notification tab and enable persistent notification.

**Comment by opusforlife2** [comment]
@aldogithuber Thanks! I'll try it out.

**Comment by opusforlife2** [comment]
Well, even after enabling the option, the notification does still disappear sometimes, but that's probably because of RAM ejection. It doesn't seem time based anymore. Thanks!
