### ISSUE TITLE
composer tag support

### ISSUE THREAD

**Issue by damian101** [vanilla-music/vanilla#1108]
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: 9
- Phone vendor / model:
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

I listen to a lot of classical music, the composer there is more important than performer, and the composer is often only listed under the composer tag.
If I search for a composer I want their music to come up, which is only possible if the composer tag is scanned and indexed alongside the other tags.

**Comment by adrian-bl** [comment]
We already support the Composer tag, but it's not visible by default.

You can enable it in Settings -> Library View -> Tabs
