### ISSUE TITLE
First seconds of a song are cut off when using a bluetooth speaker

### ISSUE THREAD

**Issue by starfishmaster** [vanilla-music/vanilla#1112]
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: Android 11 (LineageOS 18.1) as well as Android 10 (stock ROM)
- Phone vendor / model: Redmi Note 7 (but also previously on a Moto G6 Plus, so the issue seems pretty universal)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

When starting playback on a bluetooth speaker (e.g. my UE Megaboom 3), the first few seconds of audio are silent. This doesn't happen with each song, but only in the first few seconds of the first song on which playback is started (also happens if playback is started in the middle of a song).

## Steps to reproduce the issue

See description

## Suggestion to fix

Perhaps include an option in the settings to simply play a short silent audio clip each time playback is started? This seems like a quick and simple fix; I'd implement it myself but I'm terrible at Java :)

**Comment by adrian-bl** [comment]
I can not reproduce this (using bluetooth quite often with different devices), this smells like a device specific bug, so it's more of a firmware issue

**Comment by starfishmaster** [comment]
The strange thing is that this doesn't actually occur in other apps, so maybe it's just a problem that crops up for certain speakers. I unfortunately don't know what Vanilla Music does differently from other music players.

I understand that you have much more important things to do than to fix this apparently speaker-specific issue, but could you instead maybe give me a basic outline on how I could fix this myself using my original suggestion? Like I said, I'm not very good at Java, but with some guidance I could hopefully make the app play a second of silent audio at the start of every song. I really love Vanilla because of its simplicity, customizability and design, so it's pretty important to me that this small quality of life issue gets eliminated.
