### ISSUE TITLE
[Feature request] Option to disable autoscan

### ISSUE THREAD

**Issue by itsmusictomyears** [vanilla-music/vanilla#1115]
Currently, when starting Vanilla after booting the device, the music library is automatically scanned for new, modified and removed files. This works quickly for small libraries, but for really large libraries (in my case, 30,000+ songs) it naturally takes some time and in many cases needlessly drains the battery. On devices with a small battery and a large music library that are meant to be turned off when not in use, such as many Android-based DAPs, this does lead to a noticeable decrease in overall battery life.

Please consider implementing an option to disable this autoscan and only scan the library when manually selected.

**Comment by andiandi13** [comment]
Linked to #947 I guess.
If you remove your SD card when the phone is turned on, Vanilla will flush it's library and even worst than this, delete all entries from your playlists

That feature is a must have imo.

**Comment by itsmusictomyears** [comment]
Thank you, I didn't find that issue, this can be closed as a duplicate of that.
