### ISSUE TITLE
x tracks playing message

### ISSUE THREAD

**Issue by yephny** [vanilla-music/vanilla#1118]
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: 10
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

When you play a song, a message saying "x number of tracks playing" pops up. This is unnecessary and an annoyance.

## Steps to reproduce the issue

Play a track.

**Comment by adrian-bl** [comment]
Sorry, but i'd like to keep things the way the are in this regard.
