### ISSUE TITLE
Quick play/pause and previous/next song buttons

### ISSUE THREAD

**Issue by yephny** [vanilla-music/vanilla#1119]
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: 10
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

When you play a track, there is no quick controls that you can use to play/pause or skip to previous/next track on the bottom bar. You either have to pull down and use the notification or open the now playing screen.

## Steps to reproduce the issue

Play a track

**Comment by adrian-bl** [comment]
You can 'drag up' the bottom bar (to show the queue), doesn't that work for you?

**Comment by yephny** [comment]
@adrian-bl It does but you cannot browse your music archive if you have to be on the queue screen.

**Comment by adrian-bl** [comment]
You can drag the bottom bar up just enough to have the controls show, while still being able to browse the library

**Comment by yephny** [comment]
Never noticed that, thanks!
