### ISSUE TITLE
standard music player app

### ISSUE THREAD

**Issue by sgratzl** [vanilla-music/vanilla#112]
I would love to set Vanilla Music as the standard music player app. 

i.e. when currently opening a mp3 Vanilla Music doesn't show up as a possible player within the open with dialog.

**Comment by adrian-bl** [comment]
Fixed via https://github.com/vanilla-music/vanilla/commit/c8bc3705e3f01bf28c5255316b1f635307655093

We do now support and accept the content:// scheme
