### ISSUE TITLE
"go back" should go to the beginning of the same track, even when paused

### ISSUE THREAD

**Issue by ZappelMax** [vanilla-music/vanilla#1121]
When a song is playing and I press "go back" then it jumps to the beginning of the same song. Fine.
When a song is paused and I press "go back", it jumps to the *previous* track. 
I'd prefer it if it also jumped to the beginning of the *same* track.
(And if i really wanted to go to the previous track, I'd then have to press "go back" again.)

**Comment by adrian-bl** [comment]
Agreed, that's annoying. Fixed via db6e8fb74ca74bc0a25224ad97fb5fe04de399a5
