### ISSUE TITLE
.opus tracks can't be queued up or playlisted

### ISSUE THREAD

**Issue by Cwpute** [vanilla-music/vanilla#1129]
- Vanilla Music Version (Settings -> About): 1.1.0<apeil 11 2021
- Android Version: 8.1.0
- Phone vendor / model: Huawei DRA-L21
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

Tracks encoded as .opus -although they can be played by the app one by one- cannot be queud up neither playlisted, or more broadly perhaps, are not recognized as manageable songs by the app.

## Steps to reproduce the issue

Have a handful of .opus tracks in a directory (2 is sufficient). Select one track: it plays normally. Select either "Play all" in the directory, or "Queue all" or "Add all to playlist" : the app says "0 songs added to the playlist/queue".

## Screenshot / Video (If applicable)

Not necessary.

**Comment by adrian-bl** [comment]
Did you try to do a full scan from the settings menu?

**Comment by Cwpute** [comment]
The full scan doesn't work either.
I've dug a lil'bit more and it seems this is a hardware problem, by which my smartphone doesn't recognize the .opus format. It lacks a driver or something, i'm not very tech-savvy in that regard.

I can still play my music by changing the extention to .ogg, which is recognized by my device and uses the same encoding process as .opus

So i guess this issue can be closed ? unless something can be done software-wise to read .opus files as .ogg and play them as such
