### ISSUE TITLE
Queue cannot be emptied - random tracks spontaneously appear

### ISSUE THREAD

**Issue by VA1DER** [vanilla-music/vanilla#1133]
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: 12 (lineage os)
- Phone vendor / model: Samsung Tab A7 SM-T500
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [X] NA / Don't know.

## Description

The queue always has at least two entries.  If one is deleted, a random track appears. If Empty Queue is selected, two more random tracks appear. 

## Steps to reproduce the issue

Delete a queue entry.

**Comment by adrian-bl** [comment]
That's because you have random mode enabled (dice icon on the right side in the playback view): Vanilla will then automatically always fill the queue with new entries.
