### ISSUE TITLE
Disabling shuffle doesn't restore song order

### ISSUE THREAD

**Issue by ilmagico** [vanilla-music/vanilla#114]
Enabling shuffle correctly shuffles all songs in the queue, but disabling it leaves them in the shuffled order.
Steps to reproduce:
 1. Have a collection of songs with many different albums (see below) 
 2. Make sure shuffle is disabled
 3. Go to "songs" tab and press "play all"
  * Look at the queue: should show all songs in the expected order
 4. Click on shuffle icon (enable shuffle)
  * Look at the queue: should show random order
 5. Click on shuffle icon again (shuffle by album)
  * Look at the queue: should show albums in random order
 6. Click on shuffle again (icon looks like shuffle is disabled)
  * Look at the queue: SHOULD show original order, but instead, still shows album shuffle order.

I had a look at the code, in SongTimeline.java, when shuffle is enabled, the original order of the songs is replaced with the shuffled order, and the original order is permanently lost.
Unfortunately, this is not as easy as remembering the original order and restoring it, because all other methods that manipulate the timeline must now update the original order when they manipulate the shuffled songs.

**Comment by adrian-bl** [comment]
Closing this old bug. (expected behavior)
