### ISSUE TITLE
Compatibility issue when calling method

### ISSUE THREAD

**Issue by PSDroid2022** [vanilla-music/vanilla#1143]
We confirm a compatibility issue which might threaten the robustness of your app and give a detailed suggestion for you.

In ''ch.blinkenlights.android.vanilla.ScheduledLibraryUpdate", you invoke the API "<android.app.job.JobParameters: int getJobId()>"  in "onStartJob" method as shown in following. But actually, this API is introduced in API level 21(
https://developer.android.google.cn/reference/kotlin/android/app/job/JobParameters?hl=en#getJobId()).
```java
 @Override
	public boolean onStartJob(JobParameters params) {
		if (params.getJobId() != JOB_ID_UPDATE)
			return false; // orphaned job, do not start

		final boolean fullScan = (Math.random() > 0.7);

		mJobParams = params;
		MediaLibrary.registerLibraryObserver(mObserver);
		MediaLibrary.startLibraryScan(this, fullScan, false);

		return true;
	}
``` 
So when the app try to invoke this API on devices after API level 16~19, your app will run with an unpredictable results. So we suggest you add an "if(SDK_INT >=21)" to fix this potential issue. 

## Android device

 - Device: [e.g. Emulator]
 - OS: [e.g. API 16~19]
 - vanilla Version: [1.10]

**Comment by adrian-bl** [comment]
If you used a code analyzer, then the thing is flawed:

This code was never executed on devices with an sdk level < 21:

https://github.com/vanilla-music/vanilla/blob/7c0fdf09574a65a405be50b5ddeba251d89a42a7/app/src/main/java/ch/blinkenlights/android/vanilla/PlaybackService.java#L531
