### ISSUE TITLE
Vanilla stops seeing audio files (Android 12)

### ISSUE THREAD

**Issue by opusforlife2** [vanilla-music/vanilla#1146]
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: 12
- Application was downloaded from (use `[x]`):
  - [x] F-Droid
- Did this work in a previous version?
  - [x] Yes. It even works in the current version when used on Android 10. The problem seems to have arisen in Android 12 (or 11, but I don't have such a device).

## Description

Vanilla periodically updates its music library by scanning folders. But on Android 12, if there is a `.nomedia` or even just a `nomedia` file in a folder, Vanilla ignores it. This means that even if a folder was previously added to Vanilla's library, Vanilla will eventually try to scan it again and go "nope, no music files here".

This behaviour is different from Android 10. There, Vanilla successfully scans the folder even with the presence of a `nomedia` file. Then, after the library has been built, renaming the file to `.nomedia` has absolutely no effect on Vanilla's library, no matter how much time passes. I can use that file to prevent gallery apps from picking up album covers from my music folders.

## Steps to reproduce the issue

1. Put music in some folder. Let Vanilla scan it and expand its library.
2. Place a `.nomedia` file in that folder so that gallery apps ignore it.
3. At some point in the day, Vanilla will perform a scan on its own and then stop being able to see or scan files in that folder.

**Comment by MrHaplus** [comment]
It just fixed itself when I did a fresh reinstall.

**Comment by opusforlife2** [comment]
If you delete the `.nomedia` file and restart the device, it correctly scans all folders once again. It's not an unrecoverable bug.

**Comment by adrian-bl** [comment]
Vanilla always ignored folders with a `.nomedia` file but never cared about a `nomedia` file.

If this worked in the past as described, then its a change in Android itself.


There are multiple ways to exclude covers from gallery apps:

You can enable the 'shadow cover path' feature and store all your covers in `/Music/.vanilla/`: Vanilla will then read cover data from there even if a `.nomedia` file is present.

Another way is to add `.nomedia` to the music folder itself and manually add a subfolder to the scanned paths.
