### ISSUE TITLE
Crash when open play store fails (to install "Headphone detector")

### ISSUE THREAD

**Issue by Terrible-Tornado** [vanilla-music/vanilla#1147]
- Vanilla Music Version (Settings -> About):
- Android Version: 9.0
- Phone vendor / model: Google Pixel 2
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
The app crashes when it tries to open play store and fails.

## Steps to reproduce the issue
1. Open Settings - Audio
2. Click "Play when plugged"
3. Then the app would ask you to open play store, click "OK"
4. If it fails to open play store, for example, you don't have play store in your phone, it would crash

## Screenshot / Video (If applicable)
https://user-images.githubusercontent.com/119578731/206689931-b7ef915f-f137-469f-a069-1602833a26cd.mp4

**Comment by adrian-bl** [comment]
Oh, true: Fixed via ea13b1653dcff5bfdf4cca248286fa1a8b4eb798

Thanks for the report!
