### ISSUE TITLE
Remote control response doesn't always work

### ISSUE THREAD

**Issue by sanctimoniousape** [vanilla-music/vanilla#1155]
- Vanilla Music Version (Settings -> About): 1.2.2
- Android Version: 11
- Phone vendor / model: OnePlus 7 Pro
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

Player seems to stop receiving remote commands after certain actions like activating Google Assistant via wired headphones long-press.  Not an Android programmer, but guessing app doesn't fully/properly register itself to receive these events, or perhaps disassociates itself too readily?

## Steps to reproduce the issue

Play. Switch away from V.M. (hah) player, or lock device. Long press action button on wired headphones until Google Assistant tells you the time.  Play stopped & no longer responds to remote controls.

I should mention this is not just a wired control issue.  My device allows "drawing" various symbols on the touchscreen while the screen is off to emulate a Bluetooth remote (I believe), and those don't work after activating the G.A. either.

**Comment by sanctimoniousape** [comment]
I should mention this is not just a wired control issue.  My device allows "drawing" various symbols on the touchscreen while the screen is off to emulate a Bluetooth remote (I believe).

**Comment by adrian-bl** [comment]
Unfortunately, i doubt there is anything i can do since the device firmware controls whether or not to forward such events. (and to which app)

**Comment by sanctimoniousape** [comment]
I'm not an Android programmer. Are you able to point me towards a method to see how the OS is interpreting and handling the input?  It seems odd that VM is the only player app I have this issue with, but I also admittedly don't use VM the same way (I have it dedicated to play my sleep music playlist for simplicity when I'm tired).  If you don't, that's cool - I appreciate you taking the time anyway.
