### ISSUE TITLE
Track No. ≥10 ordered incorrectly

### ISSUE THREAD

**Issue by anaskaejdar** [vanilla-music/vanilla#1156]
- Vanilla Music Version (Settings -> About): 1.2.0 Released 17. Dec. 2022
- Android Version: 13
- Phone vendor / model: Samsung GS22U
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

....

## Steps to reproduce the issue

If a track has a double-digit track number, it's placed between single-digit ones rather than after them. For example, track 10 comes immediately after track 1.

## Screenshot / Video (If applicable)
![Screenshot_۲۰۲۳۰۱۲۳_۱۴۳۴۳۲_Vanilla Music](https://user-images.githubusercontent.com/32847759/214155054-9cbf2bb3-fbbd-4b8d-9081-b4293e5431f7.jpg)
“Ey Iran” is track 10, but it's placed between tracks 1 and 2

**Comment by adrian-bl** [comment]
What sort order did you use?

Pretty sure that doesn't happen with suffle off + ordering by track number.

**Comment by adrian-bl** [comment]
closing due to lack of reply
