### ISSUE TITLE
on track change/start, briefly display artist and track name in the notification bar

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#117]
I often use my phone as navigation device in my car, while also listening to (a large collection of) music with random enabled (hence I can't just look at the lockscreen widget).

I would highly appreciate to be able to know the artist and name of the track, as I sometimes can't quite remember them even if I perfectly know the track… ^^

Several other music players have that feature, namely DeaDBeeF, IIRC.

**Comment by adrian-bl** [comment]
I looked into this and the tickerText element is deprecated in 5.x, so the text will only show up on 4.x devices - the only alternative would be an heads up display which IMO is not a good alternative.

I'm therefore closing this as wontfix - but if someone sends me a patch i'd be happy to apply it.

**Comment by breversa** [comment]
Ah, too bad ! I think I'll be stuck on 4.x for quite a time anyway, but I understand your decision.

**Comment by breversa** [comment]
Er… and what about a toast notification then ?

**Comment by adrian-bl** [comment]
This would be an alternative, but the issue with the toast is that vanilla may re-create the notification (and therefore the toast) multiple times: The notification system automatically filters duplicate notifications while the toast-system doesn't, so we would have to do this ourself.

But i'll give it another try

**Comment by breversa** [comment]
Thanks for looking into it ! :-)

But why would the notification/toast be created several times ? Is there not some kind of "onTrackChangeEvent()" that would only fire up on, well, track change ?

**Comment by adrian-bl** [comment]
Because the notification may get re-created multiple times and a toast message stays visible for a fixed amount of time.

But i finally started to use the heads-up-notification feature on 5.0.

So vanilla music will now (if enabled):
Display a tickerText on 4.x / Create a heads-up notification on 5.x
Commit: https://github.com/vanilla-music/vanilla/commit/9375969eee84c48aed3d509d76fcc010568d010e

**Comment by breversa** [comment]
On Android 5.x, the heads-up notification stays on screen as long as track is being played.

Is that an intended (or normal) behaviour ?

**Comment by adrian-bl** [comment]
This is intended: The scrolling notification-type was removed in Android 5.0 and the heads up notification is supposed to stay there until the user removes it.

**Comment by breversa** [comment]
Alright, thanks for the info.
I noticed that the heads-up disappears if the screen switches off then on again. I guess I'll play a bit more with it. :-)
