### ISSUE TITLE
Please publish .apk builds on Github so people can use Obtainium to d/l and update Vanilla Music

### ISSUE THREAD

**Issue by wonder75** [vanilla-music/vanilla#1178]
Obtainium is a relatively new app that downloads and installs .apk files directly from official developer sources.
This enables users to become more and more independant on intermediate app stores and offers developers the possibilty to publish their apps directly to users in a secure way.

https://github.com/ImranR98/Obtainium

If Vanilla music would publish .apk Releases on Github, integration with Obtainium would be seamless.

I am not connected to the Obtainium project team, just using it for many apps and would love to see Vanilla in it too.

Maybe take a look.

Cheers!

1. Please take a moment to check if the same Bug has already been reported.
2. Please use our subreddit for general questions: https://www.reddit.com/r/vanillamusic/
3. Please provide all relevant information below.

**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About):
- Android Version:
- Phone vendor / model:
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

....

## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by nutpantz** [comment]
+1

**Comment by adrian-bl** [comment]
Sorry, not gonna happen: You can download the f-droid builds.
