### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Lucky390163** [vanilla-music/vanilla#1183]
App is showing wrong album arts even media store is disabled and it do not shows any other arts even first two options are enabled

**Comment by yaomtc** [comment]
Do you have the cover art either embedded into mp3 files or as image files in the album folders? Vanilla Music can't download the album art for you.

Also, please edit your issue title to summarize your issue in a few words, such as "album art not showing up". "Issue" is not a helpful title

**Comment by adrian-bl** [comment]
closing low effort bug report
