### ISSUE TITLE
play random song when Bluetooth play request received

### ISSUE THREAD

**Issue by rudyvalencia** [vanilla-music/vanilla#120]
Hi,

I have an iHome iBT22 alarm clock (very basic Bluetooth alarm clock from the drugstore). I want to hear a different song every morning when the alarm goes off. Currently I advance a few songs in my playlist without looking at it, but I would like Vanilla Music to (optionally) start playing a random song when the alarm clock sends a play request.

Thanks.

**Comment by adrian-bl** [comment]
closing as wontfix - this is a very niche feature and would complicate our playbackservice code without much gain.
