### ISSUE TITLE
[Feature Request] Add plugin/option to submit song listens to Listenbrainz

### ISSUE THREAD

**Issue by JetpackJackson** [vanilla-music/vanilla#1203]
- Vanilla Music Version (Settings -> About): 1.3.2
- Android Version: 14
- Phone vendor / model: Samsung Galaxy S21 5G
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
Hi, I would like to be able to submit listens to Listenbrainz without relying on an external app to do so (and thus reduce latency etc). I feel like a plugin would be the best way to add this so that way people who don't use Musicbrainz stuff don't have to have the functionality unused in the app and possibly increase the size of the app/require internet permissions. I saw there was the scrobble droid option in the main app settings but that appears to be only for last.fm. If I'm wrong in that regard, please let me know! I just thought this would be a cool feature to have as a plugin. Thanks in advance!

## Steps to reproduce the issue
N/A

## Screenshot / Video (If applicable)
N/A

**Comment by adrian-bl** [comment]
Thats what the scrobble function is for: This sends a broadcast which can be received by any other app (last.fm and co).
