### ISSUE TITLE
Android 5.0: lock screen notification uses too high widget

### ISSUE THREAD

**Issue by stefanb2** [vanilla-music/vanilla#122]
After upgrading to 5.0 the Vanilla Music notification on the lock screen no longer nicely appears in the upper screen with back/pause/forward buttons.

Instead now Vanilla Music is included in the list of notiications with what looks like the 4x1 widget with album art and Pause/Forward. But that widget is too high for the available space (maybe twice the height?) and is cut off at the lower end.

I guess Vanilla Music needs an update for 5.0 lock screen notifications.

* Version: 0.9.40 released Oct. 26, 2014
* Nexus 5
* Android 5.0

**Comment by adrian-bl** [comment]
This has been fixed in git - the fix will be included in the next 0.9.41 release.
