### ISSUE TITLE
Opus support

### ISSUE THREAD

**Issue by jordanl** [vanilla-music/vanilla#123]
Following up on issue #60, Android 5 is out now with opus support, but doesn't work properly in Vanilla.

If I click on an .opus file,  I get a popup saying "0 songs playing."

**Comment by adrian-bl** [comment]
Are you sure that the file was correctly indexed by the media scanner?
Vanilla doesn't really care about the file format (apart from reading out replay gain information) and should play whatever the os supports.

**Comment by jordanl** [comment]
I was using the folder browser, rather than looking for genres/albums/etc indexed from metainfo. So I'm not sure indexing is relevant here?

However, I've switched devices and am back to Android 4 for a little while. I'll be happy to test this again when I'm back on 5.

**Comment by adrian-bl** [comment]
I tested this on my 5.1 device and can confirm that Vanilla is unable to play the opus file - as every other audio player.
I googled about this issue and it seems like Opus support is simply broken in Android 5.x: The library to decode is there, but stagefright (androids av-component) never correctly decodes the file, nor does it index it.

I'm going to close this issue as there is nothing we can do about it - If google fixes it in 5.2, it will also work on Vanilla Music without any changes.

**Comment by yaomtc** [comment]
[LineageOS was supposed to](https://github.com/LineageOS/android_frameworks_base/commit/2baa408f993d2afdf7f186cc33e5a09bbad2c92d) have fixed this, but currently [it doesn't...](https://jira.lineageos.org/browse/BUGBASH-726) I'll let you know when it's fixed.

**Comment by adrian-bl** [comment]
Opus should now kind of work: we can read opus tags and will be able to play them if supported by the firmware. (Which is the case for most >= 6.x devices)
