### ISSUE TITLE
"Play Next" option in context menu

### ISSUE THREAD

**Issue by mrichards42** [vanilla-music/vanilla#125]
I would love to see a "Play Next" option in addition to the "Play" and "Enqueue" options.  This would insert tracks after the currently playing song (instead of at the end of the queue), and is useful for creating a playlist on the fly. Thanks!

**Comment by adrian-bl** [comment]
This feature has been implemented and will be included in the next release on f-droid: https://github.com/vanilla-music/vanilla/commit/57cbf181a1298bfa4c2a6a598152abc7f15aff7b
