### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#127]
We should probably (slowly) start thinking about moving to material design.

**Comment by aminb** [comment]
Do you suggest working on a separate `material` branch or keep everything on `master`?

**Comment by adrian-bl** [comment]
A seperate material branch would probably be a good idea.
However: I didn't look into it yet and have no idea how much work it will be - i first have to read the UI docs anyway ;-)

I also do not consider this as an urgent issue: Vanilla Music works quite well on Lollipop and i fixed the most annoying issue with the notification in my last commits.

**Comment by Allanitomwesh** [comment]
I'd like to suggest the orange from the app logo that is around the speaker as the color for the notification bar in material design. Lollipop changes the notification bar color to match the app color

**Comment by aminb** [comment]
[googlesamples/android-UniversalMusicPlayer](https://github.com/googlesamples/android-UniversalMusicPlayer) could be a nice source of inspiration, the screenshots look simple and elegant.

**Comment by adrian-bl** [comment]
@aminb nice find: i was even able to build it (after fighting with gradle) - this will probably turn out as a helpful reference :)

**Comment by aminb** [comment]
@adrian-bl thanks glad to hear that! yeah it really does look simple and nice.

**Comment by adrian-bl** [comment]
I created a new 'lp-design' branch and already did some changes to the master to make things simpler.

A build compiled using the lp-branch will have a HOLO design while running on Android 4.x - Running on 5.x will automatically show the (unfinished) material design

**Comment by adrian-bl** [comment]
@aminb I continued to work on the lp-design branch and it is IMO in pretty OK shape:

* I styled most of the material elements and fixed small color issues
* I pushed some handy changes (that do not break anything existing) directly into the master. (mostly splitting stuff up and adding new color definitions)
* The play/pause, etc buttons are now automatically inverted if vanilla runs in 'light theme' mode. See: https://github.com/vanilla-music/vanilla/commit/f058f21b97fb638162df1b93195f1ee7e1138bc1 
This is very handy but might need some additional work for the 'enabled' buttons: They are still using the HOLO colors - we should probably redraw them and have the class set the accent/holo color depending on the sdk version + mode

Still broken are:

* The search dialog (Colors)
* The Library View actionbar: The now-playing item is still on the top - i'll try to move it to the bottom or restyle it if it is too much work
* The no-cover-placehoder looks ugly. Someone should redraw it - i'm not an artist ;-)

**Comment by aminb** [comment]
@adrian-bl Great work.

About the *broken* stuff:

- I'll try to take a look at the search dialog and also see how other apps have implemented theirs (more in terms of styling). I think we should have a search icon on the action bar and have the search box show up on the action bar itself.
- For the now-playing item (which on `lp-design` is now on the action bar), maybe we could use [umano/AndroidSlidingUpPanel](https://github.com/umano/AndroidSlidingUpPanel) and/or do something like the CM Eleven app ?
- Unfortunately I'm no artist eiter :-/ Does anyone in the community want to help with this?

**Comment by adrian-bl** [comment]
* I agree that the search bar should show up in the action bar - but for me the big question is still if the 'now playing' should also be in the action bar (or maybe we just place it at the bottom and get rid of the action bar itself)
* Yeah, we could do something like this if the 'now playing' entry in the library view stays at the bottom - but it should be possible without using an external library as we can use v21 of the SDK (and do not have to worry about android < 4.x)

**Comment by notfoss** [comment]
Regarding the "no-cover-placehoder", I searched a bit on openclipart.org. Here are some of the ones:

https://openclipart.org/detail/166613/music
https://openclipart.org/detail/12413/two-sixteeth-notes
https://openclipart.org/detail/4835/45-record-album

All of these are in the public domain: https://openclipart.org/share

**Comment by Allanitomwesh** [comment]
I like the two sixteenth notes.

**Comment by adrian-bl** [comment]
@aminb I created a new 'searchbar' branch, see: https://github.com/vanilla-music/vanilla/tree/searchbar
(It's up-to-date with the master and can be merged with the lp-design branch)

The branch removes the old searchbar code and uses the native SearchView actionbar implementation, making the code MUCH simpler.

* The new implementation looks pretty much ok to me on Android 5.x
![lp screenshot](http://www.watson.ch/imgdb/5f3e/Qx,C,0,0,0,0,0,0,0,0/8789508063692467)
 (there are some color issues (cursor and field having the wrong color) but this should be trivial to fix)



* ..and this is how it looks on the HOLO theme:
![holo screenshot](http://www.watson.ch/imgdb/02ac/Qx,C,0,0,0,0,0,0,0,0/21153918647512)

It is pretty different and not-so-pretty. But given the fact that the old search bar was buggy anyway (it was always shifted by 44px for me) i'd say that we go with the SearchView class - unless there are any objections :-)

**Comment by notfoss** [comment]
@adrian-bl 

maybe the material search field can have an underline to highlight it properly? Other than that it looks fine to me.

**Comment by Allanitomwesh** [comment]
lit does look better with the search bar above the tabs like on lollipop but if the search function itself works well then go for it. Put the cursor back though, looks off without it.

**Comment by aminb** [comment]
@adrian-bl Nice work Adrian, looks good! Except, as @notfoss mentioned, we could style the EditText a bit to better indicate that it's indeed an EditText; by adding an underline (have a look at [rengwuxian/MaterialEditText](https://github.com/rengwuxian/MaterialEditText) README).

@Allanitomwesh What do you mean by cursor?

**Comment by Allanitomwesh** [comment]
@aminb the vertical line that shows you are typing,its not there in either screenshot. It should be " sou| " not " sou " . That cursor.

**Comment by adrian-bl** [comment]
The search box is messed up because the theming in values-v21 is incomplete, should be easy to fix.
So i'll merge the 'searchbar' and 'lp-design' branches into the master if there are no objections.

**Comment by Allanitomwesh** [comment]
Throw in the "two sixteenth note" art as "no-cover-placeholder" while you are at it. No objections here.

**Comment by aminb** [comment]
@adrian-bl Sounds good here.

Also, per @notfoss and @Allanitomwesh 's suggestions for the album cover placeholders, while they're all nice, I think these one's are really beautiful too, especially the first one :

https://openclipart.org/detail/59923/vinyl-lprecord-album
https://openclipart.org/detail/202377/raseone-record-1

**Comment by Allanitomwesh** [comment]
Personally think the now "old" tilted vinyl from the current player looks better than those two. Of the two though i favor "raseone". Maybe tilt that. 
My vote goes to "two sixteenth note" in first place and "tilted raseone" in second.

**Comment by adrian-bl** [comment]
I do not really like the 'two sixteeth' - it somehow reminds me about comic-sans ;-)
The vinyl-lp-record-album looks nice IMO (without the sandwich) and would probably have a good contrast.
Are the cliparts on this site public domain?

**Comment by Allanitomwesh** [comment]
Wouldn't it just be a black circle? That's just me at least. The lines in the second one add detail.

**Comment by adrian-bl** [comment]
No: The Material theme uses a light background.
Running on 4.x will use the old holo theme (and therefore the old placeholder icon)

**Comment by adrian-bl** [comment]
Devices running 5.x usually have a good display, so i think it would look nice.
But the best thing is to give it a try on real hardware: i'll include it after i merged everything into the master (probably in a few days)

**Comment by Allanitomwesh** [comment]
Okay then,am gonna flash CM12 just to check out the new look.

**Comment by notfoss** [comment]
> Are the cliparts on this site public domain?

Yes, everything on openclipart.org is in the public domain.

**Comment by aminb** [comment]
Here are some relatively easy issues I think we should address before the next release:

- The color of song artist name in the action bar is black; they should be white for better contrast with the action bar bg and also to match the rest of the controls on the action bar.

- Update the text colors in `about.html` to a darker color now that the background is light.

- Vanilla's icon is a bit too big compared to other apps. We need to increase 
the padding for each icon size to make it consistent with other lollipop icons.

- I'm not 100% sure but I think I noticed the `searchbar` branch (now merged into master) introduces a bug for pre-lollipop versions which puts the search icon under the 3-dot menu icon in the bottom action bar and makes it inaccessible.

- When the search bar is visible on the action bar, pressing the back button should exit search mode instead of navigating out of Vanilla.

**Comment by adrian-bl** [comment]
I fixed 1,2 and 5 in the git master (task 2 is a rather hacky solution but the best i could come up with)

On issue 3: Did you see this on real hardware?

**Comment by aminb** [comment]
Great! Yeah looks a bit hacky, but it's pretty much the same thing that I was going to do, even better :stuck_out_tongue: .

Yes the third one (icon size) is noticeable on my device (galaxy nexus).

Here's an screenshot, noticeable both on the dock (bottom) and in the folder:
![screenshot_2015-04-12-09-47-57](https://cloud.githubusercontent.com/assets/1254858/7105815/91d9a678-e0f9-11e4-8576-9f1094b78ccb.png)

I think the size should match the system icons (Gallery, Calendar, Email, etc) . Looking at the [guidelines](http://www.google.com/design/spec/style/icons.html) might help.

**Comment by adrian-bl** [comment]
Oh sorry: I wasn't talking about the icon: it should have been number '4' ;-) -> The searchbar bug.

I pushed a changed icon to the git repo a few seconds ago - it overlaps now nicely with lollipops contacts icon (the xhdpi version uses exactly the same area) - does it look better to you?

**Comment by aminb** [comment]
The icon looks much better now :)

And yes, I noticed the searchbar on my phone. It's fine with Material design, but with Holo it appeared under the 3-dot menu on the bottom action bar.

**Comment by adrian-bl** [comment]
How did you get the holo version? Did you compile it without the v21 folder or use it on a 4.x device?

In the first case, this would be normal: The library-cover-view will clamp the widht at 200px while running on pre-5.0 devices while it will try to occupy all space on 5.x devices.

In the 2nd case, it would be a bug - but i tested it today on a S3 and a Nexus 7 - both running 4.4 and it looked ok to me.

**Comment by adrian-bl** [comment]
I pushed a small change to the master which enables us to style the default cover using the themes.xml. The outcome is, IMO, quite okay:
![screenshot](http://i.imgur.com/7MgBOcL.png)

The HOLO version looks slightly different (but now looks like a CD) and the Material version is in my opinion also ok (it looks better on real hardware than on the screenshot) - any opinions?

**Comment by aminb** [comment]
> How did you get the holo version? Did you compile it without the v21 folder or use it on a 4.x device?

I was testing the `searchbar` branch before it was merged into master and I noticed that. I'm not sure if it was a real bug or not, but I do remember running `ant clean` after pulling and before building. Maybe it was just a random thing.

---

The cover looks quite nice IMO, great job.

Once we do this release, I'll open a few issues for iterating and gradually improving the design for future versions.

**Comment by adrian-bl** [comment]
Ah ok: so you were running the searchbar branch on 5.0: Then this is a known issue: The full expansion of the view (only done on 5.x) doesn't work well with the HOLO theme but is ok while using the Material theme. This shouldn't happen in the master anymore as the lp-design branch was merged and the view only expands while using the Material theme (otherwise it uses 200px , like the old code)

I'll test-drive this version for a few days and if everything looks fine, i'd say we do a release on f-droid. ..and 1-2 weeks later i'll push the release to the play store (if the f-droid users do not repot any critical bugs :-) )

**Comment by aminb** [comment]
@adrian-bl Yes, exactly it was he searchbar branch on lollipop 5.1. I see, so that's why.. Yeah the material design is fine (now merged in master). I was just curious to see the changes for pre-lollipop devices, so I tried `searchbar` on my GNex, which runs lollipop.

Doing a release sounds good. We could even bump (skip) a couple of versions since we've got quite a few changes + Material this time, or not :stuck_out_tongue:.

As I mentioned I'll organize and list some improvements and refinements on the design for the next version (after this upcoming release).

**Comment by adrian-bl** [comment]
I'm closing this as 0.99 is out :-)

**Comment by notfoss** [comment]
I just tested out the new version, and I must say that the material design looks really slick. Though the colours can be a bit more vibrant ;).

Thanks for the great work.

**Comment by Allanitomwesh** [comment]
It is grey instead of light blue,otherwise it is great.

**Comment by un-logic** [comment]
I appreciate the work you guys have done for adopting material design, but updated look become so bright and inconvenient in darker conditions unlike good ol' Holo. I'm aware that abandoning dark theme is a trend started by Google, but such a high contrast on bright background really hurts my eyes and also affects power consumption on AMOLED displays.
What I'm asking is to add optional darker theme. TIA.

**Comment by Allanitomwesh** [comment]
And put back the light blue notification bar,grey everything is very dull. 
Dark Theme could be added to Miscellaneous

**Comment by un-logic** [comment]
Agreed on colours, also, just noticed, that default cover art image is absent if you set 'Playback screen' - 'Display mode' option other then 'Fixed on top' (I'm guessing options' names, sorry, but I don't know how to change app's locale quickly so it's a reverse translation) looks like these layouts were not thoroughly tested.

**Comment by adrian-bl** [comment]
Oh right: The default cover is missing in the other layouts. I'll open a bug for this to have it fixed in 1.0.1

About the dark theme: Adding a dark material theme is on my todo list but i won't get around to do it anytime soon. Patches are welcome.

**Comment by TheLastProject** [comment]
Just out of curiousity, is there any reason the Material design is 5.x only? I'm stuck on 4.2.2, yet would love to use the material design. It also would seem that it's much more work to maintain both Holo and Material.

**Comment by adrian-bl** [comment]
Mostly due to personal preferences: IMO, an app should look as native as possible, so on 4.x, it should look like an holo app.

And: Providing a material design on 4.x would force us to use googles support library (which i have no idea how to build from source, and i do not like binary-jars) and even then it would only be a fake-version of the material design (eg: animations are not supported).

> It also would seem that it's much more work to maintain both Holo and Material.

The additional work is minimal: It basically comes down to maintaining these two files:
https://github.com/vanilla-music/vanilla/blob/master/res/values-v21/theme.xml
https://github.com/vanilla-music/vanilla/blob/master/res/values/theme.xml

The most annoying part is that we have to provide multiple versions of some drawables (dark + light), but we have to do this anyway with the dark material theme, so a 3th holo version doesn't result in much work.

**Comment by okungnyo** [comment]
I don't mean to be rude, but the app as it currently stands is not Material design.

Vanilla does not have the correct spacing, icons, fonts, and animations.

If you compare it with Ponograph or Timber, the difference is striking.

Please consider re-opening this issue and implementing a proper Material redesign.

**Comment by adrian-bl** [comment]
> Vanilla Music does not have the correct spacing, icons, fonts, and animations.
> Compare the app with Ponograph or Timber, and the difference is striking.

I know that we do not have any fancy animations and material style icons.
But could you provide some examples about fonts and spacing?

**Comment by okungnyo** [comment]
Here are a few:

* there should be more padding/empty space between list items and the dividers. Right now it looks too dense and cluttered.
* the font needs to be bigger too. Again, too small -> looks cluttered.
* the size of the album art is too aligned to the dividers.
* the [ARTISTS ALBUMS SONGS etc.] tab area should be the same color as the toolbar, not white

If you download Ponograph or Timber, you will see what I mean.

And here are a few other unrelated things I noticed:
* [Settings] should be in a navigation drawer, not in the action overflow
* "Sort By" should be "Sort by" for consistency with the other texts

**Comment by Allanitomwesh** [comment]
I agree that settings in Android 5 apps is usually in the tab that swipes in from the left. The others,i dunno.

**Comment by adrian-bl** [comment]
> there should be more padding/empty space between list items and the dividers. Right now it looks too 
> dense and cluttered.

We could do some experiments with that: We are using a much denser layout than other apps as the library view tends to have an huge list:

The 'standard material' padding is IMO fine for small lists (eg: whatsapp contacts), but quickly becomes a waste of space if you work with > 1'000 entries.

> the font needs to be bigger too. Again, too small -> looks cluttered.

We use the the system standard font size in library rows: The size used in other Apps looks IMO the same (didn't measure it - just looked at it on my 4-inch screen)

> the [ARTISTS ALBUMS SONGS etc.] tab area should be the same color as the toolbar, not white

I agree: We should probably change this.

> [Settings] should be in a navigation drawer, not in the action overflow

This doesn't play well with the ViewPager and other apps using it (eg: whatsapp) also do not implement it.

> "Sort By" should be "Sort by" for consistency with the other texts

Yeah, that's wrong: i opened a ticket for this (https://github.com/vanilla-music/vanilla/issues/239), there are also other cases (eg: Play Next)

I opened a new ticket to discuss + track these changes, see: https://github.com/vanilla-music/vanilla/issues/240
