### ISSUE TITLE
make playback queue as a tab.

### ISSUE THREAD

**Issue by sk280** [vanilla-music/vanilla#128]
Feature request: 
Currently adding/enqueuing songs to the queue displays a notification. However viewing or changing the playback queue is rather cumbersome as I have to go to now playing, click show queue to view the current queue. To workaround this, I have set the swipe up gesture to display current queue and its still cumbersome. Would it be possible to display the current queue as an additional tab?

My use case: 
1. New tab called: "queue" 
2. Any changes to the playback queue immediately reflects in the queue tab.
3. "queue" tab to appear in the list of actions when setting gestures: "Show queue" 
4. "queue" tab to appear in when "show queue" is selected from Now playing screen.

**Comment by aminb** [comment]
@sk280 Can you please create a separate issue for your second request?

I'll look into them. The second one seems trivial to implement. I'll just have to think about it first.

**Comment by K-RAD** [comment]
I saw a way nicer implementation in a different app, where the queue was a fragment that would switch with the cover image in Now Playing

**Comment by quite** [comment]
Came here to request the same thing as OP. And my work-around is the same. Would very much like to have a queue tab that works as described above.

**Comment by UCanGitIt** [comment]
I also would vote for an Queue Tab. For the same reasons already pointed out.

**Comment by R0M4N0F5K7** [comment]
This request is quite old, but I'd also like to have the option to add a Queue Tab...

**Comment by adrian-bl** [comment]
Closing this as we now have the slide-up queue in the library view.
