### ISSUE TITLE
No reaction on pause/play buttons when using Bluetooth headset

### ISSUE THREAD

**Issue by Fokradin** [vanilla-music/vanilla#135]
Hello. I have Sony RBT-1MDR bluetooth-headset, and though "previous"/"next" buttons work fine in Vanilla, "pause"/"play" doesn't work. Is it a bug or am I doing something wrong?

**Comment by adrian-bl** [comment]
Does it work in the standard music player?

**Comment by Fokradin** [comment]
Yes.

**Comment by Fokradin** [comment]
I have changed my Firmware to upstream and now everything works fine. Seems like it wasn't vanilla's fault.

**Comment by aminb** [comment]
Good to hear :) I'll close this issue then.

If the issue happens again, we'll re-open it.

**Comment by NeverWise** [comment]
I think it is a bug.
I have android 7 and I have resolved this issue putting on the home screen the widget of vanilla music, but without this "trick" no music are played.
Another way to make it works is to open vanilla music at least once, no need to play just open, you can also remove it from the recent app and it still works.
This behaviour makes me think that there is something that will not start on device boot.

**Comment by rhithyn** [comment]
I've been experiencing this issue with a Cardo Systems SmartPack headset.  I can start music playing, next/previous work, but the headset can't stop the music playing.  Other music apps will stop as expected, only Vanilla Music Player doesn't stop when told to.  Any suggestions on how to diagnose this?
