### ISSUE TITLE
No reaction on bluetooth headset buttons, when Vanilla window is not opened 

### ISSUE THREAD

**Issue by Fokradin** [vanilla-music/vanilla#136]
Hello. I have Sony RBT-1MDR bluetooth headset and Vanilla only reacts on "next"/"previous" headset buttons when it is active on screen. If I open browser (Vanilla still works, music is playing) my headset controls stop working. Am I doing anything wrong?

**Comment by adrian-bl** [comment]
This can not be a bug in vanilla: It seems like something hijacks the commands and refuses to pass them to vanilla music (Vanilla uses Androids builtin mechanism to receive headset events)
