### ISSUE TITLE
Playback Screen Does Not Set Now Playing Track as Ringtone

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla#137]
This is a feature I very much enjoy from the stock AOSP Music App,and most players I've used also have this feature.
When a track is playing and you are in the playback screen showing the album art,pressing the menu button (three dots) should give the option,"Use as Ringtone". I cannot find this option in Vanilla Music Player. 

Vanilla version 0.9.40 from F-Droid (P:S the source link on F-Droid leads to the old git still)
Sony Xperia SP huashan

**Comment by adrian-bl** [comment]
Closing this as WONTFIX:
I think this feature would be overkill for vanilla music.

**Comment by Allanitomwesh** [comment]
It is a pretty standard feature though in most players. Oh well.
