### ISSUE TITLE
Continuous Shuffle

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla#142]
This is related to issue #114 but it's a different request
When Vanilla shuffles tracks,it shuffles the whole queue once and then plays that order. Problem with this is that if you skip back a couple tracks they will be in the same order you played them. Same thing when you skip forward. This isn't really shuffling though,at least for me.
I'd like the shuffle to keep shuffling. For example 
I queue five songs, One Two Three Four and Five.
They shuffle to Four,One, Three,Five,Two.
I play Four and One
When playing Three I skip back to One
BUT IT DOESN'T PLAY One COZ IT HAS SHUFFLED
I then skip forward to Three
BUT IT DOESN'T PLAY Three COZ IT HAS SHUFFLED
Am calling this continuous shuffle for lack of a better name. The way to achieve this would be that other than the initial shuffle when the queue is added,the player does not play the next track in the queue like always but rather SKIPS TO A RANDOM TRACK WHEN YOU CHANGE TRACKS. It's a really nice feature.

**Comment by beamer145** [comment]
Do you mean this : http://www.acmefiles.com/FAQ/foobar2000/490-what-s-the-difference-between-shuffle-and-random-playback-order-modes  ? Because it is interesting to have both options....

**Comment by Allanitomwesh** [comment]
Yes,like that,where the next track is always random but never the same track twice. It is great.

**Comment by adrian-bl** [comment]
Vanilla needs to know in advance what the previous and the next song shall be - but we could implement this by (internally) pressing the shuffle button after switching to a new song.

But we should probably make this an option in the general audio settings: exposing a new shuffle mode in the left corner would be very confusing

**Comment by Allanitomwesh** [comment]
That sounds fine by me. In audio settings with a checkbox would work.

**Comment by adrian-bl** [comment]
Feature landed via: https://github.com/vanilla-music/vanilla/commit/88d6c285d9dbfe7880b6c92358aa512984d40252 :-)

**Comment by Allanitomwesh** [comment]
Works well thanks :)
Something i noted though,if you switch songs mid song,you will get the previous song,and not an new random song. So not totally continuous but still great.

**Comment by Allanitomwesh** [comment]
Working great now on 1.0.32
