### ISSUE TITLE
Android Lollipop: Lock screen widget improvement

### ISSUE THREAD

**Issue by notfoss** [vanilla-music/vanilla#143]
Hi, if I use the following notification setting:

`When device is locked: Hide sensitive notification content`

The lock screen widget only shows a widget with the following contents

    Vanilla Music
    Contents hidden

and no controls or album art is provided. I understand that this is due to the changes Google did with the lock screen widgets, but with the same settings, Google Play Music can display the usual controls just fine. Mabye the same can be done for Vanilla too?

**Comment by JN-Jones** [comment]
I changed that already locally for me:
Open PlaybackService.java and add after line 1911:
```java
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
	notification.visibility = Notification.VISIBILITY_PUBLIC;
}
```

That's it.

**Comment by notfoss** [comment]
@JN-Jones 

Thanks for the solution. I am using Vanilla from the F-droid repos, so I'll wait till the changes are incorporated in the upstream version.

**Comment by aminb** [comment]
@JN-Jones Thanks for mentioning. I haven't had a chance to read the changes in API 21, including [notifications](https://developer.android.com/about/versions/android-5.0.html#Notifications), yet. I'm going to read it, test this myself and push it. Or, alternatively, it'd be nice if you could open a PR for it.

@notfoss I'll be talking to @adrian-bl about the next release.

**Comment by JN-Jones** [comment]
I'll create a PR later today.

**Comment by aminb** [comment]
@JN-Jones Thank you for the PR, it was tested and merged.

**Comment by notfoss** [comment]
I just tested the updated version and it works great. Thanks all!

**Comment by aminb** [comment]
@notfoss Glad to hear :) Thanks @JN-Jones for the fix and PR.

**Comment by JN-Jones** [comment]
No problem, glad I could help
