### ISSUE TITLE
Vanilla deleted from Play Store?

### ISSUE THREAD

**Issue by averageapps** [vanilla-music/vanilla#145]
I can't find Vanilla on the Play Store anymore. Is it now completely gone from Google Play due to the DMCA troll? I thought that issue was resolved by replacing the screenshots on the store page. Did something happen again that I missed?

So is F-Droid now "the official" source to get Vanilla releases?

**Comment by aminb** [comment]
Yes, Vanilla is not on Google Play anymore. We had a lengthy discussion about this on #124.

And yes, F-Droid is the "official" source for getting Vanilla.

**Comment by averageapps** [comment]
Thanks for the link to #124. I oversaw that there was a second takedown. I can completely understand that you are all fed up with Google Play now.

Kudos to all Vanilla developers for creating such a great music player and not giving up because of this Google Play DMCA crap.

**Comment by aminb** [comment]
You're very welcome :)

Yeah it was pretty frustrating, especially because it kept happening again and again.

Thank you, it's really a joy to be part of the community around Vanilla.

Personally, I don't care the slightest about Google, so that's not an obstacle, at least not for me ;)
