### ISSUE TITLE
Changelog Popup

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla#147]
Would be nice if a new version did a one time popup with the changelog and just an okay button to dismiss it.

**Comment by aminb** [comment]
@Allanitomwesh I remember asking Adrian about including a changelog in the app, and while he said that he dosen't have any objections, he specifically mentioned he disliked this type of behvaiour (changelog popup after update).

I've don't particularly like changelog popups either, but I do recognize it's something quite a few people would like to see.

So, here's what I'm thinking: add changelog as an option in the *Settings* page (above the *About* option). But also have a setting (probably disabled by default) that the user can enable to have the popup show up after each update.

What do you think @adrian-bl?

**Comment by Allanitomwesh** [comment]
I suggest you put it INSIDE Settings › About as a TAB such that a swipe switches between changelog (and the option for changelog popup) and the licences
In the end though no matter how its implemented a view of the changelog is always great.

**Comment by aminb** [comment]
That's an option too; personally I think that'll be too "deep" in terms of hierarchy.

Let's what @adrian-bl and/or others think.

**Comment by adrian-bl** [comment]
I do not have a strong opinion on this but as i already said i do not really like the popup approach.

I'm not against the popup but i would prefer that we either add a new entry to the Settings scrollview (below about) or that we put the changelog inside the about dialog either as a link (after  'issues') or as a new section: Version -> *Changelog* -> Contributors -> Licenses

**Comment by Allanitomwesh** [comment]
Inside Settings › About is fine by me.

**Comment by aminb** [comment]
Keeping it in *About* sounds good to me too.

We'll have a **Changelog** section in *About* starting with the next release.

**Comment by Allanitomwesh** [comment]
Sweet
