### ISSUE TITLE
Album art quality

### ISSUE THREAD

**Issue by notfoss** [vanilla-music/vanilla#150]
Hi, I use embedded artwork for all my files and the size is usually around 500 x 500 px. But in Vanilla Music, the quality of most artwork seems rather poor with artifacts and blockiness visible in many of them. I believe this is because of the downscaling involved.

Does Vanilla music use its own mechanism for retrieving and displaying album art or does it use some built-in Android solution?

Finally, can something be done to fix the problem?

**Comment by adrian-bl** [comment]
Vanilla music uses 3 stages to find album artwork:
#1 it looks in /sdcard/Music/.vanilla/$artist/album.jpg
#2 if not found, it searches for $path_where_the_playing_file_is_located/{album,cover}.jpg
#3 it this still fails, it will use the (often low quality) version provided by android

**Comment by notfoss** [comment]
> #1 it looks in /sdcard/Music/.vanilla/$artist/album.jpg

How is this populated?

Also worth mentioning is that the notification widget's album art looks fine, but that is perhaps because of its small size.

**Comment by adrian-bl** [comment]
It is supposed to be populated by the user:

The main use case for this is to have a directory that will be ignored by the media scanner (= the cover art does not show up in the gallery) if you place a .nomedia file in it.

An example path may look like this:
/sdcard/Music/.vanilla/jack white/blunderbuss.jpg

That said: vanilla music will also search the directory of the playing file for a cover.jpg file

**Comment by notfoss** [comment]
So, from what I understand Vanilla doesn't read embedded album art directly?

Since I have no image files inside any of my music directories, that means Vanilla is using the artwork scanned by Android in my case.

If it is so, and there are no plans to add direct support for embedded artwork, I guess you can close this issue.

**Comment by adrian-bl** [comment]
Yes: Vanilla Music doesn't extract album art from the files on its own: It uses the MediaScanner framework to do this.
