### ISSUE TITLE
Placing the cover view under the ActionBar / over the top controls

### ISSUE THREAD

**Issue by Florent1510** [vanilla-music/vanilla#158]
How can I place the CoverView under the ActionBar / top controls?

Not layout-wise I think as the cover view is placed over the LinearLayout, in an other way it fills up the space what might be the thing...

Thanks for explaining me how I can place under the AB!

**Comment by adrian-bl** [comment]
The CoverView is not placed 'over' a linear layout. It is a custom view class and gets inflated in src/ch/blinkenlights/android/vanilla/FullPlaybackActivity.java - just like any other view class would get inflated.
