### ISSUE TITLE
Does not remember song position in a list after deleting

### ISSUE THREAD

**Issue by anaggh** [vanilla-music/vanilla#162]
This happens when I am sorting out songs and deleting unwanted ones.
I have around 400+ songs. 
When I delete a song for example the 250th file from the "Songs" tab, the list refreshes and returns to the first song. Its difficult to delete files, since you have to scroll down and find the position from where you deleted the last file.

Is there any way Vanilla Music Player can remember the position?

**Comment by adrian-bl** [comment]
Should be fixed via: https://github.com/vanilla-music/vanilla/commit/f9082f89325268d71e6f5c993cc324d7deffc5d0
