### ISSUE TITLE
Sort by date added in Artists tab

### ISSUE THREAD

**Issue by ToNIX-** [vanilla-music/vanilla#166]
Please, add an option to sort the artists by date added (which I assume is the modified date, so if one artist has multiple albums with one added recently, it will be recently added).

Thanks!

**Comment by adrian-bl** [comment]
Sorry, but this is not possible:

Androids media library doesn't have a 'modifed' column: It works using incremented id's.

Adding a new Album created by the existing Artist 'Example' (with, lets say id=62) will not modify the artists id. So vanilla has no way to know that a new album has been added for this artist while querying the artists index.
