### ISSUE TITLE
Sort Songs Tab Alphabetically By Song Title

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla#167]
Currently the Songs tab sorts alphabetically by Artist not Song Title,and it throws me off. Say I want to listen to the song Rolling in the Deep by Adele,in my mind I'm thinking "songs tab › R " but it is actually on of the first songs on the Songs tab,as her name starts with A.

**Comment by ToNIX-** [comment]
You can sort it by "name" in the songs tab options.

**Comment by aminb** [comment]
@ToNIX- is right, there's a whole bunch of options for sorting them in the "Sort By" menu option.

I'm closing this; but feel free to comment if you had something else in mind.

**Comment by aminb** [comment]
@ToNIX- is right, there's a whole bunch of options for sorting them in the "Sort By" menu option.

@Allanitomwesh I'm closing this; but feel free to comment if you had something else in mind.

**Comment by Allanitomwesh** [comment]
Is it possible to have this particular tab sorted by name,by default,in the next update? Cheers

**Comment by aminb** [comment]
@adrian-bl

**Comment by adrian-bl** [comment]
It won't make it into 0.99 but i'll have a look at it before releasing 1.00

**Comment by Allanitomwesh** [comment]
Thanks alot :)
