### ISSUE TITLE
2 widgets broken in 0.9.90 Update

### ISSUE THREAD

**Issue by anaggh** [vanilla-music/vanilla#168]
**Vanilla Music 4x1 B widget** broken
**Vanilla Music 2x2 B widget** broken

Error on Launcher: **"Error: Problem loading widget"**

Vanilla Music Player Version: 0.9.90

_Other Details:_
Device: Moto E 1st Gen
ROM: Cyanogenmod 12.1 (Based on AOSP 5.1.1)

**Comment by adrian-bl** [comment]
Thanks for the bug report, i fixed it in the git HEAD: https://github.com/vanilla-music/vanilla/commit/1bb44eb17259beabc6d39ea720296996d3507ef6 .
A release with the fix should show up in f-droid next week.

**Comment by ka223** [comment]
I can confirm this bug at 0.9.99, thanks for fixing it so quickly.
