### ISSUE TITLE
HTTP Streams and INTERNET Permission

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#169]
I hacked up support for http streaming: It turned out to be pretty simple, but requires us to request internet/networking permissions during the installation:
https://github.com/vanilla-music/vanilla/commit/a671586d21746f5075dd3732bc5ae4cb4724821f

Are there people who would actually like to see this feature and if yes: is it worth changing the permissions?

**Comment by anaggh** [comment]
Yup, would be useful and unlike closed source music players, people could always check the source if they have doubts about the app requiring internet/networking permissions.

**Comment by un-logic** [comment]
Only open source alternatives I have found was ServeStream http://sourceforge.net/projects/servestream/ and VLC both are overkill for me. So It would be nice to see it implemented.

**Comment by call5** [comment]
yes that good, now i use apollo for listen http stream, but i want use just vanilla. so i wait for this fonctionnality for switch to vanilla for all music local or stream and playlist like m3u

**Comment by adrian-bl** [comment]
Closing this as i do not want to add internet permissions (and the branch is unmergeable anyways)

**Comment by adrian-bl** [comment]
No, thats not possible: multiple code parts expect to be able to do random file io which wont work with streams.

**Comment by ildar** [comment]
I see: code refactoring required.
