### ISSUE TITLE
Default cover missing in some fullplaybackactivity view modes

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#171]
The default cover is mysteriously missing in some modes, also things look bad.

**Comment by adrian-bl** [comment]
nope: not a bug. was always like this.

**Comment by un-logic** [comment]
Even though that's not a regression, 'Info below cover' display mode still looking kind of weird - when album art is present is okay, but when art is absent then block of Id3 tags gets moved in centre of album cover placeholder and, judging by block's size of horizontal margins, gets resized just to fit text also. I find this awkward. Instead it is logically to expect that absent cover art to be replaced with default one.
TIA.

**Comment by adrian-bl** [comment]
Yes, it really looks confusing.

Hmm.. i considered to remove the non-default cover-views anyway.
Are people really using them? (at least the 'text on cover' looks ugly to me :-) )

Anyway: I hacked up a small patch: this should would fix the issue:
https://gist.github.com/adrian-bl/eab1c40cf1bd6188b9bd

**Comment by un-logic** [comment]
Thank you, Adrian!
I am not any good in understanding java, but does this patch also fix mentioned above 'Text on cover' mode, as it expected to have an album art cover layer beneath the text block?
Considering necessity of different modes, I myself being stuck with 'Info below cover'. Guess it is appealing to user - being able to alternate UI with ease, even for a tiny bit.

**Comment by adrian-bl** [comment]
The 'text on cover' mode will still have no bitmap.
I tested it and it just didn't look good to me (white text on grey background), so i kept the current behaviour as the missing cover does not break the layout (unlike it does in the text_below_cover case)

btw: i commited the patch to the git head, so it will be included in 1.0.31

**Comment by un-logic** [comment]
First of all Thanks for the patch!
Well, if 'Text on cover' mode will get default cover as a background then it's box should became semitransparent, like when the caption is placed over existing cover which is fine. Also when tested with dark material theme current behaviour of this mode isn't so ugly to me either. But again, that's not my favorite.
