### ISSUE TITLE
Automatic play when headset detected

### ISSUE THREAD

**Issue by ToNIX-** [vanilla-music/vanilla#174]
I know there's another app to have this functionality, but I have only recently discovered it.

In the Settings > Audio, there could be a link to the app on the Play Store under the "Pause When Unplugged" option (or either integrate the functionality into Vanilla Music).

I'm also wondering if there could be a way, with this option enabled, to set the default play volume (either in Settings > Audio or in the external app itself).

Thanks!

**Comment by adrian-bl** [comment]
I added an option to the audio preferences:

It will launch the app (new: with preferences) if installed or redirect to the market if the app is missing.

commit: https://github.com/vanilla-music/vanilla/commit/d4f17d2c9a252910d53775d4e7ae3fb20439ddb8
