### ISSUE TITLE
Songs don't queue

### ISSUE THREAD

**Issue by dhuyvetter** [vanilla-music/vanilla#175]
When I select a folder in Files view and choose Play or Enqueue it says 0 song playing or 0 songs queued and nothing happens. Also in Artists and Albums and Songs views there are only a few artists/albums/songs showing. I am unsure if this is a Vanilla or Android issue, but it is very anoying as I can only select tracks one by one in Files view.

**Comment by dhuyvetter** [comment]
![screenshot_2015-05-22-12-34-06](https://cloud.githubusercontent.com/assets/323400/7768871/96c84df6-007f-11e5-87cf-3a8f188f6685.png)
![screenshot_2015-05-22-12-33-50](https://cloud.githubusercontent.com/assets/323400/7768877/af859826-007f-11e5-9bfe-09d08bd59b95.png)

**Comment by adrian-bl** [comment]
The files are simply not indexed: Vanilla can only add indexed files recursively.

You could try to trigger a re-scan of the media database by using one of the 'media rescan' apps.
Rebooting the phone also should help (this will also trigger a re-scan of the media database)

**Comment by dhuyvetter** [comment]
I had tried restarting, but didn't work. I ended up doing a media rescan via Apps > Media Storage > Clear data and that resolved the issue.
