### ISSUE TITLE
Search button is overlapped by settings button

### ISSUE THREAD

**Issue by softwareliberator** [vanilla-music/vanilla#176]
Hello, I downloaded Vanilla Music 1.0.10 from Google Play. But it has a problem.
Search button is overlapped by settings button when the mobile phone is vertical.
So, I can't push the search button.
When the mobile phone is horizontal, it's no problem.
![screenshot_2015-05-28-07-51-56](https://cloud.githubusercontent.com/assets/12633552/7849357/74586dde-050f-11e5-821c-ea798865f51e.png)

**Comment by adrian-bl** [comment]
What version of Android are you running?
..and what kind of device is this

**Comment by softwareliberator** [comment]
I should have written the detail of my device, sorry.
The following is the "About phone" in "Settings".

Model number    : FT151A
Processor info  : Qualcomm Technologies, Inc MSM8916
Android version : 4.4.4
Kernel version  : 3.10.28 root@compile-server #54 Tue Mar 31 16:07:28 CST 2015
Build number    : freetel_FT151A_20150131

I couldn't find English official website, because the device is sold in Japan only.
The following is the translation from Japanese website(https://www.freetel.jp/ec/item_detail/index/538#tabs-2).

SIM Slot   :  double slot - slot1:2G/3G/4G, slot2:2G
SIM Size   : microSIM
Size       : Width:66.3mm, Depth:8.9mm, Height:132.8mm
Processor  : Quad core 1.2GHz
Bands      : WCDMA 800(B19,B6)/ 2100MHz(B1) - LTE 800MHz(B19)/ 1800MHz(B3)/ 2100MHz(B1) - GSM(850/900/1800/1900MHz)
Battery    : 1700mAh, Stand-by:Up to 120h, Talk time:Up to 5h
OS         : Android 4.4.4
Display    : 4.5inches
Resolution : 854 x 480 pixels(FWVGA)
Memory     : ROM:8GB, RAM:1GB
Camera     : Primary:5.0Mpix, Secondary:2.0Mpix
Bluetooth  : version 4.0 LE
Sensors    : GPS(with A-GPS), Accelerometer, proximity, e-compass
Wi-Fi      : IEEE802.11 b/g/n(2.4GHz)

This device doesn't have vendor specific apps, except Japanese input method.
It looks like original android OS.
I think Japanese input method or font is not related to this problem, because it occurs even though the language setting is changed to English.

**Comment by adrian-bl** [comment]
Thanks a lot for the detailed information:

I tried to reproduce the device in the emulator and the layout looks ok: Do you know the display density (dpi) of the device?

**Comment by softwareliberator** [comment]
DPI isn't written on the manual or other documents. I estimate 218 from "Display" and "Resolution".

**Comment by aminb** [comment]
@softwareliberator If you're not sure, one way to find out the DPI is:

- Install a file manager on your phone (if you don't already have one).
- Open `/system/build.prop`. That is,
  - go to `/system` directory
  - open `build.prop` file
- Look for the line containing `ro.sf.lcd_density`.
- The number in front of it is your DPI.

For instance, mine is `ro.sf.lcd_density=320`; which means the DPI is 320.

**Comment by softwareliberator** [comment]
I read /system/build.prop, but I couldn't find ro.sf.lcd_density in the file.
The following is build.prop.

I used the app "tDpiInfo" to get the dpi.
Would you see screenshots?
Probably, they are enough information.

# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=KTU84P
ro.build.display.id=freetel_FT151A_20150131
persist.bvc.smtversion=false
persist.sys.language=ja
persist.sys.country=JP
persist.sys.timezone=Asia/Tokyo
ro.product.locale.language=ja
ro.product.locale.region=JP
ro.com.android.dateformat=MM-dd-yyyy
ro.config.ringtone=freetel_aqua.ogg
ro.config.ringtone_2=freetel_regulus.ogg
ro.config.notification_sound=Altair.ogg
ro.bvc.wifi_direct_name=FT151A
ro.bvc.wifi_ap_name=FT151A
ro.bvc.bluetooth_name=FT151A
ro.bvc.ime=
ro.bvc.screen_brightness=102
ro.bvc.screen_off_timeout=60000
ro.build.version.incremental=266
ro.build.version.sdk=19
ro.build.version.codename=REL
ro.build.version.release=4.4.4
ro.build.date=Sat Jan 31 17:40:38 CST 2015
ro.build.date.utc=1422697238
ro.build.type=user
ro.build.user=root
ro.build.host=compile-server
ro.build.tags=release-keys
ro.product.model=FT151A
ro.product.brand=qcom
ro.product.name=FT151A
ro.product.device=FT151A
ro.product.board=msm8916
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.manufacturer=BVC
ro.wifi.channels=
ro.board.platform=msm8916
# ro.build.product is obsolete; use ro.product.device
ro.build.product=FT151A
# Do not try to parse ro.build.description or .fingerprint
ro.build.description=FT151A-user 4.4.4 KTU84P 266 release-keys
ro.build.fingerprint=qcom/FT151A/FT151A:4.4.4/KTU84P/266:user/release-keys
ro.build.characteristics=default
persist.sys.bootmusic=
ro.adb.secure=1
ro.product.hardware=HW_1.0
ro.product.internumber=SW_1.0
persist.service.adb.enable=0
persist.sys.usb.config=mtp,adb
ro.baseband=HW_1.0
ro.com.google.clientidbase.am=android-plusone
ro.com.google.clientidbase.gmm=android-plusone
ro.com.google.clientidbase.ms=android-plusone
ro.com.google.clientidbase.yt=android-plusone
ro.com.google.clientidbase=android-plusone
# end build properties
#
# from device/qcom/msm8916_32/system.prop
#
#
# system.prop for msm8916
#

#rild.libpath=/system/lib/libreference-ril.so
rild.libpath=/system/vendor/lib/libril-qc-qmi-1.so
rild.libargs=-d /dev/smd0
persist.rild.nitz_plmn=
persist.rild.nitz_long_ons_0=
persist.rild.nitz_long_ons_1=
persist.rild.nitz_long_ons_2=
persist.rild.nitz_long_ons_3=
persist.rild.nitz_short_ons_0=
persist.rild.nitz_short_ons_1=
persist.rild.nitz_short_ons_2=
persist.rild.nitz_short_ons_3=
ril.subscription.types=NV,RUIM
DEVICE_PROVISIONED=1
# Start in cdma mode
ro.telephony.default_network=20

debug.sf.hw=1
debug.egl.hw=1
debug.composition.type=c2d
persist.hwc.mdpcomp.enable=true
debug.mdpcomp.logs=0
#Enable translucent status bar feature
persist.hwc.ptor.enable=true
dalvik.vm.heapsize=36m
dev.pm.dyn_samplingrate=1
persist.demo.hdmirotationlock=false
debug.sf.gpu_comp_tiling=1
debug.enable.sglscale=1

#ro.hdmi.enable=true
#tunnel.decode=true
#tunnel.audiovideo.decode=true
#lpa.decode=false
#lpa.use-stagefright=true
#persist.speaker.prot.enable=false

#
# system props for the cne module
# modify by chenming, set it to 4 for can not enter sleeep mode, org is 1
persist.cne.feature=4

#
# system props for the dpm module
#
persist.dpm.feature=0

#system props for the MM modules
media.stagefright.enable-player=true
media.stagefright.enable-http=true
media.stagefright.enable-aac=true
media.stagefright.enable-qcp=true
media.stagefright.enable-fma2dp=true
media.stagefright.enable-scan=true
mmp.enable.3g2=true
mm.enable.smoothstreaming=true
mm.disable.sec_smoothstreaming=true
media.aac_51_output_enabled=true
#codecs:(PARSER_)AAC AC3 ASF AVI DTS 3G2 MP2TS QCP FLAC
mm.enable.qcom_parser=168563

#
# system props for the data modules
#
ro.use_data_netmgrd=true
persist.data.netmgrd.qos.enable=true

#system props for time-services
persist.timed.enable=true

#
# system prop for opengles version
#
# 196608 is decimal for 0x30000 to report version 3
ro.opengles.version=196608

# System property for cabl
ro.qualcomm.cabl=2

#
# System props for telephony
# System prop to turn on CdmaLTEPhone always
telephony.lteOnCdmaDevice=1
persist.omh.enabled=true

#
# System props for bluetooh
# System prop to turn on hfp client
bluetooth.hfp.client=1

#Simulate sdcard on /data/media
#
persist.fuse_sdcard=true

#
#snapdragon value add features
#
ro.qc.sdk.audio.ssr=false
##fluencetype can be "fluence" or "fluencepro" or "none"
ro.qc.sdk.audio.fluencetype=none
persist.audio.fluence.voicecall=true
persist.audio.fluence.voicerec=false
persist.audio.fluence.speaker=true
#Set for msm8916
tunnel.audio.encode = false
#Buffer size in kbytes for compress offload playback
audio.offload.buffer.size.kb=32
#use VERY_HIGH_QUALITY for audio resampler
af.resampler.quality=4
#Enable offload audio video playback by default
av.offload.enable=false
#enable voice path for PCM VoIP by default
use.voice.path.for.pcm.voip=true
#
#System property for FM transmitter
#
ro.fm.transmitter=false
#enable dsp gapless mode by default
audio.offload.gapless.enabled=true

#Audio voice concurrency related flags
voice.playback.conc.disabled=true
voice.record.conc.disabled=true
voice.voip.conc.disabled=true

#Set composition for USB, removed by chenming, we have modify it to the path build.sh
#persist.sys.usb.config=mtp,adb
#persist.sys.usb.config=diag,serial_smd,rmnet_bam,adb

#Set read only default composition for USB
ro.sys.usb.default.config=diag,serial_smd,rmnet_bam,adb

# set max background services
ro.config.max_starting_bg=8

#property to enable user to access Google WFD settings
persist.debug.wfd.enable=1
#propery to enable VDS WFD solution
persist.hwc.enable_vds=1
ro.min_freq=800000
#disable strict mode, add by luoneng, 20140912
persist.sys.strictmode.visual=0
persist.sys.strictmode.disable=1

# add by chenming using the DSDS
persist.radio.multisim.config=dsds
#
# ADDITIONAL_BUILD_PROPERTIES
#
dalvik.vm.heapgrowthlimit=128m
drm.service.enabled=true
keyguard.no_require_sim=true
ro.com.google.gmsversion=4.4_r5
ro.com.google.clientidbase=android-google
ro.com.android.dataroaming=true
ro.carrier=unknown
ro.config.notification_sound=OnTheHunt.ogg
ro.config.alarm_alert=Alarm_Classic.ogg
ro.vendor.extension_library=/vendor/lib/libqc-opt.so
persist.radio.apm_sim_not_pwdn=1
dalvik.vm.heapstartsize=8m
dalvik.vm.heapsize=256m
dalvik.vm.heaptargetutilization=0.75
dalvik.vm.heapminfree=2m
dalvik.vm.heapmaxfree=8m
persist.service.stk.gesture=0
persist.service.stk.pulse=0
persist.sys.dalvik.vm.lib=libdvm.so
net.bt.name=Android
dalvik.vm.stack-trace-file=/data/anr/traces.txt
persist.gps.qc_nlp_in_use=1
persist.loc.nlp_name=com.qualcomm.services.location
ro.gps.agps_provider=1
ro.pip.gated=0

# begin fota properties
ro.fota.platform=MSM8916_KK
ro.fota.type=phone
ro.fota.oem=tzdz8916_KK
ro.fota.device=FT151A
ro.fota.version=freetel_FT151A_20150131
# end fota properties
![screenshot_2015-06-01-04-52-52](https://cloud.githubusercontent.com/assets/12633552/7903865/4d73714c-0824-11e5-8435-9b770757780d.png)
![screenshot_2015-06-01-04-53-05](https://cloud.githubusercontent.com/assets/12633552/7903867/4d73cf0c-0824-11e5-9305-88a190234446.png)
![screenshot_2015-06-01-04-53-12](https://cloud.githubusercontent.com/assets/12633552/7903868/4d75eecc-0824-11e5-87e8-cc96d7901112.png)
![screenshot_2015-06-01-04-53-23](https://cloud.githubusercontent.com/assets/12633552/7903866/4d73c7a0-0824-11e5-9da3-998463f8c90a.png)
![screenshot_2015-06-01-04-53-33](https://cloud.githubusercontent.com/assets/12633552/7903870/4d77d9f8-0824-11e5-85cc-ba1efaf03c84.png)
![screenshot_2015-06-01-04-53-43](https://cloud.githubusercontent.com/assets/12633552/7903869/4d77a97e-0824-11e5-8dab-fe64d2d0044e.png)
![screenshot_2015-06-01-04-54-09](https://cloud.githubusercontent.com/assets/12633552/7903872/4da77d34-0824-11e5-9518-670507f25936.png)
![screenshot_2015-06-01-04-54-15](https://cloud.githubusercontent.com/assets/12633552/7903871/4da60bca-0824-11e5-9ae4-07a82fdb4207.png)

**Comment by adrian-bl** [comment]
Ah ok: So you got an hdpi device with an, for an hdpi device, unusually large screen.

I was able to reproduce the issue in the emulator and it should be fixed in the git-master.
If you have the SDK installed, please give it a try by compiling and installing the lastest git head.

Or you could use this APK file:
https://mega.co.nz/#!ulNhhahD!eiUYN-WJq4nTw_67p3SNdwLwF_G1aT8oxc1ucaoYWRQ

It was compiled a few seconds ago and includes the (hopefully working!) fix.

**Comment by softwareliberator** [comment]
I tried the compiled app. It's no problem. Thank you.
![screenshot_2015-06-02-02-46-00](https://cloud.githubusercontent.com/assets/12633552/7919641/a1ec21d2-08d4-11e5-8742-3e3a2cd4e393.png)

**Comment by adrian-bl** [comment]
Looks good, great :-)

I'm therefore closing this ticket. The fix will be included in the next release.

Thanks a lot for the bug report and testing the fix!

**Comment by adrian-bl** [comment]
fixed via: https://github.com/vanilla-music/vanilla/commit/3d3bc45fe11de69a9af3e6136eb190c3d099f888
