### ISSUE TITLE
ReplayGain will not increase volume past native max

### ISSUE THREAD

**Issue by CyberTootie** [vanilla-music/vanilla#178]
If I set the Vanilla ReplayGain preamp to +6db and play a file with a ReplayGain value of -3db, it will effectively play that file back as if it had a ReplayGain value of -6db in that scenario. Irrespective of whether the value was -1db, -4db or -5.99db, the effective playback level will stop increasing at what seems to be the hardware maximum volume of the file without clipping. Expected ReplayGain behavior calls for increases in playback volume beyond the clipping threshold for softer-mastered music.

**Comment by adrian-bl** [comment]
This is the expected behavior and is even documented in the preferences screen.
