### ISSUE TITLE
Clear queue does not clear completely

### ISSUE THREAD

**Issue by mase76** [vanilla-music/vanilla#182]
Hi!
The clear queue option completely clear the queue. At least the current track stays. I have to open the queue and remove the remaining tracks by swiping them away.
A playing song should be stopped, and the queue should be really cleared.

**Comment by aminb** [comment]
@mase76 I think that's the "Empty queue" you're looking for (see #149 for discussion).

**Comment by aminb** [comment]
Also, I think you're using an out of date version, since it's been a few releases that `Clear queue` was renamed to `Dequeue rest` and `Empty queue` was introduced.

We'll have the rest of discussion over at the other issue.

Closing this.
