### ISSUE TITLE
Rearrange Menus in Playback Screen

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla#183]
On the playback screen pressing menu (three dots button) the drop-down lists several options
It is long and cluttered (my phone is 720p,your milage may vary) and i noticed that it is because of a lot of queuing options.
Dequeue rest
Enqueue album
Enqueue artist
Enqueue genre
Show queue
I propose that all the above options be moved into SHOW QUEUE. This would shorten the menu to
Settings
Delete
Add to Favourites
Show Queue
which is much easier on the eyes and less intimidating. Also,it would allow changes on the queue be seen in real time,like how you immediately see Empty queue happen but cant see something like Enqueue album add the album tracks.

**Comment by adrian-bl** [comment]
closing this old bug as the menu entries have been re-arranged (split up) due to the queue slider
