### ISSUE TITLE
Sorting albums by year just sorts alphabetically

### ISSUE THREAD

**Issue by mvdan** [vanilla-music/vanilla#184]
I've been having this issue for years, for as long as I remember using Vanilla. I always thought "I must be doing something wrong, this can't be happening to everyone" and attributed it to an error of mine.

But since the media tags work everywhere else including MPD on my laptop, I just don't know what else to do. I use easytag to mass modify and clean up the tags on the audio files, which currently does ID3v2.4 by default, if that matters.

Here's a `mediainfo` of one of the files on my library, for example:
```
General
Complete name                            : Music/Frank Zappa/Frank Zappa - [1967] Absolutely Free/01 - Plastic People.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 21.6 MiB
Duration                                 : 3mn 42s
Overall bit rate mode                    : Variable
Overall bit rate                         : 817 Kbps
Album                                    : Absolutely Free
Track name                               : Plastic People
Track name/Position                      : 01
Performer                                : Frank Zappa
Recorded date                            : 1967
Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 3mn 42s
Bit rate mode                            : Variable
Bit rate                                 : 816 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 KHz
Bit depth                                : 16 bits
Stream size                              : 21.6 MiB (100%)
Writing library                          : libFLAC 1.2.1 (UTC 2007-09-17)
```

As you can see, sorting by folder name would work mostly ok for me (wink wink #61) but that doesn't take away the fact that sorting by year seems to just not work.

I can provide more information if needed.

**Comment by mvdan** [comment]
Just as a note, this happens both on the "albums" tab and when clicking on an artist to add their songs to the playlist. In both cases, the albums get sorted alphabetically.

**Comment by adrian-bl** [comment]
Well: Did android actually pick up the information? (-> play the song and long-press on the metadata info: is 'year' filled with data?)

Sorting by year works fine for me but android media scanner can be very picky

**Comment by mvdan** [comment]
You're right, "year" is empty while others like "artist" and "album" get picked up just fine.

**Comment by adrian-bl** [comment]
So i suppose that your tagging software does not write the expected tag.
Note that android expects YEAR for vorbiscomments (ogg + flac) while many taggers use the DATE field.

**Comment by mvdan** [comment]
Hmm, easytag uses ID3 and it indeed uses Date instead of Year. Never heard of vorbiscomments before. Tried making easytag use ID3v1 instead of ID3v2.x tags but it still writes Date. Seems like it doesn't do vorbiscomments.

This is all still on flac files.

**Comment by mvdan** [comment]
Anyway, thanks for the help and sorry for the noise. Sounds like the Android media scanner does a pretty bad job, especially since both mpv and mpd read the Date flag just fine.

**Comment by mvdan** [comment]
Found the issue in MediaScanner and sent a patch to Cyanogenmod: http://review.cyanogenmod.org/#/c/101467/

I'm assuming this is a problem in AOSP which should be fixed in all ROMs, but will see what these guys have to say first before sending the patch to AOSP. Besides, I'd like the fix to hit my nightly builds :)
