### ISSUE TITLE
[Lint error] NewApi: Calling new methods on older versions

### ISSUE THREAD

**Issue by trophygeek** [vanilla-music/vanilla#185]
Using the latest Android build tools, Lint gives this error which seems like a potential bug:

```
../../src/ch/blinkenlights/android/vanilla/VanillaMediaPlayer.java:78: 
Call requires API level 16 (current min is 15): android.media.MediaPlayer#setNextMediaPlayer
  75 	 * Sets the next media player data source
  76 	 */
  77 	public void setNextMediaPlayer(VanillaMediaPlayer next) {
  78 		super.setNextMediaPlayer(next);

  79 		mHasNextMediaPlayer = (next != null);
  80 	}
```

There is this discussion about how to do this on older android versions like 15:
http://stackoverflow.com/questions/18468364/android-mediaplayer-setnextmediaplayer-alternative

This does not seem like a trivial Lint complaint, but might cause `setNextMediaPlayer()` to break on Ice Cream Sandwich.

**Comment by adrian-bl** [comment]
The method will never be called on ICS as the triggerGaplessUpdate() function already checks the SDK version, so the code would work just fine on pre-ICS devices.

But i agree that the wrapper could also do a check, so would this make lint happy: ?
 https://gist.github.com/adrian-bl/1135b6ae5d43bd2444be
