### ISSUE TITLE
Some files are not played

### ISSUE THREAD

**Issue by Pastafarianist** [vanilla-music/vanilla#186]
Not sure if this is a Vanilla issue or not, but it cannot play some audio files (like [this one](https://drive.google.com/file/d/0B0Jnpz9ldbuHNFlhVVowbW5MVGs/view?usp=sharing)). Upon pressing the "play" button its icon changes to "pause", but the time slider doesn't move and, naturally, there is no sound. VLC works just fine with this file.

I can attach any necessary logs (gathered via aLogcat Root) if you tell me which filter keyword you might be interested in.

**Comment by pejakm** [comment]
The file can't play for me, neither.

**Comment by Pastafarianist** [comment]
A friend tells me that it doesn't work for him in Chrome for Android, however, the default Sony player on Lollipop handles the file well.

**Comment by adrian-bl** [comment]
I tested the file on two devices:

#### Device 1 Running AOSP 4.2
As described, the play button switches into pause mode and the file does not play at all.
MediaPlayer returns error -19 (AUDIOTRACK_ERROR_SETUP_INVALIDSTREAMTYPE)
The stock AOSP Music player is also unable to play the file and displays a duration of 422 minutes

#### Device 2 Running CyanogenMod 12.1-nightly (5.1)
The file can be played but there are occasional audio drop-outs


Ogginfo shows that the file was not encoded by the reference implementation:
```
$ ogginfo *.ogg
....
Vendor: AO; aoTuV [20110424] (based on Xiph.Org's libVorbis)
```

So there is either a bug in androids MediaFramework or the file is simply somehow broken.
In any case there is nothing i can do about it as Vanilla Music is a normal consumer of the MediaPlayer class provided by android.
