### ISSUE TITLE
Approve Serbian language request

### ISSUE THREAD

**Issue by pejakm** [vanilla-music/vanilla#188]
Please approve my request for Serbian (sr) language, over at Transifex.

Thanks.

**Comment by adrian-bl** [comment]
Hi @pejakm,

I approved your request.

Thanks!

**Comment by pejakm** [comment]
I have also requested to join Serbian team, please add me to a "coordinators" group, and also, you can now delete "Serbian (RS)" language (sr_RS) as we mainly use "sr" for Android (and in general) translations.
Thanks. :)

**Comment by adrian-bl** [comment]
Done: I added you to the group.
But for some reason i can not delete sr_RS: i get an error :-/
Transifex really sucks sometimes ;-)
