### ISSUE TITLE
[RFE] Optionally exclude genres in random playback mode

### ISSUE THREAD

**Issue by b3nmore** [vanilla-music/vanilla#190]
Some items in my library are not very meaningful to listen to in random mode, like audiobooks, podcasts, etc. So it would be really nice, if one could setup a list of genres, which are excluded when the shuffle queue gets populated.

**Comment by adrian-bl** [comment]
Androids Genre handling is a big mess, Vanilla Music already uses an SQL injection to get albums-by genre, so this would probably be A LOT of work.
But having an option to blacklist certain paths/folders (dup of: https://github.com/vanilla-music/vanilla/issues/22) would be easier. Would this also solve your use case?

**Comment by b3nmore** [comment]
> But having an option to blacklist certain paths/folders (dup of: #22) would be easier. Would this also solve your use case?

Yes, either whitelisting or blacklisting would work for me. Thanks.

**Comment by adrian-bl** [comment]
Ok, i'm then closing this as a duplicate of #22 (targeted for version 1.1.0)
