### ISSUE TITLE
Option to disable album cover art being display in lockscreen.

### ISSUE THREAD

**Issue by itprojects** [vanilla-music/vanilla#191]
In the latest Android, the album covers can be seen as background to the lock screen. There should be an option to prevent any such broadcasting of album cover art, on principle.

This may also be related to the bug:

"If no cover art embedded in music file, lockscreen displays the last cover available #146"

**Comment by KonomiKitten** [comment]
Would very much like to see this added, I don't want my lock screen to have cover art on it.

**Comment by adrian-bl** [comment]
implemented in: https://github.com/vanilla-music/vanilla/commit/7f1f5c0cdd54413a6ee8c53ec1ab25ad636a70f0
