### ISSUE TITLE
Updating Transifex strings

### ISSUE THREAD

**Issue by RiseT** [vanilla-music/vanilla#193]
@adrian-bl Could you please update the translated strings from Transifex when doing a release (in order to include corrections, etc)?

Thanks in advance!

**Comment by adrian-bl** [comment]
Sorry, i forgot to look at transifex: i pushed the updates to the git head - 1.0.31 will probably be released soon anyway.

btw: i changed Wartereihe back into 'Warteschlange' - Both Eleven and Deezer also translated 'queue' into 'Warteschlange'.

**Comment by RiseT** [comment]
@adrian-bl For "queue" I've used "Wartereihe" instead of "Warteschlange" for consistency with the corresponding verb "enqueue" ("einreihen") in order to make it clear in the wording that both are related.

But if you prefer "Warteschlange", that's fine with me.

**Comment by adrian-bl** [comment]
I see your point and it makes sense, but 'Warteschlange' just seems to be the more popular translation :-)

**Comment by RiseT** [comment]
@adrian-bl Could you do the Transifex updates just prior to releasing a new version (i. e. the latest thing you do prior to release)? So the translations would be most up to date.

**Comment by adrian-bl** [comment]
@RiseT meinst du das ändern von last.fm im values.xml? Das sollte keinen Einfluss auf die Übersetzungen in Transifex haben, da sich der Key nicht geändert hat.

**Comment by RiseT** [comment]
@adrian-bl Nein, der Kommentar war eher genereller Natur.
Es kommen ja ggf. immer noch Korrekturen oder Neuübersetzungen in den verschieden Sprachen dazu (ich habe jetzt beispielsweise auch noch einige Kleinigkeiten geändert). Wenn Du die Transifex-XMLs erst als Letztes vor dem Release aktualisierst, hast Du die aktuellsten Sprachdateien. Ich kenne das z. B. von TextSecure so. Ich meine - irgendwann musst Du es ja sowieso machen, da kannst Du es auch zum Schluss machen ;-)

**Comment by adrian-bl** [comment]
Das mach ich normalerweise auch: Ich probiere, neue Strings so früh wie möglich ins values.xml zu bringen und lade die Übersetzungen so spät wie möglich herunter.

Bei 1.0.30 habe ich das vergessen, war aber sowieso ein f-droid only release - und 1.0.31 ist noch nicht released (auch nicht auf f-droid -> kein tag)

**Comment by RiseT** [comment]
@adrian-bl Ach so - alles klar. Perfekt. Danke für die Antwort!
(... und auch danke für einen überragenden Player!)

**Comment by RiseT** [comment]
@adrian-bl 
PS: Der Last.fm-String ist übrigens heute bei Transifex als unübersetzt aufgetaucht (habe die Übersetzung bereits wieder eingetragen).

Meiner Erfahrung nach wird - falls Du den xml-Key nicht änderst - der String auf unübersetzt gestellt, allerdings bleiben Verlauf, Vorschläge und Kommentare erhalten.

Bei Änderung des xml-Keys hingegen ist alles weg - Übersetzung, Verlauf, Vorschläge, Kommentare.
Ist auch irgendwie logisch, denn Transifex entscheidet ja anhand des Keys, ob das ein bereits vorhandener oder ein komplett neuer String ist.

**Comment by adrian-bl** [comment]
Ok, danke vielmals! Habe den korrigierten String bei einigen anderen Sprachen anhand der History auch wieder eingetragen.

Ja: Wenn sich die Keys ändern, löscht Transifex die ganze Übersetzung, samt aller History: Bei uns im Büro hats mal einger geschafft, ein falsches XML hochzuladen - dann war alles weg ;-)
