### ISSUE TITLE
Metadata of a few files is not read

### ISSUE THREAD

**Issue by RalfJung** [vanilla-music/vanilla#196]
Of the ~2000 music files that I stored on the SD card of my phone, Vanilla Music seems unable to deal with the metadata of 5 files: They appear as "<unknown>" artist, the actual artist name (which is also the folder name) becomes the album name, and the filename becomes the title. So far I was unable to figure out what makes these 5 files different than all the others, they appear perfectly normal (and well-tagged) on my Desktop. They seem to have in common that they are variable-bitrate MP3 files, but I have way more such files in my collection.
I tried re-writing the metadata to the file and then copying the file again (with adb, that's much more reliable than MTP here), but that doesn't seem to change anything. I don't even know whether the file got re-scanned for its new metadata.

I have no idea to what extend Vanilla Music is dealing with the metadata, and to what extend Android is doing that - this is just the first stop in me trying to figure out what's happening. I am using CM12.1, an experimental build as my HW is not officially supported.

EDIT: Interestingly, I found the correct metadata in the logs
```
D/NuPlayerDriver(  333): reset(0xb5950ac0)
D/NuPlayerDriver(  333): notifyResetComplete(0xb5950ac0)
D/NuPlayerDriver(  333): reset(0xb5950ac0)
I/FFmpegExtractor(  333): android-source:0xb28340b0
I/FFMPEG  (  333): [mp3 @ 0xb2a40400] Skipping 0 bytes of junk at 1408.
I/FFMPEG  (  333): Input #0, mp3, from 'android-source:0xb28340b0':
I/FFMPEG  (  333):   Metadata:
I/FFMPEG  (  333):     album           : Radio
I/FFMPEG  (  333):     track           : 24
I/FFMPEG  (  333):     artist          : Wise Guys
I/FFMPEG  (  333):     genre           : Other
I/FFMPEG  (  333):     title           : Zwischenbilanz
I/FFMPEG  (  333):   Duration: 00:02:14.06, start: 0.023021, bitrate: 182 kb/s
I/FFMPEG  (  333):     Stream #0:0: Audio: mp3, 48000 Hz, stereo, s16p, 182 kb/s
I/FFMPEG  (  333):     Metadata:
I/FFMPEG  (  333):       encoder         : LAME3.98r
D/FFmpegExtractor(  333): FFmpegExtrator, url: android-source:0xb28340b0, format_name: mp3, format_long_name: MP2/3 (MPEG audio layer 2/3)
D/FFmpegExtractor(  333): suppoted codec(mp3) by official Stagefright
D/FFmpegExtractor(  333): ffmpeg detected media content as 'audio/mpeg' with confidence 0.08
D/ExtendedUtils(  333): extended extractor not needed, return default
```
But the player doesn't seem to use it.

**Comment by adrian-bl** [comment]
Wrong tags in MP3 files are usually due to 'double tagging':
A file might have both ID3v1 and ID3v2 tags, where one of the tags is present but empty (or wrong).
Some implementations may choose to prefer the v2 tags while others might display the v1 tag.

That said: Vanilla Music itself doesn't deal with scanning + reading metadata from files (apart from replaygain information): This is all handled by Androids media scanner.

Also note that pushing a file via 'adb' does *not* start the re-indexing: only MTP transfers do so.
You can forcefully initiate a scan with 'SD Scanner', see: https://f-droid.org/repository/browse/?fdid=com.gmail.jerickson314.sdscanner

If re-scanning with SD Scanner doesn't help, feel free to send me one of the problemeatic files via e-mail to adrian@blinkenlights.ch (as long as it is < 25MB)

**Comment by RalfJung** [comment]
> That said: Vanilla Music itself doesn't deal with scanning + reading metadata from files (apart from replaygain information): This is all handled by Androids media scanner.

I kind of expected this.

> Also note that pushing a file via 'adb' does *not* start the re-indexing: only MTP transfers do so.
> You can forcefully initiate a scan with 'SD Scanner', see: https://f-droid.org/repository/browse/?fdid=com.gmail.jerickson314.sdscanner

After editing the meta-data of each affected file once on my Desktop,
syncing them to the device, and running this scanner, the "<unknown>"
artist is now gone. Thanks!

(If there was a usable way to sync music via MTP, I'd do it, but my
experience with MTP so far has been horrible... which may also be the
fault of the Linux MTP implementation, I don't know.)
