### ISSUE TITLE
Note within replay gain settings untranslatable

### ISSUE THREAD

**Issue by RiseT** [vanilla-music/vanilla#198]
The note (including its title 'Note') 'Android does not allow [...]' has no Transifex string.

Additionally, the contrast between background (white) and font color (light grey) is too low which makes this fairly difficult to read.

**Comment by adrian-bl** [comment]
Thanks for the bug report. Should be fixed via: https://github.com/vanilla-music/vanilla/commit/87d2dd7544c26e118087cdfd61741b6c293dfc48
