### ISSUE TITLE
No ReplayGain for MP3/AAC files

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#201]
Hi,

Though I'm a big fan of FLAC and Ogg Vorbis, I noticed that my few MP3 or AAC files have no ReplayGain : "track=0.0dB, album=0.0dB".

Any idea why ?

**Comment by adrian-bl** [comment]
What encoder/tagger was used to tag the MP3 file? (We only support lame-style replay gain tags for now)

For AAC: This is a known issue: Our tag reading library (bastp) simply doesn't support m4a files yet.

**Comment by breversa** [comment]
I've used SoundKonverter (https://github.com/HessiJames/soundkonverter) as a front-end to mp3gain, using APE tags. I'm currently recalculating the gain with ID3v2 tags instead, but I hope it won't mess up with my other players…

**Comment by breversa** [comment]
… and I'm afraid it did. :-/

So tell me : when you talk about LAME-style tags, do you mean ID3v2, or did I get this wrong ?

**Comment by adrian-bl** [comment]
Actually i was wrong: we support ID3v2 AND lame-style replay gain.

ID3v2 replay gain information is expected to be encoded in a TXXX field:
https://github.com/adrian-bl/bastp/blob/master/ch/blinkenlights/bastp/ID3v2File.java#L124

If the file lacks an ID3v2 header (or if the ID3v2 tag does not have any replay gain information), we will fall back to lame/xing headers (these headers are usually what people are talking about when they talk about id3v1):
https://github.com/adrian-bl/bastp/blob/master/ch/blinkenlights/bastp/LameHeader.java#L85

So did vanilla music fail to pick up the replay gain in the ID3v2-tagged file?
If yes, feel free to send me a sample to adrian@blinkenlights.ch

**Comment by breversa** [comment]
That's highly weird : my MP3 tags use several flavours of ID3v2.x tags, and some also have APEv2 tags, but none of them have their ReplayGain tags picked up.

I'll send you a few samples.

**Comment by adrian-bl** [comment]
This is how vanilla would parse the metadata of the 3 files:
```
 adrian@prism:~/tmp/mp3/bastp$ find ../|grep -i mp3 | java ch.blinkenlights.bastp.Test
 ------------------------------------------------------------
 <FILE> ../1.mp3
 <duration> = 55655822
 <_hdrlen> = 2048
 <type> = MP3/ID3v2

 ------------------------------------------------------------
 <FILE> ../2.mp3
 <duration> = 337
 <_hdrlen> = 2048
 <type> = MP3/ID3v2
 <REPLAYGAIN_ALBUM_GAIN> = [6.5 dB] <---- !

 ------------------------------------------------------------
 <FILE> ../3.mp3
 <duration> = 317
 <_hdrlen> = 2048
 <type> = MP3/ID3v2
```


 So we are only picking up replay gain information in '2.mp3' (parsed from the lame / xing header)

 But looking at the files, this seems perfectly valid:
```
  offset    0  1  2  3   4  5  6  7   8  9  a  b   c  d  e  f  0123456789abcdef
 ------------------------------------------------------------------------------
 00000100  00 00 4d 50  33 47 41 49  4e 5f 4d 49  4e 4d 41 58  ..MP3GAIN_MINMAX
 00000110  00 30 36 34  2c 32 30 36  54 58 58 58  00 00 00 11  .064,206TXXX....
 00000120  00 00 03 46  4d 50 53 5f  50 6c 61 79  43 6f 75 6e  ...FMPS_PlayCoun
```
 All files have an MP3GAIN_MINMAX tag, this tag is only written (and used) by mp3gain:

 I never used mp3gain myself, but according to...

 http://wiki.hydrogenaud.io/index.php?title=MP3Gain

 ..., the software applies the replay gain by changing the audio stream itself (!!).

 The MP3GAIN_MINMAX tag itself is not relevant for players.

 So it seems that vanilla music does the right thing: It uses a replay gain adjustment of 0.0
 because the audio stream itself has already been adjusted.
