### ISSUE TITLE
Replace unmaintained DragListSortView

### ISSUE THREAD

**Issue by xbao** [vanilla-music/vanilla#203]
Vanilla uses [`DragListSortView`](https://github.com/bauerca/drag-sort-listview) to display playlists and the playing queue.

The library is currently unmaintained. It doesn't look like there is a fork that is maintained either: http://forked.yannick.io/bauerca/drag-sort-listview

A possible alternative is [`AdvancedRecyclerView`](https://github.com/h6ah4i/android-advancedrecyclerview)

**Comment by xbao** [comment]
I'm trying out `AdvancedRecyclerView`. It seems okay, though the inheritance structure's a bit convoluted and the swiping sometimes has a tiny bit of jank. 

I don't really expect it to be merged, as it's a large code change (including the rotund support libraries) for very little benefit. It should be useful as an indication of what would be required to switch out DSLV if it starts causing issues on a wider range of devices.

**Comment by adrian-bl** [comment]
Wow, you are fast :-)

> I don't really expect it to be merged, as it's a large code change (including the rotund support libraries) for very little benefit. It should be useful as an indication of what would be required to switch out DSLV if it starts causing issues on a wider range of devices.

Yes: i see very little pressure to move away from DSLV at the moment: The library works pretty well (apart from this single, very rare bug) and there is still hope that someone will continue to maintain the library.

I think we should keep the AdvancedRecyclerView patch in the backburner until things really start to fall apart (eg: DSLV stops working on Android 7 or whatever)

**Comment by xbao** [comment]
> Wow, you are fast :-)

Haha thanks! But I only started it, didn't finish :) 

Yip, agree with all. Closing the issue
