### ISSUE TITLE
Playback does not resume after ringtone/call ends

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#205]
Hi all,

I noticed that when I get an incoming call, Vanilla pauses during the ring tone. If I don't pick up the call, the ringing eventually stops (when directed to voicemail), but playback does not resume.

If I pick up the call, same thing : playback does not resume when I hang up.

KDE Connect (https://community.kde.org/KDEConnect) has this nifty feature : It mutes desktop sound when a call comes in, and restores the volume after the call (whether it has been answer or not). I'm no longer missing a call when I'm listening to music at home ! ^^

**Comment by adrian-bl** [comment]
Our handling of incoming calls is really somewhat silly: This should be fixed via:
https://github.com/vanilla-music/vanilla/commit/3cfb1633fbe03668372c3a3610b54c60570460bc

VanillaMusic will (still) pause the audio playbak while the phone is ringing - but afterwards it will start to play again automatically.

But i wonder if we should implement some sort of timeout: eg: if the phone was silent for > 5 minutes: should we still automatically start to play after the user hung up the call?

**Comment by breversa** [comment]
Playback resuming immediately after call ended (either picked up or not) is totally fine to me, and what I would expect. I see no use for such a timeout. What use case did you have in mind ?

(Precision : KDE Connect actually both pauses music players AND mutes system sound on call)

**Comment by adrian-bl** [comment]
> What use case did you have in mind ?

Imagine that you had a phone call that lasted 30 minutes or so. Some users might be surprised if vanilla music automatically resumes the playback

**Comment by breversa** [comment]
Oh.
I would never have thought of it, but if other people do… I just hope that feature won't bring more bugs. :-)

**Comment by adrian-bl** [comment]
Closing as PR #197 and https://github.com/vanilla-music/vanilla/commit/954734de0558f9f868f8706d3bcaba4cd3ef1b9b have landed
