### ISSUE TITLE
Automatic creation of top-50 playlist

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#206]
I hacked up a feature to automatically create top-xyz playlists using the playcounts database (Vanilla Music already keeps track of how often a track was played, so the info is already there)

The patch is here: https://github.com/vanilla-music/vanilla/commit/564c1d19cc81d72daaab9be36e60ea0724f258eb

What do people think? Should i merge it (i'd say yes ;-))? ..should it be enabled by default or will it confuse the users?

**Comment by ToNIX-** [comment]
Yes!

**Comment by breversa** [comment]
Please merge, as an option. ;-)

I've mostly been listening to FLAC files lately, and I can't have thousands of them on my device, so I rotate them from my computer (using Clementine : https://github.com/clementine-player/Clementine ;-) ) instead, but I can see the use for people who have on-device, large, non-rotating libraries, so go ahead ! :-)

**Comment by adrian-bl** [comment]
Implemented in master via 9de67792c7b99eb36d4092e8c896b7254490152c
