### ISSUE TITLE
Sometimes, queue size is cut off

### ISSUE THREAD

**Issue by TheLastProject** [vanilla-music/vanilla#209]
I'm not sure why this happens, I can't even reliably reproduce it, I just sometimes randomly notice it.

Motorola Moto E 2015 - CyanogenMod 12.1 (Android 5.1.1)

![tmp_19704-screenshot_2015-09-24-07-12-341633291242](https://cloud.githubusercontent.com/assets/1885159/10066477/a415c148-6293-11e5-8628-98cfd1199d7c.png)

**Comment by adrian-bl** [comment]
Yes, i noticed this too - rumors (on stackoverflow) have it that singleLine turns on ellipsis="end"
We should probably switch to maxLines=1 in the layout (as we do not have to care about line breaks in this text element - maybe setting the gravity would also do some good)

**Comment by adrian-bl** [comment]
Fixed via: https://github.com/vanilla-music/vanilla/commit/ad4fa0a9d2278aa8715353dc6786a9356af0ce2f

We prepare the view now to hold at least 00/00, so the text will not be cut off while switching from 9/10 to 10/10
