### ISSUE TITLE
Create a BETA deployment

### ISSUE THREAD

**Issue by xbao** [vanilla-music/vanilla#212]
I was thinking about this today. It would be nice to have a beta release channel, as changes/fixes are tested before release and users that want the latest changes/fixes can get them.

Some considerations:

Build origin
* HEAD of master - latest changes, more chance of being unusable
* special branch/tag - requires maintenance, less chance of unusable updates

Build interval
* Every commit
* Nightly
* Every x weeks

Building & deploying
* Github release 
 * no setup, requires manual building/uploading or deploying from a CI (such as ship.io below)
 * User's need to check page for update, download & install manually
* CI - ship.io
 * some setup, automatically builds from GitHub repo
 * User's get an email with a link to the build after it occurs
 * I gave it a go this morning, took about 10 minutes to sign up and start the build. Example link to deployed APK: [link](http://mandrillapp.com/track/click/30245361/app.ship.io?p=eyJzIjoidTZncEpNdUZlRGlManpfWnpIdlRNbHQycEtJIiwidiI6MSwicCI6IntcInVcIjozMDI0NTM2MSxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2FwcC5zaGlwLmlvXFxcL2J1aWxkc1xcXC85ODQ4OGNhZS1jYmY2LTRhZjctOGNlYi0yNWY0ZGEzZjY5ZjlcXFwvYnVpbGRfc3RlcHNcXFwvOXZ1ZGRQVzNcXFwvYXJ0aWZhY3RzXFxcL3ZhbmlsbGEtcmVsZWFzZS5hcGs_YnVpbGRfYWNjZXNzX3Rva2VuPTdkOGJhZDMyZDkxNDVhZWYyXCIsXCJpZFwiOlwiOTUxZGNkMjdlMzVjNGVkNzgxNDk0Y2E1MmE2NTg0YzNcIixcInVybF9pZHNcIjpbXCJhMWJjMDMxMGJiYWM0YTI3N2MzYTIwZWRhMjJhY2VmZmU5ZjcxMzM0XCJdfSJ9)
* F-Droid custom repo
 * High amount of setup & maintenance
 * Requires manual building/uploading or deploying from a CI (such as ship.io above)
 * User's are notified by updates and install them in the usual way

What are your thoughts on the subject @adrian-bl?

**Comment by adrian-bl** [comment]
I think this would be a very neat thing to have and ship.io looks pretty much OK to me.

My main concern is the package name: Does ship.io have some way to change the package name?
If not, then users will have to first uninstall the version installed via f-droid or play store, so they will lose all settings.

It's not a big drawback (i do not expect people to hop-around that often) but still somewhat annoying.

**Comment by ToNIX-** [comment]
Could there be some way to import/export settings to storage?

**Comment by xbao** [comment]
@adrian-bl I'm not sure if ship.io supports that directly, but it allows custom build commands (I think) so I'm sure we can find a way to do it. I'll look into it when I get a chance. 

Unrelated: I bought the [vanillamusic.io](http://vanillamusic.io) domain and set up a redirect to the github page. If you want it for anything else, it's yours :)

@ToNIX- That would be nice to have regardless! Maybe make an issue? :) In the context of a beta deployment, it would still require users to manually load/store the settings. The nice thing about having a beta and non-beta app with different package names is that if the user wants to listen with the latest released version (such as if the beta build is bugging out) they can do it by simply opening a different app.

**Comment by xbao** [comment]
Oh no, looks like ship.io is shutting down: https://ship.io/ship-io-is-shutting-down/. Pity, it had a really nice setup.

**Comment by adrian-bl** [comment]
Oh, that's too bad :-(

I could actually use one of my servers as a build host if google would start to distribute an 64bit version of the SDK.. but for some reason, they are unable to provide this....
(All my hosts are runnig pure 64bit, no biarch)

**Comment by xbao** [comment]
Yeah, at my previous job we used ship.io which had the same deal. I ended up statically including the required 32 bit libs & linker and hacking the ELF headers of the SDK executables so that they used them. Fun times.

[CircleCI](circleci.com) is another very easy to use one, we could just use the free tier

**Comment by adrian-bl** [comment]
I hacked up my own small build system while playing with aws-sdk-go:

Every 24h hours, my 'build server' launches an AWS instance which will fetch the vanilla git-master, build it and drop it there: http://android.eqmx.net/android/vanilla/

**Comment by adrian-bl** [comment]
I'm closing this issue for now as building on AWS seems to work fine.
I also changed my buildscript to use a different package name + change the icon, so users can install nightly-builds and normal releases at the same time.

**Comment by xbao** [comment]
Nice! I was out of town for a few days, installed the beta deployment, looking good! I like the subtle color change for the icon, good way to know which is which

![vanilla_beta_icons](https://cloud.githubusercontent.com/assets/8990412/12013081/3e907aa0-ad63-11e5-8daa-354041285c3a.png)

Could be a good use for vanillamusic.io? If you think you might want to use it, send me your gandi.net handle and I'll transfer it to you!

**Comment by adrian-bl** [comment]
> Could be a good use for vanillamusic.io?

Yes, good idea. Hmm.. i'm usually using name.com but the transfer fee for io domains is 99$ O_O

I'll create a gandi account and send you my handle via e-mail
