### ISSUE TITLE
please allow characters like :? etc in file and folder names

### ISSUE THREAD

**Issue by sekret1** [vanilla-music/vanilla#215]
I format my android system and my external memory card with linux filesystems, in my case EXT4 or F2FS, which support characters like : and ? etc. Windows filesystems like FAT and NTFS don't support those.

It looks like vanilla only supports charakters which are supported by Windows. But since Android is a Linux system it would be cool if files containing such characters could also be played back. The default music player of cyanogenmod supports this, so it's possible ;) But I'd love to use vanilla instead!

**Comment by adrian-bl** [comment]
Where did you face issues with these characters?

We use the filesystem API provided by android, so i don't see expect any breakage with : and ?

**Comment by sekret1** [comment]
Well, for example I have the star wars soundtrack on my phone, the storage path is:

/storage/sdcard1/Musik/john williams/2005 star wars episode iii: revenge of the sith/*.ogg

It doesn't play with vanilla music, there's a popup which tells me

Failed to load song /storage/sdcard1/Musik/john williams/2005 star wars episode iii: revenge of the sith/01 star wars and the revenge of the sith.ogg. It may be corrupt or missing.

This only happens with files, which have a : in their path. Right now I don't have songs with other characters in their path, like ? or whatever, so my guess was that it's caused by vanilla, also because the stock music player of android, which is being used in cyanogenmod, plays them just fine.

**Comment by adrian-bl** [comment]
I'm afraid but this seems to be an android bug:

strace shows that 'mediaserver' (the process doing the actual playback) gets a permission-denied (while, for some reason, other processes are able to open the file just fine)

> the stock music player of android, which is being used in cyanogenmod, plays them just fine.
This is not true for me:

On my phone, the CM-Stock-Player, Google Music and Vanilla Music all fail to play the file (all of them are using the mediaserver process)
Only VLC is able to play the file (vlc doesn't use mediaserver and is therefore not affected by this issue)

**Comment by sekret1** [comment]
Hm, ok, that's really interesting! May I ask what version of Android / CyanogenMod you are using? I'm on 5.1.1, current snapshot.

How did you do this strace? I only know strace from Linux and since I cannot find any strace program on f-droid I'm a bit lost. But I'd love to show my output to you and the CyanogenMod people.

**Comment by adrian-bl** [comment]
My build is about 2-3 weeks old (self-compiled for Z3C)

strace is included in CM, but you need to enable root via adb, then do:

adb shell
# ps | grep mediaserver
..take note of the PID
# strace -ff -s 4096 -p PID_OF_MEDIASERVER | grep ogg

**Comment by sekret1** [comment]
Thanks! Actually I should have known this ;)

With vanilla, I think I get the same output you get (with the denied permission)

But with the stock music player strace goes completely crazy! Only launching it produces so much output my laptop's cpu goes hot only by showing the data in the terminal. Looks very strange to me and might be a clue why my battery drain feels so high when listening to music.

Ok, I believe you that it's not caused by vanilla, so this bug report is hereby resolved.

* Adrian Ulrich <notifications@github.com> [01.10.2015 19:30]:

**Comment by mathstuf** [comment]
Fixed in 1.0.34 by 939c59fe71d10c1034e130c62f96541fd91ac6bb.

**Comment by sekret1** [comment]
Thanks! Now it works fine and I can finally use this player 😊
