### ISSUE TITLE
Donation version?

### ISSUE THREAD

**Issue by KonomiKitten** [vanilla-music/vanilla#217]
I was wondering if the idea of having a VIP version of Vanilla Music would be a good idea? **Before going into it I want to clarify I am in no way suggesting features would be missing from the default version.** I'm thinking of in the way Xabber currently do this. They have a VIP version which basically only has a different icon as a form of donating to support the developer. I'd like to be able to slide the developers of open source projects a donation and this seems like a nice way to do it for android apps.

What does everyone think?

**Comment by adrian-bl** [comment]
I used to have a 'donate app' in the play store but removed it after google forced people to publish their full address in the play store.

Also note that there is a 30% transaction fee.

I'd rather add a donate link in the Settings (or about) dialog to a paypal/bitcoin/flattr link.

@aminb What do you think about this?

**Comment by ToNIX-** [comment]
I'm all in for a donate link in the Settings, but make it pretty obvious (like on the last line, not buried in the about dialog where people never look).

**Comment by aminb** [comment]
Yeah I think a donate link in the settings would be nice.

@adrian-bl Have you heard about [gratipay](https://gratipay.com/) or [bithub](https://whispersystems.org/blog/bithub/) ?

**Comment by adrian-bl** [comment]
Bithub would look pretty nice, but requires a coinbase account: Creating one requires you to upload a photo of your ID/Passport .. and i won't do that.

I applied for an GratiPay account, see: https://github.com/gratipay/team-review/issues/90

**Comment by adrian-bl** [comment]
We got accepted by Gratipay and i added a donate-button to the README.md - let's see how rich we will get ;-)
