### ISSUE TITLE
Equalizer doesn't load

### ISSUE THREAD

**Issue by halnine** [vanilla-music/vanilla#218]
Under settings > audio > equalizer
no screen is loaded, as if the menu item is dead.

app version: Vanilla Music v1.0.31 
OS: Android 4.1.1

**Comment by adrian-bl** [comment]
Does the equalizer work in any other application?

We are using the systetem-equalizer dialog, so if your phone does not have a builtin version, this is expected to happen

**Comment by halnine** [comment]
Not really sure I know what this means. Never even knew there was a system EQ.

**Comment by adrian-bl** [comment]
Android provides a 'native' Equalizer dialog, and that's what we are using.
The equalizer only shows effects/config-options which the device is actually able to do (some devices have full fledged sound effects while others only support minor modifications)

Having the dialog not show up either means that your vendor messed up android badly or that your hardware doesn't really support any effects. There is not much we can do about this.
