### ISSUE TITLE
LRU should have a disk cache

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#220]
We should store generated covers in a disk cache.

Care should be taken to limit the TTL of 'empty' covers (eg: we are indexing the album while the user uploads the contents and cover.jpg is not present yet)

**Comment by adrian-bl** [comment]
@aminb i hacked up a branch with an on-disk cache:
https://github.com/vanilla-music/vanilla/tree/disk-cache

Could you give it a try to see if it makes things better (or worse/same) on your device?
I don't see much of a difference on my Z3, but on my Moto G, the difference is visible for albums with large cover artwork (loaded from cover.png by vanilla itself)

**Comment by aminb** [comment]
@adrian-bl I didn't see that big of a difference on my Nexus 5 either, however without caching I did sometimes see cover arts fade-in (casually), but with caching I never got that which is nice.

So although getting casual fade-ins weren't that big of a problem for me, I prefer not seeing them at all, and for that reason I think the caching makes things better.

And I didn't notice any weird behaviour, so unless you've noticed anything unsual, this is great and I think we're good for merging this :+1:

**Comment by adrian-bl** [comment]
> And I didn't notice any weird behaviour, so unless you've noticed anything unsual, this is great and I 
> think we're good for merging this 

Cool, thanks for having a look at it!

So i'll include the change (after doing some fine-tuning) in 1.0.34 (1.0.33 has been tagged yesterday and should show up soon on f-droid)

**Comment by aminb** [comment]
Sounds good, thanks!

**Comment by kirbyfan64** [comment]
Is this going to be optional for those of us who don't have that much SD space left?

(Granted, I only have about 5 cover arts, but I'm trying to get more.)

**Comment by adrian-bl** [comment]
It uses the 'app-internal-cache' which is usually located on the internal storage. (eg: /data)

Android will automatically flush the cache if the device runs out of storage space (and you can do this yourself via: Settings -> Apps -> Vanilla -> Clear Cache).
Also: The code will try to keep the cache at ~25MB, so storage space shouldn't be a big issue

**Comment by adrian-bl** [comment]
Implemented in: https://github.com/vanilla-music/vanilla/commit/d5d0b23db42d8d32f2f27dbc3af905cd810cc536

I rewrote the previous patch to use an SQLite database instead of the raw-files storage.
This simplifies the code a lot and makes purging old entries much simpler and faster.
