### ISSUE TITLE
Import/Export settings

### ISSUE THREAD

**Issue by xbao** [vanilla-music/vanilla#222]
It would be nice to be able to save settings to a file and restore them from that file. Raised by @ToNIX- in #212 

A starting point could be the following StackOverflow answer: [How can I backup SharedPreferences to SD card?](http://stackoverflow.com/a/10864463/2631829)

Thoughts?

**Comment by ToNIX-** [comment]
@xbao You have my support :)

**Comment by adrian-bl** [comment]
This looks fine to me (and using an hardcoded path, eg /sdcard/vanilla-settings.db is probably good enough).

If someone would like to work on this: feel free to send me a pull request :)

**Comment by Almtesh** [comment]
You could just make a tar.gz of the apps data, I don't know how the settings are stored, but it can work.
