### ISSUE TITLE
option to display audio bitrate, format, bit depth, fe...

### ISSUE THREAD

**Issue by calimou** [vanilla-music/vanilla#224]
Hi,
Very few player provides those informations, will vanilla make it ?

**Comment by adrian-bl** [comment]
Vanilla Music already displays this information: Just do a long-press on the title in the playback view.

**Comment by calimou** [comment]
Thanks Adrian, that's cool ! Note the long-press doesn't work when the title is set to be displayed in the center of the playback view. (it pauses the playback instead).
