### ISSUE TITLE
White theme broken on Android 6

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#225]
Google changed the white-color. Theme Helper should fix this up.

**Comment by adrian-bl** [comment]
I created a new 'android 6' branch which fixes layout issues on Android M and also uses the new permission model:
https://github.com/vanilla-music/vanilla/compare/master...vanilla-music:android6

So far i was only able to test it in the emulator and everything seems to work ok.

@aminb @xbao Do you have access to an Android 6 device? It would be nice to confirm that everything is working on real-hardware before merging this into the master (make sure to uninstall any older versions on of Vanilla Music in order to go trough the new permission-request dialog)

**Comment by aminb** [comment]
@adrian-bl Unfortunately I don't have any Marshmallow devices and I can't flash any ROMs at the moment, so I'm stuck on CM 12.1 (Android 5.1.1) for a while until I find some time to figure things out.

**Comment by xbao** [comment]
I did see one of the nexus' at work upgraded to M, I'll have a look when I get to the office

**Comment by xbao** [comment]
Yip I got one, I'll give it a go after close of business. With respect to the styling, what I looking for? Is it obviously wrong?

**Comment by xbao** [comment]
Seems fine to me:

![vanilla-prefs](https://cloud.githubusercontent.com/assets/8990412/10422395/9bdce210-7105-11e5-81e1-228bd6f321e1.png)
![vanilla-playlists](https://cloud.githubusercontent.com/assets/8990412/10422394/9bdb0602-7105-11e5-82e9-163a86c09521.png)
![vanilla-songs](https://cloud.githubusercontent.com/assets/8990412/10422393/9bda9668-7105-11e5-8e54-95239851cc65.png)
![vanilla-nowplaying](https://cloud.githubusercontent.com/assets/8990412/10422396/9bdcf1ec-7105-11e5-9f05-5d8f8d821559.png)

I played some songs, made a couple of playlists. Switched to dark theme, switched back. Didn't notice anything out of the ordinary.

**Comment by adrian-bl** [comment]
@xbao thanks a lot for the testing - looks indeed fine.

> Yip I got one, I'll give it a go after close of business. With respect to the styling, what I looking for?
> Is it obviously wrong?

The only big breakage was the background color in the full playback activity as google changed the background color of the light theme from 0xffeeeeee to 0xfffafafa

How did it behave after you granted it the requested permissions? Did it correctly restart itself?
I'm asking because i am using a pretty ugly hack to get things working, see:

https://github.com/vanilla-music/vanilla/compare/master...vanilla-music:android6#diff-de456221087dd40d2e3b777dd0edc6a4R66

The code kills the currently running PID/VM: This is required (at least in the emulator) because otherwise we would end up with partial permissions: Reading from the content provider would work, but reading files from /sdcard won't work until the VM gets restarted :-/

**Comment by xbao** [comment]
Hmm, it never requested any permissions. Could it be because nexus devices don't have a 'real' sdcard?

**Comment by adrian-bl** [comment]
No: the permission is needed to read any file outside the private app dir and to query the media database.

Did you fully uninstall the old version before installing the new (m-sdk) compiled version?

**Comment by xbao** [comment]
There wasn't an existing install (my install would have failed due to cert conflict), but I may have installed it twice or something stupid. I'll give it another go tomorrow.

---- Adrian Ulrich wrote ----

**Comment by xbao** [comment]
Yip, must have done something stupid. Dialog popped up, restarted fine (barely noticeable): https://xbc.nz/owncloud/index.php/s/j8ZQ1Pexn3zpioT 

Let me know if that link works, first time I've tried using my owncloud setup :)

**Comment by adrian-bl** [comment]
Yes: it worked :-)

Thanks a lot for testing it: i'm glad that my restart hack also works on real hardware :-)

**Comment by adrian-bl** [comment]
Closing as the android6 branch was merged (via: https://github.com/vanilla-music/vanilla/commit/a1552370c66803c547b5303d60cfa0966904a3be)

Thanks again for testing!
