### ISSUE TITLE
Light theme has obscure color on play mode buttons

### ISSUE THREAD

**Issue by snelltheta** [vanilla-music/vanilla#226]
So the disabled button appears as grey and the enabled button is a very washed out blue that appears grey to the user. Exaggerating the colors would be helpful for usability. This also goes for the dark mode, but to a lesser extent.

**Comment by adrian-bl** [comment]
This may depend on the screen, but i can clearly tell the difference between the blue + grey on my Z3C.

What RGB values would you recommend?

**Comment by snelltheta** [comment]
That is a hard question to answer,

**Comment by adrian-bl** [comment]
Closing as i can not 'reproduce' this issue on my devices.
Feel free to reopen the bug with some suggested hex values.
