### ISSUE TITLE
Accelerometer shake acts while not playing

### ISSUE THREAD

**Issue by snelltheta** [vanilla-music/vanilla#233]
This symptom occurs when the always-on notification is enabled. Whether or not screen is off and whether or not songs are playing.

**Comment by adrian-bl** [comment]
This works as designed: Shakes are processed as long as the service is active (otherwise the play/pause action would be useless)

**Comment by snelltheta** [comment]
This would be fine for the play/pause action, but pausing a podcast and leaving the phone in my pocket or accidentally bumping it while it is in pause mode, it is undesirable to skip to next track.
