### ISSUE TITLE
Issued with : in song titles?

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla#235]
Not sure if this was already reported. I'm not much of an Android developer (I hate Java :), so let me know if there's any more info you need.

Basically: if I try to play a song with a colon in the filename or title (not sure which one), Vanilla Music says the file cannot be opened or is corrupted. Which is kind of irritating when you get all your music from YouTube... :O

**Comment by adrian-bl** [comment]
This was already discussed in bug #215 
Unfortunately there is nothing we can do about it, as it is a bug/feature of the android media framework (Vanilla Music itself would handle the files just fine)
