### ISSUE TITLE
Enqueue next enhancement

### ISSUE THREAD

**Issue by ToNIX-** [vanilla-music/vanilla#236]
When long pressing an item (song, album, artist, playlist, genre), have an "enqueue next" action added to the context menu. This would, of course, enqueue the song(s) after the current one.

The new context menu would be:
- play
- play next
- enqueue
- enqueue next

**Comment by adrian-bl** [comment]
We already have a 'play as next' option.
I do not see a difference between 'play next' and 'enqueue next'

**Comment by ToNIX-** [comment]
You're right, but "play next" always enqueue by default (it doesn't clear the "now playing" list to play the selected songs). Should it be renamed to "enqueue next" instead of "play next"?

The new context menu would be:
- play
- enqueue
- enqueue next

**Comment by adrian-bl** [comment]
> Should it simply be renamed to "enqueue next" instead of "play next"?

I'm not a native english spearker, but 'play as next' is, IMO, a much better description than 'enqueue next'.
But how do other players call this feature? We should probably use the same wording

**Comment by adrian-bl** [comment]
The Squeezebox server also seems to label the feature as 'Play Next'
![](http://i.imgur.com/T2gAgcB.png)

**Comment by ToNIX-** [comment]
Alright, english isn't my first language too. Let's keep it this way, thanks for checking it out!
