### ISSUE TITLE
Add support for Windows Media Audio (WMA) file format

### ISSUE THREAD

**Issue by mary-kate** [vanilla-music/vanilla#238]
Currently Vanilla Music does not support Microsoft's [Windows Media Audio (WMA)](https://en.wikipedia.org/wiki/Windows_Media_Audio) file format. It would be awesome if it did, since WMA is the default file format for audio files copied from CD-ROMs via Windows' built-in Windows Media Player.
While most "power users" like myself are able to easily convert our audio files to an alternative format supported by Vanilla, like MP3, this is likely not feasible for newbies who want things to "just work" out-of-the-box.

**Comment by adrian-bl** [comment]
Vanilla Music uses the media framework of android: It does *not* ship whit its own set of codecs.

So the lack of WMA support is the fault of your phone vendor who choose to not implement (and license! WMA is *not* an open format.) WMA.
