### ISSUE TITLE
Marshmallow bugs

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#243]
So I don't know if these are fixed or not on `master`, but in 1.0.33, scrolling the list of artists, albums, etc. just stutters at the top. Kinetic scrolling or slowly scrolling both do this. It also seems that Vanilla is refusing to play some songs that Apollo can. Maybe targeting SDK 23 will fix this? Will try a local build here to see if `master` is OK.

**Comment by kirbyfan64** [comment]
I have version 1.0.32, and it works. The only time it stutters is when I'm running an SD card scanner. Do you have one installed?

**Comment by mathstuf** [comment]
No. It doesn't seem to be a performance stutter. It just refuses to scroll past the first page.

**Comment by mathstuf** [comment]
Custom build can't play some songs either (first I thought it was 48kHz files that couldn't be played, but Apollo handles them just fine and I found some 44.1kHz files which won't play either).

**Comment by adrian-bl** [comment]
So did this also happen on 1.0.32 ? (would be a surprise as we didn't touch the library pager in 1.0.33: https://github.com/vanilla-music/vanilla/compare/1.0.32...vanilla-music:1.0.33 - but the git HEAD contains a newer version of the viewpager code)

> just stutters at the top.
What do you mean exactly? Is the animation not fluid or does it refuse to display the contents?
I do not have a real device with Android 6, but the artist + album view works just fine for me in the emulator (with 256 fake albums and artists)

About the non-working file: Feel free to mail me such a file to adrian@blinkenlights.ch (up to 50MB are accepted by my mailserver)

**Comment by mathstuf** [comment]
1.0.32 is fine.

As for files:

http://benboeckel.net/files/441khz.ogg

I'll probably have to send the 48khz file (that one is OCRemix and Creative Commons).

**Comment by mathstuf** [comment]
48kHz file sent.

**Comment by adrian-bl** [comment]
> 1.0.32 is fine.

Did you downgrade to 1.0.32 or was it ok before upgrading to 1.0.33 ?
I tested the HEAD again in an emulator running 6.0 and i see no issues.

You could try to pin-point the faulty commit by going trough the commit list from 32 -> 33 if you have the SDK installed (diff: https://github.com/vanilla-music/vanilla/compare/1.0.32...vanilla-music:1.0.33). But as i said: We didn't touch any of the libraryadapter code.

> http://benboeckel.net/files/441khz.ogg

This URL throws a 403. I tested the 48kHz file on my Z3 (CM 12.1) and the Emulator (6.0) and it plays fine on both of them.

**Comment by mathstuf** [comment]
I had downgraded (running from FDroid). I'll check permissions on the file. I'm using a Nexus 5X.

**Comment by mathstuf** [comment]
Ah, found the "failed to play a file" problem:

```
11-12 09:19:33.434  3723 31499 E FileSource: Failed to open file '/storage/emulated/0/Music/music/SoulEye/2011 — PPPPPP: The VVVVVV Soundtrack/1/11 — SoulEye — Pressure Cooker.ogg'. (Permission denied)
11-12 09:19:33.434  3723 31499 E GenericSource: Failed to create data source!
11-12 09:19:33.422 31499 31499 W generic : type=1400 audit(0.0:245): avc: denied { search } for name="default" dev="tmpfs" ino=573 scontext=u:r:mediaserver:s0 tcontext=u:object_r:storage_file:s0 tclass=dir permissive=0
11-12 09:19:33.435  3723 31498 D NuPlayerDriver: notifyListener_l(0xf2e58120), (100, 1, -2147483648)
11-12 09:19:33.435 31080 31206 E MediaPlayer: error (1, -2147483648)
11-12 09:19:33.439 31080 31093 E VanillaMusic: IOException
11-12 09:19:33.439 31080 31093 E VanillaMusic: java.io.IOException: Prepare failed.: status=0x1
11-12 09:19:33.439 31080 31093 E VanillaMusic:  at android.media.MediaPlayer._prepare(Native Method)
11-12 09:19:33.439 31080 31093 E VanillaMusic:  at android.media.MediaPlayer.prepare(MediaPlayer.java:1163)
11-12 09:19:33.439 31080 31093 E VanillaMusic:  at ch.blinkenlights.android.vanilla.PlaybackService.prepareMediaPlayer(PlaybackService.java:628)
11-12 09:19:33.439 31080 31093 E VanillaMusic:  at ch.blinkenlights.android.vanilla.PlaybackService.processSong(PlaybackService.java:1319)
11-12 09:19:33.439 31080 31093 E VanillaMusic:  at ch.blinkenlights.android.vanilla.PlaybackService.handleMessage(PlaybackService.java:1498)
11-12 09:19:33.439 31080 31093 E VanillaMusic:  at android.os.Handler.dispatchMessage(Handler.java:98)
11-12 09:19:33.439 31080 31093 E VanillaMusic:  at android.os.Looper.loop(Looper.java:148)
11-12 09:19:33.439 31080 31093 E VanillaMusic:  at android.os.HandlerThread.run(HandlerThread.java:61)
```

but it doesn't make any sense? The filesystem permissions are the same between "works" and "doesn't work" files. And Apollo can play them. The audit line indicates that SELinux may be getting in the way. I wonder if there's some bit that Apollo sets which Vanilla isn't?

**Comment by mathstuf** [comment]
Also, upgrading to 1.0.33, the scroll stuttering isn't there. Not sure what that was about.

**Comment by adrian-bl** [comment]
Ah, thats a known android bug:

Your file has a colon in its filename and mediaserver refuses to play such files, see: https://github.com/vanilla-music/vanilla/issues/215

I tested such a file with Apollo in the emulator and it also fails (as expected) to play the file:

> 11-12 16:19:52.600  1015  2963 E FileSource: Failed to open file '/storage/foobar/jay/x:0.ogg'. (Permission denied)

**Comment by mathstuf** [comment]
Apollo *can* play files with colons in it though on my phone…but not if I open it from the File Manager, only from its library (I see the FileSource error there). I'm using Apollo from F-Droid, version 1.1.

**Comment by mathstuf** [comment]
Clarification: the FileSource error happens when I open from the File Manager.

**Comment by adrian-bl** [comment]
Ok, i had a look at Apollo's source and it seems to use content://-style URLs -- sometimes.

The reason on why we fail is because we are using MediaPlayers setDataSource(path) - and it seems that android expects a file://-style path while silently accepting most unix-style paths.

The funny thing is, that Androids *own* setDataSource(context, uri) function also fails on such paths as it also passes unix-style paths to the setDataSource function...

Well: In the end, all of these functions call setDataSource(Filedescriptor) anyways, so i changed the code to do the same:
https://github.com/vanilla-music/vanilla/commit/939c59fe71d10c1034e130c62f96541fd91ac6bb

With this fix, i'm able to play files with a ':' in the pathname on my device.

**Comment by mathstuf** [comment]
Thanks! I'll try it out when F-Droid has it (I doubt I'll have time before they do the build).

**Comment by kirbyfan64** [comment]
YESSSSS!!!!!

**Comment by mathstuf** [comment]
Confirmed to work :) . Apollo now no longer necessary :D .

**Comment by okungnyo** [comment]
Wow, I follow a lot of projects on Github (well, about 10) and this is probably the first time I have seen a developer do a 180 and actually listen to feedback, instead of brushing off the user like they are little children, saying that (whatever X) will never be changed, and closing the issue.

A truly great developer, thumbs up.

**Comment by adrian-bl** [comment]
Thanks, but the credit should go to @mathstuf who did not listen to me when i tried to tell him that this is an android bug ;-) (and demonstrated that it *does* work in apollo)

**Comment by mathstuf** [comment]
In some way, it *is* an Android bug. It shouldn't be trying to match the colon as the protocol separator because a protocol may not have a `/` character. And `EPERM` is a stupid `errno` for such a problem. `EINVAL` would be better.

**Comment by adrian-bl** [comment]
> And EPERM is a stupid errno for such a problem. EINVAL would be better.

Hmm.. maybe Mediaserver thinks that it will open a network stream and refuses to do so as Vanilla Music has no network permissions. If this is the case, then the error message makes somewhat sense (and could be an interesting attack vector)

Just FYI: 1.0.34 was released on F-Droid today - the Play Store release will happen in ~4 weeks (I'm in tokio for a few weeks - so things have to wait).

For people using the play store release: A pre compiled and signed version can be downloaded from:

https://mega.nz/#!25VXxQpR!ZFWRNajZtv2QYNwWqRLKw0oorfBNqO1FvrK9z6sSYtg

**Comment by okungnyo** [comment]
Why such a huge time gap between F-Droid and Play Store, if you don't mind my asking?

**Comment by mathstuf** [comment]
> (I'm in tokio for a few weeks - so things have to wait).

I think manual upload is necessary for the Play store, but F-Droid maintainers can build tags themselves.

**Comment by adrian-bl** [comment]
Because: As i mentioned: i'm currently 9500km away from home without access to a computer where the SDK could be installed (my laptop runs 64bit-only linux)

**Comment by okungnyo** [comment]
I didn't know that F-Droid built the apps themselves.

adrian-bl, I was not asking why the Play Store release is late, I was asking why 1.0.34 was released on F-Droid but not Play Store.
