### ISSUE TITLE
Reverse Engineer Android 6 Opus replay gain

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#245]
Check if (how?) the mediaserver handles opus replay gain and configure `bastp' to match.

(Is R128 checked? Does it obey header fields?)

**Comment by kepstin** [comment]
I've taken a quick look at the public Android M source, and it looks like

- the header "output gain" field is unconditionally applied at the decoder stage (the value is read from the header and passed to the decoder library via a ctl, which is the normal way of implementing this).
- The tag parsing code is shared between the opus and vorbis implementations
- I can't find any code that handles or applies the R128 gain tag values; they appear to be ignored.

**Comment by adrian-bl** [comment]
> the header "output gain" field is unconditionally applied at the decoder stage
> (the value is read from the header and passed to the decoder library via a ctl, which is the normal way of implementing this).

Hmm: ok:

So if replay gain is enabled, we can ignore the header value (as android already took care of it) and only have to add the R128/REPLAYGAIN values.
But if replay gain is disabled, we would have to undo androids correction.. not sure if this is possible as we are not able to raise the volume to more than (what android thinks is) 100%... hmm.. this will be tricky :)

**Comment by kepstin** [comment]
The ogg opus spec explicitly says that "Virtually all players and media frameworks SHOULD apply [the header output gain] by default." 

Basically, you shouldn't ever reverse the gain applied from the header "output gain" field; it's treated as part of the audio encoding. It's pretty much the same as if someone had used e.g. the 'mp3gain' tool to adjust the volume of an mp3 for non-replaygain-aware players.

**Comment by adrian-bl** [comment]
> It's pretty much the same as if someone had used e.g. the 'mp3gain' tool to
> adjust the volume of an mp3 for non-replaygain-aware players.

Ah, thanks! I never understood the meaning of the header field but this now makes sense.

Ok, so in this case i won't undo (and probably do not even have to parse) the gain set by the header

**Comment by adrian-bl** [comment]
We do now read opus headers and detect them to have replay gain
