### ISSUE TITLE
Option to make vanilla ignore permanent and temporary changes in audio focus.

### ISSUE THREAD

**Issue by timwelter09** [vanilla-music/vanilla#247]
Would be a nice feature to have as it's kinda annoying to have my music pause everytime I play a video or open a game which changes the audio focus.

**Comment by okungnyo** [comment]
This would be amazing.

**Comment by adrian-bl** [comment]
Targeted this Feature for 1.0.34.

I see 2 ways to implement this:

#1 An option to ignore any audio focus changes

#2 An option to rewrite permanent audio losses to 'duckable' losses. eg: VanillaMusic would decrease the volume to 50% while playing a youtube video.

I'd prefer #2 as the user then still can change the volume to 0% (= be silent but keep playing) or 100% (= just keep playing).

**Comment by adrian-bl** [comment]
I hacked up a prototype of #2 in https://github.com/vanilla-music/vanilla/commit/cd93f28df78456bdd00200d41d367a736e7456dd

**Comment by adrian-bl** [comment]
pushed to master via: https://github.com/vanilla-music/vanilla/commit/b42e92367545e7a8693fce3c492d70f892562230
