### ISSUE TITLE
Rename [Preferences] to [Settings]

### ISSUE THREAD

**Issue by okungnyo** [vanilla-music/vanilla#250]
I understand that Linux applications call it "Preferences", but in the world of Android, 99% of app call it "Settings".

**Comment by adrian-bl** [comment]
The Settings menu entry is already called 'Settings'
Where did you spot the string 'preferences'?

**Comment by okungnyo** [comment]
Oh, was this a recent change?

**Comment by adrian-bl** [comment]
No

**Comment by okungnyo** [comment]
I guess I'll just wait for the new version to reach the Play Store in four weeks then...
