### ISSUE TITLE
Hardware button volume & track control [Request]

### ISSUE THREAD

**Issue by Vonotar** [vanilla-music/vanilla#253]
Hello there,
it will be possibile to add an option to use button volume on phones as track control when the phone is locked?

As example, by long press volume up it will skip to next track. I really love to have this feature.
As far as I know there aren't app using it, but it's by defaul in CGM.

Thank you :)

**Comment by okungnyo** [comment]
CGM?

**Comment by Vonotar** [comment]
It stay for cyanogenmod, an Android ROM.

**Comment by adrian-bl** [comment]
No: Hardware buttions are handled by the device itself.

Vanilla Music is just a consumer and can not change the behaviour of hardware buttons.

**Comment by adrian-bl** [comment]
..that said: skipping tracks using the volume buttons works perfectly on my phone even in locked mode (CM 12.1 for Z3C), so this must be a bug in your ROM
