### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by thomassimonet** [vanilla-music/vanilla#254]
Hi all, I'm new to this project and I wanted to help a bit. Sorry if this is not the right place (I'm new to GitHub) or if it has already been discussed, but I wanted to know how the translations are handled with Transifex. 
I updated the French strings today (almost complete now) and added some for Esperanto (from 0 to around 15%). But how and when is modified the content in the app ? Is it automatically handled between Transifex and GitHub, or do I have to update a file ? I'd be interested to know. Also how often is updated the app on GooglePlay ?

Thanks in advance and sorry for the silly questions.

**Comment by tonghuix** [comment]
https://www.transifex.com/projects/p/vanilla-music-1/

**Comment by thomassimonet** [comment]
Thanks but that doesn't help me. I modified the strings with transifex. How are they updated to the GitHub project ?

**Comment by tonghuix** [comment]
someone from this project who has privilege will merge our translation to next release. I hope so, maybe next release not far behind..

**Comment by adrian-bl** [comment]
@thomassimonet 

> But how and when is modified the content in the app ? Is it automatically handled between Transifex 
> and GitHub, or do I have to update a file ?

The updates are not automatically: i usually 'sync' github + transifex a few days before tagging a new release. So as a translator on transifex: there is nothing you must do to 'trigger' an update: i'll take care about it.

> Also how often is updated the app on GooglePlay ?

Whenever a new release is ready ;-) (usually each 4-10 weeks).


Btw: Thanks a lot for your contribution!

**Comment by thomassimonet** [comment]
Thanks :) 
I have another question about the languages : How is it chosen in the app, is it detected with the one used in Android? Because I didn't find the "esperanto" language in the Android settings so I don't see how to use it in Vanilla...

**Comment by adrian-bl** [comment]
> is it detected with the one used in Android?

Yes: Vanilla Music uses the standard localization (builtin framework) of Android and will always use the configured system language (while falling back to English for missing strings)

> Because I didn't find the "esperanto" language in the Android settings so I don't see how to use it in Vanilla...

Oh yes: that's a shame: seems like Android really doesn't support Esperanto.
Transifex does because it isn't limited to Android - it can be used for almost any i18n system out there

**Comment by thomassimonet** [comment]
Ok thanks. So there's no need to translate to esperanto, I did it for nothing ^^ I'll try to complete the french, that will be more useful.

**Comment by adrian-bl** [comment]
Maybe google will include it in a newer version of Android - but i doubt it as such things seem to take a loooong time in the android world ;-)
