### ISSUE TITLE
Playing files from folder?

### ISSUE THREAD

**Issue by anahuj** [vanilla-music/vanilla#256]
In the file folder tab: how to play all files with one click? Player plays only the first file. Tried to fiddle with settings but nothing helped ("play all", "add all to queue" etc).

Someone else requested the selection of multiple files but you went on arguing on nerd stuff (shame). Does the player have selection of multiple files?

If not yet implemented, implement these:
(1) Play all files from the folder.
(2) Select and put all files from the folder to playlist.

I prefer playing directly from folders. My Samsung mp3 player works like that, and it is only way to play when mp3 files do not have artists/song texts - just plain mp3 files. I record from youtube and use file names 001.mp3, 002.mp3 etc - no tags.

**Comment by adrian-bl** [comment]
> In the file folder tab: how to play all files with one click? Player plays only the first file. 

Clicking on an item in the files browser will always expand the view (= go into the subfolder)
The only way to (recursively) play a folder is to long-click on it and hit 'Play'

> but you went on arguing on nerd stuff (shame).
Well thanks. Insulting the lead developer of a project probably won't help :-)

> If not yet implemented, implement these:

These are already implemented. But as i said: You must long click on the folder to bring up the context menu.
