### ISSUE TITLE
How to delete from queue?

### ISSUE THREAD

**Issue by anahuj** [vanilla-music/vanilla#257]
I don't know how to delete songs from queue. I find only options to delete either all or the rest. Cannot select a song (or multiple) and delete that from the queue.

(Any alternative Android player which already have all the whistles and bells? Open source, of course. Edit: Checked players - Vanilla is best we have in GPL domain.)

**Comment by ankitmhatre** [comment]
@anahuj I can't be sure but the piece of code from line 65 to line 70 in ShowQueueActivity.java can be replaced by this:


mListView.setOnItemLongClickListener(new OnItemLongClickListener() {
			@SuppressWarnings("deprecation")
			@Override
			public boolean onItemLongClick(AdapterView<?> parent, View view, final int position, long id) {
			AlertDialog ad=	new AlertDialog.Builder(ShowQueueActivity.this).create();
			ad.setTitle("Dequeue");
			ad.setMessage("Are you sure to dequeue?" );
			ad.setCanceledOnTouchOutside(true);
			ad.setButton("Cancel", new DialogInterface.OnClickListener() {
				
				@Override
				public void onClick(DialogInterface dialog, int which) {
					// TODO Auto-generated method stub
					
				}
			});
	ad.setButton2("Dequeue", new DialogInterface.OnClickListener() {
				
				@Override
				public void onClick(DialogInterface dialog, int which) {
					// TODO Auto-generated method stub
					mService.removeSongPosition(position);
				}
			});
			ad.show();
				return true;
			}});


@adrian-bl I think you should implement this

**Comment by ToNIX-** [comment]
You can swipe a song to remove it from the queue (right to left. starting on the little squares used to re-arrange the queue).

**Comment by adrian-bl** [comment]
@ankitmhatre Thanks, but i do not think that we need a context menu for this. Swiping items 'out' is a common UI pattern on Android.

**Comment by ankitmhatre** [comment]
I am Sorry I never knew :( It had that. My bad.

**Comment by ToNIX-** [comment]
@ankitmhatre It took me a while to figure it out too!
