### ISSUE TITLE
Close button (X) on vanilla widget in "pull down status bar" is not working

### ISSUE THREAD

**Issue by quite** [vanilla-music/vanilla#258]
The close button (X) on the vanilla widget in the "pull down status bar" is not working. It does not do anything. So, I cannot exit the program, and thus not get rid of the vanilla icon in the status bar. Sorry, I most probably don't have the correct terminology.

This is vanilla 1.0.35 on a Nexus 5 with Cyanogenmod 12.1 (Android 5.1.1).

I'd say the situation has been like this since quite some versions. Possibly since I upgraded from Cyanogenmod 11 (Android 4.4) a couple of months back...

**Comment by adrian-bl** [comment]
This works perfectly for me on all devices (from android 4.2 up to 5.1 and CM 12.1)

Maybe you changed the notification mode to 'Always' (= this makes it impossible to close the notification) in Settings -> Notifications -> Notification mode ?

**Comment by quite** [comment]
Aha! Yes, that's correct. Changing that setting to "show when playing" does
let me close the notification. Also, the notification seems to stay around
even when "playing" actually is *paused*. This is just fine for me, since I
do want to see and use the notification even if I temporarily pause the
music. But it's not very clear from the settings UI that this is how it
works (if it's even consistent on different OS and devices). And this is
probably why I changed the setting in the first place -- I want the
notification when playing & paused, but I also want the possibility to get
rid of it. I'm quite certain that I never touched it again since.

Should the close button perhaps be removed when "always show" is set? But
what is the usecase for that anyway?

**Comment by adrian-bl** [comment]
> Also, the notification seems to stay around even when "playing" actually is *paused*

This depends on how the Vanilla Music was paused: It will vanish if the pause was initiated from a widget or the playback activity. Pauses from the Notification or a headset-unplug will keep the Notification alive (to give the user the possibility to quickly resume playback).

> Should the close button perhaps be removed when "always show" is set?

Yes, it would make sense to hide it in always-shown mode.

> But what is the usecase for that anyway?

The always-shown mode? Uhm... to keep the notification around as long as possible :-)

**Comment by quite** [comment]
Ah, perfect. I'll close this and add a ticket for removing the close button in always-shown mode.
