### ISSUE TITLE
Doesn't seem to send song info to Pebble

### ISSUE THREAD

**Issue by LoneFenris** [vanilla-music/vanilla#260]
It seems my Pebble Classic can properly control the player (play/pause, skip), but shows no song info for the currently playing song when using Vanilla. Song info shows fine on my car's display, though. Pebble song info works fine with both VLC and Apollo. Android 5.1.1.

**Comment by adrian-bl** [comment]
I don't own a Pebble so i can't debug this - but the metadata shows up just fine on google wear.

Appollo seems to use MediaSession while we are using the (old) RemoteControlClient - we should migrate to MediaSession anyway, this might also fix #132 and would *probably* also make things work on Pebble

**Comment by LoneFenris** [comment]
I understand. I'll be happy to let you know if it worked.

**Comment by adrian-bl** [comment]
@LoneFenris Could you please give the APK at https://drive.google.com/file/d/0Byx0H5q6Z7OCYXVpZGVZZzZmbk0/view?usp=sharing a try?

This build uses the new mediaSession API of Android >= 5.x

Note that you must uninstall your currently installed version of VanillaMusic.
(...and you'll have to uninstall this test version after testing in order to get new updates via playstore/f-droid as it was signed using a different key)

**Comment by LoneFenris** [comment]
Doesn't seem to have made a difference for the issue on my end, though the version number I'm seeing from the app is still 1.0.35.

**Comment by LoneFenris** [comment]
If it helps, the open-source Timber music player in beta also shows song info on the Pebble correctly.

**Comment by adrian-bl** [comment]
Timbre is a fork of Apollo and sends exactly the same metadata as Apollo.

But hmm.. maybe the pebble app uses broadcasts? Did you try to enable the 'Send stock broadcasts' option in Vanilla Music?

**Comment by LoneFenris** [comment]
Just tried that. Still no effect.

**Comment by adrian-bl** [comment]
In this case i have no idea: Vanilla Music works just fine with Android Wear and multiple scrobbler.
Googling about this issue brings up some funny threads about failing to work on Spotify + Rocket Music player on some Pebble models. So i guess that Pebble somehow hardcoded a list of players and does (for some funky reason) not use scrobbler information.

Do they have a support forum? I'd recommend to ask them directly as i don't see how this could be Vanilla Musics fault.

**Comment by LoneFenris** [comment]
Hm. I'll see if I can track down an answer from Pebble on this, then.

**Comment by adrian-bl** [comment]
Closing this as this is most likely not our bug:

We are sending normal broadcasts which are received by other software (LastFM, Google Wear, Lyrics lookup), so i suppose that pebbles software is to blame.
