### ISSUE TITLE
add Pause/Play, previous track, next track buttons to Queue display

### ISSUE THREAD

**Issue by Piscium** [vanilla-music/vanilla#263]
Some Android players have Pause/Play, previous track, next track buttons in the Playlist display. I wonder if such buttons could be added in Vanilla to the Queue display, and maybe also to the Playlist display. 

Use case: when djing I like to know what music is being played, what will be played soon, as well as the ability to pause and continue playing a song.

Currently the Pause/Play, previous track, next track buttons are available through the Notifications display but that is much less convenient than having them in the Playlist display.

**Comment by adrian-bl** [comment]
The new bottom-bar in the library will probably be extended to slide up where some controlls will be available.

Including the bottom-bar in the queue should also be possible

**Comment by adrian-bl** [comment]
Closing this as the new slide-up queue view provides controls (See #284)

**Comment by Piscium** [comment]
Thanks.
