### ISSUE TITLE
support forum or mailing list

### ISSUE THREAD

**Issue by Piscium** [vanilla-music/vanilla#264]
It would be nice if there was a support forum or mailing list so that Vanilla users could help each other with respect to Vanilla use.

I would suggest Google Groups as Android users already have Gmail accounts so would not need to create a new account, and it is likely easier to administer than, say, a PHP based forum. There are however dozens of other possibilities.

**Comment by ToNIX-** [comment]
Simply using reddit could also be a possibility.

**Comment by adrian-bl** [comment]
I simply do not have time to run a support forum, but if someone would like to administer one: feel free to step forward. (Should be low traffic anyway)

I didn't know that google groups still existed ;-)
I think reddit or a g+ community would be better

**Comment by aminb** [comment]
:+1: For subreddit, and I can help manage it/answer questions in my free time.

It appears that @ToNIX- has created /r/vanillamusic (~3 months ago). Would you mind adding me as a mod?

**Comment by ToNIX-** [comment]
Yeah no problem, I made sure it wouldn't fall in bad hands. 
@aminb Is your username the same one?
@adrian-bl What's your reddit username?

**Comment by adrian-bl** [comment]
I don't have one - i'm not really using reddit myself :)

**Comment by ToNIX-** [comment]
@adrian-bl You should, it's 2016! ;)

**Comment by aminb** [comment]
@ToNIX- Thanks for reserving it for the project!

And yes, I'm `aminb` on reddit as well.

**Comment by ToNIX-** [comment]
@aminb Done.

**Comment by aminb** [comment]
@ToNIX- Thanks :beers: 

We should probably link the subreddit in the app (`About`), README and the website. @adrian-bl

**Comment by Piscium** [comment]
Good to see progress. I don't have an account on Reddit but I can create one. And yes, links in the app, etc, are needed for people to learn of the forum existence.

Thanks.

**Comment by adrian-bl** [comment]
@aminb fine with me: feel free to add the link(s) to the master branch

**Comment by ToNIX-** [comment]
I applied a theme to [/r/VanillaMusic](https://reddit.com/r/VanillaMusic).

**Comment by aminb** [comment]
I added a "Subreddit" link to the about page.

@adrian-bl can you add a link somewhere to the README as well? I didn't know where to put it.

**Comment by adrian-bl** [comment]
Just create a new section such as 'User Help / Documentation' - nobody is reading the readme anyway ;-)

**Comment by aminb** [comment]
Will do when I get home.

**Comment by aminb** [comment]
Will do when I get home.

**Comment by aminb** [comment]
Will do when I get home.

**Comment by aminb** [comment]
I just added a Community section to the README :)

Closing this, but everyone feel free to comment or ask to re-open if want to share anything.
