### ISSUE TITLE
Monitor memory usage

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#265]
We can be quite a memory hog:
- We are using a fixed 16 mb LRU cace
- Drawing large covers sometimes requires ~20MB of memory due to fixed-size-scaling
- Maybe there are also some bitmap leaks?

We should therefore try to reduce our memory usage to, say.. at most 70MB

**Comment by xbao** [comment]
Just out of interest I installed LeakCanary on a [branch](https://github.com/xbao/vanilla/tree/feature/%23265-memory-usage) and ran it. 

It picked up a couple of leaks. One was the static BitmapCoverCache holding a reference to the LibraryActivity (as a context), the other was some content provider callback doing something similar. Pretty sure these aren't doing much harm as they're not continuously leaking anything. Anyway I fixed the first one in the HEAD commit of that branch because it was super-easy, didn't look at the second.

I did see something interesting in the hprof dump: the notifications each allocated 10mb. Is that the bitmap scaling thing? 

Watching the memory usage when flicking between songs with ~1mb cover art, it definitely jumped up to ~60-70mb, but triggering a GC always brought it back down to ~20-30mb, so it seems like the app's well-behaved in that respect.

**Comment by adrian-bl** [comment]
Cool: Thanks for digging around - i didn't know about LeakCanary, but i'll also give it a try!

> Pretty sure these aren't doing much harm as they're not continuously leaking anything. 
> Anyway I fixed the first one because it was super-easy, didn't look at the second.

Great: I already cherry-picked it into the master

> I did see something interesting in the hprof dump: the notifications each allocated 10mb.
> Is that the bitmap scaling thing? 

I suppose it is: I noticed the same with widgets and they get, like the notification, a big version of the cover. Android probably keeps a memory of the original bitmap in memory for each ImageView instance :-/

> Watching the memory usage when flicking between songs with ~1mb cover art, it definitely jumped up
> to ~60-70mb, but triggering a GC always brought it back down to ~20-30mb, so it seems like the app's
> well-behaved in that respect

Yeah, i've seen the same in android studios memory profiler: Forcing a GC always brings the app down to a reasonable level.

Maybe we should just clean up the whole cover handling to:

a) Never scale up cover images
b) Use the devices native resolution instead of hardcoded 600x600 images
c) Introduce a medium-sized image variant for use in Notifications and widgets (or pre-scale them before assigning them to an image view)

**Comment by adrian-bl** [comment]
I played around with the android-studio monitor and, for magical reasons, everything looked better after rebooting my device: Seems like the bad ram usage (up to 100MB) was an Android/CM bug (which, for some reason, did not surface if i changed the small cover size from 88px to 99px (?wtf?)).

Anyway: I think we are mostly OK: My Z3 now stays below 10Mb unless the FullPlaybackActivity is open, which is IMO quite okay.

**Comment by xbao** [comment]
> Cool: Thanks for digging around - i didn't know about LeakCanary, but i'll also give it a try!

Yeah it's pretty great. If you're a podcast listener the creator is on an [Android Developer Backstage episode](http://androidbackstage.blogspot.com.au/2015/07/episode-32-leak-canary.html). Does all the heap analysis and what not on the device.

> Great: I already cherry-picked it into the master

Easy

> (which, for some reason, did not surface if i changed the small cover size from 88px to 99px (?wtf?)

Hahaha. WTF indeed.

> My Z3 now stays below 10Mb unless the FullPlaybackActivity is open, which is IMO quite okay.

Yip, that seems fine to me too, given that having a couple of mp3s in memory would run up to ~7-8mb anyway. 

Hmm I just gave it another go, I'm still getting ~35mb of usage. `meminfo`:

```
[10:38 AM] ~/dev/android/vanilla/vanilla (master) $ adb shell dumpsys meminfo ch.blinkenlights.android.vanilla
Applications Memory Usage (kB):
Uptime: 65329221 Realtime: 235210879

** MEMINFO in pid 25097 [ch.blinkenlights.android.vanilla] **
                   Pss  Private  Private  Swapped     Heap     Heap     Heap
                 Total    Dirty    Clean    Dirty     Size    Alloc     Free
                ------   ------   ------   ------   ------   ------   ------
  Native Heap    13393    13244        0        0    21533    21533    25570
  Dalvik Heap    22917    22556        0        0    48404    36627    11777
 Dalvik Other      566      444        0        0                           
        Stack      248      248        0        0                           
       Cursor        6        0        0        0                           
    Other dev     8142     7988        4        0                           
     .so mmap     3157      152      684        0                           
    .apk mmap      493        0      296        0                           
    .ttf mmap      194        0      180        0                           
    .dex mmap      716        0      712        0                           
    code mmap     3191        0     1764        0                           
   image mmap     1482      640      264        0                           
   Other mmap       70        4        8        0                           
     Graphics    13888    13888        0        0                           
      Unknown      257      256        0        0                           
        TOTAL    68720    59420     3912        0    69937    58160    37347
```

We can probably ignore the non-heap fields (I think that's what Studio does - it showed 35mb of usage when I ran that meminfo)

This was on a 5.0.2 Sony Xperia Z3+ Dual. I'll keep digging, see if I can find anything useful
