### ISSUE TITLE
Auto play on application start

### ISSUE THREAD

**Issue by guilhas** [vanilla-music/vanilla#266]
Start to play automatically last selected playlist on application start-up

**Comment by kirbyfan64** [comment]
As an option? It would bug me to death if I couldn't turn it off...

**Comment by adrian-bl** [comment]
Sorry, but this will not get implemented.

You can use a widget if you would like to start playback with a single touch

**Comment by guilhas** [comment]
Yes. Option 'On start immediately play last list'.

The idea was to execute  it with a app scheduler.
It could be used as a kind of alarm clock.

Sorry for answering just now.
Thanks

**Comment by xbao** [comment]
Does the app scheduler you're using allow you to launch an intent to start a service? If so, the following intent configuration should work:

action: `ch.blinkenlights.android.vanilla.action.PLAY`
package: `ch.blinkenlights.android.vanilla`
classname: `ch.blinkenlights.android.vanilla.PlaybackService`

**Comment by guilhas** [comment]
Ok it seems it does, although as basic user I would never have guessed what an intent is.

Thank you

**Comment by xbao** [comment]
> as basic user
I think you might have left that group :)

> Thanks a lot
My pleasure!
