### ISSUE TITLE
Keep scroll position in media tabs after Media Database update

### ISSUE THREAD

**Issue by sellsky** [vanilla-music/vanilla#271]
I tried SD Scanner, as mentioned in https://github.com/vanilla-music/vanilla/issues/270 — although scanning is extremely slow, Vanilla finally sees music, which is great.

However, I've met this funny behaviour. It looks like Vanilla refreshes its media tabs for every Media Database update. During this refresh, a scroll position in active list is reset as well, so list rewinds to the top, which is quite confusing. Also, it becomes just impossible to scroll the list while initial scan is performed.

Is there any chance you'd teach Vanilla to hold updates in the current tab until it loses the focus and/or to keep the scroll position, say, closest to the topmost survived entry?

**Comment by adrian-bl** [comment]
I don't think there is a reasonable way to keep the scrolling position without too much hacking around (given that having the app open during a full media re-scan is a corner case)

If someone comes up with a non-hacky solution to this: feel free to send a PR

**Comment by adrian-bl** [comment]
This should have become better in recent releases as the scroll-restore code has been improved
