### ISSUE TITLE
Shuffle algorithm

### ISSUE THREAD

**Issue by sandrc** [vanilla-music/vanilla#272]
Shuffle keeps repeating "clusters" of songs. In my library of ~1200 songs, I would get 20-30 repeated songs when I hit next 50 times. The repeating cluster of ~7-8 songs changes every time I restart the app.

**Comment by adrian-bl** [comment]
I noticed this too - there really seems to be something off with the shuffling

**Comment by Almtesh** [comment]
The good way would be to create a virtual playlist containing songs in the waiting playlist and shuffle them and play this virtual playlist.
I thing that my desktop music player does it something like that way. It's Amarok, the player from KDE.

**Comment by sandrc** [comment]
#14 #71 #72 and the fix from #142 could be related

**Comment by adrian-bl** [comment]
I'm not sure if the shuffle algorithm itself is to blame: I don't see how it could create duplicates.

And on a second thought: i'm not sure if the bug *really* exists: I noticed that i simply had the same song on the device multiple times, so including it in the playlist multiple times was correct.

Hmm.. but i'll keep an eye on it

**Comment by adrian-bl** [comment]
Closing this as i could not reproduce the issue after cleaning up the duplicate songs on my device (caused by SyncThing)

**Comment by Almtesh** [comment]
I found a mode that produce once and for all the random playlist so there's no repeat.
