### ISSUE TITLE
"Favorit/Star" Button to quickly generate a "Favorits" Playlist

### ISSUE THREAD

**Issue by mindforger** [vanilla-music/vanilla#277]
I'd like to have, when scrolling through the Folder/Album/Files List on each Song either an additional Flag to mark them as Favorit or an easier to use assembly funtion for playlist all toghether

because when i go on a long trip, i want to have a shuffled list of songs that fit my mood that day ... but i do not want to sit there and go through hundreds of songs, each:
-select
-settings
-add to playlist
-select playlist

something like a star as symbol did the trick on my old phone with its stock samsung music player
i just scroll my files, hit the star whenever i want to add or remove it from my "Favorits" and when i finish i just start playing my favorits and hit shuffle

it's simpy just:
-you're hot
-you're hot
-you're __not__
-you're hot
 
:)

**Comment by adrian-bl** [comment]
I implemented this in the 'favourites' branch:

Normal:
![Image](http://i.imgur.com/6xjpA1K.jpg)

In Favourites:
![Image](http://i.imgur.com/bRlgfWg.jpg)


Seems to work fine so far, i'll test-drive it for a few days and then merge it into the master.

**Comment by mindforger** [comment]
as far as i overlooked the code this only will add the star feature to the current playing song window, but not directly to the other listings right?
this is awesome enough for me but i'd take it one step further to add the star feature to the file listings when in landscape mode as in normal mode there isn't enough place i think
or it could be a single button in the context menu

**Comment by adrian-bl** [comment]
> as far as i overlooked the code this only will add the star feature to the current playing song window, but 
> not directly to the other listings right?

Yes

> this is awesome enough for me but i'd take it one step further to add the star feature to the file
> listings when in landscape mode as in normal mode there isn't enough place i think

I don't think that's a good idea as, even in landscape mode, the rows will end up 'overloaded' and adding a song from the library view is already possible with 2 clicks.
It would also force us to keep the whole favorites-playlist in memory while the current code can work using the content resolver.

> ... listed in the favourite tab?

Damn, stupid copy-n-paste spelling mistake :-)

**Comment by adrian-bl** [comment]
Merged via https://github.com/vanilla-music/vanilla/commit/7afff3890fe79f0b2ee3c3227932c35e4534202b, will be in the next nightly

**Comment by mindforger** [comment]
lovin it

just one detail, and i don't know if you have any influence to this but does the notification have to be this far down on the screen? it's blocking the controls ... i can still tap on the buttons and skip or play but it's kind of annoying to have the notification blocking the buttons visually ... i could make this an new issue regarding the "notifications blocking controls in title playing window visually" if you want :D

**Comment by adrian-bl** [comment]
No: The notification is part of the system UI: We can not change the position nor the layout of the notification
