### ISSUE TITLE
Android 5 sticky heads up notification

### ISSUE THREAD

**Issue by paul70078** [vanilla-music/vanilla#278]
When heads up notifications are used they stay until you swipe them away. I like the info about a new song, but if the notification stay permanent, it gets annoying

**Comment by adrian-bl** [comment]
...and what kind of UI element should we use then?
Android 5.x does not (unlike 4.x) allow us to briefly show text in the notification bar.

**Comment by adrian-bl** [comment]
Closing due to lack of reply
