### ISSUE TITLE
"Fast scroll" option for library navigation

### ISSUE THREAD

**Issue by Alexandrejoe** [vanilla-music/vanilla#279]
When you have a lot of musics/albums/artists it takes some time to navigate from the top to the end of the library. It would be nice to have the availability to enable a fast scrolling option in the settings that make the scrollbar cursor larger on library screens (Artists, Albums, ...) and let users scroll the list by moving that cursor.

**Comment by adrian-bl** [comment]
We had this in older versions but disabled it as it collides with the touch-space of the 'expand' and 'drag' items in the queue. I just checked it on anroid 5.1 and the fastscrollbar still consumes a huge amount of the touch target, making hitting the 'expand' button almost impossible :-/

**Comment by Alexandrejoe** [comment]
Thank you for bringing this back !
