### ISSUE TITLE
Widgets are unavailable when Vanilla app is moved to SD card storage

### ISSUE THREAD

**Issue by Alexandrejoe** [vanilla-music/vanilla#280]
Existing Vanilla widgets and widgets creation is not possible when app data is moved to SD card. I have to move it back on the phone storage to get it back.
(Android 5.1.1 - Vanilla 1.0.36)

**Comment by adrian-bl** [comment]
That is not the fault of vanilla music:

Widgets will always be broken for apps stored on the SD-Card.
