### ISSUE TITLE
Skip/FastForward occassionally doesn't work

### ISSUE THREAD

**Issue by mshillinger** [vanilla-music/vanilla#281]
When using the skip/fast forward control to move to the next song, sometimes the audio will stop.  The UI shows that the next song is playing but I hear nothing.  Pressing Pause then Play will resume the audio, but it will continue playing the original song at the point where I pressed skip.  The UI and audio will now be out of sync, with the UI showing the song I skipped to. It does not matter if I am using the the control on the lock screen or inside the app. 

By pressing skip repeatedly I will eventually land on a song that will play and the audio and UI will be back in sync.

Seems to only occur when "shuffle" is enabled.  Perhaps related to #272 

This started occurring after the upgrade to version 1.0.36. (Android 5.1). Moving back to 1.0.35 for now.

**Comment by adrian-bl** [comment]
Just to clarify:

* Are you using a remote/bt-headset to skip/fast forward or are you using the UI (or a widget?)
* While in this state: Does vanilla music claim to be paused?

**Comment by mshillinger** [comment]
I am not using the the remote skip - just the UI.  After I encountered this problem, I disabled the preferences for remote/bt control - didn't make a difference.  

When I hit this, the UI does not show paused.  On the lock screen, the title of the new song will be displayed.  If the app is open - the progress indicator is moving and the text and image displayed on the screen are associated to the next song, but there is no sound. 

A correction to my original comment - I am on Android 6 (not 5.1).

**Comment by adrian-bl** [comment]
That's a very odd bug:
Having the progress bar move, means that Android actually thinks it *is* playing some audio (we get the current position by polling androids mediaserver each second).

How often did this happen on 1.0.36? Was it more likely to happen on some songs or did it show up completely random?

Another strange thing is, that most of the code changes from 1.0.35 -> 1.0.36 are UI changes
(https://github.com/vanilla-music/vanilla/compare/vanilla-music:1.0.35...1.0.36).

The only thing that has a *minimal* chance of triggering this issue would be the new ignore-audio-focus loss feature.

It would be great if you could re-upgrade to 1.0.36 and play with the following settings:

* Audio >> Equalizer: Ensure it is off
* Audio >> Replay gain: Also turn it off
* Audio >> Volume during notification: Make sure that 'Keep playing on ...' is not ticked

These are the only 3 settings which cause Vanilla Music to do 'advanced' stuff to the mediaserver.
It would also be great if you could grab a logcat after this happened.


@aminb  @xbao You both are running Android 6, correct? Did you ever see this happen?

**Comment by mshillinger** [comment]
Removing 1.0.35 and installing 1.0.36 manually seems to have resolved the problem. Strange, because I had tried reinstalled 1.0.36 before writing up this issue.  The original upgrade from 1.0.35 to 1.0.36 occurred automatically via PlayStore magic.  Perhaps auto upgrade leaves some config cruft?? 

When I manually updated, I used the APK's from F-Droid, not the PlayStore - I assumed they are the same binaries.

Anyway, everything is working, you can close this issue.

Thanks for looking into it.

**Comment by aminb** [comment]
I think I' ve seen something a bit similar to this, but haven't tried to reproduce it.

I think what happens for me is that sometimes when I play a song and turn off the screen, when I switch back on the progress bar is showing the progress of song at the point which I turned off the screen, even though the song has progressed (or might have even finished).

I don't even know that this is exactly what happens, but I have experienced the app UI being out of sync with songs casually. And yes, I'm on Android 6.0.1.

I'll see if I can reproduce it.

**Comment by adrian-bl** [comment]
@mshillinger That's very strange o_O.
The f-droid and the play-store release should be almost the same binary: The only difference is that i compile the play store releases by myself while f-droid builds are done automatically by the f-droid guys.

@aminb Thats also very strange ;-) Are you using a Nexus 5? I'm thinking about buying a slightly broken one (eg: cracked glass) cheaply to have it as a test phone. But while Vanilla Music is in this state: does it recover after skipping to the next song? This *might* be somehow related to #244

**Comment by mshillinger** [comment]
If the weird skip behavior happens again, I will capture the logcat output and send it to you.

**Comment by aminb** [comment]
@adrian-bl Yeah I have a Nexus 5, it's a quite nice phone.

As for your question, I haven't really tried that. If it happens again or I manage to reproduce it, I'll try skipping to the next song and see what happens.

**Comment by kirbyfan64** [comment]
I don't think this is a Nexus 5 issue. I have the same phone, and that doesn't happen to me.

**Comment by xbao** [comment]
> @aminb @xbao You both are running Android 6, correct?

I'm on Lollipop :( also keeping an eye out for a cheapie nexus for testing

**Comment by adrian-bl** [comment]
What should we do with this bug report?
This never happened to me, was someone able to reproduce it and capture a log?

**Comment by aminb** [comment]
I haven't had this occur to me, but I'll keep an eye for the scenario that I mentioned above that happened a couple times.

Anyone else able to reproduce?

**Comment by ctz** [comment]
I experience this too, on 1.0.40. Moto G 3, Android 6.0. I go to the next or previous track, and get silence with normal progress movement. Shuffle is not enabled. Touching the progress bar starts the audio at the correct place. I'll try to get a log.

**Comment by adrian-bl** [comment]
Closing this as i can not reproduce this bug on any device and i'm pretty sure that it is firmware specific anyway, so there will not be much we can do (apart from switching to exoplayer at some point)
