### ISSUE TITLE
Show Queue Button in FullPlayBack Activity

### ISSUE THREAD

**Issue by folol** [vanilla-music/vanilla#284]
As an avid user of vanilla  , i would like to suggest an enhancement .
In FullPlayBack Activity ,I use "Show Queue" menu item frequently and it bothers me to touch two times repeatedly to see queue . It would be better if there is an direct button for that in action bar like the one shown in image(all other major music player give this option). if you guys want i can work on this feature and send pull request .
![vanilla final sq](https://cloud.githubusercontent.com/assets/8148617/13034024/be4c10da-d34f-11e5-8cb2-118426f1037d.png)

**Comment by aminb** [comment]
I agree with you. I too use the queue frequently and having to tap twice is somewhat annoying for such a frequently used feature.

There were some discussions on #240 about implementing an expandable 'bottom bar', similar to the Timber app. I was wondering what would be best to do, to utilize that, and if possible provide an easier way to access the queue page.

Right now, if you tap on the bottom bar, it opens up the full playback activity. If we implement the slide-up bottom bar, it would at the very least have *back*, *play*, and *forward* buttons, so it would technically eliminate the need for full playback screen, and we could change the bottom bar tap action to open up the queue instead (we could even have this as an option).

Or, alternatively, we could try to implement something similar to the Cyanogenmod music app (Eleven) with their sliding playback/queue activity.

What does everyone think? @folol, @adrian-bl, what are your thoughts?

**Comment by adrian-bl** [comment]
Having the menu entry as an icon is fine with me (we do this already for the favorites button and implementing it should be 1-2 lines of code).
The menu bar might get a little bit crowded, depending on how long the translation for 'Now playing' in the current language is, but android will automatically handle the space in the bar, so it shouldn't be a real issue.

>  it would at the very least have back, play, and forward buttons, so it would technically eliminate the
> need for full playback screen, and we could change the bottom bar tap action to open up the queue
> instead (we could even have this as an option).

I'd rather keep the current tap-action :-/

But maybe we should just (finally) stuff the whole queue-display into the library activity as a tab:
I hacked this up at https://github.com/vanilla-music/vanilla/tree/queue_adapter - still pretty buggy but it somewhat works. However: We also must convert all list views into DSLV listviews to enable the dragging. This won't be impossible but could be somewhat painfull.

The UI could then look like this:
![](http://i.imgur.com/qEeLTCP.png)

**Comment by aminb** [comment]
Hmm, having a 'Queue' tab would potentially be better than what we have now, but IMHO it still won't make it much more accesible.

Maybe we could have a queue icon beside the search icon on the bottom bar?

I'll also take a look at Timber's code base to see how they implement their bottom bar to see how hard it'd be to port over so we can slide it up and access the <kbd>|<</kbd>, <kbd>|>/||</kbd>, <kbd>>|</kbd> buttons.

**Comment by xbao** [comment]
My 2c: I agree that the queue should be easier to get to. First thing I do with a fresh install is make 'swipe up' show the queue. Works fine for me, but I'm guessing some users prefer swipe up doing something else.

**Comment by adrian-bl** [comment]
@aminb @xbao I created a prototype where the queue can be slided-up in the full playback activity, see:

https://webm.lol/v/1z20122348.webm

What do you think about this: should we go with something like this?

Or wouldn't it be better to just add the <kbd>|<</kbd>, <kbd>|>/||</kbd>, <kbd>>|</kbd>  buttons to the existing queue view (+ have an option to open it instead of the full playback activity)?

**Comment by xbao** [comment]
> https://webm.lol/v/1z20122348.webm

For my usage that works great! I use the queue mainly to see what's playing next, and maybe do some 'local optimisation' of the next few songs based on what I feel like listening to at the time. Not needing to leave the FullscreenPlaybackActivity to do that is a win.

> Or wouldn't it be better to just add the |<, |>/||, >| buttons to the existing queue view (+ have an option to open it instead of the full playback activity)?

I have no strong feelings either way about this. 

Off topic: on April 1st we should show the playback icons as they are in the screenshot ;)

**Comment by aminb** [comment]
@adrian-bl The prototype looks good, nice job Adrian. However, I'd really like to have that accessible throught the whole app (i.e. bind it to bottom bar).

Also, one more thing that I just thought of, is to add a middle state for the slide-up queue: When you slide up the bottom bar, the back/play/forward buttons would appear (like Timber), then you can slide up further to reveal the queue.

This way, we'd have the back/play/forward buttons available throughout the app (basically elliminate need for frequently opening to FullPlayBackActivity), and also if we further slide up, you'll have access to the queue.

> Off topic: on April 1st we should show the playback icons as they are in the screenshot ;)

Great idea, we should *totally* do that! :sweat_smile:

**Comment by adrian-bl** [comment]
I uploaded my prototype to the slide-up branch, see: https://github.com/vanilla-music/vanilla/compare/master...slide-up

Still buggy and needs much love, but it somewhat works. (Doesn't have any velocity tracker yet, so no flinging around)

> @adrian-bl The prototype looks good, nice job Adrian. However, I'd really like to have that accessible 
> throught the whole app (i.e. bind it to bottom bar).

That would be nice: The branch uses a 'show queue' fragment which can be used in multiple places in the app, so doing this should be possible once the code is stable.

We could also create a nice landscape view for tablets with the Contents on the left side and the queue on the right.

> This way, we'd have the back/play/forward buttons available throughout the app (basically elliminate 
> need for frequently opening to FullPlayBackActivity), and also if we further slide up, we'll have access to 
> the queue.

The library activity is a little bit trickier as we need to shrink our previous child and getting the playback  service instance (required by the fragment) deadlocks with the generic init code. It's doable, but i'd first like to get the code stable in the FullPlaybackActivity case.

**Comment by adrian-bl** [comment]
@aminb & @xbao 
The 'slide-up' branch now includes the queue in both the FullPlaybackActivity and in the LibraryActivity.

Demo video: https://webm.lol/v/1z57d476e0

What do you think about it? (I know that there a few graphical quirks).

Some thoughts:
* Sliding up in the library view has currently multiple 'stages': normal -> controls -> queue. Sliding down does the same. Not sure if this is a good idea: maybe we should also hide the controls?
* The back button is currently ignored: we chould use it to collapse the view.
* The enqueue-xyz (long click) action flushes other queue items. It should probably append them to the queue (or enqueue them as next?)

**Comment by xbao** [comment]
I'm playing around with it now, very nice! 

> Sliding up in the library view has currently multiple 'stages': normal -> controls -> queue. Sliding down does the same. Not sure if this is a good idea: maybe we should also hide the controls?

I like the behaviour as it's currently implemented; it gives me the option of having the controls on-screen without taking up screen when I don't want them. Having the controls at the top of the panel also makes both of the slide up views look/act consistently, which I think is important. The current implementation is a little erratic in terms of which of the stages are chosen (sometimes it chooses 'normal' when it should probably choose 'controls'), but when it works it feels very natural.

A peculiarity of the 'queue' stage is that the overflow and search button no longer make any sense, as they apply to the library screen which is completely hidden. Not sure how to accommodate this, maybe disabling or removing the overflow/search buttons when the panel's fully up?

> The enqueue-xyz (long click) action flushes other queue items. It should probably append them to the queue (or enqueue them as next?)

Yeah, I wouldn't expect an 'enqueue' action to clear any current queue items. I think either appending or adding next is a reasonable behaviour.

**Comment by adrian-bl** [comment]
> The current implementation is a little erratic in terms of which of the stages are chosen (sometimes it 
> chooses 'normal' when it should probably choose 'controls'), but when it works it feels very natural.

Yeah, the current implementation isn't very smart as it always goes to the next 'expansion stage'. But i'll fix this next week to make it smarter.

> A peculiarity of the 'queue' stage is that the overflow and search button no longer make any 
> sense, as they apply to the library screen which is completely hidden. Not sure how to 
> accommodate this, maybe disabling or removing the overflow/search buttons when the panel's 
> fully up?

I think that disabling the search + sort-by menu entries would make sense in the expanded stage.
It probably also would make sense to add a few new entries, such as 'save queue as playlist' and 'empty queue', etc.. to the menue while in expanded stage.

> Yeah, I wouldn't expect an 'enqueue' action to clear any current queue items. I think either 
> appending or adding next is a reasonable behaviour.

Yepp, that's pretty confusing :-)
Changing the feature to do a 'enqueue after currently playing' would make sense.

**Comment by aminb** [comment]
Sorry for my super late reply in this thread, I didn't have Java development env set up on my laptop for the last two weeks, but I finally got around to setting it up tonight and gave this a shot.

> We could also create a nice landscape view for tablets with the Contents on the left side and the queue on the right.

Agreed.

> Sliding up in the library view has currently multiple 'stages': normal -> controls -> queue. Sliding down does the same. Not sure if this is a good idea: maybe we should also hide the controls?

It's pretty good as it is right now (3 stages), except I'd suggest that maybe we make the height of the 'controls' stage a bit taller (more like *Timber*) and make the button margins a bit bigger to make them easier to use.

For the sliding behaviour, we could probably add some logic to skip the 'controls' state all together if the user slides (flings) the panel all the way close to the top of the screen, and the same thing when flinging the panel back down.

> The back button is currently ignored: we chould use it to collapse the view.

:+1: we should definitely do this.

Since we're at it, I'd say we make the whole list view of the queue draggable (to be used for collapsing) if we're at the top of the queue list view. This would make it easier to collapse the queue without having to reach to the top of the screen to drag the 'bottom bar' back down again.

Also, about glitches, I can spot two:

- When sliding up towards the fully expanded state, the time between lifting the finger from screen and the panel reaching the top, the library list view is completely white.
- Same issue as the previous case (background being white instead of showing the list view), when sliding the panel back down.

Over all, the panel looks beautiful and feels natural to use.

Great work @adrian-bl :beers:

**Comment by adrian-bl** [comment]
> except I'd suggest that maybe we make the height of the 'controls' stage a bit taller (more like Timber) and 
> make the button margins a bit bigger to make them easier to use.

Agreed - we probably also should add a progress bar there - the current controls are just a re-used layouts snippet. Changing this will be easy.

> For the sliding behaviour, we could probably add some logic to skip the 'controls' state all together if 
> the user slides (flings) the panel all the way close to the top of the screen, and the same thing when 
> flinging the panel back down.

Yes, the slide logic is currently pretty dumb and should take the current position into account (eg: dragging from bottom -> top should not just show the controls)

> When sliding up towards the fully expanded state, the time between lifting the finger from screen and 
> the panel reaching the top, the library list view is completely white.

I know: That's because we have to adjust the 'parent' view to match our size. The current code just does this while the animation starts - it should be done when the animation finishes (or on drag-start)

**Comment by adrian-bl** [comment]
I think we are mostly done with this task:
I checked in some fixes to this in the master branch and it's mostly feature complete:

* Swipes are handled 'smart' with multiple stages (tries to match best stage)
* Back-Button is handled
* Queue entries have a context menu
* The view menu hides/shows entries depending on the slide stage.

@xbao @aminb Could you please give it a test drive and give some feedback? (Its already included in the current nightly build)

We should probably improve the controls in the library view, but this could be handled in a seperated issue (and wouldn't stop me from doing an f-droid only release ;-) )

**Comment by aminb** [comment]
Looks great!

I feel like the animations (slide up/down) could feel more natural if we use a non-linear timing function (easing,etc) and 'smart' stages could be tweaked to react to dragging/flinging more "naturally", but these are minor improvements.

Great work :beers:

**Comment by adrian-bl** [comment]
Yeh, the flinging could use some work.
I tweaked it a little bit in 4ef83abf326cc72b7990a2e929658749b82c7455 , not sure if it is better but it's different ;-) (and i somehow like it more on my Z3C)

* We are now taking the fling-speed into progress to calculate a virtual distance
* Stages are not 'magnetic' anymore (eg: do not snap-in to the nearest point) but obey gravity (its the law)
* I changed the animation from 300ms to 250ms which is the value we are using in the cover swipe

**Comment by adrian-bl** [comment]
Closing this as the fragment seems to work quite fine so far.
I opened a ticket (#319) for a redesigned library-queue-controll-element
