### ISSUE TITLE
Automatic playlist generation

### ISSUE THREAD

**Issue by vincentqb** [vanilla-music/vanilla#287]
I believe I had seen a message saying that the player can generate automatically a playlist from the most-played songs. Is that indeed a feature? How can I access it?

**Comment by aminb** [comment]
Yes, that's indeed a feature.

Go to `Settings > Miscellaneous features` and tap on `Automatic platlisy creation`. The available options (as of now) are: None, top 25, top 50, top 75, or top 100.

**Comment by vincentqb** [comment]
Great, thank you. The list did not appear immediately, but I'm assuming the playlist will populate with time, am I right?

**Comment by aminb** [comment]
You're welcome!

I didn't pay attention whether it appeared immediately or not for me, but it *should* appear and will be populated over time.

Closing this issue, as I think I've answered your question, but feel free to comment or ask if anything comes up.

**Comment by vincentqb** [comment]
Yes, you answered very well. Thanks again!

**Comment by aminb** [comment]
You're very welcome!

Cheers :beers:
