### ISSUE TITLE
Material ListView, Contextual Menu and PopUpMenu 

### ISSUE THREAD

**Issue by ankitmhatre** [vanilla-music/vanilla#289]
Can we create a material type menu like those in the screenshots, they have an overflow menu for each row and OnLongClick event give multiple selection options like deleting adding to queue , and they look a lot cleaner too.
![screenshot_20160219-202058](https://cloud.githubusercontent.com/assets/6874272/13178986/ad5ad922-d747-11e5-9bb5-562122b153e4.png)
![screenshot_20160219-202509](https://cloud.githubusercontent.com/assets/6874272/13178985/ad529f14-d747-11e5-93ae-24d3be14d498.png)

etc.

**Comment by adrian-bl** [comment]
What kind of (usability) problem would such a change solve?

**Comment by ankitmhatre** [comment]
Multiple selection for adding to queue, playlist, and delete. Even it feels like a more cleaner ListView :p

**Comment by adrian-bl** [comment]
Closing this as i don't think this will happen anytime soon. I'm just not a big fan of this kind of UI
