### ISSUE TITLE
Ignore  .nomedia files when scanning

### ISSUE THREAD

**Issue by Almtesh** [vanilla-music/vanilla#292]
Is that possible to ignore  .nomedia files or be able to set the music directory. That's because my music is in the Android/data directory in which a  .nomedia file is automaticly put.
I can't put my music elsewhere since Android 4.4+ refuse syncthing to write anything elsewhere.
Thanks.

**Comment by adrian-bl** [comment]
No.
The point of .nomedia is to indicate that the folder does not contain media suited for playback.

**Comment by Almtesh** [comment]
The problem is that the user is not the only one to add these  .nomedia file, Android does too on his own, where it wants, when it wants, so it will be great to be able to disable this parasit behaviour or set by hand the directory in which the music is.

**Comment by xbao** [comment]
> Android does too on his own

Interesting, I hadn't heard about this. Where have you encountered this behaviour?

**Comment by Almtesh** [comment]
I have a one in /storage/sdcard1/Android/data/. Like I said earlier, my music is under because my sync application cannot write elsewhere.

**Comment by adrian-bl** [comment]
1) Android does not create .nomedia files randomly: most likely some app is to blame.

2) I am using syncthing myself and it can write to the internal sdcard just fine. Writing to the external card (=your use case) requires root or a patched ROM.

Anyway: Both points are not vanilla musics fault.

**Comment by Almtesh** [comment]
1) Android does not create .nomedia files randomly, but places them in place where I don't want to and without asking me about that.
2) I have a D2303 stock (without root and the famous patch I'm prising). So, I can only write to the syncthing's external card directory, but, two levels up, there the Android automatic .nomedia fucking anoying file. I can't either write my music on internal storage, it's a 8Go, including 3Go of Android (fucking heavy, indeed), and 1Go for the dalvik cache for these heavy stock default useless apps.

I know that is not vanilla music's fault, but the way it's designed does not help me at all.

**Comment by xbao** [comment]
Just out of curiosity, what happens if you replace the `.nomedia` file with a `.nomedia` folder? The Android media scanner ignores folders when checking for `.nomedia`, and hopefully whatever app is creating the file will think it's already there

**Comment by Almtesh** [comment]
Perhaps normal androids, but not the one installed on my phone. Well, sometimes, the behavior is badly defined.

**Comment by xbao** [comment]
Ah well, it was worth a shot. Yeah, as Adrian said it sounds like your ROM _really_ wants to keep the .nomedia there or there's another app that's creating it. 

I made a question on android.stackexchange: https://android.stackexchange.com/questions/138215/find-out-what-app-is-creating-nomedia-files. Could you add any further relevant information there (e.g. phone API level, when the .nomedia file is recreated after deleting it)? Hopefully someone has a solution :)

**Comment by Almtesh** [comment]
OK, I think I would just update manually (remove sdcard, put in computer, sync, remove from computer, put sdcard).
Thanks.
