### ISSUE TITLE
More cover filenames 

### ISSUE THREAD

**Issue by tjubutsi** [vanilla-music/vanilla#293]
All my album art is named Front.jpg so would it be possible to either add a custom string or add something like take any jpg in the album folder as cover?

**Comment by adrian-bl** [comment]
Relaxing the cover-lookup code would definitely be a good idea.

We could probably do something like this:
```
pseudocode:
$read = 0;
$match = undef;
foreach $file (readdir($path)) {
   if $file =~ /(front|cover|album).(jpe?g|png)/) {
       $match = $file;
       break;
   } else if $file =~ /\.(jpe?g|png) {
     $match = $file;
 }
 break if $read++ > 100; # abort on too large directories
}
```

**Comment by xbao** [comment]
Location of current logic: [CoverCache.BitmapDiskCache.createBitmap(Song song, long maxPxCount)](https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/CoverCache.java#L380)

**Comment by aminb** [comment]
@xbao Thanks for the link, though I suggest linking the [canonical form](https://news.ycombinator.com/item?id=8046801) for future reference. This way, the link stays relevent even when the file is modified with changes (unless the commit is deleted). Basically, link to the where we are in the repo history.

GitHub makes this easy, just press <kbd>y</kbd> to expand to canonical form, before you copy the address.

Example: [CoverCache.BitmapDiskCache.createBitmap(Song song, long maxPxCount)](https://github.com/vanilla-music/vanilla/blob/a347f38eb70bd57bdf31bd24bff3395e7e8407a4/src/ch/blinkenlights/android/vanilla/CoverCache.java#L380)

**Comment by xbao** [comment]
@aminb Nice! Thanks for the tip, link updated

**Comment by aminb** [comment]
@xbao Cheers!

**Comment by adrian-bl** [comment]
Implemented in https://github.com/vanilla-music/vanilla/commit/62d83dbf32109982e5af0008c3bfdbe4e402adac

We are now looping trough up to 50 entries while searching for:

# cover or album .jpg/png
# cd, front, artwork .jpg/png
# anything ending with .jpg/png

The best match is then used as the album cover (eg: if both album.jpg and front.jpg are found, album.jpg will win)
