### ISSUE TITLE
Search in genre remains after selecting genre

### ISSUE THREAD

**Issue by xbao** [vanilla-music/vanilla#295]
Searching for a genre, for example 'Com' (to look for 'Comedy'), in the genres list then clicking on the 'Comedy' genre will open the 'Artists' list filtered by the 'Comedy' genre as expected. The issue is that the 'Com' search will still be present, so the artists will also be filtered by 'Com'.

Screen capture: https://webm.lol/v/1z64312123

**Comment by adrian-bl** [comment]
Thats true for all other searches:

* Go to Albums, search for 'Blunderbuss'
* Expand the result

The result is then filtered by TWO things: The newly created limiter AND the search string.
However: As the search searches in title, artist and album, this does not have any negative side effects.

But this does of course not work for genres. Hmm: Maybe we should just reset the search after a view has been expanded. This would 'fix' the issue and would probably be better usability wise anyway...

**Comment by xbao** [comment]
Yip, I think that's a good solution. I can't think of any use case for keeping the search after expanding an item, though that might just be me.

_Seems_ to be a straightforward change code-wise too: 3d4a7b53832e128debcad69a27bf22a304add451.

**Comment by adrian-bl** [comment]
Yeah, that should work: Feel free to push it into the master.

(Btw: in which branch is this? I see the commit but can't find the branch hosting 3d4a7b5 ;-) )

**Comment by xbao** [comment]
I would, but I don't have write access to the repo :) cherry-pick this one?

Branch is reset-search-on-expand: https://github.com/xbao/vanilla/tree/reset-search-on-expand?files=1. Weird that Github doesn't show branches the commit's reachable through.

**Comment by adrian-bl** [comment]
Ah: it's in your repo - that's strange: because github shows 3d4a7b5 to be in the 'vanilla-music' repo (at least according to the URL). That's probably a bug in github itself :-)

I cherry-picked it as https://github.com/vanilla-music/vanilla/commit/5a72d52153a622394690357d0ad882997d238c53

Oh: and i added you to the list of 'contributors' in the github privileges page - so you should now have commit rights (i was under the impression that i did this a long time ago)

**Comment by xbao** [comment]
> Ah: it's in your repo - that's strange: because github shows 3d4a7b5 to be in the 'vanilla-music' repo (at least according to the URL). That's probably a bug in github itself :-)

Yeah, very strange...

>Oh: and i added you to the list of 'contributors' in the github privileges page - so you should now have commit rights

Excellent, ta!

> (i was under the impression that i did this a long time ago)

Yeah, I was under the same impression. This is like the Twilight Zone of GitHub issues.
