### ISSUE TITLE
ordering by track number fails with letters in track number

### ISSUE THREAD

**Issue by majewsky** [vanilla-music/vanilla#297]
I added the soundtrack for "Portal Stories: Mel" to my music library. When I click on the album in the collection view, it adds all the tracks to the queue and starts playing (as expected), but there is a slight ordering problem.

The problem is with several tracks that have two versions, which are identified by track numbers e.g. "13a" and "13b". These tracks are reproducably sorted in the wrong order when being added to the queue, with "13b" coming before "13a". To illustrate this, here's the ID3 tags for two such files, as reported by [kid3 3.3.1](http://kid3.sourceforge.net/):

![screen24](https://cloud.githubusercontent.com/assets/24696/13529121/a87c4a48-e21a-11e5-89f9-ee9aaa48abc2.png)
![screen25](https://cloud.githubusercontent.com/assets/24696/13529125/ac0f1ba4-e21a-11e5-8834-f0b70ce2afdf.png)

**Comment by xbao** [comment]
> When I click on the album in the collection view, it adds all the tracks to the queue and starts playing (as expected), but there is a slight ordering problem.

Is the order also incorrect in the library view of the album?

**Comment by majewsky** [comment]
Yes, it's the same order in the library view.

However, while scrolling through there, I noticed that the error is not completely deterministic. Of 9 pairs of songs with this structure, only 7 are ordered wrongly.

**Comment by adrian-bl** [comment]
I wouldnt be surprised if the track number field in the media database was an INT ;-)

**Comment by xbao** [comment]
```
CREATE VIEW audio_meta AS SELECT <snip> track, <snip> FROM files;
CREATE TABLE "files" (<snip> track INTEGER, <snip>);
```
@adrian-bl's bang on the money, the track's stored as an int.

I copied a mp3 file and changed the ID3v2 track from 1 to 1b. The MediaScanner just chops it off:

```
id3v2 tag info for 1 - Better To Be.mp3:
TIT2 (Title/songname/content description): Better To Be
TRCK (Track number/Position in set): 1 
id3v2 tag info for 1b - Even Better To Be.mp3:
TRCK (Track number/Position in set): 1b
TIT2 (Title/songname/content description): Even Better To Be

SELECT artist, album, track, title FROM audio WHERE title LIKE "%Better%"
Liam Finn|I'll Be Lightning|1|Better To Be
Liam Finn|I'll Be Lightning|1|Even Better To Be
```
Sorry @majewsky, not much we can do about this. Vanilla gets all the song metadata from the OS MediaStore which apparently only stores numeric track information.

**Comment by adrian-bl** [comment]
Closing this as there is nothing we can do about it: as @xbao already said: we use Androids media database, so there is no way to fix this.
