### ISSUE TITLE
Speed control feature request

### ISSUE THREAD

**Issue by pmeckoni** [vanilla-music/vanilla#299]
Please add a feature to control the **speed of the track being played as 0.75x, 1x, 1.25x, 1.5x, 2x**. Useful for listening to speech audio like podcasts or downloaded lessons from MOOCs. This feature is there in YouTube and in many MOOCs' video players used from web-browsers. I wish we had this in audio players as well. Please get this into Vanilla Music.

**Comment by Adonai** [comment]
The relevant bug is lasting for ages in Android bugtracker: [here](https://code.google.com/p/android/issues/detail?id=1961)

VanillaMusic uses Android MediaPlayer as a backend, so this feature depends mostly on Android development...

**Comment by willemw12** [comment]
The feature is available in [(API level 23)](https://developer.android.com/reference/android/media/PlaybackParams.html#setSpeed(float)).

Working example code:

    mMediaPlayer.setPlaybackParams(new PlaybackParams()
            .allowDefaults()
            .setSpeed(1.20f));

**Comment by adrian-bl** [comment]
Cleaning some up some old bugs:

I don't think this is a feature we should implement - there are already plenty of (free) audiobook players.

**Comment by jspraul** [comment]
Can anyone link to other open source players that support this functionality?

**Comment by adrian-bl** [comment]
Vlc supports this

**Comment by gaul** [comment]
Any chance to revisit this in 2020 with newer API levels?  I have foreign language MP3s that I would like to listen to at a slower speed.

**Comment by SebiderSushi** [comment]
@gaul For non-music i can recomment Voice 
https://f-droid.org/packages/de.ph1b.audiobook
https://github.com/PaulWoitaschek/Voice

Voice allows for playback speed in 0.1 steps from x0.5 to x2.5


Regarding the feature: I think it is an interesting experience to listen to music at different speeds as well so i think this would be a nice feature, but given the niche interest it's very understandable to focus resources towardz other thing in Vanilla Music.
