### ISSUE TITLE
Widget should remain display song metadata after reboot 

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#301]
After rebooting the phpne, the widgey no longer displays the currently selected (paused) song in terms of artist, title and artwork. Only the default text Vanilla Music is shown. Opening and closing the app, without playing anything, fixes this. However, the widget shouls always display the proper metadata.

**Comment by aminb** [comment]
This is something I've noticed and would like to have 'fixed' as well, and I believe in doing so we'd need to ask for at least one new permission (totally worth it in this case IMHO) to receive the boot completed action.

**Comment by adrian-bl** [comment]
Not sure if the end result would be *that* great on newer android versions: Android >= 5.x really tries to stretch-out auto-starts at boot. So it could take quite some time until vanilla starts - and in the meantime, the widget wold still display no contents.

But if someone would like to give it a try, feel free to do so

**Comment by PanderMusubi** [comment]
Do other ways exist to trigger this? Perhaps other rights?

**Comment by adrian-bl** [comment]
No: android starts services whenever it likes to do so.

**Comment by adrian-bl** [comment]
Closing this as it would require permission to launch on boot, which is done in a very 'relaxed' way since Android 7.x, so we wouldn't gain much (it could take minutes until we get started)
