### ISSUE TITLE
Please Support *.lrc files.

### ISSUE THREAD

**Issue by abc1236762** [vanilla-music/vanilla#302]
Please Support *.lrc files which are in the same folder where music files are to make vanilla music can show lyrics.

**Comment by Adonai** [comment]
Why use it when most files have USLT tag or similar? Isn't it better to integrate mp3 tinkering to write the lyrics into the same file? Or do you have such music collection?

**Comment by xbao** [comment]
> Why use it when most files have USLT tag or similar?

I don't now much about this stuff, but isn't USLT just text without any of the synchronisation metadata that .lrc contains?

**Comment by adrian-bl** [comment]
Btw: Talking about downloading lyrics (see PR #303): I just gave QuickLyric (https://f-droid.org/repository/browse/?fdid=com.geecko.QuickLyric) a try and it works fine with Vanilla Music: It receives our broadcasts and fetches lyrics after clicking on the notification.

**Comment by abc1236762** [comment]
but not lyric of any song can be found use quicklyric, sometimes we have to find or make lrc files by ourselves.

**Comment by adrian-bl** [comment]
Closing this old bug:

We now have plugins (and a lyrics plugin!), so this would be better handled there.

**Comment by Adonai** [comment]
Lyrics plugin can already write to *.lrc files btw
