### ISSUE TITLE
[RFC] Plugin System

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#304]
Vanilla Music should provide a plugin system like Twidere: We would like to keep the core of vanilla music small while allowing people to extend the player to their needs. Of course: People would always be free to fork us and implement any feature they like - but this is undesirable for us, our users and the people maintaining a fork.

**How will plugins work**
We can use androids standard Intents feature for this: This is the lightest and most stable way to do communication between multiple apps.
Vanilla Music already supports some intents, but they are not 'official' - we should probably mark some of them as 'public' and 'stable'

**Permission system**
Do we need this? Maybe - maybe not - twidere has this, but handles, unlike us, personal data (the media database is open anyway)

**Settings integration**
Would be very nice and could be done without too much hassle (android supports <meta> tags to indicate stuff)

**Comment by Adonai** [comment]
Regarding lyrics fetching, what to do with external applications? Vanilla-Music can emit some intent-signals about what it's doing but it cannot fetch back the answer that will be given. There should be a special agreement between developers of VM and external app.

This way there's no point in writing plugins that are already implemented by other tools.

**Comment by Adonai** [comment]
Also it would be better to outline strictly what can be included in PRs and what should remain as plugins. This way there will be no work done in vain.

**Comment by xbao** [comment]
Nice, I think a plugin system is a good way to provide the non-music functionality that some people want to have in the app.

> Vanilla Music already supports some intents, but they are not 'official' - we should probably mark some of them as 'public' and 'stable'

Definitely. 

> Permission system
> Do we need this? Maybe - maybe not - twidere has this, but handles, unlike us, personal data (the media database is open anyway)

I'm a bit confused about this. Is the idea that we have a custom `ch.blinkenlights.android.vanilla.PLUGIN` permission that plugin apps need to declare, that the user reviews (in theory ;) ) along with the other permissions the app declares on installation?

@Adonai raises a good point about level of integration. Will plugins be limited to simply observing whatever Vanilla's doing and providing their own UI? Or do we want to support more integration, e.g. adding context menu items?
The extreme end of this would be integrating a plugin provided View into the app using [RemoteView](https://developer.android.com/reference/android/widget/RemoteViews.html). For example, a lyrics displayer plugin could provide a view that dynamically displays the current lyrics, perhaps as a toggle-able replacement of the coverview in the fullscreen playback screen.

**Comment by berrythesoftwarecodeprogrammar** [comment]
or a plugin which allows the album art view to display the actual album art extracted from the currently playing mp3 instead of from android's inferior media database

**Comment by adrian-bl** [comment]
>  but it cannot fetch back the answer that will be given. 

Yes, but a plugin could send data back using an intent. Or we could use remoteviews if we really go crazy ;-)

> I'm a bit confused about this. Is the idea that we have a custom ch.blinkenlights.android.vanilla.PLUGIN 
> permission that plugin apps need to declare, that the user reviews (in theory ;) ) along with the other 
> permissions the app declares on installation?

No: From what i've seen, Twidere has its own permission system where it will ask you if it is ok for a plugin to eg. post on your behalf. The permission is enforced by twidere itself during runtime.
But we probably do not need such a thing as we, unlike twidere, do not handle any sensitive data.

> or a plugin which allows the album art view to display the actual album art extracted from the currently 
> playing mp3 instead of from android's inferior media database ;)?

Vanilla already can do something better: It will use 'cover.jpg' files in the same folder (IMO, embedded album artwork is a misfeature)

**Comment by Adonai** [comment]
Some bits were implemented in #447. What is the remaining work? Should we explore the way RemoteViews or DexLoader work for plugins or shall we settle on what we have now?

**Comment by adrian-bl** [comment]
I'd close this for now. If we need something which is more fancy, we can still re-open the issue at some later point.
