### ISSUE TITLE
files tab - sort by modification date/time

### ISSUE THREAD

**Issue by eternalbit** [vanilla-music/vanilla#305]
An option to sort the list of files (in the files tab) by modification date/time would be neat.

Explanation: this would make it easy to find the newest/oldest additions, which is what I often want to do.

**Comment by un-logic** [comment]
Meanwhile it's possible to sort by _date added SONGS_, _ALBUMS_ and _PLAYLISTS_. Just saying.

**Comment by jeremywh7** [comment]
I would more generally suggest having all the same Sort options available when navigating by Files (/Directories) as by Artist/Album/Genre tags.

**Comment by adrian-bl** [comment]
That's not possible as we are displaying files which are not indexed (eg: folders and images)

**Comment by abika** [comment]
I will try implementing this prior to #575.
