### ISSUE TITLE
Unable to reorder Tabs in Library setting

### ISSUE THREAD

**Issue by collectorgeneral** [vanilla-music/vanilla#306]
I tried to change the order of Tabs using:
Settings->Library screen ->Tab order

The only thing i can do is select whether a particular tab is displayed or not. Dragging the options does not work.

OS: Cyanogen OS 12.1.1-YOG7DAS2K1, Android 5.1.1

**Comment by aminb** [comment]
Can you provide more info/screenshot?

Can you see the drag handles, or are they invisible/disabled?

Also, which version of Vanilla are you using?

**Comment by collectorgeneral** [comment]
Sorry this issue is seems to be on my side. My phone was misbehaving for some reason and had to factory reset it. Everything seems to be fine now. Thanks for the reply though!
