### ISSUE TITLE
Set dark theme as default

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#309]
IMO, the dark theme looks better and should be the default on a fresh installation.

Any objections? ;-)

**Comment by aminb** [comment]
For me, I'm more used to the light theme and that's what I use throughout the day, although the dark theme is great for night time.

I wonder if we should add a very simple preference option for *automatic night mode* that would automatically switch to the dark theme on the given time interval (persumably at night) every day.

**Comment by kirbyfan64** [comment]
I like the dark theme, but, to me, the playback screen looks a bit odd when there's no cover art:

![Playback Screen](http://s5.postimg.org/vfd8tmhaf/Screenshot_20160320_103248.png)

IMO, the disc looks too dark. I mean, I'm probably just seeing things, but it just looks a bit odd to me...

**Comment by adrian-bl** [comment]
> I wonder if we should add a very simple preference option for automatic night mode that would
 > automatically switch to the dark theme on the given time interval (persumably at night) every day.

Twidere seems to have this feature, but for a music player i'd say that would be a little bit of overengineering ;-)

> IMO, the disc looks too dark. I mean, I'm probably just seeing things, but it just looks a bit odd to me...

What would you change? The disk is supposed to have a gradient. Do you think that the dark part of the gradient is to dark?

**Comment by collectorgeneral** [comment]
I use the dark theme and love it. It's more easy on the eye for me at any given time of the day so I would definitely support the option to make it default!

**Comment by adrian-bl** [comment]
Closing this for now: lets stick with the old defaults
