### ISSUE TITLE
[Feature Request] Add sub sort option

### ISSUE THREAD

**Issue by collectorgeneral** [vanilla-music/vanilla#310]
I have this issue, where I have several discs in an album, and I constantly find that sorting Alphabetically does not result in the albums being sub sorted in a particular way. As an example, I have attached a few pics. I have an album called "Assassins Creed 2" which has 2 discs. I have both of them stored in the sub folders "Disc 1" and "Disc 2". In the player, there are 2 entries, which I like. However the order is the otherway around. The first thing displayed in the library is the second disc. I suspect that by default its sub sorting by date added. Is it possible to add an option that will allow us to sub sort the items once you have sorted them in a particular way? So like in my case, i would like the ability to sort by Disc number once it is already sorted in alphabetical order.

![screenshot_2016-03-26-10-07-38](https://cloud.githubusercontent.com/assets/15972594/14060206/600216e4-f33b-11e5-8d09-9e4c34c5fa53.png)
![screenshot_2016-03-26-10-08-12](https://cloud.githubusercontent.com/assets/15972594/14060205/60020262-f33b-11e5-9b29-4b9e24bf0214.png)
![screenshot_2016-03-26-10-08-16](https://cloud.githubusercontent.com/assets/15972594/14060204/600035cc-f33b-11e5-9c87-22dca340d356.png)

**Comment by adrian-bl** [comment]
I'm sorry, but that's not possible:

Sorting is the result of a single SQL query and we can only use the columns which are available for a given 'type' (eg: album, song, artist)

Sorting by albums doesn't have any information about the album-number:

http://developer.android.com/reference/android/provider/MediaStore.Audio.AlbumColumns.html

(Note: album-id is an internal, mostly random number. So we can't use that)
