### ISSUE TITLE
Wish: normal playlists

### ISSUE THREAD

**Issue by Spielmops** [vanilla-music/vanilla#314]
Now if any trouble appears with media-scanner: the music is "gone" until next scan and the playlists are really gone for ever, my work is wasted! I wish, that vanilla-music creates normal playlists (m3u), which are stored at sdcard/Vanilla

Spielmops

**Comment by Spielmops** [comment]
Even worse: yesterday I installed a radioplayer for Internetradio where I stored a dozen radiostreams. They all apeared in Vanilla as playlists ...
Spielmops

**Comment by sKolar42** [comment]
I run into the first problem a lot too.  Simply the ability to save a playlist to a file would be a great help.

**Comment by adrian-bl** [comment]
-> Related to mediadb (#460)

**Comment by Spielmops** [comment]
Thank you for the reboot resitent playlists! Next project. import/export m3u .... :-)

**Comment by Spielmops** [comment]
My favourite music player is now https://play.google.com/store/apps/details?id=simosoftprojects.musicplayerforpad. I is independent of the mediascanner, can look inside .nomedia-folders and reads/writes playlists as files, which I can access.

**Comment by adrian-bl** [comment]
Glad that you found a player you like.

Just keep in mind that the software you are recommending has access to:

* your contacts
* your microphone
* the internet

That's not something *i* would use.

**Comment by Spielmops** [comment]
Thank you for this information. I'm aware of this. Most apps do that and this is the reason my phone is rooted, internet is blocked by AFWall, ads are blocked by AdAway and I use XPrivacy. This way the live with my phone is wonderful, because no ads make me angry and nothing happens without my permission ...

**Comment by adrian-bl** [comment]
Closing this as our playlists do not use the android media db anymore.
