### ISSUE TITLE
Add Persian Language

### ISSUE THREAD

**Issue by SaeedHashemi** [vanilla-music/vanilla#316]
Hi Dear 
I wanna translate this app to Persian,please add Persian language.
tnx

**Comment by aminb** [comment]
I can help with Persian translation too.

**Comment by adrian-bl** [comment]
We use Transifex to manage Translations:

Please register at Transifex and go to https://www.transifex.com/vanilla_music/vanilla-music-1/ and then request Persian as a new language.

I'll then add it + authorize you to edit the language.

**Comment by aminb** [comment]
Done.

**Comment by adrian-bl** [comment]
Ok, i accepted the language request in transifex

**Comment by aminb** [comment]
Thanks Adrian, I requested join as well.

**Comment by adrian-bl** [comment]
I accepted both join requests: Let us keep this bug open until the translation is done.
After this, just drop a comment here and include the new translation in the master tree

**Comment by adrian-bl** [comment]
I commited the 80% complete translation via https://github.com/vanilla-music/vanilla/commit/628e5938b63e1244ffa7ee340a14d5a51386b6af to the HEAD.

Updates to the translation will get fetched by our new 'update-translations.pl' script, so i think we can close this bug in the issue tracker.
