### ISSUE TITLE
Library search: no results on Meizu M2

### ISSUE THREAD

**Issue by xbao** [vanilla-music/vanilla#317]
No searches return any results. 

![searchnoresults_presearch_small](https://cloud.githubusercontent.com/assets/8990412/14230337/4c4eb6f6-f995-11e5-88f2-7d1e199eafe3.png) ![searchnoresults_noresults_320](https://cloud.githubusercontent.com/assets/8990412/14230336/4c4d5a2c-f995-11e5-8939-875bbb14efbe.png)

Pretty sure it's something to do with my device being terrible. Device is Meizu M2, 5.1. It's 'stock', but with heavy modifications by the manufacturer (as there's no back or recent tasks buttons...). 

Tested with latest master, Nightly and 1.0.35 from F-Droid

**Comment by adrian-bl** [comment]
Ieeks :-/

And this only affects search? Is it able to display Genres + filter them?

**Comment by xbao** [comment]
Yip, genres works as expected - displays and filters. I also just noticed that Playlists is empty. The built-in music app shows the playlists, but its search functionality is similarly broken. 

I have a Moto G3 on the way to replace the M2, probably won't look into this much more unless others report similar issues

**Comment by adrian-bl** [comment]
So they messed with the public API while keeping the private SQL structure untouched. Genius.

Do other players such as Timbre work better on the device?
If Timbre / Eleven has the same issue, we can probably scrap this as the device really is broken.

**Comment by xbao** [comment]
> So they messed with the public API while keeping the private SQL structure untouched. Genius.

Pretty much.

I did a bit more debugging, it looks like the problem can be fixed by stripping all the whitespace from keys returned by 'keyFor()', commit (on my fork): 4c223cbf5384fd3a0213fba2b34797bc895a536d. I think that's not a good idea in general though.

I installed Timbre, search seems to work, it would be good to see how they're doing their search.

**Comment by adrian-bl** [comment]
Oh, nice find!

I had a look at the AOSP sources and figured out the following:

Android seems to seperate each letter in the output by a TAB char (\s+ also matches TABs).
This seems to be done to avoid partial matches and happens here:
https://github.com/android/platform_frameworks_base/blob/master/core/java/android/provider/MediaStore.java#L1376

So a search for 'Bla' will actually result in a search for '.B.l.a.'. Eg: The following code
{code}
				Log.v("VanillaMusic", "getCollationKey(FOO)     *"+DatabaseUtils.getCollationKey("FOO")+"*");
				Log.v("VanillaMusic", "getCollationKey(.F.O.O.) *"+DatabaseUtils.getCollationKey(".F.O.O.")+"*");
				Log.v("VanillaMusic", "keyFor(FOO)              *"+MediaStore.Audio.keyFor("FOO")+"*");
{code}

Results in this output:
{code}
V/VanillaMusic(17176): getCollationKey(FOO)     *3EE*
V/VanillaMusic(17176): getCollationKey(.F.O.O.) *	3	E	E	*
V/VanillaMusic(17176): keyFor(FOO)              *	3	E	E	*
{code}

So the tabs *do* serve some purpose - and there is no guarantee that they are actually tabs: they could be any character.

Anyway: The 'tabbed' string then gets passed to a LIKE search, i'm not sure if this is super correct but the API documentation tells us that the result of keyFor() can be used for search - and it seems to work fine on any other device.

So i think we should just keep things as they are: IMO, we are doing the right thing and the M2 seems to be the only device which is affected by this issue.

**Comment by xbao** [comment]
Nice! Good to know. 

> So i think we should just keep things as they are: IMO, we are doing the right thing and the M2 seems to be the only device which is affected by this issue.

Completely agree. If more devices/people were affected a workaround might be in order, but we'll cross that bridge if we come to it.
