### ISSUE TITLE
Enhancement idea: scroll to playing song on library start

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#318]
Title says almost all. Covering all cases, like starting in library mode or returning from `PlaybackActivity`. Also scroll to playing album/artist in other lists. I'm planning to implement this, is it ok as a feature to be merged?

P.S. pls add enhancement label

**Comment by adrian-bl** [comment]
How would this work?
Would it scroll to the relevant entry in all tabs? (Song, Artist, Album, Genre, Files)

IMO, this could become confusing: i often scroll trough my library, change to some other app and expect the library to stay where i left off.

**Comment by Adonai** [comment]
> Would it scroll to the relevant entry in all tabs?

Yes, if the current song is present with current limiter config, that was the idea.

> IMO, this could become confusing

Makes sense, what about an option in settings menu like "Scroll to current playing track"?

It is convenient for me cause I always use shuffled playlists :)

**Comment by adrian-bl** [comment]
> Makes sense, what about an option in settings menu like "Scroll to current playing track"?

Would be OK with me if we make it an option and if it doesn't touch too much existing code (the whole adapter stuff is already complex enough)

Make sure to run it in a background thread - and it should probably only get triggered by LibraryActivitys onResume or onStart - otherwise we would jump around while the user is scrolling during a song change :)

**Comment by Adonai** [comment]
I just remembered. @adrian-bl, what do you think of highlighting current playing song in library view?

**Comment by adrian-bl** [comment]
That would be nice, but first we would have to change the library_row_expandable into the draggable_row layout to use the 'highlightRow(bool)' function

**Comment by Adonai** [comment]
Guess this can be closed as implemented ;)

**Comment by adrian-bl** [comment]
@Adonai fyi: i just pushed my changes to replace library_row_expandable with DraggableRow to the master, see: https://github.com/vanilla-music/vanilla/compare/9c47a3b90c084c819985faa07d916aea31aa3bb6...HEAD

so implementing the highlighting of the playing song would be simpler (already hacked up a prototype at https://gist.github.com/adrian-bl/05bdf344f83a681140fa14c12fdbe55f)
