### ISSUE TITLE
Offer two-way heart functionality for scrobbling 

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#320]
When using Somple Last.FM Scrobbler https://github.com/tgwizard/sls offer a two-way heart functionality. 

This may also be synces with star functionality (after a user explicitly activates this via settings in Vanilla Music and/or the scrobbler)

**Comment by adrian-bl** [comment]
Sorry, but i do not understand your report: Could you describe what the 'two-way heart functionality' is supposed to do?

**Comment by PanderMusubi** [comment]
Ah, to "heart" is to like a song in terms of LastFM and LibreFM. However, this can also be done and undone by other players and the websites of the services. Hence the two-way in the request. There is plenty of reference implementation out there, also for Android.

**Comment by adrian-bl** [comment]
I think that this feature would be an ideal candidate for the plugin feature (#304 ) or some other standalone app:

This could be implemented outside of Vanilla Music quite easily as the app would only have to 'synchronize' the Favourites playlist

**Comment by PanderMusubi** [comment]
Well the link with the favourits was just an additional idea up for discussion.

The core of this request is the "heart", for which the API is already in a standalone app, https://github.com/tgwizard/sls

Think better not to mix the "star" and the "heart", espcially not automatically. What is left, is to be implemented in vanilla and should only show up when scrobbler API is present and active.

**Comment by adrian-bl** [comment]
Closing this as wontfix as this could be done using a plugin.
