### ISSUE TITLE
playlist silent gap

### ISSUE THREAD

**Issue by Piscium** [vanilla-music/vanilla#322]
Mixxx has a feature in its AutoDj mode whereby a silent gap of up to 9 seconds can be played between songs. I like silent gaps. To achieve it with Vanilla I add a 2 second silent mp3 in my playlists after each song. This works but the downsides are that the playlist becomes twice longer and hard to read.

Enhancement suggestion: a new configurable parameter called “Playlist Silent Gap” that can have a value between 0 to 9 seconds. If > 0 then a silent gap will be automatically played by Vanilla after a  song in the playlist ends and before the next one starts.

**Comment by adrian-bl** [comment]
Sorry, but that's not a feature i'd like to implement.

**Comment by Piscium** [comment]
No problem. 
Thanks for a great program.
