### ISSUE TITLE
Controls swipe down notification drawer should be white

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#323]
Controls swipe down notification drawer should be white. Currently the pause, next and previous buttons are black.

**Comment by adrian-bl** [comment]
Could you please explain this in more detail?

I have no idea which UI element you are talking about.

**Comment by PanderMusubi** [comment]
If Vanilla is playing, you swipe down from the top of the screen. You see for Vanilla the album art and some playback buttons and 'x' to exit Vanilla.

**Comment by adrian-bl** [comment]
Yes, and what is the issue with the notification?
Could you provide a screenshot?

**Comment by PanderMusubi** [comment]
![white](https://cloud.githubusercontent.com/assets/198964/14466048/84e436ac-00d5-11e6-9763-4927084fa95a.png)

**Comment by adrian-bl** [comment]
Ok, so you are using a non standard theme - or is this a stock theme?

Material Notifications are supposed to be white.

**Comment by PanderMusubi** [comment]
I am using default Cyanogen OS 12.1.1 on Android 5.1.1 that ships with One Plus One

**Comment by adrian-bl** [comment]
Ok, so the 'geniuses' messed with the default color.

We could force the notification to use the default background color for notifications, but i suppose that they also changed it to black (the notification inherits this parameter usually)

What color is used for other notifications? Do they also show up black?

**Comment by PanderMusubi** [comment]
Yes, someone has dropped the ball for a second. ;)

All/most other colors are fine. Same problem arises with one other app (that is probably also playing nice and using default colors and not overriding them with custom stuff). Think this needs is a bug report upstream. Could you do that please?

Is it possible to make a workaround until they fix it? (Get the default text color in dark theme, if black -> use white, blah blah)

PS   Soon, my device will be upgraded OTA to the next version. I will keep an eye out if that fixes it.

**Comment by adrian-bl** [comment]
> Could you do that please?

No, sorry. I do not have the time to file bug reports for messed up firmware.

> Is it possible to make a workaround until they fix it?

We could get around by tinting the button using a framework color.
Could you please provide a screenshot of the expanded notification using this apk?:
https://mega.nz/#!r5Ny2KCQ!Y9BrXiZu2K0snZ_M6KS-h5FgPTdrS4tDiidX0o45gQI

(or recompile with https://gist.github.com/adrian-bl/b34f98c0f1b11178c208d45801e3dff7)
The button on the right edge should look OK if they also adjusted the text color.

**Comment by PanderMusubi** [comment]
My device fails to let F-Droid install it. :( Can only test build that come via F-Droid store at the moment.

**Comment by adrian-bl** [comment]
You need to uninstall the fdroid version first because the APK is signed using a different key.

After this, you can install the APK from any filemanager or via

adb install package.apk

**Comment by adrian-bl** [comment]
closing due to lack of response

**Comment by PanderMusubi** [comment]
haven't gotten around yet to test it, sorry

**Comment by PanderMusubi** [comment]
Bit late but meanwhile, it is fixed.
