### ISSUE TITLE
Start when headset plugged in (CM13)

### ISSUE THREAD

**Issue by steelman** [vanilla-music/vanilla#325]
CyanogenMod 13 (and respective Android I suppose) can start a music player when user plugs in headset.

https://github.com/CyanogenMod/android_frameworks_base/blob/c6aef76f38c17f115be164bbbae09d4d3ddaff31/services/core/java/com/android/server/audio/AudioService.java#L5136

Please make Vanilla Music launchable this way.

**Comment by adrian-bl** [comment]
Fixed via: https://github.com/vanilla-music/vanilla/commit/a7bc9c7cc4225a20d06fda3ec87372722db016e8

We are now acting as APP_MUSIC
