### ISSUE TITLE
Improve icon in top of screen

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#326]
Please improve the icon in the top of the screen. See attachment below. The square border gives it a hard user experience and is also in contrast to most of the icons to be expected there. Removing that square border gives the icon a more gently experience and complies more with other icons there. Also, the resulting round can be made a bit bigger so that the margin with the triangle that points to the right is bigger, making it a more robust icon.

With the current icon, I have to look twice what it is because visually I have to filter the border away. The proposal will make the icon and the app more associated with each other and increase user experience.

![icon](https://cloud.githubusercontent.com/assets/198964/14466347/b478d8c2-00d6-11e6-9727-fa450da8bb24.png)

**Comment by adrian-bl** [comment]
I do not think that the existing icon is that bad. It resembles the app icon and is IMO quite okay.

But we can change it if someone comes up with a better design and provides an SVG version of it.

**Comment by PanderMusubi** [comment]
Preview:
![status_icon svgz](https://cloud.githubusercontent.com/assets/198964/14543680/a22e58de-0295-11e6-9377-3fd268a1bf22.png)

SVG:
[status_icon.svgz.zip](https://github.com/vanilla-music/vanilla/files/219954/status_icon.svgz.zip)

**Comment by rejhgadellaa** [comment]
Isn't that the default 'play icon within a circle'-icon? It's really easy to generate notification icons for those using Roman Nurik's Android Icon Generator. It creates all the versions for various dpi's (from mdpi to xxhdpi) and sdk <= 13 + > 14.

I've taken the liberty of creating a zip:
https://stor4ge.rejh.nl/_stored/dump/various/ic_stat_av_play_circle_fill.zip

Here's a link to the generator with the correct icon:
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.space.trim=1&source.space.pad=0&source.clipart=res%2Fclipart%2Ficons%2Fav_play_circle_fill.svg&name=ic_stat_av_play_circle_fill

**Comment by adrian-bl** [comment]
@PanderMusubi Thanks for the SVG file: This is a screenshot of the old + new icon taken on real hardware:
![image](http://i.imgur.com/Mv15Gn8.png)

I somehow like the old icon more, but maybe it's just because i am so used to it. @aminb & @xbao : what do you guys think? should we switch to the new icon?

@rejhgadellaa Thanks for the link, didn't know about this handy site. However: We try to have SVG sources for as many drawables as possible: The drawables are automatically converted to PNGs using inkscape by ```generate-pngs.sh```. Having the SVG sources in-tree makes it easy to support newer display sizes

**Comment by xbao** [comment]
Nice proposal. I like that the proposed icon isn't as 'busy' as the current one. However, I already have trouble associating notification icons with the app that created them, and as @adrian-bl said the current icon looks like the Vanilla app icon which I find helpful. I prefer the current icon to the proposed icon.

**Comment by aminb** [comment]
@PanderMusubi Thanks for the SVG.

I generally agree with @adrian-bl and @xbao but I have to admit I quite like the new proposed version.

I'm thinking maybe we could find a middle ground. How about getting rid of the thin circle in the current version (the square icon) and have the triangle directly inside the square. This way the the icon would also shrink a bit and be more consistent with other notification icons (as shown in the screen shots). I wonder how that would look.

**Comment by PanderMusubi** [comment]
Agreed on another evolution. The old/current done is too big and each time I think: "What is this?" because it screams a bit for attention. The one in the screenshot with the mountains looks better with its smaller size and 1997's rounded corners. Woudl that one with a play triangle be a good new one?

**Comment by relan** [comment]
How about this?

![status-icon](https://cloud.githubusercontent.com/assets/8256809/14934294/8739a81a-0ebd-11e6-891f-17889252394a.png)

It resembles Vanilla's launcher icon and thus could be easily recognized by user. And it does not have sharp corners.

**Comment by adrian-bl** [comment]
Looks nice to me

**Comment by PanderMusubi** [comment]
Mine B followed by A

See also https://github.com/vanilla-music/vanilla/blob/master/res/drawable-hdpi/icon.png

**Comment by rejhgadellaa** [comment]
I think B has the most presence (largest amount of white, that helps :)) so that's easiest to spot I guess.

**Comment by rejhgadellaa** [comment]
Grr. Mobile, can't edit comments. I wanted to add: "without begin all white and thus not recognizable"

**Comment by adrian-bl** [comment]
@relan do you have an SVG version of the icons?
If yes, i'd push it to the master, so people could give it a try on 'real hardware' using a nightly build.

**Comment by relan** [comment]
> do you have an SVG version of the icons?

Yes.

> If yes, i'd push it to the master, so people could give it a try on 'real hardware' using a nightly build.

Tell me which one you want and I'll make a pull request as soon as I get to my PC (tomorrow, I think).

**Comment by adrian-bl** [comment]
Great: i think we should give variant 'B' a try

**Comment by relan** [comment]
Sorry for the delay, created #335.

**Comment by un-logic** [comment]
Variant 'A' may be a little bit more stylish if you think of it not as representation of a speaker (as in 'B') but as a top view of turntable with dark vinyl disc on top instead.

**Comment by aminb** [comment]
I like both `A` and `B`, but I do like `A` better.

**Comment by adrian-bl** [comment]
@relan Thanks for the PR - I merged it into the master and forced a nightly build, so a version using this icon is now available from http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk

IMO, the icon looks very nice :-)

**Comment by relan** [comment]
Thanks all for your feedback! It would be great if you share your impressions after using the app for some time on your real devices.

I'm surprised nobody likes D. It's my favorite: it resembles launcher icon as much as possible and looks fine even on low resolution screens.

**Comment by adrian-bl** [comment]
Btw: this is already live in the playstore version: i had to push a bugfix update and included the commit by accident, oops ;-)

But anyway: we will get even more feedback now ;-)

**Comment by un-logic** [comment]
Well, first thing I've noticed upon installation of nightly was that new icon is a bit smaller than old square one. In my opinion new icon is looking somewhat off when compared to TouchWiz ones in size. But I'm totally aware that it might be a perfect fit to other launchers' themes.
Here's the screenshot for comparision purpose:
![screenshot_2016-05-05-23-33-25](https://cloud.githubusercontent.com/assets/9430664/15083958/711a8eae-13e1-11e6-84c4-d11b948042ea.jpg)

**Comment by adrian-bl** [comment]
The old icon was always a little big to big (for material standards), the new one is IMO correct: It matches the size of the screenshot icon perfectly

![http://i.imgur.com/gViWi6fl.jpg](http://i.imgur.com/gViWi6fl.jpg)

**Comment by rejhgadellaa** [comment]
I agree with @adrian-bl. It's better to use the specs that the platform officially uses instead of a manufacturers implementation. Especially not Samsung's :P

**Comment by adrian-bl** [comment]
The new icon now has been 'live' in the play-store & f-droid builds for quite some time.
So far i didn't get any negative feedback and i quite like it :-)

What should we do about this bug? Should we close it or give one of the other variants a try?

**Comment by un-logic** [comment]
I'd like to try out variant 'A', in my humble opinion, it should look better than 'hole in the middle' design that is currently in use. 
Although I don't believe in democracy when it comes to making such a decision, because it may all end up in countless changes and in the end there will still be unsatisfied minority, so maybe simply close with chances of reopening in case of riots?

**Comment by aminb** [comment]
@relan Do you have the svg/png for other variants by any chance? I'd like to try them out on my device.

**Comment by PanderMusubi** [comment]
Perhaps in stead of B the hole in the middle, B with a circle in the middle? Think that will solve the hole thing too.

**Comment by un-logic** [comment]
@PanderMusubi
Do you mean variant 'C' or do you propose new variant: 'E'?

**Comment by PanderMusubi** [comment]
E, as example here but inner circle bit smaller

![test](https://cloud.githubusercontent.com/assets/198964/15293231/5bb40506-1b87-11e6-83a3-e833bc6d2fab.png)

**Comment by relan** [comment]
> Do you have the svg/png for other variants by any chance?

Nope. You can easily remake them from `orig/status_icon.svgz` using Inkscape.

**Comment by Allanitomwesh** [comment]
I like the current icon, I believe it's B? It looks good

**Comment by adrian-bl** [comment]
Closing this issue as we are going to keep the current icon
