### ISSUE TITLE
Breadcrumb navigation in files should jump to folder, not close it

### ISSUE THREAD

**Issue by Stevko-sk** [vanilla-music/vanilla#327]
In files, when I am in a folder /foo/bar/baz/foobar, I get [breadcrumbs](https://en.wikipedia.org/wiki/Breadcrumb_(navigation)) of them in lower part of the screen with X next to them. When I touch (for example) baz, I get to fo folder bar (one above baz). I expected that clicking the folder name would jump into it (and only clicking X would close it). Can you either make it like that? Or even make it so that clicking a folder name jumps into it and remove X from breadcrumbs (it could have an option to choose behavior)

**Comment by adrian-bl** [comment]
Sorry, but the UI element is not supposed to be a breadcrumb:
They are (internally) called Limiter and act as a filter. While they seem to have some sort of hierarchy, they really don't have one, so jumping to the 'middle' of a limiter chain is not possible.
