### ISSUE TITLE
Playlists lost after update

### ISSUE THREAD

**Issue by aminb** [vanilla-music/vanilla#340]
On behalf of /u/smitt75 [from reddit](https://www.reddit.com/r/vanillamusic/comments/4hv7kc/love_vanilla_music_but/):

> After updating one of the most recent versions via F-Droid all my playlists were lost. Maybe allow the backup of playlists.

P.S. There was an effor for adding import/export of settings at #222 and #246. For exporting playlists, there was #179, which was rejected, but it'd be nice to have the export of settings also export playlists as well.

**Comment by adrian-bl** [comment]
Sorry, but this just can't be the fault of Vanilla Music:

The playlists are stored in androids media store and they are persistent - they will even survive an uninstallation of vanilla music.

**Comment by un-logic** [comment]
@adrian-bl
I second you on that, adding or deleting of playlist is system-wide and it can be observed easily e.g. when running both stable and nightly builds of Vanillas simultaneously. But as for I've recently discovered a nice feature of sorting _Songs_ library view by _play count_ with further queuing of tracks with _shuffle mode_ off; I wonder how to backup _play count_ info? It has been noticed, that stable and nightly builds doesn't share this sort of information between each other. And yes, there is _Top 100_ automatic playlist generation, but it won't restore play count info in any way.
@aminb 
F-droid repository also contains kreed/vanilla music player (abandoned software), could there be any misconception?

**Comment by aminb** [comment]
@adrian-bl Sounds logical.

@un-logic That might have been the case, but I can't know for sure. The user hasn't replied [yet].

**Comment by adrian-bl** [comment]
Closing this issue as it must have been triggered by some other issue
(A common source of errors are playlists stored on sd-cards which are not available anymore after a reboot - but there is not much we can do as we are just a consumer of the media database)
