### ISSUE TITLE
Show queue action has gone [Regression]

### ISSUE THREAD

**Issue by un-logic** [vanilla-music/vanilla#341]
It is now impossible to bind tapping or long pressing on cover art to show up Queue activity.
I think this is due to latest changes discussed on #284 and #319. Although it is clear that binding _Show queue_ to horizontal and vertical swipes may lead to glitches and confusion I find it crucial to have a way to bring up queue with simple touch, especially when device lays on smooth flat surface, instead of bottom-to-top swipe. That wouldn't hurt anyone, right?

**Comment by adrian-bl** [comment]
Yes, it would't hurt and we have now a clean api to communicate with the slider, re-implementing it shouldn't be a big issue.

**Comment by un-logic** [comment]
Nice to hear this. And once you tagged this issue as an enhancement I'd like to extend my request to accelerometer shake action too. Also for accelerometer action _Show now playing_ option is appropriate addition. Or even combined _Toggle Library/Queue/Now playing_ option that will make accelerometer shake useful again.

**Comment by ToNIX-** [comment]
Yay, swip down makes to show queue makes sense, thanks @adrian-bl !

**Comment by adrian-bl** [comment]
Ok, this should be fixed in https://github.com/vanilla-music/vanilla/commit/2ae7e3123daee458af6aa6a0841936392edb97da and is already included in the latest nightly build

**Comment by un-logic** [comment]
Just finished testing latest nightly build and noticed following:

- Binding _Show queue_ to swipes, tap and pressing cover art works flawless, thank you, @adrian-bl!

- Binding _Show queue_ to accelerometer shake action doesn't work - no reaction. Expected to trigger at library, now playing and queue views.

- _Toggle controls_ to accelerometer shake action doesn't work nor on nightly neither on stable builds. Expected to trigger at now playing and queue views.

- _Toggle controls_ action prevents execution of _Show queue_ action. Example given. Say I'm anxious about Queue, thus set all swipes and tap on cover art to _Show queue_ and long press to _Toggle controls_. Normally Now playing view has controls visible and there's a **menu** option to _Show queue_. Now if you hide controls using long press followed by any of the actions, assigned to _Show queue_, there won't be any changes on the screen, except, that **menu** option _Show queue_ has changed over to _Hide queue_. Any further attempts to bring up queue list will be blocked this way until you long press once more to toggle hidden controls. Eventually Vanilla process halted when I've tried to switch back and forth to Library view some after. Expected behaviour is to be able to bring up queue list with or without controls, also, consider combination of _Toggle controls_ action bound to accelerometer shake with queue list toggling by e.g. bottom-to-top swipe.
Sorry, this reply didn't ment to be so long, anyways, thank you for your response!

**Comment by adrian-bl** [comment]
> Binding Show queue to accelerometer shake action doesn't work - no reaction. Expected to trigger
> at  library, now playing and queue views.

This never worked as the accelerometer signal is consumed by the PlaybackService which can not really send this to the (maybe, maybe not) existing view. We should probably make ShowQueue & HideControls unselectable as a shake action.

> ... there won't be any changes on the screen, except, that menu option Show queue has changed 
> over to Hide queue. 

Yeah, that's because the view of the queue gets hidden.
We should probably forcefully show the controls if the queue becomes visible - or just ditch the 'hide controls' feature - does someone really use it? :-)
