### ISSUE TITLE
Sorting Library view by Play count [Bug]

### ISSUE THREAD

**Issue by un-logic** [vanilla-music/vanilla#342]
In the _SONGS_ tab sorting by play count in ascending order brings most popular tracks, having bigger value, on top of the list and sorting in descending order brings them down. Such a behavior,  although being quiet handy, is not what it is expected to be, which is contrary.

**Comment by adrian-bl** [comment]
This is intentional, see: https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/MediaAdapter.java#L319

I agree that it is confusing but i'm not sure if we really should change it: I wrote the code this way because i always have my sort order in ascending order - as it makes most sense for any other sorting mode (alphabet, track, year, etc) - the playcount is some kind of special snowflake here.

**Comment by un-logic** [comment]
That was something I have suspected to be the case.
So if we have informal order for _play count_ that is convenient, why don't then apply same behaviour for _number of tracks_, _date added_  and _year_, because it will be convenient to have longest, most recent or newest items on top by default, rather than need to select _descending_ order additionally. Of course, if it will be decided this way then, in my opinion, it's logical to subtitude _ascending_ and _descending_ bullets with _invert_ checkbox for rare cases.
Or we might switchback to formal sorting, which is strict, but not always as convenient as it could be. 
Also consider added confusion to user experience #339.

**Comment by adrian-bl** [comment]
I agree that the sorting-dialog is badly designed.

> It's logical to subtitude ascending and descending bullets with invert checkbox for rare cases.

I think thats a nice idea and we could just swap the bullets with an invert/reverse-sort checkbox in all cases:

This would make the 'sort by playcount' clearer and wouldn't harm normal sort options such as 'sort by name'

**Comment by adrian-bl** [comment]
ok, i implemented this in https://github.com/vanilla-music/vanilla/commit/7a8f349f374358e8ec33669d411c29a798d093fd and i think it's much better than what we had before:

![img](http://i.imgur.com/1DswrMt.png)
