### ISSUE TITLE
How to open the Vanilla Equalizer?

### ISSUE THREAD

**Issue by adelriosantiago** [vanilla-music/vanilla#345]
How do I open the equalizer named **activity_equalizer.xml** and **activity_equalizer.xml**?? Currently when I click on the Settings > Equalizer the Android' default equalizer comes up, however this equalizer is very limited as there is no way to change the gain on each band.

**How do I open the Vanilla Equalizer?**

**Comment by ToNIX-** [comment]
Unless I'm mistaken (I don't use any equalizing presets), you'll need a distinct app for this. Pressing the equalizer settings from Vanilla Music will launch your preferred app.

**Comment by adelriosantiago** [comment]
Closing issue, you are right, the default action has always been to open the Android's Equalizer. And the **activity_equalizer.xml** is on another branch.
