### ISSUE TITLE
Sort By Year not working

### ISSUE THREAD

**Issue by mhanna49** [vanilla-music/vanilla#346]
When I sort by year when I am in the albums view showing all of the albums on my device or all of the albums by a particular artist, the sort by year option appears to only sort by name. My files are properly tagged and are sorted appropriately in apps such as Poweramp and GMMP.

**Comment by adrian-bl** [comment]
Are you sure that Vanilla picked up the year correctly?
We are using Androids internal media database and android can be *very* picky about indexing the year (eg: old versions simply failed to do this for some file formats)

You can verify that the year was actually indexed by long-pressing on the song information in the playback screen: This will show you additional information, such as genre, replay-gain and the indexed year.


I just checked this on my device running CM12 and it seems to be working as expected.

Data from sqlite:
```
sqlite> select album,minyear,maxyear from album_info;
album|minyear|maxyear
The Slip|2008|2008
Faszination Weltraum|2014|2014
iDisco Single||
```

..and selecting 'order by year' in vanilla music will result in exactly the same sorting.

**Comment by mhanna49** [comment]
I did a long-press on the song information and it looks like it isn't getting the year from the tags on my files. I have the year stored in a %date% tag so that is probably the issue. I tried adding a year tag with the same value as the date on a few albums and it properly sorted those. Is there any way Vanilla can sort the year by using the date tag or is it always looking for the year tag?

**Comment by adrian-bl** [comment]
Vanilla itself doesn't read the tags: this is done by Androids MediaScanner library:
This library only looks at the 'year' tag, see: https://android.googlesource.com/platform/frameworks/base/+/cd92588/media/java/android/media/MediaScanner.java#623

**Comment by mhanna49** [comment]
Thanks for the responses. I'll close this out because it's an issue with my tagging scheme.
