### ISSUE TITLE
Queue obscures parts of track info fixed on top

### ISSUE THREAD

**Issue by v1kn** [vanilla-music/vanilla#347]
Display track info `fixed on top` shows more information, like replay gain, compared to two other options.  With new design, the queue covers up replay gain leaving only essential track info. 

The issue is, dismissing queue does not bring back replaygain info. Display is stuck with only essential track info. To get back replaygain one has to go back to settings, choose a different option for track display, and then revert back to fixed on top. Opening up queue will mess it up again though

**Comment by adrian-bl** [comment]
> the queue covers up replay gain leaving only essential track info. 

Expanding the queue will collapse the extended track information

> To get back replaygain one has to go back to settings, choose a different option for track display

Doesn't long-touch on the track-info open it again? That's actually the only way to bring it up in the first place anyway :-)

**Comment by v1kn** [comment]
Yes it does, thanks. 
Didn't think of long-pressing the info  ;)
Still it would be nice if it was done automatically on dismissing the queue

**Comment by adrian-bl** [comment]
I agree: We should probably either restore the old state or not collapse it (but make the queue view consume less space)

**Comment by adrian-bl** [comment]
fixed via 3fd4c28386a276e2e23ba71e894bb2eb137eb23b
