### ISSUE TITLE
ID3 Lyrics

### ISSUE THREAD

**Issue by aminb** [vanilla-music/vanilla#348]
On behalf of /u/saisar [from reddit](https://www.reddit.com/r/vanillamusic/comments/4jigk3/thanks/):

> Can you display lyrics from ID3 tags? (like in iTunes iguess). Not as the other guy was saying, from the Internet, but from the song itself.

**Comment by un-logic** [comment]
What about time [synchronized](http://id3.org/id3v2.3.0#Synchronised_lyrics.2Ftext ) lyrics tag?
Also, this will need some extra space in UI, either add 'Lyrics' tag listing to existing tags list, and/or reuse playback layout mode 'over an album art' for display purposes, or even something better.

**Comment by Adonai** [comment]
@aminb , I requested a transfer of [my repository](https://github.com/Adonai/vanilla-music-lyrics-search) to you, pls place it into org as well.

**Comment by aminb** [comment]
@Adonai Done! :)

**Comment by hphi** [comment]
It seems that it is now possible to show ID3 lyric tags with the lyrics plugin for Vanilla Music. It would be a great feature! Where can I download the .apk file and/or how to best install the plugin?

**Comment by Adonai** [comment]
I guess this can be closed as we now have ID3 lyrics support via [Lyrics Plugin](https://github.com/vanilla-music/vanilla-music-lyrics-search) + [Tag Editor Plugin](https://github.com/vanilla-music/vanilla-music-tag-editor) integration.

**Comment by adrian-bl** [comment]
+1 for closing this issue

**Comment by aminb** [comment]
Awesome, thanks for your contributions @Adonai, and thanks @adrian-bl too!

Closing this then.
