### ISSUE TITLE
track skip-count

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#350]
we already track the play count, we could do the same with the skip count - and then implement weighted-shuffle or something nice.

**Comment by un-logic** [comment]
Great idea, IMO!
And what about backing up or even exchanging [play count](http://id3.org/id3v2.3.0#Play_counter) and [this popularity](http://id3.org/id3v2.3.0#Popularimeter) information via idv3 tags? May there occur any problems related to updating tags?

**Comment by adrian-bl** [comment]
We do not have write-support in our tag-reading library - and vanilla music also supports other formats which do not have such a field, so storing this information for *some* file types would be quite confusing - also: there is absolutely no guarantee that we have write permission on a file

**Comment by un-logic** [comment]
OK.
Just for information, usually tag writing mechanism is being triggered by user himself once in a while, so it's his obligation to ensure that all files are accessible and providing user with some mass-retry and mass-skip options is a good enough practice.
The only thing that is bothering me is backing up and moving these stats to a new device.
Anyways, looking forward to see new feature.

**Comment by adrian-bl** [comment]
Skip-Count is now implemented via d4747757bdc54741f6c31f0c6b365a2655c4d77e (no user visible features yet, but we are at least tracking it)
