### ISSUE TITLE
[BUG] Pause button don't really pause music

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#351]
Most of the time, when I pause my music and I play it then, the song don't continue where I left it but it move forward **as if I have not pressed pause** , however, the minutes are the same (for instance, I pause at 1:02 , when I press Play, it will continue to 1:03 1:04 1:05.. BUT the song will be far from these values)

As I said, its most of the time but not every time (its very rare that it work though)

**Comment by adrian-bl** [comment]
What device and android version are you using?
Could you please provide a logcat?

**Comment by andiandi13** [comment]
I'm using a  SONY XPERIA V (Model LT25i), running on JellyBean 4.1.2 stock

I generated a logcat with **Catlog** app while I was pausing/playing a song, I hope the log will be helpful
[2016-05-16-14-49-04.txt](https://github.com/vanilla-music/vanilla/files/266102/2016-05-16-14-49-04.txt)
.

**Comment by adrian-bl** [comment]
Unfortunately there are no unusual errors in the logcat and i don't think i can do much about this :-/

The only unusual thing i've seen is, that the audio-service crashed at least once.
Did you try to reboot the phone? and if yes: does it get 'better' or stay the same?

**Comment by andiandi13** [comment]
I've just restarted my phone and the problem is the same, my pause button is almost useless :/

I noticed that if I play the music again after it was paused for 3/4 seconds it's OK, the song plays where it stopped **but if the "pause time" is more than these 3/4 seconds** (approximately) the song plays far. 

It's like PAUSE is active for a very few time, very strange...

I have tried almost a hundred of music players on my phone and none of them had this issue.

**Comment by adrian-bl** [comment]
Thats strange - and you seem to be the first user with this issue.

What i do not quite get is why the time-indicator is off: We do not have this information on our own but get it directly from the android media-service

**Comment by andiandi13** [comment]
My sister has the same phone - same ROM and same issue..

I am installing cyanogen 5.1.1 right now to see if the issue come from the ROM or the phone/the app

**Comment by andiandi13** [comment]
It seems to be the ROM ! 
On Cyanogen 12 it works perfectly. I won't stay on it though since it drain battery on an old Xperia V but at least I know that my ROM is responsible (and maybe vanilla I dont know)

I suppose that you can't do anything

**Comment by adrian-bl** [comment]
Ok, thanks for testing this.

I'll then close the ticket as it is impossible to debug this for me.

If you would like to play around with it: have a look at PlaybackService.java mMediaServer - maybe you'll find something unusual, but AFAIK, we do not do any funny stuff which could trigger such an unexpected behavior.
