### ISSUE TITLE
Themes support

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#352]
I was somewhat bored and created the 'colors' branch: https://github.com/vanilla-music/vanilla/compare/master...colors

The branch makes it simpler to support more than two themes:
![](http://i.imgur.com/d5f1gcb.png)
![](http://i.imgur.com/ASd5NHi.png)
![](http://i.imgur.com/AD0VkMx.png)

If you would like to play around with it: Edit 'generate-theme.pl' and run it, then recompile.

generate-theme.pl will automatically create all required XML files for the new/changed theme

/cc @aminb @xbao

**Comment by aminb** [comment]
Looks cool! I like the last one (dark one) in particular, and I'm sure we could get interesting results playing around with colors.

**Comment by adrian-bl** [comment]
I also like the dark one very much (we had this in a very early stage of the material-design work ;-) )

Orange and green don't look so good on real hardware, i'll also play around with the colors when i have time - and we also need a nicer theme-chooser (currently just a listview in a dialog)

**Comment by adrian-bl** [comment]
Fyi: i merged this into the master. A simple theme chooser fragment has also been created

**Comment by Allanitomwesh** [comment]
I've installed a couple of popular material players just to compare. More have the X than dont have,so removing it might be unnecessary
I like the notification changing color,that's nice. 
The X on vanillas notification is the largest,it needs to be resized smaller
One of the players has "swipe up from now playing screen to enter queue",its very nice I like it. 
You can generally swipe into new screens more on the other players,not sure how this can be done in vanilla but I'll come up with ideas

**Comment by Allanitomwesh** [comment]
Oops a mixup
What I wanted to ask here is, Is it possible to get some default ones in settings that you can just click on,like say,a dozen popular colors?

**Comment by adrian-bl** [comment]
Yes: The nightly build already has an orange color scheme, more will come when i feel like it :-)
If you have the sdk installed: feel free to experiment with it: Just edit 'update-themes.pl' and run it to update the metadata, then recompile and install (no code changes required)

**Comment by Allanitomwesh** [comment]
That's great to hear,I'll look out for it on the next update. I'm sure someone will play around with this and help you before I figure out how SDKs are installed

**Comment by andiandi13** [comment]
Hi, the theme option crash in the nightly build for me. Is it because I'm on jellybean and themes are only for 5.0+ ? (My vanilla being black and not white)

**Comment by adrian-bl** [comment]
Yes, themes are only available on 5.x, see #375

**Comment by andiandi13** [comment]
Oh OK then thanks

**Comment by adrian-bl** [comment]
Closing this as themes support has been released - people are invited to send new color schemes as pull request
