### ISSUE TITLE
folder long-press should have a play-all

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#354]
Either as long-press action or as a toplevel entry (like we have in other views)

**Comment by Alper9** [comment]
Good Afternoon, 
I just want to know which file I should modify to fix this issue ?

Kind Regards

**Comment by adrian-bl** [comment]
Thanks for the pull request, but unfortunately the patch doesn't work that well:

* Long pressing a folder and selecting Play All works - but this functionality was already present with the 'Play' option
* Long pressing on an *item* inside a folder and hitting Play All will only play this single item (the idea behind #354 is to play all files in this folder)
* Please try to stick to the existing coding standards: '(foo,0)' should be written as '(foo, 0)'

**Comment by adrian-bl** [comment]
https://github.com/vanilla-music/vanilla/commit/010aa84185e14127829693aa8b8886b2f8af56bf implements the play all header
