### ISSUE TITLE
Genres tab: expand to Songs when Artists tab disabled

### ISSUE THREAD

**Issue by pinnie** [vanilla-music/vanilla#356]
There was a change [back in 1.0.34](https://github.com/vanilla-music/vanilla/issues/181) which altered the way the Genres library functions - instead of expanding to Songs, tapping the arrow goes to Artists (only noticed the change today while setting up a new phone - had remained with 1.0.20 on the old one).

This behaviour isn't so great for someone who primarily selects tracks by genre while tending not to play by artist. I'd always disabled the Artists tab, but in the current version, the result is that the arrow next to a genre does nothing. Perhaps when the Artists tab is disabled, the old behaviour (Genres > Songs) could take effect?

**Comment by adrian-bl** [comment]
This has been fixed via: 8e4fad61ed8ff82c3ce09c8b5e967ec55789d711

We will now switch to the 'next best' visible item: Artist > Album > Track
