### ISSUE TITLE
Show song durations.

### ISSUE THREAD

**Issue by zappathustra** [vanilla-music/vanilla#360]
It would be convenient if the currently playing playlists showed song durations. And That would be nice to see that too when selecting songs from the library.

**Comment by adrian-bl** [comment]
How would this visually work? I don't see how we can fit this information in the library row

**Comment by zappathustra** [comment]
Flushed right after the title. Judging from my library, there is quite some room, all the more as long titles are spread over two lines.

**Comment by adrian-bl** [comment]
I don't agree: This is a random screenshot from my library and there isn't much room left on many titles:
![](http://i.imgur.com/HYWosWe.png)

**Comment by zappathustra** [comment]
At worst, long titles can be shortened with an ellipsis. And if you're afraid people don't like that, showing time can be set as an option.

Note that I have no idea of the work involved. But I listen mostly to stuff with long and often unpredictable playing times (jazz, prog, jambands), and I often want to know how long this or that song is going to be.

**Comment by adrian-bl** [comment]
> And if you're afraid people don't like that, showing time can be set as an option.

We can not make everything an option - and i really do not see a way how we could get this going on smaller screen sizes.

I'm sorry, but this is not a feature i'm going to implement.
