### ISSUE TITLE
"Interesting" cover art choices

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla#362]
Just updated Vanilla (I hadn't since around December). I decided to open up my media player, and Vanilla's cover art choice was...interesting...

![cover](http://s5.postimg.org/xi2b6cfif/Screenshot_20160525_200534.png)

I searched my entire file system. There are *no* filesike this that even contain the words "cover", "artwork", or "album"...

**Comment by kirbyfan64** [comment]
Also, that cover art file Vanilla picked is called...

...`YR9TYTT.png`. No clue why it's getting picked.

**Comment by xbao** [comment]
Interesting. Is the `YR9TYTT.png` at least in the same folder as the song that's playing? 

Also, props for having a flow chart of open source licenses on your phone :)

**Comment by adrian-bl** [comment]
Newer versions take any picture in the same folder if no cover/front/artwork.jpg file was found.

Maybe we should exclude the Downloads directory for the cover search

**Comment by kirbyfan64** [comment]
@adrian-bl Yeah, Downloads usually has random crud that doesn't exactly qualify as "cover art". :)

Maybe the corresponding setting should be updated? In Settings -> Cover Art, it still only mentions conver/artwork/album.jpg.

**Comment by kirbyfan64** [comment]
Or, preferably, you know, make it an option...

(I say that at the risk of sounding like https://xkcd.com/1172/)

**Comment by adrian-bl** [comment]
I think just blacklisting basedir == downloads-dir should be good enough for the file-cover-loader: No need to make this a config option as searching for images in 'Downloads' is probably always a bad idea.  (the internal + shadow-cover loader will still work)

**Comment by adrian-bl** [comment]
This is fixed in 58527422f0e48ba6b0cb9aa1b2b14b5d3b9219f7 : We are now not loading folder-artwork if the file is stored in the Downloads directory (shadow and in-file covers are still loaded).

Note that you must flush the cache to see the effect: Either wait 2 weeks or go to Settings -> Cover and toggle one of the options (causes a cache drop) + kill the app to get rid of the in-memory LRU cache.
