### ISSUE TITLE
Can't add track to playlist

### ISSUE THREAD

**Issue by p2635** [vanilla-music/vanilla#368]
Vanilla Music v1.0.40 (downloaded from fdroid), Android 6.0.1, Samsung S6, Locale is Japanese

I have a file in this path storage/emulated/0/Voice Recorder/file1.m4a. From the Files dialog, I press an hold file1.m4a, add to a new playlist and when I view that playlist it's empty.

Have I done something wrong?

**Comment by adrian-bl** [comment]
The file is probably not part of the media database: Vanilla Music uses androids internal media database for playlists and can not save files which are not present in this DB.

You could try to first force a rescan of the library by using https://play.google.com/store/apps/details?id=com.gmail.jerickson314.sdscanner

**Comment by p2635** [comment]
Thanks Adrian,

Is there a way to rescan within the app itself? If not, will there be 
support for this in the future? If not, it's ok its just a minor 
annoyance that I can live with for now.

Phil

**Comment by adrian-bl** [comment]
Not yet, but this is planned, see #312
