### ISSUE TITLE
pause music when in "do not disturb"

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#369]
I put my phone in do not disturb at work without a timeout since I set it only when it gets distracting and fiddling with the time is annoying. However, when I then get in the car and Bluetooth connects, vanilla starts playing even though no audio is happening. It'd be nice if vanilla would just not play if it is do not disturb mode.

**Comment by adrian-bl** [comment]
What exactly does cause Vanilla Music to start?
Do you have the headphone detector app installed?

**Comment by mathstuf** [comment]
I have it installed, but this is for Bluetooth. It happens for headphones too though.

**Comment by adrian-bl** [comment]
But i'm still curious why Vanilla Music gets launched: It won't launch itself, so some other app needs to trigger this behaviour - and, IMO, the best solution would be to avoid the launch during the 'do not distrub' phase.

I had a quick look at the SDK doc and i'm not sure if there is a public API to detect this mode: The feature seems to be called 'ZEN_MODE' internally (https://android.googlesource.com/platform/frameworks/base/+/c323b8d%5E!/) but there seems to be no public API for it: https://developer.android.com/reference/android/provider/Settings.Global.html :-/

**Comment by mathstuf** [comment]
Fun. Seems that Android really should know better than to start music players when it will just silence them later. Thanks.

**Comment by mathstuf** [comment]
I wonder if this doesn't come as part of the "expose a stock media player interface" bit to make it appear on homescreens.

**Comment by adrian-bl** [comment]
Hm? What do you mean with 'expose a stock media player interface' ? :-)

**Comment by mathstuf** [comment]
The option is called "Emulate stock broadcasts".

**Comment by adrian-bl** [comment]
Ah, that shouldn't make any difference: This option just causes Vanilla Music to use the package name of the stock player while sending 'notifications' about the currently playing song.
