### ISSUE TITLE
Selecting Album and then pressing back does not clear filters at the bottom

### ISSUE THREAD

**Issue by waqas** [vanilla-music/vanilla#371]
From the Albums tab, click on an Album. It moves to Songs tab (with some filters added at the bottom which are still confusing to me, tbh), then click back button it goes to Albums tab but since an artist filters still remains the list is empty.

**Comment by adrian-bl** [comment]
The back button is supposed to keep the artist filter.
But the list should not be empty, maybe your tags are messed up?
