### ISSUE TITLE
Display new songs in vanilla

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#373]
When we copy new music files, we have to wait a certain time for them to display in vanilla.

What I do against that, is killing "Media Storage" app, which also kills vanilla and display all the newer Songs when we open it again.

So I Think a new option should be added in vanilla to reload the library, you can for example add an option that kills media storage and restart vanilla automatically.

**Comment by adrian-bl** [comment]
Duplicate of #312
