### ISSUE TITLE
Different volume level for FLAC/Ogg/MP3 when using Replay Gain ?

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#380]
Hi there,

It took me a while to notice (especially after #201), but the volume level seems to be different with different files, when using Replay Gain.

Notably, MP3 files sound way quieter than FLAC and Ogg. I must point out that most of my MP3 files are rather low-quality, and with Replay Gain directly applied to the audio stream (I call that "crippling").

HOWEVER, when playing the same files on my computer (using Clementine and VLC, both with track Replay Gain activated), there's NO noticeable difference in volume.

**Comment by breversa** [comment]
I just gave a try with Apollo, and there's no volume difference between files. So I believe there's definitely something fishy with the way Vanilla handles the volume and/or Replay Gain correction.

Vanilla 1.0.4 (from F-Droid)
Replay Gain mode : track
Pre-amp : +3dB
Adjustement for files without Replay Gain : +0dB

**Comment by adrian-bl** [comment]
IMO, Apollo doesn't even handle replay gain tags, so i'd be surprised if a mix between adjusted + tagged files sound OK.

> Is there any way I can help troubleshoot this ?

If you are mixing *tagged* and *adjusted* files, you should not touch the pre-amp value:

Eg: Your flac has a tag of -10dB and an MP3 (with not rg-tag) was adjusted to be -10dB:
Playing these files in your configuration would cause the MP3 to be played at -10dB and the FLAC at -7dB

**Comment by breversa** [comment]
Wait, does that mean that pre-amp is *only* applied to files with non-zero RG tag, while those get the "without RG" adjustement ?

If that's the case, would setting both to the same value make all my files sound as loud ? :-) I'm giving it a try now…

**Comment by adrian-bl** [comment]
Yes, but thats mostly due to the fact that the end result (tagged gain + preamp) must not be > 0 as android does not allow us to raise the value above 100%

**Comment by breversa** [comment]
Wait, does that mean that pre-amp is *only* applied to files with non-zero RG tag, while those get the "without RG" adjustement ?

If that's the case, would setting both to the same value make all my files sound as loud ? :-) I'm giving it a try now…

**Comment by breversa** [comment]
Sorry for necroposting, but what are the Replay Gain tags that Vanilla Music understands for MP3 ?

id3v2 or APE ?
