### ISSUE TITLE
Allow multiple genres in genres tab

### ISSUE THREAD

**Issue by gsantner** [vanilla-music/vanilla#381]
Allow use of multiple genres of music files in the genres tab. The most common two ways to seperate genres are semicolon (`GENRE1;GENRE2;GENRE3`) and double-backslash (`GENRE1\\GENRE2\\GENRE3`).
<img src="https://cloud.githubusercontent.com/assets/6735650/16134909/615ec96c-3420-11e6-9fe0-fc94783da094.jpg" width="33%" height="33%" >
In this example there are multiple songs which are tagged with `Punk;Alternative`. This genre should not be there after the issue is resolved, the song should than be listed in both `Punk` and in `Alternative`.

**Comment by adrian-bl** [comment]
Sorry, but there is nothing we can do about this: Putting songs into a genre is done by androids very own media database which we are using as a source.
