### ISSUE TITLE
Detect Opus files

### ISSUE THREAD

**Issue by Trevonn** [vanilla-music/vanilla#384]
It can already play opus files if they are selected in the file view but they don't appear in the album, song views

**Comment by adrian-bl** [comment]
What container are you using?
Android only supports mkv containers for opus: https://developer.android.com/guide/appendix/media-formats.html

**Comment by Trevonn** [comment]
It was in an Ogg container but the file extension is ".opus" which I see android does not support natively. Other media players such as VLC can detect opus files just fine but they are probably using an in-house media detector rather than the standard android one.

**Comment by adrian-bl** [comment]
Yes, VLC uses ffmpeg / libavcodec and has its own database.
Vanilla Music uses androids native database and media codecs. This has both up and downsides. (Eg: we are at googles mercy, but can use offloading if the device supports it)

I just tested opus support on 5.x and 6.x devices:

z3c Running CM 12.1: Both MKA and OGG files with opus streams get indexed, but there are no tags
N5 Running 6.0: Both MKA and OGG files with opus streams get indexed, but android only reads tags from the OGG container.

So: Opus is mostly unuseable on 5.x while 6.x should work pretty okay with the ogg container format (even if google claims that MKA is supported)
