### ISSUE TITLE
Backup playlists

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#385]
I think it will be great to add a way to backup the playlists in a file, which we can restore from whenever we want.

Its the issue with the new SD rescan option that deleted all my playlist that gave me the idea, which still can be handy if we reinstall the app or the OS.

**Comment by xbao** [comment]
What about using [Slight backup](https://f-droid.org/repository/browse/?fdfilter=playlist&fdid=de.shandschuh.slightbackup) to do this?

**Comment by andiandi13** [comment]
@xbao Thank you, it just makes me realized that vanilla playlists are in fact system playlists so its easy to backup, I'll download it :)

So, I think this "issue" can be closed UNLESS someone want to include this option in vanilla..

**Comment by adrian-bl** [comment]
I really would like to keep vanilla music small - given the fact that the import/export can be handled by external apps, i'd rather not include such a feature.
