### ISSUE TITLE
Please accept my join request to localization project

### ISSUE THREAD

**Issue by cassiodoroVicinetti** [vanilla-music/vanilla#386]
I requested to join the localization team for the Italian language, but my request has not been accepted yet.

I decided to join because translations are inaccurate, and sometimes wrong, in "Italian (Italy)" strings, and moreover there are some untranslated strings.

Examples:
- Shuffle albums -> ~~Album in shuffle~~ Riproduzione casuale album
- Swipe up action -> ~~Azione Swipe su~~ Azione allo scorrimento rapido verso l'alto
- Cover long press action -> ~~Azione copertina pressione prolungata~~ Azione alla pressione prolungata sulla copertina
- Default playlist action -> ~~Azione playlist default~~ Azione predefinita per le playlist
- Send broadcasts emulating those sent by the stock music player to work with 3rd party lockscreen controls, widgets, etc. -> ~~Invia brodcast simulando quelli inviati dal riproduttore musicale nativo con i controlli di 3rd parti, widgets,ecc.~~ Invia broadcast emulando quelli inviati dal lettore musicale preinstallato per funzionare con i controlli del blocco schermo, i widget, ecc. di terze parti.
- Restore default -> ~~Ripristina impostazioni iniziali~~ Ripristina impostazioni predefinite
- Last used action -> ~~Ultime azioni~~ Ultima azione utilizzata
- Filebrowser home -> ~~Home ricerca file~~ Cartella iniziale del navigatore di file

**Comment by adrian-bl** [comment]
Hi @cassiodoroVicinetti 

I accepted your request for Italian (Italy): You should now be able to update the translation of this ressource.


And thanks a lot for your contribution! Please let us know if you'd like to be added to the 'About' page.

**Comment by cassiodoroVicinetti** [comment]
Thank you!
