### ISSUE TITLE
Scrolling shows T's from "The"

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla#387]
Sorry, but I couldn't think of a better issue title...

Basically, Vanilla sorts songs ignoring the word "The" at the beginning. So "The Encounter" is under E.

However, the T's are shown on the scrollbar when scrolling.

So I'll start scrolling down by dragging the scrollbar, and the bubble with the letter E appears next to the scrollbar. Then I reach "The Edge of Green", and the E with change to a T, then back to E when I pass it, then to a T when I reach "The Encounter", and back, etc.

**Comment by adrian-bl** [comment]
Thats indeed an issue: we should have a look at how AOSP handles sorting of The, Der, die, etc...

Also: using an uppercase letter would also be better

**Comment by adrian-bl** [comment]
Fixed via https://github.com/vanilla-music/vanilla/commit/e5723db214437a729e4a0220cd3740d0ae43ef97
