### ISSUE TITLE
Play remainder?

### ISSUE THREAD

**Issue by stiggybaby** [vanilla-music/vanilla#388]
Hi, First thanks, I really like Vanilla Music Player a lot. It's the only player that I found that I like with one exception...

When browsing my library (artists > album > track 4 for example) when I tap any song in that album, then it shows 1 song playing. On all my previous stock music players (LG smartphone, Yamaha airplay app, etc) the player will continue to play all songs after the one that I tap until the album is finished.

Basically if I tap song 2, it will play 2 through 10 of 10, if I tap 9 then it will play 9 through 10 of 10. This is really great if it's a long album or if you don't like the 1st song for example, or if you have shuffle on and you want to start on track 3 (your favorite track for example), etc.

Am I just missing adjusting a setting, or is this a feature that is not present in this player?

So far the only way I found to play tracks 3 through 10 of 10 is to press play all above track 1, then skip forward to track 3.

**Comment by adrian-bl** [comment]
Go to Settings -> Library Screen -> Default Action and change it to 'Play All'

After this, tapping on an item causes Vanilla Music to enqueue all visible items, starting at the item you tapped.

But thinking about it, it might be nice to have this option as a long-press-action too

**Comment by stiggybaby** [comment]
Thanks for a great player, and for taking the time to address my question/request.

I did that, and I would call it a work around with undesirable side effects... Instead of taping on an artist > album and navigating to the song list on that album and selecting starting playing on track 3, I instead get everything enqueued visable as you state. So, yes a long-press-action would be exactly what I would hope for to get both expanded and start on desired track with play through end.

Thanks again.

**Comment by adrian-bl** [comment]
You can still 'expand' a view by clicking on '>' at the right corner.
But i agree that this is cumbersome (that's why 'expand' is the default tap action).

I plan to include the long-press feature in the next release

**Comment by adrian-bl** [comment]
This has been implemented in df895dd5fdfd2c838653a90194db786bce104513 and will be in the next release
