### ISSUE TITLE
don't ignore music files with no tags

### ISSUE THREAD

**Issue by andrewrk** [vanilla-music/vanilla#390]
I imported some music from youtube, so actually they're videos that have a file name like `MitiS - Life Of Sin (Pt. 4).mp4` but there are no ID3 tags etc. Vanilla music player ignores these files and does not queue them when I try to queue all songs. Further when I use the file browser to explicitly queue these songs, in the display it doesn't even show the file name, it just shows blank. If Vanilla Music Player gets closed and reopened, for example when the phone reboots, these items are then deleted from the queue.

Further, if I save a queue as a playlist with these songs, queuing them from the playlist ignores them.

**Comment by adrian-bl** [comment]
Vanilla Music is just not supposed to index *Video* files - it's a music player.

The fact that you can play these files (audio-only) by selecting them in the file browser is just possible because we do not exclude videos of they got opened by path name - but we never index them (and therefore can not add them to playlists as they have no media id)

**Comment by andrewrk** [comment]
Why not? Just because a media file happens to have a video stream doesn't mean it's not music. And it's in the music directory.

**Comment by adrian-bl** [comment]
Because we would then also pick up WhatsApp videos and all other junk.

**Comment by andrewrk** [comment]
Vanilla Music Player already has the concept of a music directory. Why not only search this directory for music?

**Comment by adrian-bl** [comment]
> Vanilla Music Player already has the concept of a music directory

No, it has not: We are using the Android Media library. The user-selectable directory is just the start point for the file browser.

**Comment by andrewrk** [comment]
Still, vanilla knows what directory the user considers the root of their music collection, and it knows the file path of each media item. It's easy enough to see if one is in the other. 

I argue that it's more common for a user to want a music video to be considered part of their music collection than a music file outside of the music directory.
