### ISSUE TITLE
Notification bliking while pausing/playing

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#391]
I'm on Jellybean 4.1 and each time I pause a song (or tap next) the notification disappear and reappear immediately. Its quite annoying :/

In fact this problem disappear on 4.3+ and seems to come from the creation of a new notification each time there is an action in vanilla.

I found something here http://stackoverflow.com/questions/19025056/how-can-i-avoid-blinking-notification-update-while-changing-button

But I dont understand at all. Can someone fix this issue for Android 4.1 or its impossible ?

**Comment by adrian-bl** [comment]
I think we are unlikely to fix this as this issue is *clearly* a bug in Android 4.1 (or at least on your device).

I just tested it on my Phone running 4.2 and the problem does not surface there. Also: Looking at the code, we do everything as documented in the SDK (push a new notification with the same ID).

The 'solution' on stackoverflow would just complicate the code and might not even help

**Comment by andiandi13** [comment]
@adrian-bl Fine, thank you for answering

**Comment by adrian-bl** [comment]
closing as wontfix as this seems to be an OS issue (fixed in newer versions)

**Comment by andiandi13** [comment]
Can you reopen the issue, I have some news

**Comment by andiandi13** [comment]
I have some news on that issue, if you can reopen the issue.

It's nothing but a notification priority problem !

When I have toogles from other apps sticking in the notification panel, the play/pause/next/previous actions will cause Vanilla to blink because another app have an higher priority than Vanilla.

To prove that, I downloaded "App Settings" thought Xposed and make Vanilla priority to MAX (nothing is now above than Vanilla, which stay stick to the top).

The result is clear, no more blikings. Please take a look :

**Without any modification** : [YouTube](https://youtu.be/G-yDpXJHW9Y)

**With App Setting mod (MAX Priority)** : [YouTube](https://youtu.be/QLOvDuQf0b8)


From there, solving the issue wouldn't be too hard, I guess. Maybe we can set a priority directly into the code or a second way would be too add a "service" in Android Accessibility Service too maintain the notification at the top as many apps do (Blackr, Twilight, Universal Copy...).

Thanks.

**Comment by adrian-bl** [comment]
Interesting finding: Android >= 4.1 knows about notifiction priorities - could you give the latest nightly build a try? It changes the priority from default to high:

f88f96d61529efe3bc82dfb442de9c23577d6c37

**Comment by andiandi13** [comment]
Thanks. So I tried it and most of the time it works (I obviously disabled the xposed module - app settings - ).

There is just some rare apps that at above by default (for example Power Toggles) but most of the time we can change the priority inside their app.

But I think it's better to change the priority to 'max' to reduce the probability of priority conflicts with apps that also are in 'high', and so blinks.
What do you think.

**Comment by adrian-bl** [comment]
> But I think it's better to change the priority to 'max' to reduce the probability of priority conflicts with apps 
> that also are in 'high', and so blinks.

But there may still be other apps with MAX: This is a game we can't win, it's like increasing the z-index to 99999 in CSS :-)

I'd prefer to keep it at HIGH for now: MAX would cause a HeadsUp notification on Android 5.x which is absolutely not something we want.

**Comment by andiandi13** [comment]
Alright its rare than an app "win" tough so its ok :)
