### ISSUE TITLE
Directory view jumps back to the top entry (during the ~first hour after installation)

### ISSUE THREAD

**Issue by Wikinaut** [vanilla-music/vanilla#393]
On my Huawei Y201 Android 4.0.3,

the Library directory view  (Bibliotheksansicht) - when sliding to entries belows always (e.g. to a directory starting with "M") - immediately jumps back so that again the top entries ( "A" "B" "C" ... ) are on top of the screen. 

It makes it impossible to select entries further down in the list.

On my other device with Android 5.x it works as expected.

**Comment by Wikinaut** [comment]
(I cleaned the display)

Closed as invalid.

**Comment by Wikinaut** [comment]
After a while it works. So perhaps this quirky reaction of the list screen is only during indexing (or a similar job) running on a new device, or when the Vanilla app is newly installed.

**Comment by adrian-bl** [comment]
Vanilla Music does not do its own indexing, it uses androids media db - so there is nothing special done after the installation as the library is already indexed.

What version of Vanilla do you have installed?

**Comment by adrian-bl** [comment]
closing due to lack of response
