### ISSUE TITLE
[Suggestion] Add a cross-fader between tracks

### ISSUE THREAD

**Issue by Wikinaut** [vanilla-music/vanilla#394]
I'd like to have a cross-fader between the tracks.

**Comment by adrian-bl** [comment]
Sorry, but we already support replay gain and crossfade would collide with it.

**Comment by Wikinaut** [comment]
@adrian-bl Hmmmm, Mp3DirectCut http://mpesch3.de1.cc/mp3dc.html is a Windows programm (I use it with WINE on Linux) for mp3 manipulation (cutting, adding fades etc.), which works in the _compressed_ domain and which *can* *add* *fades* - in the compressed domain (I think this is what is needed for Vanilla, too).

I don't want to be too pushy, but I think, it _would_ be possible to have at least a kind of cross-fading also in the Android context. I will look for possible implementations.

**Comment by adrian-bl** [comment]
Sorry, brainfart from my side: i wanted to write gapless playback.

**Comment by Wikinaut** [comment]
(I just wanted to kindly request the cross-fade-feature again but was reluctant and lazy to ask again. Perhaps someone knows how this can be implemented.)

**Comment by Wikinaut** [comment]
Is there a new thinking about implementing a cross-fader between tracks? Just asking for a friend.

**Comment by adrian-bl** [comment]
No, i do not plan to implement crossfade.

**Comment by xeruf** [comment]
Poweramp also supports crossfade and replaygain, but is unfortunately proprietary. Would love to see this feature here!
