### ISSUE TITLE
[Suggestion] In the settings when playing a title, remove the dangerous option "Delete"

### ISSUE THREAD

**Issue by Wikinaut** [vanilla-music/vanilla#395]
When a title is played, there is "Löschen" (delete)., which apparently **removes** the file from the SD card. (Who actually needs this dangerous action here?)

What I want to suggest:

* Change play-setting "Löschen" to play-setting "remove from current playlist and proceed to next title"
("Entfernen diesen Titel aus der aktuellen Playlist und spiele den nächsten Titel")

**Comment by andiandi13** [comment]
It can be useful to delete songs quickly while we are listening though. I would personnaly suggest a checkbox to confirm the deletion (like in FX File explorer), a password or a second message to confirm..

**Comment by Wikinaut** [comment]
A confirmation question is already present.

But the (German) text "Löschen" (delete) is quite close to "Entfernen" (remove - with the meaning "remove from current list"), but this is not offered in the list.

**Comment by adrian-bl** [comment]
I do not think that we should change this.
I'm a native german speaker and IMO, the translation
```
  <string name="delete_file">Datei „%s“ löschen?</string>
```

is clear.
