### ISSUE TITLE
[Suggestion/Improvement] While playing and when selecting to save as a playlist, show the already existing lists

### ISSUE THREAD

**Issue by Wikinaut** [vanilla-music/vanilla#396]
When I want to save the current list as a playlist, I am prompted to enter a playlist name. Before that, the list of existing playlists should be shown.

**Comment by Wikinaut** [comment]
Existing playlists: let user select between "overwrite" and "append to".

**Comment by adrian-bl** [comment]
The playlist dialog has been reworked in the git head and this is now implemented
