### ISSUE TITLE
[Bug] Playlist/s got empty now and then

### ISSUE THREAD

**Issue by Wikinaut** [vanilla-music/vanilla#398]
I noticed, that my Playlists contents disappeared (empty content) now and then. 

Currently I have no idea what could be the reason, but will report here as soon as I have more details.

**Comment by mindforger** [comment]
@Wikinaut this happened to me now and then until i used an app (that i forgot the name, sorry) to clean all my media databases and refreshed them ... vanilla gets it's media connections from the media provider app of your OS, and if the service is bonked you either need to clear all your media cache by hand or use an app for that

be aware all your playlist may be gone then

**Comment by Wikinaut** [comment]
@mindforger I also noticed today, when "adding items (five songs of an album) to a playlist" ("Einreihen") that these five items of a music album where not added at the end but inserted arbitrarily in the mid of my playlist.

**Comment by adrian-bl** [comment]
Playlists are an 'OS-Feature' of Android itself: If they get empty, this usually indicates an issue with the OS itself (eg: booting in safe mode or failing to find some storage devices during boot, so all files are removed from the index and therefore the playlist becomes empty).

So in the end this is not 'our' bug: It's an issue with android itself or the ROM you are using.
