### ISSUE TITLE
[Suggestion] Deletion of playlist or current list entries on left and right "swipe" (motion) event: make sensitive area bigger

### ISSUE THREAD

**Issue by Wikinaut** [vanilla-music/vanilla#399]
Playlists entries can be moved with a short click and move action in the list, however, a deletion is cumbersome and requires a long click and selection of "delete" entry.

I suggest to also allow list item deletion with the Android swipe-left and swipt-right motion event.

**Comment by adrian-bl** [comment]
Which dialog are you referring to?

The playlist editor already supports swipe-to-remove, but there is no 'Move' menu entry

**Comment by Wikinaut** [comment]
@adrian-bl 

Ahh, now I see! I notice, that the sensitive area - the area where this swipe-to-remove works - is very narrow on the right side, and is apparently _not_ identical to the area of the small-dot handle (icon).

Can you please make the whole item area (the whole area of an item, left-to-right, bottom-to-top) sensitive for i) left or right => delete from list ii) up/down => shift up/downwards in the list.

Again: the underlying problem is not the missing functionality (it is present) but appears to be too-small-area !

**Comment by adrian-bl** [comment]
No: we can not make the whole area sensitive as this would make the normal scrolling skewy.

I think that our current touch-area is big enough (works well for me on a 4.3 and on a 5.5 phone)

**Comment by Wikinaut** [comment]
I disagree. The area is too small, I have a 3,5" and a 4" device with 4.0.3 and 5.0 Android, and the active area is some square millimeters or so. Pls. make it larger, or change the dot-icon to a clean button.
