### ISSUE TITLE
[BUG] Not all music is seen.

### ISSUE THREAD

**Issue by teod0r** [vanilla-music/vanilla#401]
When I select a folder to play, not all tracks get to the queue!

I have two directories whith music. The are the identical. They contain 134 tracks each. They contain several new songs. Those new songs isn't in the queue list if I select /storage/sdcard1/Music/. When I select /storage/sdcard0/Music/ there are fore of the new songs (latest) and no more songs at all. When I tap the folders Music instead playing them, there are all tracks listed.

I have the problem with new tracks not visible with all players that I have tryed.

**Comment by adrian-bl** [comment]
Some files are probably not indexed.

In Vanilla Music, go to Settings -> Miscellaneous Features -> SD Scanner and hit the rescan button to trigger an index update
