### ISSUE TITLE
Build error: /vanilla/src/ch/blinkenlights/android/vanilla/PlaylistDialog.java

### ISSUE THREAD

**Issue by Wikinaut** [vanilla-music/vanilla#405]
@adrian-bl 

version 3163505c78dc60db8ac61f87fd4233c121b8a165

When building from the source, I receive 1 error:

```
/vanilla/src/ch/blinkenlights/android/vanilla/PlaylistDialog.java
Error:(35)
Error: This fragment should provide a default constructor(a public constructor with no arguments)
(ch.blinkenlights.android.vanilla.PlaylistDialog) [ValidFragment]
```

**Comment by adrian-bl** [comment]
This works for me.

How did you setup your environment?

You must run

 * android update project --path .
 * ant debug

to build the application.

**Comment by Wikinaut** [comment]
I set up via "Android Studio > Import"

**Comment by adrian-bl** [comment]
Then please check the SDK version, fix the error or disable lint ;-)

**Comment by Wikinaut** [comment]
My Android Studio has been updated to the latest versions of the SDK and the other dependencies.

Only the addition of a default constructor is apparently needed in your code to avoid it:
Error: This fragment should provide a default constructor(a public constructor with no arguments)

**Comment by adrian-bl** [comment]
Ok, then please submit a PR and we will merge the fix for this.

**Comment by adrian-bl** [comment]
Closing due to lack of reply
