### ISSUE TITLE
Startup crashes 

### ISSUE THREAD

**Issue by surfuture** [vanilla-music/vanilla#406]
07-22 00:27:44.414 W/VanillaMusic(14355): Failed to load state
07-22 00:27:44.414 W/VanillaMusic(14355): java.io.FileNotFoundException: /data/data/ch.blinkenlights.android.vanilla/files/state: open failed: ENOENT (No such file or directory)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at libcore.io.IoBridge.open(IoBridge.java:456)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at android.app.ContextImpl.openFileInput(ContextImpl.java:955)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:175)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at ch.blinkenlights.android.vanilla.PlaybackService.loadState(PlaybackService.java:1928)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at ch.blinkenlights.android.vanilla.PlaybackService.onCreate(PlaybackService.java:436)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2753)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at android.app.ActivityThread.access$1900(ActivityThread.java:144)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1383)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at android.os.Looper.loop(Looper.java:135)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at android.app.ActivityThread.main(ActivityThread.java:5243)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at java.lang.reflect.Method.invoke(Native Method)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at java.lang.reflect.Method.invoke(Method.java:372)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
07-22 00:27:44.414 W/VanillaMusic(14355): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at libcore.io.Posix.open(Native Method)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
07-22 00:27:44.414 W/VanillaMusic(14355): 	at libcore.io.IoBridge.open(IoBridge.java:442)
07-22 00:27:44.414 W/VanillaMusic(14355): 	... 16 more

**Comment by adrian-bl** [comment]
That's not a crash. Thats just an exception as the state file was unreadable (which is normal on the first start)
