### ISSUE TITLE
Add ability to edit ID3/VorbisComment/FlacTags fields of file

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#407]
Basically what's needed
- A dedicated dialog or fragment with edit fields for standard tags
- Support for viewing lyrics from ID3/Vorbis/Flac tags (resembles #348) in NowPlaying actions (e.g. add to action list on long press)
- Rescan the file after edit (and probably refresh NowPlaying page) to reflect changes in MediaStore

@adrian-bl , @aminb , what do you think?

P.S. Pls add enhancement label.

**Comment by aminb** [comment]
I remember desperately needing this, so I wrote my own ID3 tag editor, but didn't do nearly a good enough job to even consider opening a PR for inclusion in Vanilla :grin:

But if we don't end up pulling any/many dependencies and if the interface is neat and not hacky, it's a :+1: from me.

@adrian-bl ?

**Comment by adrian-bl** [comment]
I really do not think that we should include this in Vanilla Music itself: A 800kb library is actually pretty big if you consider that the whole application is about 1MB in size (and most of it is hi-res drawables).

I *really* think that this would be yet another ideal candidate for a plugin:

> A dedicated dialog or fragment with edit fields for standard tags

We could extend Vanilla Music to check if the 'tag editor plugin' is installed and include an 'Edit Tag' option in the context menu if the application was found.
Selecting the 'edi tagt' option would then launch the app and pass the filename (or library id?) to it.

> Rescan the file after edit (and probably refresh NowPlaying page) to reflect changes in MediaStore

The library view automatically picks up changes in the media store - The 'Now Playing' screen does not - but fixing this would be a nice idea anyway (We just needed yet another listener or a callback from the LibraryAdapter)


So what about this plan:
* An external Tag-Editor will be developed (which doesn't even need to be visible in the app drawer, so it won't clutter the phone)
* We extend Vanilla to scan for the package name (or a (newly invented?) tag-editor intent category consumer) and have it include an 'Edit Tags' option if found)
* We also add a 'Plugins' section to the Settings screen where we can list all known 3th party plugins (such as the tag editor and the headphone detector)


Having this as an external application also gives you much more flexibility as you can do what you want without having to wait for us to accept a pull request :-)

**Comment by mindforger** [comment]
`We extend Vanilla to scan for the package name (or a (newly invented?) tag-editor intent category consumer) and have it include an 'Edit Tags' option if found)` Wouldn't it be more clean when you extend the Plugin API with some sort of event and listener-prototype to be registered and called when opening the context menu

**Comment by aminb** [comment]
Ha, implementing this as a plugin is also a nice idea. We could host the plugin repos under the Vanilla Music org (e.g. `vanilla-music/tag-editor`) if the author likes to do that, and they'd have full access rights on the repo.

> We also add a 'Plugins' section to the Settings screen where we can list all known 3th party plugins (such as the tag editor and the headphone detector)

👍, à la 'Apps' section of OpenKeychain where they endorse the plugins user can install / has installed.

**Comment by Adonai** [comment]
Hm-m, you're proposing to do it via plugin system too.
So I first have to implement plugin system for it, no?
Then I should make a separate application which would receive the plugin system intent.
Then implement a return intent from the plugin that would refresh adapters and views.
Then I should publish it to submission queue on F-Droid and wait for inclusion.

I'm sorry, why would I want that? There are plenty of ID3 editors around, we can now send songs to them via "Share" button and just refresh in `onResume`.

**Comment by adrian-bl** [comment]
> So I first have to implement plugin system for it, no?

For this feature: not really: This can all be solved via intents. The callbacks for mediadatabase updates are already in place

> Then implement a return intent from the plugin that would refresh adapters and views.

No: You update the media database and vanilla will be notified about it by Android itself (just like an MTP update)

> I'm sorry, why would I want that? There are plenty of ID3 editors around, we can now send songs 
> to them via "Share" button and just refresh in onResume.

Yes, thanks to androids intents system. (and no: there is no need to refresh if the editor triggers an media database rescan/refresh).

**Comment by Adonai** [comment]
I know about android updates for content resolvers, I meant primarily NowPlaying page as it can't repaint itself in STYLE_OVERLAPPING_BOX.

So, this issue can be closed then? I'm surprised actually, I thought there was quite a hype about this feature in reddit / telegram.

**Comment by adrian-bl** [comment]
> I meant primarily NowPlaying page as it can't repaint itself in STYLE_OVERLAPPING_BOX.

As of now, the FullPlaybackActivity won't consume media database updates, but there is no technical reason to not implement this - it simply hasn't been done yet: Re-Drawing the picture if the current song changed wouldn't be that hard.

**Comment by dandv** [comment]
I would loved ID3v2 tag editing. It's unclear to me why that would take 800KB of code, but even then, 2MB by today's standards is tiny. (Note that I'm much against bloat, and started my coding career in assembly, participating in code golfing for size.)

**Comment by adrian-bl** [comment]
> ... 2MB by today's standards is tiny.

My point is that i do not see a reason to *double* the _code size_ of the application for a feature that could be handled very well by an external application. Each new feature + external library we add increases the 'maintenance cost' of the app. (And keep in mind that i'm doing this in my spare time.)

And as i tried to explain multiple times: There is just no technical reason to include the editor itself in the app as we can use the intents system of android to do this. (heck! that's exactly what it was built for!)

**Comment by Adonai** [comment]
I don't think library usage increases maintenance costs... E.g. in my app "Man Man" I use, like, 6 or 8 libraries and I never had to fight with their API or sudden upgrades, not even once.

As for size, I use proguard afterwards to strip all the unneeded symbols and classes from libs. Resulting API file is just 1.5 mb, which is fairly small.

Intent system is great for sharing and IPC, but as plugin system it's rather poor. Besides, I'm yet to see good FLOSS id3 tag editor.

I guess I'll implement this feature anyway and leave it in my private fork as with lyrics support

**Comment by adrian-bl** [comment]
> Intent system is great for sharing and IPC, but as plugin system it's rather poor. 

I disagree: it would be a great fit for this case and wouldn't complicate things:

Flow if it was part of vanilla:
* LibraryActivity starts EditorActivity and passes a Song object to it
* User edits, hit save
* EditorActivity triggers indexer and calls finish()
* The MediaAdapter gets notified and rebuilds the library views.

Flow if it was an *external* application:
* LibraryActivity checks if an editor plugin is installed
* Calls the intent of the activity, passing the path (or library id to it)
* User sees editor, edits and hits save
* Editor triggers indexer and calls finish()
* The MediaAdapter gets notified and rebuilds the libary views.

So there is simply not much difference and having it as an external application means, that it could also be started by other apps (such as a file manager).

> I guess I'll implement this feature anyway and leave it in my private fork as with lyrics support

Ok, then i guess we can close this issue.

**Comment by aminb** [comment]
@Adonai Okay so I was under the impression that there's an easy way to display a dialog (not opening a separate activity) on the Now playing screen, implemented _cleanly_ via a plugin system. I don't think that's easily possible (or possible at all), but I may be wrong.

I personally would love to have a tag editor inside Vanilla, and I would be all for it to be implemented internally if the intents would be a drag, or if having it as a plugin would mean having to work around unnecessary obstacles and also end up being more limited. However, if @adrian-bl thinks accepting it would pollute the codebase, then there's not much left to be said.

I'm starting to think maybe having a plugin system for a *light weight* music player would be an overkill (granted, not in all cases though) at least with Android's current limitations; and it'd be a good idea to add a feature directly to the codebase if the feature is not obtuse and there's been several requests for it already, and if it can be implemented with a clean interface. But that's just my humble opinion.

@Adonai if you do end up implementing a tag editor in your own fork, I would definitely cherry-pick it and would love to use it.

**Comment by adrian-bl** [comment]
> I don't think that's easily possible (or possible at all), but I may be wrong.

Implementing an activity as a dialog is a no-brainer: http://stackoverflow.com/questions/1979369/android-activity-as-a-dialog

> ... at least with Android's current limitations

What kind of limitations? :-) Android is actually pretty great in this respect: You can even do funny things like RemoteViews (https://developer.android.com/reference/android/widget/RemoteViews.html) where the process owns a view which is updated by a different process.

**Comment by dandv** [comment]
> And as i tried to explain multiple times: There is just no technical reason to include the editor itself in the app as we can use the intents system of android to do this.

If that approach works seamlessly enough, I'm all for it.

**Comment by aminb** [comment]
@adrian-bl Oh cool, glad to see I was wrong!

@Adonai How do you feel about this?

**Comment by Adonai** [comment]
I'll give plugin version a shot, let's see how far can I get. Not instantly, anyway, as I work mostly in my spare time like all of us.

**Comment by Adonai** [comment]
Ready.

1. PR #442 
2. [VM Tag Editor plugin](https://github.com/Adonai/vanilla-music-tag-editor)

Ready to transfer ownership to vanilla-music.

**Comment by aminb** [comment]
@Adonai I just built and tried your PR on my device. Great stuff!

Some minor details/thoughts:

- Can we clean up the song context menu dialog and put the plugin entries (such as Tag Editor) in the main context menu, or do we stick to the current approach of putting them all under "Plugins".
- Is there a way to avoid using the _VM_ abbreviation in the name? Took me a few seconds to figure out :stuck_out_tongue: How does "Vanilla Tag Editor" sound?
- It'd be nice to have a "Plugins" section in the "Settings" activity, similar to the "Apps" page of OpenKeychain. Not urgent though, just a nice to have.

P.S. I can accept the transfer whenever you like. I can't reacall, do I need to do something on the Vanilla org first, or can you just go ahead and send a transfer request?

**Comment by Adonai** [comment]
@aminb , I'll see what I can do tomorrow. 
> It'd be nice to have a "Plugins" section in the "Settings" activity, similar to the "Apps" page of OpenKeychain. Not urgent though, just a nice to have.

Sounds good, I'll make it with further commits.

> Is there a way to avoid using the VM abbreviation in the name? Took me a few seconds to figure out :stuck_out_tongue: How does "Vanilla Tag Editor" sound?

Tee-hee, I'll stick with Vanilla Tag Editor then. Yeah, VM sounds more like "Virtual Machine": for me.

> Can we clean up the song context menu dialog and put the plugin entries (such as Tag Editor) in the main context menu, or do we stick to the current approach of putting them all under "Plugins".

We can put plugin entries in menu but there's a certain roundtrip time between player plugin query and collecting plugin answers, so it will take more time to appear... But context menus need cleanup, that's a fact.

>  I can accept the transfer whenever you like. I can't reacall, do I need to do something on the Vanilla org first, or can you just go ahead and send a transfer request?

I tried just now and failed, it says "Transfer this repository to another user or to an organization where you have admin rights.", seems I should be in vanilla-music to handle transfer correctly, so can you put me in?

**Comment by aminb** [comment]
> @aminb , I'll see what I can do tomorrow.

@Adonai Sounds good, thanks!

> Tee-hee, I'll stick with Vanilla Tag Editor then. Yeah, VM sounds more like "Virtual Machine": for me.

Yeah that was exactly my thought about VM haha.

> We can put plugin entries in menu but there's a certain roundtrip time between player plugin query and collecting plugin answers, so it will take more time to appear... But context menus need cleanup, that's a fact.

Ah I see. So in that case let's leave it in the sub-dialog then for now. And yup, we should probably open an issue and discuss cleaning up the interface.

> I tried just now and failed, it says "Transfer this repository to another user or to an organization where you have admin rights.", seems I should be in vanilla-music to handle transfer correctly, so can you put me in?

I see! I just sent you an invitation. Let me know if it doesn't work, and I'll adjust your access level for the transfer. Or alternatively, you could transfer it to me and I'd move it to the org afterwards. Whichever you prefer.

Thanks!

**Comment by Adonai** [comment]
Done, I'm in, still it insults me with

![No permissions!](http://i.imgur.com/Vc8itWM.png)

when I try to transfer it

**Comment by aminb** [comment]
@Adonai I elevated your permissions to admin temporarily. You should be able to do the transfer now!

**Comment by Adonai** [comment]
Transferred, check permissions please
Thanks for swiftness btw :)

**Comment by aminb** [comment]
@Adonai Awesome, thanks a lot!

> Thanks for swiftness btw :)

No problems, and thank _you_ for making your code part of Vanilla! I'll be adjusting your permission to member mode in a bit, but will make sure you have full rights to your repo.

Cheers :beers:

**Comment by adrian-bl** [comment]
@Adonai @aminb : I removed Adonai from the 'contributors' team but added him as an outside-colaberator to the tag-editor repo:

This allows for more fine-grained privileges: He is now a full admin on this own repo but doesn't have admin rights on other repositories.

Also: Would someone be so kind to upload some pre-compiled binaries of this? I'd like to give it a shot but currently do not have the ability to compile code (i'm on holiday and my laptop is 64bit-only - no 32bit cruft = no android sdk)

**Comment by Adonai** [comment]
@adrian-bl 

Sad to hear, I wanted to remain in vanilla-music.

**Comment by aminb** [comment]
@adrian-bl We didn't have to remove him from the org. If the 'write' access to this repo was too much, we could have removed him from the 'Contributors' team but leave him in the org. That way, he'd have _read_ access to all repos but still be part of the org. Also, I'd given him admin rights on his repo before.

To strike a nice middle ground, I've re-invited @Adonai to the org and when he joins, I'll assign him admin rights on his own repo (the tag editor). By not adding him to any teams, he'll only have read access to the rest of repos (just like any other user) however he'll still be a part of the Vanilla org.

@Adonai Please accept the invitation and I'll make sure you still have admin rights to your repo.

**Comment by aminb** [comment]
@adrian-bl Here's a zip file containing
- Vanilla with @Adonai's patch for plugins
- The tag editor apk

[vanilla-tag-editor.zip](https://github.com/vanilla-music/vanilla/files/491731/vanilla-tag-editor.zip)

**Comment by Adonai** [comment]
@aminb , I'm in, thanks. Looks like I have all required rights. Glad to be here.
I'm planning to transfer Lyrics Search plugin soon, so will need some help from you for that.

Also, would like to publish all these plugins in F-Droid and Google Play after PR is merged.
Should I do it with my own tags or credentials or is there some procedure for Vanilla?

**Comment by aminb** [comment]
@Adonai Cool, welcome back! I just double checked and you're rights are as they should be, like you said :)

As for transfering your other plugin, sure. I can either do what I did last time (temporary admin access) or you could transfer the repo to me and then I'd transfer it to Vanilla right away.

And for publishing plugins on the F-Droid and Play, I don't think we have a procedure for it in Vanilla, or not one that I'm aware of. I think you'd publish it with your own credentials. Can you comment on this @adrian-bl ?

**Comment by adrian-bl** [comment]
@aminb ok, that's fine with me - i didn't think much about the organization membership as all our repos are public anyway ;-)
Also thanks a lot for the pre-compiled zips: i tested it and it seems to work fine so far.

@Adonai F-Droid does their own builds, so you could just ask them in the forum (they have a special section for this) to include the application. For the play store: Just create your own account and submit it by yourself (we could then add a link to your plugin n the description). However: I'd recommend to wait until the version with plugin-support has been published to the play store for some days to avoid confusion.

That said: I still see some issues with the current pull request:

* IMO, the whole thing is now too tightly bound to work on a single song. Wouldn't it make sense for plugins to declare what kind of 'objects' (song, album, artist, filepath) they support? This way we could also have plugins working on files or whole artists

* The current code 'awakes' plugins if no plugins were found: But what happens if there is a 2nd plugin installed after the 1st plugin has been found? Wouldn't the code fail to 'wake' it up?

* I think it would also be nice if plugins could pass a short description back to vanila music during the discovery phase: With this information we could even have a small 'plugins overview' section in the settings

* Oh: And we need some sort of plugin spec/example. But this can wait until the plugin-api has been frozen

**Comment by aminb** [comment]
No problems Adrian! :wink:

**Comment by Adonai** [comment]
@adrian-bl 

> IMO, the whole thing is now too tightly bound to work on a single song. Wouldn't it make sense for plugins to declare what kind of 'objects' (song, album, artist, filepath) they support? This way we could also have plugins working on files or whole artists

Yes, but these plugins can just re-use extras that we pass with song. It contains artist, title, album and so on.

> The current code 'awakes' plugins if no plugins were found: But what happens if there is a 2nd plugin installed after the 1st plugin has been found? Wouldn't the code fail to 'wake' it up?

No, packages in Android are unique per-app.

> I think it would also be nice if plugins could pass a short description back to vanila music during the discovery phase: With this information we could even have a small 'plugins overview' section in the settings

They are already passing it via EXTRA_PLUGIN_DESC, but it's just unused for now.

> Oh: And we need some sort of plugin spec/example. But this can wait until the plugin-api has been frozen

No problem with that. But like I said, plugin subsystem will bring *lots* of potential work-hours into vanilla-music. It's now not just one app with all memory and services and methods available at hand, it's IPC and that is hard.

I'll be finishing Lyrics plugin soon enough that will interact with tag editor and this shall give some insight on spec and examples.

**Comment by adrian-bl** [comment]
> Yes, but these plugins can just re-use extras that we pass with song. It contains artist, title, album 
> and so on.

Actually i don't see a reason to pass these as strings: Would't it make more sense to pass a type and an ID to the plugin?

Eg: If i long-click on an artist and select a plugin, the plugin would get type=artist id=artist_id (which is information we already have present in the intent)


> It's now not just one app with all memory and services and methods available at hand, it's IPC and 
> it's hard.

I would imagine that the lyrics plugin could make good use of the RemoteView class of Android.

..or we could also give DexClassLoader a try: This would free us from the IPC

**Comment by Adonai** [comment]
> Actually i don't see a reason to pass these as strings: Would't it make more sense to pass a type and an ID to the plugin?

> Eg: If i long-click on an artist and select a plugin, the plugin would get type=artist id=artist_id (which is information we already have present in the intent)

Sounds reasonable but this would lead to duplication of the code inside plugins. Each of them will need to call content resolver on the given id to get required info that we already have at hand in Vanilla. Also, IDs can change as a result of Tag Editor plugin work as it schedules rescan of the media file. I mean, it puts additional code into plugins, is this really a requirement?

What kind of plugins would operate on artist-only or album-only level? I can imagine only "Show-me-wiki-page-for-a-band"-like plugin.

> I would imagine that the lyrics plugin could make good use of the RemoteView class of Android.

How would you use it? (I'm asking because already implemented it without RV)

> ..or we could also give DexClassLoader a try: This would free us from the IPC

I'll have a look at it today.

**Comment by adrian-bl** [comment]
> Sounds reasonable but this would lead to duplication of the code inside plugins. Each of them will 
> need to call content resolver on the given id to get required info that we already have at hand in Vanilla.

Well, but media database lookups are a core feature of android and it takes about 4 LOC to do so.
Also note that right now we are not exposing all information anyway: Eg: No genre or artwork information is passed to the plugin.
Given the fact that Android has a builtin Media database, there is little reason to not use it when possible.

> Also, IDs can change as a result of Tag Editor plugin work as it schedules rescan of the media file.

Sure, everything could change: A plugin could even delete a file.
But Android guarantees you that the ID will stay unique as long as the file is not replaced (and even then: the plugin could have read the path and just re-query the new ID).

> What kind of plugins would operate on artist-only or album-only level? I can imagine only
> "Show-me-wiki-page-for-a-band"-like plugin.

Batch editing (eg: change genre of whole album), a cover downloader.

> How would you use it? (I'm asking because already implemented it without RV)

A remote view is a widget which gets populated by a resource owned by a different package (https://developer.android.com/reference/android/widget/RemoteViews.html)

So you create a RemoteView in Vanilla and 'attach' the resource-id of a different package to it.
NB: Widgets and Notifications are also remote views.

**Comment by Adonai** [comment]
I tried to do this today. I ended up building all the same structures for Song (because how would I get the artist + title from cursor that I want to close), media constants (because how would I transfer integer type), duplicating huge bulks of queries that made by Vanilla's MediaUtils (because how would I get the songs given only foreign id). This is not a good path, in my opinion.
So fixing plugin call timeout and I think I'm done with that PR. We can extract common jar file out of vanilla and plugins later, if we want.

Current system is clunky a bit, but I'm no architect, sorry. It works fairly well and can send all types of information needed for plugins.

Batch editing - well, don't think this is possible at this level of operation. Suppose we can call plugin system for an album, for a genre. What should tag editor show for it? Should it open all these files to see what's inside them, compare and show only fields that are same across all the files? That's a huge I/O we're talking about. And subject for another enhancement, out of this topic.

> A remote view is a widget which gets populated by a resource owned by a different package 

When I implemented my widgets for Vanilla I found out that it doesn't support EditTexts and whole bunch of other staff. Still suspicious with it but maybe something changed.

**Comment by adrian-bl** [comment]
> I tried to do this today. I ended up building all the same structures for Song (because how would I get 
> the artist + title from cursor that I want to close),

Sorry, but i don't understand the issue here: All you would have to do is to give the content resolver a query and the fields you would like to get. (= Projection)


> media constants (because how would I transfer  integer type)

You don't: The media types are private to vanilla music. You would use Androids MediaStore constants.

> It works fairly well and can send all types of information needed for plugins.

It may work for this specific use case but a plugin system should be flexible.
While i appreciate the work you have done, i won't merge the pull request like this as i think that having a set 'hand picked' values passed to plugins is not a good idea: What we really should do is pass type + id or just the content:// - style URL to the plugins (MediaStore.Audio.*.EXTERNAL_CONTENT_URI)

**Comment by Adonai** [comment]
Sorry, have no time for this for now, next window in November/December.
Don't see a way to implement it with 4 LOC anyways, you can help with that since you grasp the idea.

**Comment by Adonai** [comment]
@adrian-bl , pls take a look at the latest comments. I looked through the code carefully to understand what was the issue that prevented us to merge #442 earlier. It was the content resolver calls, and you suggested to take them instead of path strings. Earlier this day I asked if it would be appropriate to use ContentResolvers in plugins and it seems it's now `file:///` URIs that are in favor.
So what about I simply redo the PR and plugins with `file///` URI instead of path strings? Will this be appropriate?

**Comment by adrian-bl** [comment]
@Adonai i'll try to have a look at it this weekend

(Currently pretty busy as i just started on my new job)

**Comment by Adonai** [comment]
@adrian-bl , did you have a chance to look at it?
Is it ok to just pass music files by `file:///` reference to plugins and back? Or do we have some specific content resolver URI to query our new media db?

I'm asking because last time you rejected that PR #442 because of that.

**Comment by adrian-bl** [comment]
> @adrian-bl , did you have a chance to look at it?

I'm still quite short on time (and invested most of it into the media-library feature) but i had a quick look at the PR again:

* Passing ```file:///``` around is fine with me and now seems to be a more 'natural' choice than proxying everything trough artificial media id's
* Maybe we discussed this before, but i don't understand why the 'plugin collection' happens in the PlaybackService - couldn't this also be done in the LibraryActivity? That would IMO be cleaner as we wouldn't have a ```LibraryActivity -> PlaybackService -> LibraryActivity``` flow
* Which leads to the question: Do you think it would make sense to have this in SlidingPlaybackActivity? (Well: not important as we could do this at any later point)

**Comment by Adonai** [comment]
@adrian-bl , I'll try to address it. Thanks, now I'm finally able to rejuvenate #442

**Comment by Adonai** [comment]
Think this issue is now (and finally) resolved in a way all sides agreed on. Glad to see collaboration in team!
