### ISSUE TITLE
Fast-forward in playback screen

### ISSUE THREAD

**Issue by arromdee** [vanilla-music/vanilla#408]
A request to fast-forward by holding down the buttons that currently skip to the next/previous track.

Mentioned in https://github.com/vanilla-music/vanilla/issues/141 but that has a lot more stuff.  I am requesting only fast-forward in the playback screen.  That issue suggests that it's unnecessary because there is a progress bar in the track, but I think that this behavior would be an expected part of the user interface (I certainly expected it based on past experience) even if it is also possible to do it by touching the progress bar.  Furthermore, using fast forward is much more useful than touching the progress bar if the "song" is actually a long podcast or audiobook, since it is hard to get a lot of accuracy from touching the progress bar when the progress bar represents an hour or more.

**Comment by adrian-bl** [comment]
This would collide with the normal long-press=tooltip action, which probably wouldn't be a big loss.

@aminb what do you think?

**Comment by mindforger** [comment]
well .. i just tested the log press and accidentially disabled the notification .. now vanilla is gone from my lock ascreen and i have no clue how to get it back ... additionally i support this potential irritating feature :D

**Comment by aminb** [comment]
@adrian-bl I'm on the same page. Besides, we already have long-press actions for the repeat and shuffle buttons, so I don't think it'd be off-putting to have a long-press action for fast-forward and backward as well. Also, I think a lot of people actually expect this behaviour by default.

@mindforger Glad to see you figured it out 😃

**Comment by adrian-bl** [comment]
I'm not so sure anymore if this is such a great feature: There will be no way to implement this in widgets and in the Notification which would introduce a very inconsistent UI.

Doesnt' the cover long+press/Swipe '10s forward' feature already suffice?

**Comment by mindforger** [comment]
but i still say that the original feature is irritating and should be removed or replaced
or the issue with the notification beeing registerd with name "null" and default audio player symbol should be resolved in some way

**Comment by adrian-bl** [comment]
@mindforger i'm sorry, but i don't really understand your comment.

Is it related to the notification? Where does it show 'null' and use the 'default audio player symbol' ?

**Comment by mindforger** [comment]
>phew it managed to get into my notification filter somehow ignoring ALL other settings and it displayed as "null" with the default theme audio symbol, not even with the vanilla poayer symbol!

when I tested the log press feature, my vanilla player vanisched from my lockscreen and looking under the  notification filter just revealed a lot of apps i already blocked +  entries with name "null" and the default media player icon, but no vainlla player! When i removed those entrys from my blocklist, my vanilla player worked again normally. 

i suppose there is something wrong with the way the vanilla player is registered when it is notification blocked

**Comment by adrian-bl** [comment]
There is no 'long press feature' in Vanilla Music: The long press on notifications is handled by the Operating System. If it displayed Vanilla as 'null', then thats clearly a bug in the ROM you are using.

**Comment by mindforger** [comment]
oh okay, i must admit i did not test it on my new phone yet and the CM13 ROM on my MIUI was pretty bogus

**Comment by adrian-bl** [comment]
closing this as wontfix as we will never be able to make this working on notifications and widgets.

**Comment by n-o-o-b** [comment]
@adrian-bl Surely it's better to have the feature in some form that not to have it at all? While having it on notifications and widgets would be cool, it isn't that hard to open the app to do it and it would be a very useful feature to have.
