### ISSUE TITLE
Identical album name in different folders treated as two albums

### ISSUE THREAD

**Issue by arromdee** [vanilla-music/vanilla#409]
I ahd two folders containing tracks from the same album.  I did this so that I could have a different cover.jpg used for some tracks.  The album name in the MP3 tag is identical.

Vanilla Music Player shows this as two albums with the same name, one corresponding to each directory.

**Comment by adrian-bl** [comment]
This is the expected behavior: We (well: androids media scanner) treats albums with the same artist/album tags in different folders as seperated albums.
