### ISSUE TITLE
 Impossible to set different cover image for different track in same album

### ISSUE THREAD

**Issue by arromdee** [vanilla-music/vanilla#410]
This is generally reported as a problem with Google's media scanner; for instance, [this](https://code.google.com/p/android/issues/detail?id=40551) is probably the most recent version, but [it has been around for years](https://code.google.com/p/android/issues/detail?id=35082).

However, [an official Google project member](https://code.google.com/p/android/issues/detail?id=40551#c13) says that it is in fact possible for the music player to read the individual image embedded in the individual MP3 file, and that most music players just don't do it.  I don't know enough about development to be able to say whether that is true, but if it is true, I request that Vanilla do it.

A workaround might be to use different directories, which does successfully show different images, but because https://github.com/vanilla-music/vanilla/issues/409 has been closed, this workaround is not possible.

**Comment by adrian-bl** [comment]
While this would be technically possible, i'm not 100% sure if this would be such a great feature:

# The artwork provided by the media database is low-res and looks pretty ugly on xhdpi devices (that's why we have our own cover-loader)
# ...so we also would have to extend the cover-loader to look for $filename.jpg
# using per-song covers trashes both the on-disk and in-memory cache: If we assume that a normal album has about 20 songs, our ability to cache covers simply decreases by a factor of 20 :-/

**Comment by arromdee** [comment]
I don't know exactly how this player caches them, but I imagine something like caching them on demand.  Whenever you play a song (and possibly whenever displaying the contents of an album, since you need the cover art for icons), load that song's cover art and put it in the cache.  Keep track of the past 100 or so requests. 

I can't imagine this would require a very large cache.

(Please ignore if you're already doing this.)

**Comment by adrian-bl** [comment]
Imagine the cache as a number of 'slots'.
Lets say we have 80 slots: if each album has one shared cover, we can cache art for 80 albums.

If we do per-song-caching, our cache can cache about 80 *songs*, so we will have to do a lot of resizing again and again as artwork will most likely drop out of the cache

**Comment by arromdee** [comment]
If a song is 3 minutes, then 80 songs is 4 hours worth.  I understand that use cases are different, but that's probably plenty for a lot of people.

Also, if it really uses a lot of resources, you could add a setting "Use per-song album art? (Warning: may be slow on some systems)".   I suspect that it would be fine for a lot of people; phones are getting better all the time.

**Comment by adrian-bl** [comment]
Is there actually a single player doing this on android?

I just gave this a try and android itself already seems to group-art-by-id, so there is just no way to get the artwork of a single song (unless we build or own artwork extractor which is non-trivial to do)

I also noticed that even VLC on Linux does this: It will only read the album art of the first file in an album and then use it for every other song.

**Comment by adrian-bl** [comment]
closing this as WAI
