### ISSUE TITLE
m4a issue

### ISSUE THREAD

**Issue by ziekke** [vanilla-music/vanilla#412]
Vanilla detects my m4a files but when I hit play it doesn't move. I can seek through the song using seek bar but it just stays where I leave it. 

Does this app have m4a support or am I experiencing a bug?

**Comment by adrian-bl** [comment]
That's most likely an issue with your firmware: We are using androids native media player to play files. So if your OS can't play it, we can't either.

You can mail me the file to adrian@blinkenlights.ch and i'll have a look at it, but there is probably not much i can do in the end.

**Comment by adrian-bl** [comment]
closing due to lack of reply
