### ISSUE TITLE
Set library action separately for individual song

### ISSUE THREAD

**Issue by arromdee** [vanilla-music/vanilla#413]
Settings/Library screen/Default action has an "Expand".   However, if you choose "Expand" and select a song, it will play the song.

There is no way to say "Expand, but play all if on a song" or "Expand, but enqueue if on a song". 

I want the behavior of touching a song and playing from that song until the end of the album.  "Play all" would do this, but I am forced to give up "Expand".

I think there should be a way to do this.  I'm not sure what the best user interface is, but perhaps something like "Default library action (artist/album)" and "Default library action (song)".

**Comment by adrian-bl** [comment]
You can just do a long-press on the row and select a different action.
