### ISSUE TITLE
Fails to read OPUS files tags

### ISSUE THREAD

**Issue by IgnacioFDM** [vanilla-music/vanilla#414]
When playing an opus file, it fails to read title, artist, etc data.

I encoded the opus file with ffmpeg and ```-i INPUT.mp3 -y -b:a 150k -acodec libopus OUTPUT.opus```. Other players do read the tags of said file correctly, and vanilla reads correctly for ogg, mp3, flac but not opus.

**Comment by adrian-bl** [comment]
We are using androids media database which has incomplete opus support.

So this is an issue with Android itself and we cant do much about it
