### ISSUE TITLE
"Play All" numbers tracks starting from the track you played

### ISSUE THREAD

**Issue by arromdee** [vanilla-music/vanilla#415]
Find an album with 141 tracks.  Play track 70 by holding it down and selecting "Play All".  It shows up as playing 1 of 141.

This makes it very difficult to start at a particular track which you know by number.

**Comment by adrian-bl** [comment]
Thats the expected behavior.

Use the 'Play All' option of the header if you want to start at the first track

**Comment by arromdee** [comment]
I think you are misunderstanding this.  The problem is not that I want to start at the first track.

The problem is that I want to start at a later track, but I also want it to be numbered as being a later track.  Right now if you start at a later track it won't number it as such.
