### ISSUE TITLE
Playing a folder uses filesystem order, not e.g. filename sorting

### ISSUE THREAD

**Issue by madduck** [vanilla-music/vanilla#417]
When  long-pressing a folder and chosing to play it, the order of songs played seems random. I think it's the unsorted result of a `readdir()` call, i.e. filesystem-dependent. Instead, I'd expect it to use an ordering based on filenames.

**Comment by adrian-bl** [comment]
The code actually does a select like this:

SELECT $fields FROM media WHERE path like '$prefix%';

adding an ORDER BY album_id,track_id wouldn't hurt.

**Comment by madduck** [comment]
Is this also the case when I don't go via the library, but use the Files tab to browse my folders directly?

**Comment by adrian-bl** [comment]
> Is this also the case when I don't go via the library, but use the Files tab to browse my folders directly?

Yes, actually i was assuming that you meant exactly this.

If you add songs from the 'normal' library, they will be grouped by track number (unless shuffle is active)

**Comment by madduck** [comment]
So you're saying that the filesystem listing itself is actually read into sqlite??

**Comment by adrian-bl** [comment]
Yes: That's actually a feature of android: It's called the 'MediaStore':

Android indexes any media element (audio, video, pictures) it sees and puts it into the MediaStore.
Applications can then query this database.

SDK Documentation: https://developer.android.com/reference/android/provider/MediaStore.html

**Comment by madduck** [comment]
"feature" ;)

So the music player then actually recreates the filesystem view?

Anyway, sounds like your `ORDER BY` could solve this…

**Comment by adrian-bl** [comment]
* The listing (eg: what you see in the 'Files' tab) is the result of readdir + stat
* Recursively adding songs is the result of the SQL query (which is *much* faster than searching a deeply nested folder tree)

**Comment by madduck** [comment]
Okay, makes sense (although I would never implement it like this, especially not force it upon developers by implementing it at the OS level).

So then, your `ORDER BY` is the key…

**Comment by cil8** [comment]
Given the context of playing a folder while navigating the filesystem, I think the playing order should be set by the filenames rather than album or track id.

**Comment by adrian-bl** [comment]
I agree: using the same (alphabetically) sorting as we use for displaying the folder contents would make more sense.

So we should ORDER BY path

**Comment by madduck** [comment]
Frankly, if I access an album through the media library and either select "Play All" from the context menu of an album, or open the album and then select "Play All" up top, the tracks are played in random order too — and of course shuffle mode is off!

**Comment by adrian-bl** [comment]
>  the tracks are played in random order too — and of course shuffle mode is off!

No: They get enqueued in the same order as they are displayed in the library.

**Comment by cil8** [comment]
Just checked looking at the track number inside my mp3 files: the play order respects the track number, if it is specified. Files without track number get grouped together before the numbered ones in an unspecified order.

madduck: likely your album's files do not contain the track number, so they get enqueued in seemingly random order.

There should be a better ordering when no track number is present (alphabetically by track name maybe?), and when playing a folder from the filesystem browser the order should be given only by the filenames.

**Comment by madduck** [comment]
@cil8 @adrian-bl My tracks all have track numbers. See screencast here: http://scratch.madduck.net/.tmp__SCR_20160814_213128.mp4

**Comment by adrian-bl** [comment]
You have the suffle mode enabled. Turn it off if you'd like to preserve the track/sorting order.

**Comment by madduck** [comment]
Isn't the shuffle mode indicated by a set of dice at the bottom right? If you look at the screencast you'll see that the icon is that of "repeat all", but it's not even enabled.

What makes you think I have shuffle enabled? Where would I disable it?

**Comment by adrian-bl** [comment]
The dice (on the rigt) is the random mode where we fill up the queue with random songs.

Shuffle is the button on the left side. (Long press on the button to see the modes)

**Comment by madduck** [comment]
OMG now I feel incredibly silly. Thanks for your patience helping me clear this up. I've now changed the theme to be able to spot this myself better in the future (I am colourblind…).

It seems like playing from the files browser now also works as expected. Doh!

**Comment by adrian-bl** [comment]
No problem.

I'm reopening this because i have to check what we are currently doing: i think that orde by path would be the way to go

**Comment by hashn0n** [comment]
Well, I have same problem @madduck had but without shuffle on.
The problem happens when I `Play`, `Enqueue` and `Add to playlist...`
For example here is ls of directory with one of albums:
001 - Take It Back.mp3
002 - Hurt Less.mp3
003 - Dirty Words.mp3
004 - Renegade.mp3
005 - Fading Halo.mp3
006 - The Only Love Song.mp3
007 - Lifes Too SHort.mp3
008 - Apocalypse.mp3
009 - Bones.mp3
010 - Your Revolution.mp3

And here how Vanilla "sorts" it:
010 - Your Revolution.mp3
007 - Lifes Too SHort.mp3
008 - Apocalypse.mp3
006 - The Only Love Song.mp3
009 - Bones.mp3
005 - Fading Halo.mp3
003 - Dirty Words.mp3
004 - Renegade.mp3
002 - Hurt Less.mp3
001 - Take It Back.mp3

That's same as `ls -U`.
And that is extremely annoying especially coupled with constant problem of "forgetting" content of playlists.

**Comment by adrian-bl** [comment]
95cd3b3329c756c9b85f0bb722d4af6a0b254ad3 fixes this issue
