### ISSUE TITLE
Track numbering in lists

### ISSUE THREAD

**Issue by arromdee** [vanilla-music/vanilla#421]
I previously opened https://github.com/vanilla-music/vanilla/issues/415 but it was closed under what I believe was a misunderstanding.  It was closed with the comment "Use the 'Play All' option of the header if you want to start at the first track".

I don't want to start at the first track.

What I want to do is change the _numbering_.   That is, if you have 141 tracks and press on the 70th one, I still want it to _start at_ track 70; however, I want to start this track while calling it "70/141", not "1/141".

Alternately, perhaps we could have an option:

Number tracks for "play all":
( ) Starting with track initially played
( ) Starting with first track in list

**Comment by adrian-bl** [comment]
Sorry, but that is just not a feature i want to implement. Adding an option for every user wish is also not an option - and in this case, the desired behavior can be achieved with just a few additional steps (play all -> slide up queue -> hit desired song)

**Comment by arromdee** [comment]
The desired behavior cannot be achieved with a few additional steps because I have no way of telling that the song is track 70.  The use case isn't for literal songs, it's for a long set of radio dramas or other shows and going back to the list after playing different audios from other sets.  I write down that I am on show 70 so that I know where to go back to. 

It would make no sense to start on the first audio and manually count down to 70.  If it was a normal record album with 15 songs or so, I could do that, but 70 is too many.  I need to be able to see the number so that I can know which audio I am on.

**Comment by adrian-bl** [comment]
> What is, if you have 141 tracks and press on the 70th one, I still want it to start at track 70;
> ...The desired behavior cannot be achieved with a few additional steps because I have no way to "hit desired song". 

Aren't you contradicting yourself? How would you be able to find the 70th song in the library view while you would not be able to do so in the queue view?


But again: You can simply long-press on play-all on either the header or the song.
If you do so on the song (eg song 70 of 141), vanilla will build a queue like this:

70 -> 141 -> 1 -> 69

So the 70th song will be the first queue item while the 69'th will be the last. That means that your songs will be in the correct order (eg: going back from 70 will go to 69)

**Comment by arromdee** [comment]
>How would you be able to find the 70th song in the library view while you would not be able to do so in the queue view?

I would guess and pick a song somewhere near 70, then look at the number and see that it is 68 or whatever, then, going by that number, know that I have to skip forward by two more songs to get to 70.

>You can simply long-press on play-all... That means that your songs will be in the correct order (eg: going back from 70 will go to 69)

Being in the correct *order* isn't enough.  They need to be correctly *numbered*.  If they are correctly numbered, I can find track 70 because if I pick 73 I can read the number, and think "that is 73 so I need to go back by 3 in order to get to 70".  If the numbering begins with the track that I picked, the numbers are useless for this purpose.

Incidentally, I already have a patch for this, which I suppose is a benefit of open source, but I'd rather not have to patch each version as it comes out.
