### ISSUE TITLE
Vanilla Music starts playing and adding songs in random order to the queue when I plug in headphones. [Android 4.0.4/CyanogenMod 9]

### ISSUE THREAD

**Issue by JORGETECH** [vanilla-music/vanilla#422]
When I plug in headphonesVanilla Music opens in background and starts playing and adding songs to queue randomly, the headphone app does not seem to affect this.

**Comment by mindforger** [comment]
just by chance, do you have continous randomize enabled? (The Dice Symbol on the right)

**Comment by JORGETECH** [comment]
No, I do not have it activated. In fact when I plug in the headphones it automatically activates the randomize function.

**Comment by adrian-bl** [comment]
Please provide a logcat

**Comment by mindforger** [comment]
i freshly installed Vanilla Music on a brand new Galaxy A5(6) without ANY playlist, just uploaded the music to it. 
When i hit the play button the randomizer also activated for me. 
Not sure if this is intended ... it kinda looks like for me but i want to mention it anyways :)

**Comment by adrian-bl** [comment]
Yes, it is: if you hit play without any music enqueued, it will resort to random mode.

**Comment by adrian-bl** [comment]
closing due to lack of reply (Vanilla Music itself does not listen to headphone events, so it must be the fault of a 3th party app)
