### ISSUE TITLE
Sort "Artist, album" should be "Artist, year, album"

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#425]
Sorting on artist and albums should be on artist, year and album, or this should at least be offered as an extra sort option and make it selected by default for sorting. Of course, this will sort albums within the same year alphabetically and not in order of when they were released, but it is better than being able to sort only on album alphabetically.

Implementing this will provide users a synchronous listening experience when playing all the albums of a certain artist.

As was discussed in other issues, sorting on year should be done in a fail safe way as tracks from an album could have different years (because of errors in the ID3 metadata). Default is empty string for year. Best to use histogram of year for all tracks in an album to find the most used year and use that to correct for wrong or incorrect years. e.g.:

track 1 year 2001
track 2 year 2001
track 3 year 200 (error in year)
track 4 year 2001
track 5 year 2001
track 6 year (not set, empty string)
track 7 year 2001
track 8 year 2001
track 9 year 20011 (error in year)

year histogram (empty strings are not considered as that is the default):
6x 2001
1x 200
1x 20011

hence the year for this album is 2001.

See also https://github.com/vanilla-music/vanilla/issues/372

**Comment by adrian-bl** [comment]
Fixed in commit b469cb6c0a78a5a8a2af0cb539816a24ec2cf6ad
