### ISSUE TITLE
Use material Design Icons in player and widgets

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#426]
Please, use Material Design icons in player,  widgets and notification tray pull-down. Benefits are that the visual language conforms to the general experience of Android, prevents misinterpretations, improves more quick understanding and eliminates support of certain icons in Vanilla Music.

See the the following links for icons in Material Design for the player, widgets and notification tray pull-down:
- https://design.google.com/icons/#ic_skip_previous for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/widget_previous.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/previous.png
- https://design.google.com/icons/#ic_play_arrow for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/widget_play.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/play.png
- https://design.google.com/icons/#ic_pause for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/widget_pause.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/pause.png
- https://design.google.com/icons/#ic_skip_next for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/widget_next.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/next.png
- https://design.google.com/icons/#ic_replay
- https://design.google.com/icons/#ic_repeat for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/repeat_active.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/repeat_inactive_service.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/repeat_inactive.png
- https://design.google.com/icons/#ic_repeat_one for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/repeat_current_active.png
- https://design.google.com/icons/#ic_looks_one for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/stop_current_active.png
- https://design.google.com/icons/#ic_search for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/ic_menu_search_material.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/ic_menu_search_holo.png
- https://design.google.com/icons/#ic_more_vert for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/ic_menu_moreoverflow_normal_holo_dark.png
- https://design.google.com/icons/#ic_reorder for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/grabber.png
- https://design.google.com/icons/#ic_star for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/btn_rating_star_on_mtrl_alpha.png
- https://design.google.com/icons/#ic_casino for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/random_active.png
- https://design.google.com/icons/#ic_star_border for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/btn_rating_star_off_mtrl_alpha.png
- https://design.google.com/icons/#ic_folder for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/folder.png
- https://design.google.com/icons/#ic_keyboard_arrow_right for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/arrow.png
- https://design.google.com/icons/#ic_close for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/notification_close_dark.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/notification_close.png
- https://design.google.com/icons/#ic_music_note for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/ic_musicnote.png
- https://design.google.com/icons/#ic_album for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/ic_disk.png
- https://design.google.com/icons/#ic_person for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/ic_microphone.png (a microphone icon exists but icon of a person is better suited as not all musicians use a microphone)
- https://design.google.com/icons/#ic_shuffle for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/shuffle_inactive_service.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/shuffle_inactive.png and https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/shuffle_active.png
- https://design.google.com/icons/#ic_album for https://github.com/vanilla-music/vanilla/blob/master/res/drawable-xxhdpi/shuffle_album_active.png (or display this icon over the ic_shuffle icon)

Implement this by using only SVG icons from the Android operating system.

**Comment by adrian-bl** [comment]
I agree that the icons could benefit from a refresh.

I'm adding the 'patches-welcome' tag to this as it is a low hanging fruit and doesn't require coding skills. So if someone wants to do a pull-request for this: go for it!

**Comment by kgilmer** [comment]
The minSdk for Vanilla is 15 (https://github.com/vanilla-music/vanilla/blob/master/build.gradle#L29).  According to the docs (https://developer.android.com/training/material/drawables.html) 21 seems to be required for SVG drawables, so I believe the SVG material design resources cannot be used.

**Comment by PanderMusubi** [comment]
Thanks for finding out the details. For now this is unfortunately the case. Once that version is being used, it would benefit Vanilla's look.

**Comment by kgilmer** [comment]
For anyone looking at this issue in the future; the project maintainer does not like these icons so do not waste your time with this issue, as I apparently have.

**Comment by adrian-bl** [comment]
Please do not spread such misinformation: I just said that i am 'not such a big fan' of the material icons.

I never said that we will not use any material icons if people like them (also see my comment above).

**Comment by kgilmer** [comment]
My apologies, It is not my intention to spread misinformation @adrian-bl .  My goal is to contribute to your project.  For this ticket, can you explain to me what is needed for a PR to be merged?  Is it just in using the SVG script you mentioned in my PR or is there more?  Are @PanderMusubi 's icon selections valid, or is the scope of this issue larger?

**Comment by adrian-bl** [comment]
> can you explain to me what is needed for a PR to be merged?

* The icon must have a compatible license
* The original version of the icon should always be stored as an svg(z) in the orig/ folder
* The generated PNGs (using generate-pngs.sh) must have the correct size (mdpi/hdpi/etc)

And of course: It should 'look' okay (eg: dark-grey on grey looks bad - and note that Android 4.x uses a solid black background!)
But note that - for some cases - you can use ThemeHelper.java to apply a tint to the icon dynamically.

**Comment by kgilmer** [comment]
Thanks @adrian-bl .  I will look at the build scripts tonight and make changes accordingly.  Regarding license, the icons @PanderMusubi references above are ASL2.0.  I am not aware of any problems, but please let me know if you are.

**Comment by adrian-bl** [comment]
Yes: Apache licensed IP is compatible with our (GPLv3) license - so this is not an issue for these icons.

**Comment by kgilmer** [comment]
The custom script used to generate PNGs from SVGs is apparently Linux-only.  I have a Mac and despite having inkscape installed and doing some random hacking to be callable from the shell script, it still fails with garbage like:

```
sed: /usr/local/themes/Clearlooks-Quicksilver-OSX/gtk-2.0/pre_gtkrc: No such file or directory
W: AppleCollationOrder setting not found, using AppleLocale.
Setting LANGSTR from AppleLocale: en
Overriding empty LANG from /usr/share/locale/locale.alias
Setting Language: en_US.UTF-8
sed: /usr/local/etc/pango/pangorc: No such file or directory
sed: /usr/local/etc/pango/pango.modules: No such file or directory
sed: /usr/local/etc/gtk-2.0/gtk.immodules: No such file or directory
sed: /usr/local/etc/gtk-2.0/gdk-pixbuf.loaders: No such file or directory
/usr/local/bin/inkscape: line 159: /usr/local/bin/inkscape-bin: No such file or directory
/usr/local/bin/inkscape: line 159: exec: /usr/local/bin/inkscape-bin: cannot execute: No such file or directory
```

I don't want to sink any more time into this task. Perhaps someone with a compatible dev machine will have better luck.

**Comment by adrian-bl** [comment]
The script is pretty simple and should work on OSX: but it seems that the inkscape installation is broken (many gtk errors)

**Comment by kgilmer** [comment]
The inkscape I have installed requires X11.  There is no brew port.  I saw some stuff online claiming that the command line support should work but was unable to get it working.  I've been looking at a build with the icons and found that the following icons will need to be dark:

*_widget.png
Folder.png

Folder.png as suggested by @PanderMusubi above does not look good IMO, the "open" folder does though (https://material.io/icons/#ic_folder_open)

I will correct others as I find them.

**Comment by PanderMusubi** [comment]
On Linux, this works https://gitlab.com/fdroid/artwork/blob/master/badge/export-png.sh If you want, I can convert the SVG files to PNG for you.

**Comment by PanderMusubi** [comment]
To answer the question regarding the license. The license for the icons which are part of Material Design is https://github.com/google/material-design-icons/blob/master/LICENSE these icons are already shipped/included/available on any Android OS.

**Comment by yaomtc** [comment]
I started using Vanilla Player today from F-Droid and fairly quickly noticed that it's quite difficult to tell apart an active button and and inactive one. Shuffle is off, it's a dark gray. Shuffle is off, it's a dark blue that's quite close to the gray. Would using Material Design icons necessarily fix this, or should I find/create a separate issue for the overly low contrast?

**Comment by PanderMusubi** [comment]
Most design problems have been tackled in Material Design with plenty of mainstream apps. The shuffle/repeat button here is a very complex button. Perhaps it should be split up into two separate buttons?

**Comment by yaomtc** [comment]
I think the way shuffle currently functions is fine - shuffle off, shuffle on, shuffle albums, pretty universal - it's just the color choices that kinda suck. As for repeat, though, uh... Off, on, repeat once?, one??, random??? It's far less clear what these do and they could really use a momentary text pop-up when you push it.

**Comment by adrian-bl** [comment]
Closing as a dup of #588
