### ISSUE TITLE
Add Material Design icons to long press menu

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#427]
Please, add Material Design icons to the long press menu:
* Play https://design.google.com/icons/#ic_play_circle_filled
* Play all https://design.google.com/icons/#ic_play_arrow
* Play next https://design.google.com/icons/#ic_play_circle_outline
* Enqueue https://design.google.com/icons/#ic_queue
* Expand https://design.google.com/icons/#ic_expand_more
* More from artist https://design.google.com/icons/#ic_person
* More from album https://design.google.com/icons/#ic_album
* Add to playlist... https://design.google.com/icons/#ic_playlist_add
* Delete https://design.google.com/icons/#ic_delete

Also use https://design.google.com/icons/#ic_play_arrow before the Play all at the top of certain lists such as Artist, Album and Songs.

The icons chosen for play are selected in such way that they convey their specific function and are inline with issue 426 (where play stands for continue playing, i.e. play all).

Implement this by using only SVG icons from the Android operating system. See also https://github.com/vanilla-music/vanilla/issues/426

**Comment by adrian-bl** [comment]
IMO it's quite uncommon to have icons in a context menu.

Can you point me to any app doing this?

**Comment by relan** [comment]
> IMO it's quite uncommon to have icons in a context menu.

It's uncommon, but they may have icons. See **Contextual menus** in https://material.google.com/components/menus.html#menus-usage

**Comment by PanderMusubi** [comment]
I use this menu a lot _on the go_, meaning on my bicycle or in the car, and want to quickly find the option I need. Icons help without reading each option completely. Note that the options here have are in text very similar..  Also, therre is space to use icons and it will also serve as a legend for some of the icons used in other views such as the player view.

**Comment by adrian-bl** [comment]
Sorry, but i'm closing this as this would introduce a quite unusual UI
