### ISSUE TITLE
Use Track(s) instead of Song(s)

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#428]
Please, use Track(s) instead of Song(s). Some tracks are not songs, i.e. audio files on which you will hear people singing. It is common for media players and also audio-only media players to refer to track instead of song.

**Comment by adrian-bl** [comment]
Yes, this would make sense: We also use 'Titel' in the german translation.

**Comment by adrian-bl** [comment]
Hopefully i got them all: fixed via a940f0a4e9f6f78a918a072bd8e26b663437a18d
