### ISSUE TITLE
OPUS support?

### ISSUE THREAD

**Issue by CrusoeDaWolf** [vanilla-music/vanilla#429]
Just found your app. Great work, however, some of my audio is in OPUS format. 

How would OPUS support go about?

**Comment by kirbyfan64** [comment]
#60 #123 #358 #384 #414 

TL;DR: Vanilla Music uses Android's own playback service. So *OPUS is supported only if your Android version supports it*.

**Comment by CrusoeDaWolf** [comment]
I'm running Cyanogenmod 12 and that doesn't seem to be the case for me. My default player can't see OPUS at all, so I have to resort to using Poweramp for OPUS playback. :/

**Comment by kirbyfan64** [comment]
Seems like Cyanogenmod doesn't support OPUS:

https://jira.cyanogenmod.org/browse/CYAN-438

Oddly enough, there *is* a repo in Cyanogenmod's Git org for libopus:

https://github.com/CyanogenMod/android_external_libopus

but it doesn't seem to actually work. You could always try converting them to FLAC or something...

**Comment by CrusoeDaWolf** [comment]
Actually, the other large portion is FLAC, but that's the reason why I'm converting from FLAC to OPUS (FLAC is slowly taking up a lot of space).

Isn't the OPUS source available though? I know the guys at Xiph tend to make their stuff open source (OGG Vorbis, FLAC, etc)

**Comment by kirbyfan64** [comment]
https://github.com/xiph/opus

**Comment by CrusoeDaWolf** [comment]
I guess I might go with OGG Vorbis then or I'll try to find another ROM for my HTC One M8 (I don't really like the Sense ROMs. Too bloated for me xP)
