### ISSUE TITLE
Add Multiple files selection

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#430]
I have a suggestion that should make life easier for many users.
And It's a way to select multiple files, particularly **in the songs tab**. 

The lack of this option is disturbing when, for example, we copy a big folder of songs in the memory card and we want to put some songs in such and such playlist and we HAVE TO manage the songs **one by one** which is slow and boring when there is 300+ files...

If you can add this new option, we would be able to select multiple songs (with a check box for instance) and **apply an action** to that selection (example : _**DELETE, ADD TO PLAYLIST, PLAY ALL**_).

I really hope you'll try something, thank you.

**Comment by adrian-bl** [comment]
This is a dup of #90
