### ISSUE TITLE
"webm" file plays, but is not recognized with folder actions

### ISSUE THREAD

**Issue by WayneSherman** [vanilla-music/vanilla#431]
I have a folder with M4A and WEBM files.  Both files play correctly when selected individually.  When I long select the folder and "play" or "enqueue", only the M4A files are put on the play list and the WEBM files are ignored.  (Note: In this case, WEBM is a container for OPUS encoded audio).

**Comment by adrian-bl** [comment]
These files are probably not marked as 'audio' by android.

So we will play them if asked directly, but won't include it in library action
