### ISSUE TITLE
Allow option to choose which tabs are shown (Artists, Songs, Genres, etc.)

### ISSUE THREAD

**Issue by omertuc** [vanilla-music/vanilla#434]
I never like looking at a list of all my songs, so the Songs tab is useless for me. I also never browse by albums, so that's useless for me as-well. These tabs just take space in the interface and I must go through them when I move between other tabs using the swipe gesture.

I suggest allowing an option to choose which tabs are shown, I've seen many players offer this functionality and it doesn't sound too hard to implement (I might be wrong, I'm pretty inexperienced when it comes to Android development).

**Comment by ToNIX-** [comment]
Settings > Library Screen > Tab Order.

Check/uncheck the tabs you want/don't want, drag them to chose their order.

**Comment by omertuc** [comment]
I swear I went through the settings 100 times to look for that option. Don't know how I missed that. Thanks a lot! Issue closed.
