### ISSUE TITLE
[FEATURE REQUEST] Prevent phone from sleeping

### ISSUE THREAD

**Issue by omertuc** [vanilla-music/vanilla#435]
Maybe I'm missing something but it seems there is no option to prevent the phone from sleeping while in the Vanilla app. All I see is an option to disable the lockscreen.

When driving I really like to have the music player on all the time. without the phone turning off so I can see which song is playing.

Is it possible? Or does it require root or permissions you don't want to request?

**Comment by adrian-bl** [comment]
Implementing this should be pretty easy: it's just a windowmanager flag, see:
https://developer.android.com/training/scheduling/wakelock.html

**Comment by mindforger** [comment]
i noticed that one too, it always faded the screen to a level where i could barely see what track is playing until i touched it.
i always thought it was a bug of my phone (badly installed cyanogen) as i had the option for preventing screen lock enabled

**Comment by adrian-bl** [comment]
No: thats how the setting is supposed to behave: the idea behind it is to *not* enable the lock screen after the screen turned off.

The setting is not supposed to keep the screen on.

**Comment by adrian-bl** [comment]
Finally implemented this in 303f9d23751e37a7d8eb826f842c4cc5f1ef7bc6
