### ISSUE TITLE
Remove database

### ISSUE THREAD

**Issue by hboetes** [vanilla-music/vanilla#437]
I just noticed double entries in the database so I rescanned,  tried to remove the database entirely, uninstalled vm, reinstalled. Removed all settings, cached data and everything else that came to mind but I still had the double entries.

Where is the database stored on the file system?

**Comment by adrian-bl** [comment]
We are using androids system wide music library.

You can force a rescan via Settings > Misc > SD Scanner.

If this does not help and you are 100% sure that you do not simply have duplicate files (hint: you can delete files using vanilla music by long oressing on the library entry) you coukd try to wipe the system db by going to Android Settings > Apps > Media Storage. Then select the option to delete the data & reboot your phone. Note that this will wipe all playlists.

**Comment by hboetes** [comment]
Thanks for your reply, Adrian. The database is like it should be now.

A word of warning for people running into the same problem, this operation will change all your alarm settings.
