### ISSUE TITLE
Notification icons hard to see in black theme

### ISSUE THREAD

**Issue by blackwind** [vanilla-music/vanilla#438]
I use a black CM theme, and Vanilla Music's notification icons are black as well, making it hard to see what I'm pressing. If automatically adapting to the user's theme is too much work, a simple toggle for white icons would be great.

**Comment by mindforger** [comment]
on CM13 XIAOMI MI4C the notification icon colors are adjusted when i switch the theme!? Do you have some sort of special theme or another CM Version?

**Comment by blackwind** [comment]
Using [Dark Material](https://play.google.com/store/apps/details?id=com.chummy.jezebel.material.dark) on CM13. Perhaps its notification background isn't quite dark enough to trigger white icons? Either way, at the brightness level I use, the black icons are virtually indistinguishable.

**Comment by adrian-bl** [comment]
There is nothing that would 'trigger' white icons: Your theme simply uses an unexpected background (we expect a white background on Android >= 5.x), so the icons are hardly visible.

If someone comes up with a way to detect such themes, i'd be happy to include a workaround - but this has low priority for me given the fact that this is a custom-non-standard modification of the OS itself

**Comment by blackwind** [comment]
@mindforger made it sound like this functionality was already present. In any case, as noted in the OP, I'd gladly settle for a white icons toggle in settings instead.

**Comment by adrian-bl** [comment]
I've been thinking about this and i do not see a good/stable way to detect the notification color and adjust automatically.

But how about a 'Apply theme to Notification' checkbox in Vanillas Theme-Dialog?
If checked, we would inherit the colors from the selected theme instead of what the framework provides.

**Comment by blackwind** [comment]
Sure, works for me. As long as it produces the desired result, I'm happy.

**Comment by adrian-bl** [comment]
I had a look at this and styling the notification is just a huge pain: We can not get the current theme from the PlaybackService-Context and styling it in XML also seems to be impossibe (loading non-android attributes fails)

So maybe the best approach to fix this would be to simply use a different set of icons (eg: with a white outline). (Also see #426)

**Comment by blackwind** [comment]
I'm not thrilled with that solution, but it's a start, I guess.

**Comment by adrian-bl** [comment]
Closing this issue as there is simply no way for the application to pick up custom theme changes.
If someone figures out a way to do so (by getting the root views color - which i failed to do), feel free to send a PR.

**Comment by blackwind** [comment]
> So maybe the best approach to fix this would be to simply use a different set of icons (eg: with a white outline).

What about this idea as a stopgap? An option to use a different icon set sure beats having to switch to another app.
