### ISSUE TITLE
SD-scanner only scans /storage

### ISSUE THREAD

**Issue by Caschtor** [vanilla-music/vanilla#439]
Hi!

First of all thanks to the devs for this free and really good app.

I have a problem with the sd-scanner option, not sure if it's an issue or maybe an expected behavior. I'm using vanilla-music version 1.0.43 on a Moto G3 with Android 6.0.  I've added a sd-card ( mounted as external storage under /sdcard ). The sd-scanner option only scans /storage and not any other directory. If I add new music in any folder on the SD-card these new files aren't visible in the vanilla library after I've used the sc-scanner option. 

Is this a known issue? Is there any way to change the search directory the sd-scanner option is using?

Kind regards

Chris

**Comment by adrian-bl** [comment]
We scan whatever android claims to be the internal storage + /storage/sdcard1, the code in question looks like this:

```
private File[] mScanTargetStages = { Environment.getExternalStorageDirectory(), new File("/storage/sdcard1") };
```

..and /sdcard is usually just a symlink to /storage/sdcard1

Could you send me a list of directories in the /storage/ directory? Maybe your phone uses a different target directory for /sdcard (also: are you running a custom rom?)

As a workaround: you could simply install the stand-alone SD-Scanner (https://f-droid.org/repository/browse/?fdid=com.gmail.jerickson314.sdscanner)

Vanillas internal scanner is based on this code but was dumbed-down: The stand-alone application allows you to specify a custom path.

**Comment by xbao** [comment]
I also have a MotoG3, my sdcard path is `/storage/578F-1C17`. It's possible it's random or user assigned, so I coded up a solution using [Context.getExternalFilesDir](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir(java.lang.String)) that falls back on the hardcoded ones, it's up at PR #444 :)

**Comment by adrian-bl** [comment]
Hmm, that's interesting: So /sdcard and /storage/sdcard1 do not exist at all on your device?

But the PR looks good to me: It's for sure much better than having a list of hardcoded dirs.
Only nitpick: Coud you please add the usual function-comment-boilerplate to the getScanTargets function?

**Comment by xbao** [comment]
Yeah:

```
adb shell ls -al /storage/
drwxrwx--x root     sdcard_rw          2016-09-20 10:00 578F-1C17
drwx--x--x root     sdcard_rw          2015-07-23 16:14 emulated
drwxr-xr-x root     root              1970-12-26 02:59 self
```
Re: Javadoc, no problem :)

**Comment by adrian-bl** [comment]
Hmm.. interesting: Androids external storage handling is an eternally moving target :-) (but at least it's a lot better on 6.x with the fused storage: i love it)

I merged the pull request, so i'm going to close this bug as it should fix the issue of the reporter.

Thanks a lot for the patch!
