### ISSUE TITLE
Swipe Up/Down Action Ignores Toggle Controls Option

### ISSUE THREAD

**Issue by jashandeep-sohi** [vanilla-music/vanilla#44]
Possible bug. Under Settings -> Playback Screen -> Swipe Up Action (and Swipe Down Action) doesn't work when set to 'Toggle Controls'.
Just to be clear, the setting does get set, but when you swipe up or down on the playback screen, nothing happens.

**Comment by adrian-bl** [comment]
Hmm: The swipe action is handled by PlaybackActivity, but FullPlaybackActivity should get notified about it.
As there is no easy/clean way to have PlaybackActivity call FullPlaybackActivity, we should probably just hide this in the swipe-action-dialog

**Comment by adrian-bl** [comment]
Fixed via https://github.com/vanilla-music/vanilla/commit/0dc422a37b08f8f01118b7ff12d426123cf3125b
