### ISSUE TITLE
Opus files are removed from playback list on exit.

### ISSUE THREAD

**Issue by aibaraiduas** [vanilla-music/vanilla#441]
Opus files can be added to the playback screen just fine and play normally. However, when Vanilla Music is closed then reopened, the tracks are no longer listed on the playback list and need to be added back manually. 

Not sure if this is an issue with Vanilla music or the way Android handles opus files or something. I'm using a Nexus 5 running Android 6.0.1. Thanks.

**Comment by adrian-bl** [comment]
Thats an Android issue:

We use the Android Media Database where each indexed song has an ID (which we use to save/restore playlists and the queue)

However: Android 6.x does not index opus files and we therefore do not have an ID to save, so we are unable to restore the item later.
