### ISSUE TITLE
Ampache connector

### ISSUE THREAD

**Issue by Morrydwenn** [vanilla-music/vanilla#443]
Hello,

It would be nice to have the possibility to configure vanilla music to access an ampache server (http://ampache.org/).

With this feature, vanilla music would be the killer-app fro android ;)

**Comment by Jucgshu** [comment]
Hey guys,

Although I'm quite happy with Vanilla already, having an Ampache connector would be an awesome addition indeed.

Anyway, thanks for your work !

**Comment by adrian-bl** [comment]
Sorry, but this is out-of-scope: I'd like to keep vanilla music's scope to be a music player for locally stored music.
