### ISSUE TITLE
Songs not correctly ordered

### ISSUE THREAD

**Issue by Airon90** [vanilla-music/vanilla#445]
Songs in tab "Tracks" are ordered alphabetically by author and then by title, not just by title as expected. By now the section is a clone of Artists tab but with all songs available.

**Comment by adrian-bl** [comment]
What sort mode did you set for the tracks tab?

**Comment by Airon90** [comment]
Ok, I found out that I have to set it manually and I found out just now that settings about order is not in App settings but separately. Sorry and thank you
