### ISSUE TITLE
SD Scanner doesn't find any music

### ISSUE THREAD

**Issue by petwri** [vanilla-music/vanilla#446]
When running the SD scanner on my Sony Xperia, no music gets scanned to Vanilly. There are files stored in External Storage/Android/data/com.mb.android/ which are just not found. Any ideas? Can provide more infos if required.

**Comment by adrian-bl** [comment]
I doubt that vanilla would have read permission to this (app private) folder.

You should store your music in a public folder

**Comment by petwri** [comment]
I created the folder on my own. But anyways, what folder structure on an
external SD-card is recommended?

**Comment by adrian-bl** [comment]
There is no recommendee structure: just make sure that there is no .nomedia file in one of the parent folders as this will stopp the indexer

**Comment by petwri** [comment]
So  I created a new folder which definitely doesn't contain a .nomedia item. Scanner still didn't find tracks, but they appeared after a restart of my phone.

**Comment by adrian-bl** [comment]
The SD-Scanner is just a last resort: The phone should pick up new media anyway (eg: transferring data via MTP will notify android about new data)

But we recently made a change to improve device specific external storage paths: This is not yet in the stable version, but you could give the nightly (See http://www.vanillamusic.io) a try.
