### ISSUE TITLE
[Suggestion] Add a Vanilla-Playlist handler as workaround for buggy Android Playlist implementations

### ISSUE THREAD

**Issue by Wikinaut** [vanilla-music/vanilla#447]
From many previous issues I learnt, that Vanilla relies on the Android "Playlist", but the Android implementations are buggy and often leads to unexpected behaviour (mixing up song sequence, emptying list unexpectedly etc.)

Therefore I want to propose to code/create - as a workaround - a Vanilla-intrinsic Playlist function.

**Comment by adrian-bl** [comment]
This still wouldnt solve the root issue of your firmware: we would still suffer from random mediadb rebuilds, causing issues for other features such as the playcount db and the cover cache.
