### ISSUE TITLE
alphabetical play order

### ISSUE THREAD

**Issue by anahuj** [vanilla-music/vanilla#448]
I need to play songs in alphabetical order when I play a folder.

When I now play a folder, its contest is played in order 01.mp3 15.mp3 02.mp3 26.mp3 etc, which is wrong. The files should be played in order 01.mp3 02.mp3 03.mp3 etc.

The reason is that I recorded songs 01-14 and 15-30 separately with Audacity. Audacity inserts indexes 1 to 14 and indexes 1 to 16 to mp3 files. Vanilla plays first indexes 1 and 1, then 2 and 2, etc.

Alternative solution would be that Vanilla re-indexes all mp3 files in the folder. I have no way to modify data inside mp3 files.

**Comment by adrian-bl** [comment]
This is already fixed in git head via 95cd3b3329c756c9b85f0bb722d4af6a0b254ad3 and will be included in the next version
