### ISSUE TITLE
Music playback stops during notification sound

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#45]
Hi there, and thanks for this awesome music player that does everything I'm looking for so far (ReplayGain, FLAC, stops when headphones are plug off, etc.) ! ;-)

However, I've noticed that if I receive a notification (text message, e-mail, etc.) during playback, the music will stop, notification sound will play, the music will resume again.

Example :
1- music plays
2- music stops
3- notification sound plays
4- music resumes where it stopped

I'm not sure if that's a desired behaviour (it makes notification sounds more audible) or a bug, but it really breaks the music enjoyment for me. What's more, when using my road navigation app (OsmAnd, of course :-) ), music playback will NOT resume after direction is spoken up. 

Example :
1- music plays
2- music stops
3- "After 200m, turn right"
4- ... nothing ! I have to manually press play again.

Wishlist :
- Keep playing during notifications
OR
- Lower music volume during notification. I believe the default Android 2.3 music player had such an option, and I found it pretty nifty (called "volume ducking", IIRC). :-)

Phone :
Samsung Nexus S I9023
CyanogenMod 10.1 (Android 4.2.2)

**Comment by Allanitomwesh** [comment]
I think it would be best if 
1. instead of stopping playback,it reduced the volume and the notification played over the song. some other players do this.
2. Implement b) suggestion "resume playback in any case" 

that should solve this.

**Comment by breversa** [comment]
Yes, that's precisely what I suggested above.

Glad to see I'm not the only one looking forward to that feature ! :-)

**Comment by adrian-bl** [comment]
Closing as fixed: PR was merged

**Comment by ToNIX-** [comment]
Just a little update, works flawlessly on my Moto G XT1040 with Vanilla 1.0.32, tested with Nokia Here Maps giving GPS directions. I think that the initial 50% is too high (it should be at 25%), but all in all, an amazing addition!

**Comment by breversa** [comment]
Glad to see you too love that feature I've been longing for ! ;-)

Why not add it to the application features here : https://github.com/vanilla-music/vanilla ?

**Comment by jmorgannz** [comment]
I can't find any option in VanillaMusic to enable this - continuous playback during notifications (and alarms I am hoping)

**Comment by ToNIX-** [comment]
> I can't find any option in VanillaMusic to enable this - continuous playback during notifications (and alarms I am hoping)

Settings > Audio > Volume during notification
