### ISSUE TITLE
Progress bar in lock screen

### ISSUE THREAD

**Issue by vinniec** [vanilla-music/vanilla#457]
It possible to have a progressbar in the lockscreen? Sometimes I would like to repeat sections of a song without unlocking the phone and/or sliding-down the upper info bar.

**Comment by adrian-bl** [comment]
This sounds like a nice feature, but i'm not sure how well it will work out as we need to re-create the notification every second (could put quite some load on the phone / drain battery?) and won't be able to use the normal seek bar as we can only consume simple clicks from a notification.

But i'll try to come up with a prototype if i find some time

**Comment by vinniec** [comment]
Very thanks for consideration, vanilla is really a great player, many spans above that stock. Finally I do not have to do battle to open files from the folders, and with the latest updates the files are already sorted by name :)

**Comment by adrian-bl** [comment]
I tried this and it doesn't seem to be possible without either abusing the Notification view (by adding hundreds of button views to it) or by implementing a custom lock screen (which would be a lot of work)

So i'm closing this as wontfix.

**Comment by vinniec** [comment]
however, many thanks for trying, vanilla continues to be my reference player :)
