### ISSUE TITLE
No notification\scrobble on repeat

### ISSUE THREAD

**Issue by 1sad** [vanilla-music/vanilla#458]
If there is one song playing on repeat, notification doesn't come up after the track restarts, and it only scrobbles the first time it plays. Same deal with "repeat current track" option.

**Comment by adrian-bl** [comment]
What do you mean with 'the notification doesn't come up?'

I just tested this and we are sending a scrobble broadcast for every loop - but i wouldn't be surprised if the scrobble app filters such 'duplicates' automatically.

**Comment by 1sad** [comment]
Well, when the song switches, in the drawer, notification shows you the name of the song (verbose notification settign?), on repeat that doesn't happen for me.
Using scrobble droid, and if it switches to a different song, then I manually switch to the same song I just listened, it scrobbles fine, and there is a notification. Don't know if that's connected or what, but those are the two things happening.

**Comment by adrian-bl** [comment]
> Well, when the song switches, in the drawer, notification shows you the name of the song (verbose 
> notification settign?), on repeat that doesn't happen for me.

That's a feature of Android: It detects that the notification didn't really change and does nothing.

> Using Simple last.fm Scrobbler, and if it switches to a different song, then I manually switch to the 
> same song I just listened, it scrobbles fine, and there is a notification. Don't know if that's connected 
> or what, but those are the two things happening.

..and that's probably the same feature:
If you are on repeat, then the scrobbler detects that it received the same event again (SongA -> SongA)

But if you manually go back, the scrobbler will see SongA -> SongB -> SongA -- so SongA get's scrobbled again.

**Comment by 1sad** [comment]
So its not even a bug... Is there a workaround? It makes repeat modes completely pointless for me.

**Comment by adrian-bl** [comment]
No, not really:
There is nothing we can do on Android itself and what the scrobble app does is out of our control

**Comment by 1sad** [comment]
Oh, well, thanks then.
