### ISSUE TITLE
Implement our own MediaDB

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#460]
I do not expect any improvements in the android media database, so maybe we really should start to build our own media database.

In a first step, we should focus on a solid SQL schema and define our goals, such as having Replay Gain in the database, supporting multiple Genres + Artists per track and so on.

Using the database schema of 'Slimserver' (http://wiki.slimdevices.com/index.php/SlimServerDatabaseStructure) might be a good idea as it is a mature product which is able to please many 'picky' users ;-)

A description of the database can be found here: http://wiki.slimdevices.com/index.php/SlimServerDatabaseStructure , a partial dump of the 7.x schema is at https://gist.github.com/adrian-bl/353d1065a1f3306f109e28b1cc9578d1

Some questions which come into mind are:

[ ] Which fields are we going to store where? We don't need stuff like urlmd5, but having the playcount would be nice.
[ ] Are we using views? (Like android does)
[ ] Are we using triggers? (most likely: yes)
[ ] What are our performance goals? (Do we need to be fast on a Nexus 5 with 100'000 items?)

After the prototype is up and running, we can start to think about the actual scanning process.
Reading the tags itself will be trivial, but detecting new files could be a real challenge - but should be doable.

**Comment by Adonai** [comment]
> What are our performance goals? (Do we need to be fast on a Nexus 5 with 100'000 items?)

Don't think so. There's no storage for 100 000 items anyway. My 2k collection eats 11 GiB already and VM is blazingly fast.

> Which fields are we going to store where? We don't need stuff like urlmd5, but having the playcount would be nice.

Let's take a look at VorbisComment/ID3v2 specs, they can give us a nice overview of what is to be found in music files.

> Are we using views? (Like android does)

I think this is a thing to decide after start of actual implementation. E.g. if we encounter complex queries it would be nice to create well-named view.

> Are we using triggers? (most likely: yes)

Yes. Nice way to update stats for artists during media scan.

**Comment by Adonai** [comment]
Meanwhile, how do you plan to extract song metadata from files? Will we rely on some external media scanner for this?

**Comment by mindforger** [comment]
>playcount 
but let it count only songs played at least half a minute or so, when i zap trough titles because of mood, it shouldn't consider all tracks as played :)

>urlmd5
i have no idea what this is about exactly, but distinguishing duplicate files (md5hash) would be very usefull (due to virtual duplicated folder structures, like symlinks that almost all samsung galaxy models use afaik)
also if there are real duplicates and one file gets deleted, switching over to the alternative without rescanning would be very usefull!

**Comment by adrian-bl** [comment]
> Don't think so. There's no storage for 100 000 items anyway. My 2k collection eats 11 GiB already 
> and VM is blazingly fast.

100'000 is probably unusual but could be done (1.2MB per song on a 128GB device) - i think we should set the performance-bar high :-)

> Meanwhile, how do you plan to extract song metadata from files? Will we rely on some
> external media scanner for this?

We are going to build our own.
My hacky prototype (which already works okayish but still suffers from a bad sql-schema) can already do a full recursive scan: The first scan takes some time (mostly due to the calculation of song durations) but subsequental runs finish within a few seconds, which is already a good start for a prototype. (But the scanner itself will be the last thing i'm going to work on: i first need to get the SQL right - i just hacked it together to fill the database with real-world data)

> but let it count only songs played at least half a minute or so, when i zap trough titles because of
> mood, it shouldn't consider all tracks as played :)

We already do this with the existing playcounts implementation

> i have no idea what this is about exactly, but distinguishing duplicate files (md5hash) would be very
> usefull 

Checking the md5 of every file on the phone would take too much time.
But we already do some 'symlink-detection' by checking known 'shadow paths'

**Comment by mindforger** [comment]
while i understand the scanning will take a lot longer when using MD5 on every mp3 to make it unique, i would recommend it to be added as an option to eliminate/identify duplicates

i have around 700 tracks on my phone currently, at a size of 8mb-ish per track making aroung 5.5GB
if i calculate this with with an average readspeed of 8mb/s(taken from several benchmarks) it would take around 12minutes to only calculate the md5s.
But what is the estimated time for a full media scan compared to those 12minutes? I have no idea i just want to run down some numbers to see if it is overkill or really an usefull tradeoff eventually.

**Comment by adrian-bl** [comment]
> while i understand the scanning will take a lot longer when using MD5 on every mp3 to make it unique, 
> i would recommend it to be added as an option to eliminate/identify duplicates

And if a duplicate was found, what should Vanilla Music do?

> i have around 700 tracks on my phone currently, at a size of 8mb-ish per track making aroung
> 5.5GB if i calculate this with with an average readspeed of 8mb/s(taken from several benchmarks)
> it would take around 12minutes to only calculate the md5s.

My collection is currently about 25GB with >4k files, running md5sum via ADB takes about 15 minutes which is not acceptable.

**Comment by mindforger** [comment]
>And if a duplicate was found, what should Vanilla Music do?

to start with, i have a terrible file management, i have folders for artists, folder for albums and folder for moods or content related

sometimes i have the identical song in 3 folders (very common unfortunately) and when i assemble a playlist i am always confused in the way "didn't i already added this one? *add*" adding a copy of the exact same song to my playlist and then wondering while it plays 3 times in a row later

and most annoying, when i find a duplicate, i remove it from memory, resulting in the song missing in a couple of playlists because they don't know there is exact the same song just in another directory

**Comment by adrian-bl** [comment]
For people interested, i have a working prototype in https://github.com/vanilla-music/vanilla/tree/media-db (i'll later squash and delete the branch - it's my personal junkpile ;-) )

The branch is 'useable' but far from perfect: Biggest issues so far:

* The media scanner is pretty dumb (full rescan at every start). Did't work much on it yet
* Didn't bother to look at any encoding issues (also: we are currently using BASTP to read all tags)
* Some queries are slightly slower than using androids database - that's mostly due to the fact that we support multiple artists (not visible) and have better genre support
* Playlists are not implemented and crash often
* Most sorting options are gone (for now)
* Opening a file by path will most likely cause a crash
* Only our 'native' cover loader works: Looking up Covers in the media-db will not work

**Comment by Adonai** [comment]
@adrian-bl , I guess there will be tremendous hype when the switch actually happens, Android phone user base is so much vast that you don't know from where errors start popping up... do you have it as configurable option like "Use our own media DB" or something? I see a load of new changes everywhere (good thing actually, some classes finally got their portion of love that they lacked for years).

**Comment by adrian-bl** [comment]
> do you have it as configurable option like "Use our own media DB" or something?

No, and offering this would not be possible as we can't support two different DB schemas at the same time (the only thing we could do is to mirror the media-db of Android (with all its bugs) and *not* scan on our own)

My plan is do to an f-droid-only release and then (after a few weeks) a play-store-beta one.


> Also, do you plan on adding all media format support to BASTP or go with something else in the 
> future? 

I'm currently using it as a cheap 'filter': Androids own tag-reader (required to get the exact song duration) is only invoked if BASTP was able to read the file: This gives us a nice speedup as the tagreader would otherwise try to parse images and videos every time the scan is running.
But this is not a final solution and i'll probably not use BASTP at all for generic tags as long as i do not run into any issues with androids own tag parser.

**Comment by adrian-bl** [comment]
Btw: i created a 'mediadb' milestone.

I'll probably close this bug after i merged it into a cleaner branch. We can then use the new milestone to keep track of the progress.

**Comment by adrian-bl** [comment]
See: https://github.com/vanilla-music/vanilla/milestone/24

**Comment by adrian-bl** [comment]
I'm going to close this issue: My WIP branch has been squashed into the new https://github.com/vanilla-music/vanilla/tree/medialibrary branch - we will track the remaining issues in the media-db milestone.

**Comment by adrian-bl** [comment]
FYI: i merged the medialibrary branch into the master, so nightly builds (see http://vanillamusic.io)  will now use our own media library.

Feel free to give them a try and report any issues you find :)
