### ISSUE TITLE
Clicking Equalizer in settings does nothing

### ISSUE THREAD

**Issue by agilob** [vanilla-music/vanilla#462]
When I go to Settings -> Audio  and click on top item Equalizer, nothing happens.

**Comment by adrian-bl** [comment]
This is most likely an issue with your firmware: What phone / android-version are you using?

We launch the equalizer using this code:
```
				final Intent effects = new Intent(AudioEffect.ACTION_DISPLAY_AUDIO_EFFECT_CONTROL_PANEL);
				effects.putExtra(AudioEffect.EXTRA_PACKAGE_NAME, context.getPackageName());
				effects.putExtra(AudioEffect.EXTRA_AUDIO_SESSION, mAudioSession);
				startActivityForResult(effects, 0);
```

So if nothing happens, your firmware does not provide the required intent.

**Comment by ToNIX-** [comment]
Or you don't have any 3rd party equalizer app installed.

**Comment by Adonai** [comment]
Can't we check for equalizer app presence before sending an intent? Like, show toast if it's not found or something?

**Comment by adrian-bl** [comment]
Yeah, some feedback would be nice here: So we should implement `onActivityResult` and check for failure to give some feedback to the user.

**Comment by agilob** [comment]
Android 4.1.2 custom LG ROM.

**Comment by adrian-bl** [comment]
> Music Player from com.simplemobiletools also offers equalizer settings - which works there.

But that's something different: The settings of 'Music Player' simply offer a set of hardcoded-audiofx effects.

What vanilla is trying to do is to open the *native* equalizer UI of your ROM (which usually has many more options) - which is quite unusual to not be installed as even AOSP provides this out-of-the-box

**Comment by adrian-bl** [comment]
Closing this as it seems to be a ROM related issue: we expect the rom to ship with the native EQ.
