### ISSUE TITLE
Vanilla Music is not presented as an option for opening audio files attached to Gmail

### ISSUE THREAD

**Issue by dpbaril** [vanilla-music/vanilla#464]
Vanilla Music is not presented as an option for opening audio files attached to Gmail . If I download the file and then try and open it from the download dialog again Vanilla Music is not presented as an option . However, if I navigate with a file manager to the download folder and open it from there, then Vanilla Music is one of the options that is presented. 

I did a system reboot and wiped the cache partition but the problem persists. 

I am running the current version of Vanilla Music from the Play Store, on Android 6.0.1, on Samsung Galaxy Note 4.

**Comment by adrian-bl** [comment]
Related to #473

**Comment by adrian-bl** [comment]
I have a somewhat working version of this in https://github.com/vanilla-music/vanilla/tree/uri-path - however: i'm not sure if i like the outcome :-/

It works quite well with drive, as it allows us to open the same URI multiple times.
Gmail, however, does not allow us to use the file descriptor more than once or do random seeks - reading the tags (or playing a song twice!) is therefore not possible, which makes the whole thing somewhat useless.

Maybe we should just implement a small popup-player to handle such media, without any tag information (like elven does - for a good reason) :-/

**Comment by Adonai** [comment]
@adrian-bl , the thing I do in such cases - `File.createTemporaryFile()`, set `deleteOnExit()`, then copy stream from fd to this temp file an use it as RAF.

How does that sound?

**Comment by adrian-bl** [comment]
That's actually a nice idea: I hacked this up in https://github.com/vanilla-music/vanilla/commit/d2d3d54aafee055de459eef0ec6d1a82de435ffe and it seems to work fine so far - thanks!

Btw: deleteOnExit() doesn't do anything for me on Android - did you ever see it working?

**Comment by adrian-bl** [comment]
https://developer.android.com/reference/java/io/File.html#deleteOnExit()

So the android documentation states that this is mostly a noop :-)

**Comment by adrian-bl** [comment]
This was fixed in 1.0.53 \o/
