### ISSUE TITLE
Search Function not working well

### ISSUE THREAD

**Issue by anaggh** [vanilla-music/vanilla#482]
Using Vanilla Music Player since the past 3+ years. Did something change in the recent versions? The search was completely functional, now it returns useless or no results.

Version: 1.0.45
Device: OnePlus X Android 6.0.1

**Comment by adrian-bl** [comment]
No, there were no changes to the search functionality.

Could you provide some examples?

**Comment by anaggh** [comment]
Hi, I managed to get it fixed. My songs were stored in a directory named `Songs` in the internal storage.
* I renamed the directory `Songs` to `Songs2`.
* Settings ->Library screen -> Filebrowser home. Changed the default `/storage/emulated/0` to `/` even though I have no root access on this device.
* Used Miscellaneous features ->SD Scanner -> START RESCAN

This not only fixed the search problem but also fixed #481 and #475 for me.
