### ISSUE TITLE
Album Artist tag support

### ISSUE THREAD

**Issue by Cody-G-G** [vanilla-music/vanilla#487]
I was wondering whether the Album Artist tag could be used for songs? Loads of albums have variable artists, and until now in my music collection I'd handle this by changing "X & Y - SongName" to "X - SongName (feat. Y)" just so I can have the whole album under a single artist, although this isn't really correct and I wish to fix this. This is what the Album Artist tag is for, which I've discovered only recently to my shame.

However, if for a certain album I have a certain Album Artist but different Artists, all the artists will appear under "Artists" although all with no tracks, except the Artist which is also the Album Artist, and that one has all the songs of the other artists as well. E.g. if I have Album Artist X with album Y, which contains tracks by artists A, B, and X, artists A and B will appear in the Artist list, but have no tracks, whereas X will also appear, and have all the right tracks in the album.

**Comment by adrian-bl** [comment]
So you would like to have an AlbumArtist Tab in the library view?

**Comment by Cody-G-G** [comment]
Yep. Or an option to make the Artist tab sort by AlbumArtist instead of Artist. GoneMAD Music Player handles it like that for example, and quite nicely too, I find.

**Comment by adrian-bl** [comment]
Ok, i'll keep this on my todo list and have a look at GoneMAD

**Comment by nlecert** [comment]
Hi.
I agree with Cody, I think a sort by AlbumArtist instead of Artist would be better for the App.
GoneMad, and also Google Play Music work that way.

Thank you for your work on this app.

**Comment by adrian-bl** [comment]
Hmm, i wonder whats the best way to implement this:

Our media library now has a concept of a 'primary artist' for every album. Maybe we should just set this to Album-Artist (if available) ?

**Comment by Cody-G-G** [comment]
@adrian-bl why not just change the "primary artist" to "artist", and add the new concept of "album artist" ? Or would the refactoring on that be a monumental task (I haven't actually had a close look at the code, but hoping to when I have some time) ?

**Comment by adrian-bl** [comment]
> why not just change the "primary artist" to "artist", and add the new concept of "album artist" 

Every song is attached to an artist_id (= according to the Artist tag in the file) and every album has a primary_artist_id set (= the 'first seen ever' artist for this album).

So just using the 'Album Artist' as the source of primary_artist_id would probably do what you want?

**Comment by Cody-G-G** [comment]
Well, would that allow for sorting by "Album Artist", in addition to "Artist"? If yes, then yeah that would do it. If it just replaces it instead, and would no longer be able to sort by "Artist", then we're back to square one... they serve different purposes and both are needed.

**Comment by adrian-bl** [comment]
I suppose the best solution is simply to implement a new Album Artist tab.

We already have the concept of 'contributors' and, in fact, already index the composer.
Indexing the Album Artist would be easy - adding the new tab will be more work but it's doable

**Comment by nlecert** [comment]
What is also doable is adding a "filter" in the sort by artist tab (or in the parameters of the app) to switch between Artist or AlbumArtist. 
It's as you wish. :-)

**Comment by adrian-bl** [comment]
PSA: The next release will index AlbumArtist tags - but the contents are currently not visible.
I'm working on this in the 'new-media-tabs' branch

**Comment by adrian-bl** [comment]
Support for this is now in HEAD and will be included in 1.0.51 (and nightly builds) via 798400d71353add597f382c811053612d5a8d675

Note that the 'Album Artist' and 'Composer' tabs are hidden by default, you must enable them in Settings -> Library View -> Tab Order.
