### ISSUE TITLE
Issue with ease of donating money to author

### ISSUE THREAD

**Issue by dodo3773** [vanilla-music/vanilla#489]
I think it would be easier to donate money to the author of this project if there was a donation system setup on google play. Similar to the way the author of open camera does it. See here: https://play.google.com/store/apps/details?id=harman.mark.donation&hl=en

Unsure of how much it costs to publish apps etc... so not completely sure if this makes sense for the author.

**Comment by Adonai** [comment]
Donation system means dependency on non-free services, maybe author is avoiding that ;)
I'm up for split fdroid/gplay gradle flavor system, however.

**Comment by dodo3773** [comment]
I'm not sure that it is an in-app purchase. It's a completely separate app. You install it for 24 hours and then just remove it. It's like a completely voluntary type of thing.

**Comment by adrian-bl** [comment]
We are not in a need for donations as we do not rellay have any expensive 'infrastructure' cost (~30.- p.y.).

So i dont see the point in integrating inapp purchases code. But maybe we could add the bitcoin address to the about page.

**Comment by dodo3773** [comment]
Understood. Closing issue.
