### ISSUE TITLE
Import dependencies using Gradle

### ISSUE THREAD

**Issue by veyndan** [vanilla-music/vanilla#491]
[Some classes](https://github.com/vanilla-music/vanilla/tree/master/src/android/support) are just copied over from the support library. Surely it would be better to import them using Gradle and use Proguard to remove redundant code from the libraries than to manually copy over the classes required.

**Comment by adrian-bl** [comment]
Only iosched/tabs is a 1:1 copy, the viewpager contains modifications.

However: we also support ant builds (i am not using gradle myself) and i don't see how this would work with ant.

**Comment by veyndan** [comment]
OK that makes sense, I don't have much experience with ant. Any reason to not migrate over to Gradle, considering this is the build tool encouraged by the Android platform team and is used on most Android projects.

**Comment by adrian-bl** [comment]
> Any reason to not migrate over to Gradle

I'm happy with ant and i don't see a technical reason to switch to some other build system just because its newer.
