### ISSUE TITLE
Feature request: Randomize the order of songs played instead of adding a random song at the end of a playlist.

### ISSUE THREAD

**Issue by cobaltdr** [vanilla-music/vanilla#493]
Ideally, I would like the player to randomise the order in which it plays the songs inside a playlist, and not add songs to it.

At the moment, it will play the playlist in the order files were added to the playlist then when it reaches the end of that list, will add files from the random library queue, which could play a heavy metal song in my classical mood music playlist. This is counter-intuitive. I wonder if it would be possible to add a setting to alter this behaviour.

**Comment by adrian-bl** [comment]
> At the moment, it will play the playlist in the order files were added to the playlist then when it reaches the end of that list, will add files from the random library queue

You seem to confuse random & shuffle mode: This is only true if random mode is enabled (= the dice symbol on the right). Random mode makes sure that the queue never gets empty by appending random songs.

What you are looking for is the shuffle mode, controlled by the button on the left side.

**Comment by cobaltdr** [comment]
Thanks for the reply. The lack of documentation stumped me. You are right and I apologise. Shuffle does do the trick.

I was playing with it however, and would I be right in saying that if you pull up the queue, however, in spite of having shuffle enabled it will just play down the queue in the order files are queued, rather than shuffling them in that very specific scenario?
