### ISSUE TITLE
Feature request: cast support

### ISSUE THREAD

**Issue by Jucgshu** [vanilla-music/vanilla#494]
Hi guys,

I just bought a $40 Chromecast to my wife, mostly for Netflix streaming. Some other apps suppport this little device as well. 

Would it be an acceptable feature to consider ? Being able to stream music directly from Vanilla ? As of now, it's possible to stream the entire screen of the phone through the Android feature, but it's not Vanilla specific.

Maybe this could be a starter: https://developers.google.com/cast/docs/audio

Anyway, thanks for this wonderful piece of software of yours !

**Comment by adrian-bl** [comment]
Sorry, but this won't happen as chromecast support would force us to include the (closed source) play services

**Comment by Jucgshu** [comment]
Yup, I should have seen this one.

Thanks for your answer ;-)

**Comment by TorokLev** [comment]
I wonder if it is still true since pychromecast is not using any.

**Comment by PanderMusubi** [comment]
For sure, there are some open cast libraries. Who has a shortlist of which could be used by this app?

**Comment by TorokLev** [comment]
Pychromecast for python developers

And the rest of what I have found is for java script and many of them are already dying out.

https://github.com/googlecast/
https://github.com/xat/castnow
https://github.com/thibauts/node-castv2-client

For c++
https://github.com/eriklax/c8tsender
