### ISSUE TITLE
"Volume during notifications" doesn't work properly

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#495]
I'm the biggest fan of the "lower playback volume during notification sounds", but it seems to be bugged at the moment :
I have set the volume at 50%, but it seems that this reduction is applied to the *notification* volume instead (or in addition ? Not quite sure…) to the *music* volume, hence nullifying the usefulness of the feature.

Vanilla Music 1.0.46 (F-Droid version)

**Comment by adrian-bl** [comment]
This works for me: what android version are you using (custom rom?)

**Comment by breversa** [comment]
My bad, I forgot that :
CyanogenMod 13.1 on LG G4

**Comment by adrian-bl** [comment]
So it *does* have some effect? What happens if you set it to 0% ?

**Comment by breversa** [comment]
If I set volume to 0%, playback is totally muted during the barely-inaudible notification sound. So that *does* work.

EDIT :
I cleared Vanilla Music data and set it up again… and everything seems fine again. Weird, but oh well.
Thanks anyway ! :-)
