### ISSUE TITLE
Playback doesn't pause when phone rings or during a call

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#496]
Music playback doesn't stop when I receive or make a call.

Vanilla Music 1.0.46 (F-Droid version)

**Comment by adrian-bl** [comment]
This also works for me on CM13 (just tested it by calling a number) and is likely related to your other bug report

**Comment by breversa** [comment]
That's weird : I just tested again, and indeed, no problem. But I cleared the app's data beforehand, so maybe that's why…

**Comment by adrian-bl** [comment]
That's unlikely: Android is supposed to send us a signal when we are supposed to stop playing - if we don't stop, then the signal didn't reach us which means that the OS failed to send it or that some other app 'swallowed' it - but this is unlikely to be an issue on 'our' side
