### ISSUE TITLE
Dont show Artits Info

### ISSUE THREAD

**Issue by arkhan** [vanilla-music/vanilla#497]
Hello, 

In the last versions of vanilla, in the library does not recognize the artist tag, and everything comes out as "<unknown\>", but in other players as vlc recognizes all the information of the track.

![photo_2017-01-03_11-15-50](https://cloud.githubusercontent.com/assets/3141865/21614303/ec5e5d10-d1a6-11e6-9c97-081368af7816.jpg)

Thanks

**Comment by adrian-bl** [comment]
Are you running a stable release or a nightly build?

**Comment by arkhan** [comment]
I'm running the lastest version available on F-Droid

**Comment by adrian-bl** [comment]
That is very odd - there weren't any changes related to this part of the code between 1.0.45 and 1.0.46 (See: https://github.com/vanilla-music/vanilla/compare/1.0.45...1.0.46)

Are there any artists listed in the Artists-tab?

Are other players, such as https://f-droid.org/repository/browse/?fdfilter=ody&fdid=org.gateshipone.odyssey are able to display the artists? (Note that VLC is special as it uses its own tag reader while we are, like odyssey, using the android media database (but this will change in the next release :-) )

**Comment by arkhan** [comment]
With odyssey I get the same result

![ddff5584e61d6fded6c4aa7b831d463a](https://cloud.githubusercontent.com/assets/3141865/21621533/72776282-d1c7-11e6-86ef-e3d809788590.jpeg)

**Comment by adrian-bl** [comment]
So then your media database somehow became corrupted.

You could try to reboot your phone (this sometimes triggers an update) or - in the worst case - clear the storage of the 'Media Storage' app. (Note that this will wipe your playlists and reset your ringtones)

OR: if you are somewhat adventerious - you could give the nightly build of Vanilla Music a try:

http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk
This version does *not* use the buggy media storage but uses its own tag reader. (Note that you can install it alongside the normal vanilla music build)

**Comment by arkhan** [comment]
Vanilla Nightly works fine

![cd52d4c2428ec03019c78a51ab583045](https://cloud.githubusercontent.com/assets/3141865/21622874/b27997f0-d1cd-11e6-8de7-56e1d8951961.jpeg)

**Comment by adrian-bl** [comment]
Ok, nice: so our own tag reader works ;-)

So as i mentioned before: The reason why the stable version of Vanilla Music doesn't show the correct information is due to a corruption in your (well: Androids) media library.

If a reboot doesn't fix the issue, you only have two options (apart from keep using the nightly build)

* You could try to move your music folders via MTP to some different directory - this should trigger a rescan which hopefully picks up the tags correctly
* If this also doesn't help, the only option left is to wipe the media database (as described in my previous comment)

**Comment by arkhan** [comment]
I try the 2 options before installing the nightly version of vanilla, but it did not work,
Even delete everything and returned to copy the songs to the device, obtaining the same result.

**Comment by adrian-bl** [comment]
Ok, that's *very* strange - haven't seen this yet on any device.
Did you reboot the device after cleaning the media store data in the settings?

If you have root on your phone, you could try (as a very last resort) to delete ```/data/data/com.android.providers.media/databases/external.db*``` & reboot.

This will remove the complete media database which android should re-create on the next boot (hopefully :-))

**Comment by arkhan** [comment]
I get the same result, only works with Vanilla Nightly and VLC.

I'm thinking that the problem is in ROM (DirtyUniconrs v11 - Android 7.1.1)

**Comment by adrian-bl** [comment]
Yeah, there seems to be something very wrong with the media scanner in your ROM.
Unfortunately, there is nothing we can do, as we are just a consumer of the faulty database.

But i'm going to close this as Vanilla Music 1.0.48 should soon show up on f-droid which will use the native media db (as the nightly does), so it will 'fix' your issue automatically :-)
