### ISSUE TITLE
can't ignore media files found in root dirs

### ISSUE THREAD

**Issue by nixingizgood** [vanilla-music/vanilla#499]
My phone comes installed with undeletable music files in some root directories. Therefore I can't shuffle through my library without eventually running into these undesirable songs. I can't get rid of them without rooting this device which I don't want to do

Can you add a list of directories to ignore to preferences? (In my case I would add `/system/media/Pre-loaded`)

Thank you

**Comment by adrian-bl** [comment]
Dup of #22
