### ISSUE TITLE
Horizontically scroll long names of tracks etc

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#503]
(Extremely) long track names in the player view fall partly outside of the screen and are therefore not completely visible.

Only when this occers, and this depends of the device orientation too, after x seconds slowly horizontically scroll the name to the left and leave it for y seconds at the end. Then jump back in a hard way, no scrolling, abd repeat this way of displaying that name.

Alternatively, use a default solution available in the frameworks used.

**Comment by adrian-bl** [comment]
Do you know any track (musicbrainz link is fine) which triggers this issue?

**Comment by PanderMusubi** [comment]
At least the first track of https://www.discogs.com/Type-O-Negative-Slow-Deep-And-Hard/master/27492 triggers this.

**Comment by adrian-bl** [comment]
Well, but that's an album with quite special titles, such as this: https://musicbrainz.org/release/3e45346b-a869-3652-a741-30e1432ceec3 (which i have on my phone and do not have any trouble to identify the titles).

I feel like scrolling titles in a listview are a bad idea as they are a distraction. Adding an option to display the full title on longpress (maybe in #506) is IMO a much better option.
