### ISSUE TITLE
Vanilla Music hesitates sometimes

### ISSUE THREAD

**Issue by teod0r** [vanilla-music/vanilla#505]
Since several latest versions it hesitates for half of a second when pressing "Play" button, when switching between applications and sometimes without a reason

**Comment by adrian-bl** [comment]
That's unlikely to be an issue on your side - but could you provide a logcat?

Most likely the mediaserver on your phone got stuck - a reboot of the OS usually helps

**Comment by teod0r** [comment]
posibly it dos. reboot actualy helped.
