### ISSUE TITLE
Do not index Ringtones

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#507]
The media scanner should not index ringtones - we should probably avoid the whole ringtones folder during any scan type

**Comment by mase76** [comment]
I suggest either to scan /storage/emulated/0/music and /storage/sdcard1/music only, or let the user configure the folder(s). What is the current behaviour? I noticed an option to scan the whole filesystem. What is scanned when unchecked this?

**Comment by adrian-bl** [comment]
> /storage/emulated/0/music

Wouldn't work for me ;-) i store my music at /storage/emulated/0/SyncThing/music :-)

> What is the current behaviour?

We are currently slurping in the whole native (= androids) media database and will scan any 'volume' reported by Android on a full scan.

Making the scanned paths a config option is definitely on the todo list: see good-old #22

**Comment by adrian-bl** [comment]
Implemented in https://github.com/vanilla-music/vanilla/commit/d2c54eeb2a395d74cdd2d02ca277d4ad37a0ad1a

**Comment by Allanitomwesh** [comment]
Hi I looked into it and the hangouts tones are in /android/media/com.google android.talk

**Comment by adrian-bl** [comment]
The 'Android' directory is in our internal blacklist - so these files should not get indexed (older versions might have indexed them, so a full DB rebuild might be required)

**Comment by Allanitomwesh** [comment]
Flush seems to have fixed it thanks
