### ISSUE TITLE
Issues with apply plugin: 'com.android.application'

### ISSUE THREAD

**Issue by Technologx** [vanilla-music/vanilla#508]
I keep running into this issue when I try to build the project.

````
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/Technologx/Desktop/Android Projects/BlazePlayer/build.gradle' line: 16

* What went wrong:
A problem occurred evaluating root project 'BlazePlayer'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.10 is required. Current version is 3.3. If using the gradle wrapper, try editing the distributionUrl in /Users/Technologx/Desktop/Android Projects/BlazePlayer/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.254 secs
````

**Comment by Adonai** [comment]
What changes have you done to the project itself?

**Comment by Technologx** [comment]
I only changed the package name along with the imports in every single java file

**Comment by Adonai** [comment]
Try to bump plugin versions in `build.gradle` in that way:

```
    ... line 7:
    classpath 'com.android.tools.build:gradle:2.3.0-beta2'
    ... line 25:
    buildToolsVersion '25.0.0'
    ...

**Comment by adrian-bl** [comment]
Please keep in mind that Vanilla Music is licensed under the terms of the GPLv3 and you are bound to release the sourcecode of your modified version.

I also KINDLY ask you to NOT upload an advertisement-infested 'fork' of vanilla music to the play store. (I've seen in your github history that you asked for help to do so in some other project).

Doing so would be a very shady thing as you would rip off us and your users.

**Comment by Technologx** [comment]
I don't plan on it I deleted this project directory already and found another music player that I like better.
