### ISSUE TITLE
Doesn't read all folder.jpg

### ISSUE THREAD

**Issue by mase76** [vanilla-music/vanilla#512]
Hi!
My covers are saved as folder.jpg in every album folder. But vanilla does not read all
of them. Some covers are not recognized.

**Comment by kirbyfan64** [comment]
Did you try rebooting your phone?

**Comment by mase76** [comment]
Yes, I did.

**Comment by adrian-bl** [comment]
How many files does the folder contain? We only search up to 50 files.

Do you (maybe) have the songs of a single album spread across multiple folders?
Covers use the album as a cache key and the first found item wins. (Which might not have a cover)

**Comment by mase76** [comment]
I have 100 music files and 1 front.jpg in some folders. Some are read, some are not.
I have a lot of top 100 folders. And nothing spread.

**Comment by adrian-bl** [comment]
Ok, so this can very likely be the root cause: The read order of the files is random (= whatever the filesystem gives to us).

To have some real world data: What's your largest folder? Would increasing the limit to 150 be ok?

**Comment by mase76** [comment]
The largest is 100 music files plus one cover. So 150 would be enough. But why a limit at all?

**Comment by adrian-bl** [comment]
Because we do this on every cache-miss and IO can be quite expensive on (low-end) Android devices.
I just want to have failsafe limit so that we are not spending multiple icons searching for an icon.

I increased it to 150 in 055ed2c05382908cc8d79e7ca48f92c5c0eef926

**Comment by adrian-bl** [comment]
I also triggered a nightly build (http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk) which already includes this change

**Comment by mase76** [comment]
Ok, thx!
I think we can close this issue.

**Comment by adrian-bl** [comment]
Ok, feel free to re-open the isse if the problem is still there

**Comment by mase76** [comment]
I will test with the next release on f-droid...
