### ISSUE TITLE
Add an "Open Folder" Button in the playback screen

### ISSUE THREAD

**Issue by david-sawatzke** [vanilla-music/vanilla#513]
Sometimes (for example when aggregating related songs through the folder structure) it's useful to go to the directory of the currently playing song.
Edit: I'm currently working on a PR

**Comment by adrian-bl** [comment]
implemented in https://github.com/vanilla-music/vanilla/commit/ffe0fe55dfa0206273de907b2b2db9f6cf25fb44

**Comment by adrian-bl** [comment]
oh no wait! We don't implement 'open by folder' :-) -> Reopening it!

**Comment by adrian-bl** [comment]
Implemented in https://github.com/vanilla-music/vanilla/commit/55a5ff6aa00d0ec477b37e925ab2fe97fbff3615
