### ISSUE TITLE
Play time statistic seems to overflow

### ISSUE THREAD

**Issue by david-sawatzke** [vanilla-music/vanilla#514]
![screenshot_20170118-190724](https://cloud.githubusercontent.com/assets/11035569/22076878/3a956958-ddb2-11e6-94dd-5d77545178cc.png)
According to clementine, the total play time is around 600 hours

**Comment by adrian-bl** [comment]
Oh, good catch :-) This really overflows the MAX_INT (as the duration is stored in 'ms' internally)

I fixed this in 74f921e3a132941b3c31d39bcfd5ad9e7f03e165, which also uses String.format() to display the playtime.

Btw: How is the performance with such a large library? Do you have any issues?

**Comment by david-sawatzke** [comment]
Before the media database update it took a while to start playback after hitting "Play all" (~5s), but now it's almost instantaneous. Other than that I didn't notice anything.

**Comment by adrian-bl** [comment]
ok, thanks for the feedback, that's good to hear :-)

Closing this as the fix will be included in the next release.
