### ISSUE TITLE
Umlaut-Characters messed up

### ISSUE THREAD

**Issue by franco-bez** [vanilla-music/vanilla#515]
I'm not sure when this bug got introduced, I just noticed it with the latest Version 1.0.47.

Having special Characters like Umlaut or accented Characters in the ID3 Tags gives me Chinese Glyphs on the display. See screenshot

Ciao,
  Franco

![screenshot_2017-01-18-20-25-12](https://cloud.githubusercontent.com/assets/4195055/22079871/a05b56e8-ddbd-11e6-8590-8f3751d0b3ce.png)

**Comment by franco-bez** [comment]
I forgot to mention some details
Android Version is 4.4
The Artists should read "Bläck Föss" and "Hans Söllner"  and the last one is "Héroes Del Silencio"

**Comment by adrian-bl** [comment]
This was *most likely* already the case in earlier versions: Android has a bad habit of guessing character encodings of MP3 files.

Could you send me one of these files to adrian@blinkenlights.ch ?

**Comment by franco-bez** [comment]
Hi Adrian,
Grüezi in die Schweiz aus dem bayerischen Allgäu.
Einen der Söllner Titel habe ich angehängt.
Ciao, 
 Franco


Am 18. Januar 2017 20:58:24 MEZ schrieb Adrian Ulrich <notifications@github.com>:
>This was *most likely* already the case in earlier versions: Android
>has a bad habit of guessing character encodings of MP3 files.
>
>Could you send me one of these files to adrian@blinkenlights.ch ?
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vanilla-music/vanilla/issues/515#issuecomment-273583888

-- 
Diese Nachricht wurde von meinem Android-Telefon mit K-9 Mail gesendet.

**Comment by adrian-bl** [comment]
Ok, thanks: i'll try to have a look at it in the next few days

**Comment by PanderMusubi** [comment]
You could on a dekstop or laptop with e.g. Linux, copy the file to a new file and enter all the characters manually. Hopefully all will be Unicode UTF-8 and the problem will disappear in Vanilla Music.

**Comment by yaymeh** [comment]
Some $(head -n1 $file | hexdump -C) for comparison:

Here's an UTF-8 example with everything displayed correctly in vanilla music...
music title: (Don’t Fear) The Reaper
vanilla music artist: Blue Öyster Cult
```
00000000  49 44 33 04 00 00 00 06  1f 76 54 49 54 32 00 00  |ID3......vTIT2..|
00000010  00 1b 00 00 03 28 44 6f  6e e2 80 99 74 20 46 65  |.....(Don...t Fe|
00000020  61 72 29 20 54 68 65 20  52 65 61 70 65 72 00 54  |ar) The Reaper.T|
00000030  50 45 31 00 00 00 13 00  00 03 42 6c 75 65 20 c3  |PE1.......Blue .|
00000040  96 79 73 74 65 72 20 43  75 6c 74 00 54 52 43 4b  |.yster Cult.TRCK|
```

Next, an UTF-16 example with working Umlauts / broken Apostroph...
vanilla music title: (Donâ€™t Fear) The Reaper
vanilla music artist: Blue Öyster Cult
```
00000000  49 44 33 04 00 00 00 06  1f 76 54 49 54 32 00 00  |ID3......vTIT2..|
00000010  00 33 00 00 01 ff fe 28  00 44 00 6f 00 6e 00 19  |.3.....(.D.o.n..|
00000020  20 74 00 20 00 46 00 65  00 61 00 72 00 29 00 20  | t. .F.e.a.r.). |
00000030  00 54 00 68 00 65 00 20  00 52 00 65 00 61 00 70  |.T.h.e. .R.e.a.p|
00000040  00 65 00 72 00 00 00 54  50 45 31 00 00 00 25 00  |.e.r...TPE1...%.|
00000050  00 01 ff fe 42 00 6c 00  75 00 65 00 20 00 d6 00  |....B.l.u.e. ...|
00000060  79 00 73 00 74 00 65 00  72 00 20 00 43 00 75 00  |y.s.t.e.r. .C.u.|
00000070  6c 00 74 00 00 00 54 52  43 4b 00 00 00 05 00 00  |l.t...TRCK......|
```
And then there is ISO-8859-1...
vanilla music title: (Don?t Fear) The Reaper
vanilla music artist: Blue Öyster Cult
```
00000000  49 44 33 04 00 00 00 06  1f 76 54 49 54 32 00 00  |ID3......vTIT2..|
00000010  00 19 00 00 00 28 44 6f  6e 3f 74 20 46 65 61 72  |.....(Don?t Fear|
00000020  29 20 54 68 65 20 52 65  61 70 65 72 00 54 50 45  |) The Reaper.TPE|
00000030  31 00 00 00 12 00 00 00  42 6c 75 65 20 d6 79 73  |1.......Blue .ys|
00000040  74 65 72 20 43 75 6c 74  00 54 52 43 4b 00 00 00  |ter Cult.TRCK...|
```

**Comment by PanderMusubi** [comment]
Off-topic but hilarious that you choose (Don’t Fear) The Reaper from Blue Öyster Cult :laughing:

**Comment by franco-bez** [comment]
Hi Pander and yaymeh,
yes vanilla-music handles unicode correctly.

If I had the time to convert several thousand mp3 files I could actually work around the problem.

I tried the tool mid3iconv on an album and the resulting files are displayed correctly in vanilla-music.
Here's the howto:
[http://ask.xmodulo.com/convert-mp3-id3-tag-encodings-linux.html](http://ask.xmodulo.com/convert-mp3-id3-tag-encodings-linux.html)

Ciao,
  Franco

**Comment by adrian-bl** [comment]
@franco-bez 

Thanks for the sample file you sent my via e-mail: I tested it on 3 devices:

Nexus 5 with CM14: Works
Moto Defy, Stock Android 5: Works
HTC One X, AOSP 4.2 : Umlauts are 'okay' - but the album is padded with about 10 white spaces for somme reason.

The fact that a newer Android version (4.4) works worse than 4.2 is pretty strange - are you running a stock version (if yes: which vendor) or a custom ROM?

Do the affected files show up correctly in some other (eg. stock) music player?

**Comment by franco-bez** [comment]
It is an Acer Phone.
VLC shows the fules correctly.
See screenshots.
![screenshot_2017-01-21-15-08-17](https://cloud.githubusercontent.com/assets/4195055/22174982/fc96aa18-dfeb-11e6-9195-a8a0efdcc3ec.png)
![screenshot_2017-01-21-15-06-59](https://cloud.githubusercontent.com/assets/4195055/22174984/027e0174-dfec-11e6-9d21-6d57da4698b3.png)
![screenshot_2017-01-21-15-05-48](https://cloud.githubusercontent.com/assets/4195055/22174987/0a2df208-dfec-11e6-8835-e7e05b9e5826.png)

**Comment by adrian-bl** [comment]
Vlc uses ffmpeg, we are using androids own library for mp3.

What does the stock music player show?

**Comment by franco-bez** [comment]
You mean this Google Play Music?
Looks good.
![screenshot_2017-01-21-23-22-05](https://cloud.githubusercontent.com/assets/4195055/22178208/d4f6a054-e030-11e6-9e82-2f44765a0b7c.png)
![screenshot_2017-01-21-23-21-53](https://cloud.githubusercontent.com/assets/4195055/22178210/dc7aabd6-e030-11e6-8799-005fceb491a1.png)

**Comment by adrian-bl** [comment]
Play music also does its own parsing. Try something like https://f-droid.org/forums/topic/odyssey-music-player/

**Comment by franco-bez** [comment]
Hello Adrian,

Google Play Store tells me that Odyssey is not compatible with any of my
devices.

Strange also in FDROID I cannot install any Odyssey Musicplayer.

Do you have any other idea ?

Ciao,

  Franco


Am 29.01.2017 um 16:05 schrieb Adrian Ulrich:

**Comment by franco-bez** [comment]
Now I tried Music "The Stock Audio Player"

https://f-droid.org/repository/browse/?fdfilter=music&fdid=com.android.music&fdpage=2

Looks good as well.

![screenshot_2017-01-29-19-36-36](https://cloud.githubusercontent.com/assets/4195055/22406892/ef4ee9da-e65b-11e6-804b-cf80ecf48104.png)
![screenshot_2017-01-29-19-36-57](https://cloud.githubusercontent.com/assets/4195055/22406894/f1d653a0-e65b-11e6-86ec-283d5c1c9f2d.png)

**Comment by adrian-bl** [comment]
Thats very strange: It seems like your android release does some magic *after* reading the tags (but before putting them into the database).

I think the best way to fix this is to just not use androids own ID3v2 tag reader - and the latest nightly of Vanilla Music (See: http://vanillamusic.io/#nightly-builds - you can install it without uninstalling the normal release as the nightly is a 'different' app) has an option to do so:

Please try to enable Settings > Media Library > Always use builtin tagreader and wait until the rescan finished.

After this, your library should hopefully be OK.

**Comment by franco-bez** [comment]
Hi Adrian,
I tried the nightly and it's party a success.
However with some of the files the situation remains unchanged.
![screenshot_2017-02-04-13-59-18](https://cloud.githubusercontent.com/assets/4195055/22618717/2d005854-eae4-11e6-9fec-fa9aa118d972.png)
![screenshot_2017-02-04-13-59-37](https://cloud.githubusercontent.com/assets/4195055/22618718/2d0348b6-eae4-11e6-9b1c-cfb73f1fa1fc.png)
![screenshot_2017-02-04-14-00-10](https://cloud.githubusercontent.com/assets/4195055/22618720/2d04d9b0-eae4-11e6-8596-23ac46208e96.png)
![screenshot_2017-02-04-14-00-58](https://cloud.githubusercontent.com/assets/4195055/22618719/2d037980-eae4-11e6-98ea-0fff70bf7cb9.png)
![screenshot_2017-02-04-14-01-28](https://cloud.githubusercontent.com/assets/4195055/22618722/2d074c90-eae4-11e6-8229-82c882848f84.png)

This screenshot is "Music - The Stock Player"
![screenshot_2017-02-04-14-11-41](https://cloud.githubusercontent.com/assets/4195055/22618721/2d075d48-eae4-11e6-97c8-6616496eacb8.png)

**Comment by adrian-bl** [comment]
ID3 encodings are a mess :-/

Can you send me the two shown files to adrian@blinkenlights.ch?

**Comment by adrian-bl** [comment]
Thanks for the sample files: These files do not have ID3v2 tags: They are only tagged with ID3v1 which our internal tag reader does not support (So we fall back to Androids own, faulty tag reader)

I'd strongly recommend to simple re-tag these files with ID3v2 - ID3v1 should have died a long time ago.

But i opened a bug about the ID3v1 tags at https://github.com/adrian-bl/bastp/issues/4 (the repo of the tagreader) and going to close the bug here: Once the issue in 'Bastp' has been fixed, it will also automatically be fixed in Vanilla Music.

**Comment by franco-bez** [comment]
I just tried the latest nightly build and indeed the bug is fixed :-)
I just had to enable "always use builtin tag reader".
Thanks a lot :-)
Ciao,
  Franco

**Comment by adrian-bl** [comment]
Great, thanks for the feedback!

Also note that 1.0.49 should show up on f-droid very soon
