### ISSUE TITLE
queue progress disappeared

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#516]
The queue `x/y` indicator has been removed in the latest release. Could it be added back? (Can do it myself when I'm not on a phone if you'd like.)

**Comment by adrian-bl** [comment]
You mean the track/total display in the right upper corner?

I didnt do any changes to it, it should still be there. Are you sure that you are not in random mode? (= dice icon)

**Comment by mathstuf** [comment]
Ah, that did get changed at some point locally. Though it was playing in order (this is right after the upgrade) and loading a playlist, so maybe some weird state due to the upgrade process and database stuff?

**Comment by adrian-bl** [comment]
No, i didnt touch this part of the code recently

**Comment by mathstuf** [comment]
OK, I'm not too worried about it; now that I know what caused it, I'm not sure what assumptions I was working on before, so this probably isn't an issue. I'll keep an eye out for it though. Thanks.
