### ISSUE TITLE
Cannot play directory since 1.0.47

### ISSUE THREAD

**Issue by Stevko-sk** [vanilla-music/vanilla#518]
On Files tab when I select a folder (hold finger on it) and then choose Play in the menu that pops up, I get 0 tracks playing.

Later I found out that after scan (this seems to be a new thing which took forever) some folders do play and some do not.

**Comment by adrian-bl** [comment]
This is most likely related to #517 

Do the 'not playing files' have something in common? eg: no tags or all of them are M4A / FLAC / Whatever files?

**Comment by adrian-bl** [comment]
Closing this as a duplicate of #517
