### ISSUE TITLE
"Load artwork from Android" stopped working after 1.0.47 update

### ISSUE THREAD

**Issue by yaymeh** [vanilla-music/vanilla#519]
"Load artwork from Android" stopped working after 1.0.47 update - all embedded cover art appears missing. 
I didn't find any related error messages (but I can check logcat again if someone tells me what to look for). 

"Load cover art from folder" still works fine (even with the same jpg: I extracted the cover art from a few mp3 files and dumped them in "cover.jpg" in the same directory - without re-encoding - they work fine).

( Embedded album art still works in stock music player / other players. Also tried deleting the "cover art cache" + rebooting: the stock player re-fetched all covers just fine, too.)

**Comment by adrian-bl** [comment]
This works just fine for me: I just tested ith with a FLAC file on Android 7

Could you send me a test file to adrian@blinkenlights.ch ?

**Comment by yaymeh** [comment]
Tested with lots of different files. And these files:
[aaatest_mp3_flac.zip](https://github.com/vanilla-music/vanilla/files/721197/aaatest_mp3_flac.zip)
Cover art for both work in stock player and file manager and also in vanilla player 1.0.46

I tried around with "CoverCache.java" a bit... the cursor.moveToFirst here always fails:
[CoverCache.java#L454](https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/CoverCache.java#L454)

After replacing that whole album id lookup with:
```
Random r = new Random();
albumId = r.nextInt(100);
```
...all of my songs have pretty pictures again, just not the right ones :D

**Comment by adrian-bl** [comment]
Oh! So the lookup by path fails! Thats unexpected.

Do you have root on your phone?
If yes, it would be interesting which path (_data column) androids media db uses for songs (/data/data/com.android.providers.media/databases/external.db)

**Comment by yaymeh** [comment]
If I echo + use the string from that song.path variable manually on the db with sqlite, it appears to work fine:

`sqlite> select album_id from audio where _data = '/storage/sdcard/music/aaatest.mp3';`


returns 1171 and

`sqlite> select _data from album_art where album_id = "1171";`

/storage/emulated/0/Android/data/com.android.providers.media/albumthumbs/1485006909469

Is that what you meant?

**Comment by adrian-bl** [comment]
Ok, thats *very* strange 🤔

What does

Log.v("VanillaMusic", contentUri.toString());

show?

I suppose all your media is on an external sdcard, correct? What version of Android are you running?

**Comment by yaymeh** [comment]
Oh, yes, looks like that's the problem!
contentUri said "content://media/internal/audio/media"

So I tried:
`Uri contentUri = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI;`
With that, album art works again on external sd-card AND internal both.

Using a CM13 phone, but tested the problem / workaround on another S5 with stock samsung rom too (same results). They both appear to be using "EXTERNAL_CONTENT" for sd card AND internal memory - no idea what "internal" is for, android is weird. Maybe Samsung is weirder.

**Comment by adrian-bl** [comment]
Thats odd: 'internal' is (to my knowledge) used for stock media data (eg: pre installed ringtones), no idea why this uri is returned.

Thanks for your help: i'll commit a fix for this tomorrow when i'm back home.

**Comment by adrian-bl** [comment]
Hmm.. your phone seems to be strange: I tested this on two devices with external SD-Cards and both returned the correct (external) URI. (One of them running Stock 5.x, one CM13)

Anyway: I fixed  it in https://github.com/vanilla-music/vanilla/commit/2c5abc352c9fc6ccda50321e6666ad936bf16e04 to always use EXTERNAL_CONTENT_URI as the cover code is very unlikely to ever lookup an 'internal' (aka. ringtone) cover

**Comment by yaymeh** [comment]
Oh... the "strange" thing about my phone could be that the sd card is ext4? I sanitized my post too much above: The actual path of the test file was "/storage/[UUID-of-the-sd-card]/music/aaatest.mp3" ( my log sanitizer regex-ed it to "/storage/sdcard/music/aaatest.mp3" ).

And that's relevant because:
MediaStore.Audio.Media.getContentUriForPath + others (https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/provider/MediaStore.java)
seem to use getExternalStorageDirectory() and/or System.getenv("SECONDARY_STORAGE") depending on version / ROM. Both aren't very well documented and neither one returns my sd card path. Upstream looks kind of fishy ... from what I can tell, it can not be relied upon that getExternalStorageDirectory works (might affect: ext4 sd cards; some samsung phones; android versions older than 2014; maybe more. ). It might not even be guaranteed that "external" files really end up in "external", but I don't understand the upstream code well enough to tell that for sure. 

Anyway, I couldn't figure out what / who is responsible for populating those environment variables correctly... probably noone + nothing. Which might be the problem. I haven't submitted a bug report upstream for this because I couldn't figure out where ( or even just what exactly the bug is ).

**Comment by adrian-bl** [comment]
> Oh... the "strange" thing about my phone could be that the sd card is ext4?

Yes, that would be an unusual setup :-)

> Both aren't very well documented and neither one returns my sd card path.

But what does getExternalStorageDirectory() return on your ROM? Note that the code uses 'startsWith()', so i'd expect it to return something like '/storage'

> Anyway, I couldn't figure out what / who is responsible for populating those environment variables 
> correctly...

They are set by the vendor inits script (/init.*)

**Comment by yaymeh** [comment]
getExternalStorageDirectory() returns "/storage/emulated/0" with CM13. 
AFAIR the old samsung stock returned "/storage/sdcard0" (with the external sd card being "/storage/sdcard1") or something like that. Either way, in both cases it was directly the internal sd card.
