### ISSUE TITLE
[Feature request] Add more lockscreen controls

### ISSUE THREAD

**Issue by GoodDayWorld** [vanilla-music/vanilla#521]
This is a very nice app! It would be nice if you could add additional lockscreen controls like shuffle and going back a track.

Could be configurable.

**Comment by adrian-bl** [comment]
This is not possible: the lockscreen controls are provided by android and we have no control over them.

**Comment by GoodDayWorld** [comment]
Interesting. How can other apps have this feature? The music player in LineageOS does this.

**Comment by adrian-bl** [comment]
> you would need to write a custom lock screen widget for that!

If someone would like a lockscreen widget i'd be glad to include it. But i won't due it myself (due to lack of time and interest)
