### ISSUE TITLE
Album Track order not correct (after update to 1.0.47(?))

### ISSUE THREAD

**Issue by GitHorst** [vanilla-music/vanilla#522]
I think this only happened for me after the last update to 1.0.47 (that is to say, it was working correctly at some point before. And there was quite a long library (re)scan after the update)
Now when I select an album, it will show me the tracks in the wrong order. In the "sort by" settings the option "Artist, album, track number" is selected. And as I said, everything was working fine before, that is also all the tags are set correctly.
A manual rescan of the media library (from the vanilla music settings) did not help and I don't dare to check the "Flush media database" box, as it says "Dangerzone!" ;)
I already tried whether a reboot would help. Then, after starting Vanilla-Music, it briefly scanned some folders from my SD card again (but only a few) but the issue is still the same (also for the folders it just rescanned).
Is there anything else I can try? Or do you need some other kind of information? (oh, right -- Android 5.1)
Thanks a lot for your time! :)

**Comment by adrian-bl** [comment]
> Now when I select an album, it will show me the tracks in the wrong order. In the "sort by" settings the 
> option "Artist, album, track number" is selected. And as I said, everything was working fine before, that 
> is also all the tags are set correctly.

Are you sure that the files are correctly tagged?

Please try this:

* Play such a wrongly ordered album
* In the playback screen, long press on the 'Title / Album' (above the progress bar) to display additional information
* -> What does the 'track' row display? Does it show a number and if yes: is it correct?

**Comment by GitHorst** [comment]
hey, thanks for getting back to this so quickly! :)
the 'track' row itself is empty. next to the title it says, e.g., 1/12. (but i guess this refers to the queue?)
when i select the albums in the stock "music" player of android, the order is correct. also on my desktop, using clementine player, it is correct. and finally, it was correct with your player before :)

i noted that in the additional information list, there is also no replay gain info, although all my albums were adjusted using the "album"-gain. 

id3tags are v2.3

**Comment by Senseito7** [comment]
I'm having the same issue as @GitHorst - after updating (not sure from what version) to 1.0.47 tracks appear in the wrong order and without album art. Clearing app data and using 'flush media database' haven't helped.

Looking at additional information as suggested the 'track' row is also blank for me. I'm on Android 6.0.

**Comment by adrian-bl** [comment]
Ok, if the track row is empty, we failed to read the tag for some reason.

Could you send me a sample file to adrian@blinkenlights.ch ?

**Comment by GitHorst** [comment]
just did -- can you also check if the replay gain was also lost due to the same error? thanks again! :)

**Comment by adrian-bl** [comment]
Ok, that should be fixed via https://github.com/vanilla-music/vanilla/commit/a98eb36a1caacf0281db7b0c3a8bebacbe34a22d (Needs a full re-scan to have the library updated, but the next release will do this anyway due to some other change)

About the replay gain: I do not see any TXXX or RAV2 tags in the file (http://wiki.hydrogenaud.io/index.php?title=ReplayGain_1.0_specification#ID3v2) - so the file appears do not have any replay gain information (but the tool you used might have adjusted the MP3 volume itself)

**Comment by GitHorst** [comment]
ok, great. and thanks for the feedback on the replay gain -- might well be that [flacon](https://github.com/flacon/flacon) does it like that.

do you have an idea when the next release will happen? (otherwise i would have to compile it myself, right?)

keep up the good work! =)

**Comment by Senseito7** [comment]
@GitHorst to tide you over to the next release you can get the nightly from http://android.eqmx.net/android/vanilla/

Happy to report the issues I had are all gone with the Jan 24th nightly! Thanks for the quick fix Adrian!

**Comment by adrian-bl** [comment]
Cool, thanks for the feedback.

The next release should probably show up on f-droid in 2-3 days.
