### ISSUE TITLE
preload file not work if SD is temporary unmounted

### ISSUE THREAD

**Issue by Mannshoch** [vanilla-music/vanilla#523]
Because of some Problems with MTP I have to use the Mass-storage option. Even I tick the option for preload the whole file, Vanilla stop playing immediately if the external disk is mounted to PC.

In the best case I could setup to preload the next three Files in the Play-list (and with a limit to preload e.g. max. 50MB)

Also there is the problem that after remounting to Android the play-list not anymore work until the Mediascanner finished it's scanning.

**Comment by adrian-bl** [comment]
What do you mean with preload? The readahead feature?

This feature only tries to fill the pagecache of the kernel - it wont help against a vanished filesystem

**Comment by Mannshoch** [comment]
is it maybe possible to do something for that case?

**Comment by adrian-bl** [comment]
No, sorry: the mediaplayer needs a valid filedescriptor. Keeping the FD alive while android umounts the filesystem is simply not possible.

**Comment by Mannshoch** [comment]
:-(

**Comment by Adonai** [comment]
How does music streaming work then?

**Comment by adrian-bl** [comment]
TCP sockets are file descriptors.

Streaming would not work with a closed socket, wouldn't it?
