### ISSUE TITLE
1.0.47 is making Simple Last.fm Scrobbler and Scrobble Droid Crash

### ISSUE THREAD

**Issue by regagain** [vanilla-music/vanilla#525]
Hi!

Since I upgraded to 1.0.47 from F-Droid, Simple Last.fm Scrobbler is crashing with the following message on every track change: "Unfortunately, Simple Last.fm Scrobbler has stopped".

Somehow, after uninstalling/reinstalling both Vanilla Music & SLS the issue disappeared, but came back a few days later. Since then I can't get rid of it.

So I gave Scrobble Droid a try instead, but the same thing happened.

Has anyone else noticed this?

Android 6.0.1, Samsung Galaxy S6

**Comment by Jucgshu** [comment]
Yup, same here.

Nexus 5, Cyanogenmod 13.0

**Comment by adrian-bl** [comment]
We are probably sending a bad song id.

**Comment by adrian-bl** [comment]
This issue is fixed via https://github.com/vanilla-music/vanilla/commit/7d903348670d1b7461b7f1427927336a6171ab23
