### ISSUE TITLE
Same name albums go to same tracks

### ISSUE THREAD

**Issue by RobertoRiera** [vanilla-music/vanilla#527]
If you have 2 or more albums with the same name from 2 or more artist, for example 'Amy Winehouse'(artist) > 'other songs'(album) and you have Kendrick Lamar(artist) > 'other songs'(album) if you go to 'other album' album then you get the songs from all artists that have an album with that name.

Despite this little errors this software is really good :)

**Comment by jooola** [comment]
I can comfirm, since the new db engine, the library is broken.

I have many albums which i didn't tag the albums with the right name, so i put a "_". This is only used to build my library because i auto rename every songs to :

**Comment by adrian-bl** [comment]
I know that this case was handled differently in pre 1.0.47 versions but i have the feeling that the current behaviour is better:

The old handling had issues with single albums distributed across multiple folders (eg: album/disc1 album/disc2) and albums with multiple artists.

So i'm not sure if there is a way to fix this that would everyone make happy (and tagging albums with '_' is probably not a widespread use case)

**Comment by jooola** [comment]
> So i'm not sure if there is a way to fix this that would everyone make happy (and tagging albums with '_' is probably not a widespread use case)

There is fix, just need to find the problem !

**Comment by RobertoRiera** [comment]
I think while a 'allhappy' solution is found it would be great to put an option in the menu, I think many people would like it, even if you have to reescan the system again it would make a good soution temporally :)

**Comment by adrian-bl** [comment]
> There is fix, just need to find the problem !
> I won't change my entire audio library structure :-p

You could just use Picard to correctly tag your library.

But what would be your solution?
I do not have a big motivation to fix / workaround incomplete tagging.

**Comment by jooola** [comment]
This is useless to talk about me changing my way of managing my library or something like this. If i need to change my music player i will. I just came here to report an issue, my library isn't the problem.
Since 1.0.47 ( Changing the DB engine ) I had this issue so i just rolled back to 1.0.46.
If you want my help to find the solution ok but i really don't know Java, don't expect me to create a PR.

I guess if you want to find the problem maybe compare 1.0.46 to 1.0.47, so you could maybe see some differences.

@RobertoRiera Yes you're right this could be a good temporary solution ! But i still don't know if any actual option fixes my problem !

Best regards

**Comment by adrian-bl** [comment]
@jooola 

>  I won't change my entire audio library structure :-p
> This is useless to talk about me changing my way of managing my library or something like this. If i 
> need to change my music player i will. I just came here to report an issue, my library isn't the problem.

And your library isn't my problem either :-)

> I guess if you want to find the problem maybe compare 1.0.46 to 1.0.47, so you could maybe see 
> some differences.

I wrote the code and know the difference between 1.0.46 and 1.0.47 very well.


@RobertoRiera 

> I think while a 'allhappy' solution is found it would be great to put an option in the menu, I think many 
> people would like it, even if you have to reescan the system again it would make a good soution 
> temporally :)

While i think that the new behavior is 'better', i don't mind making this a configuration option:

I just wonder how we should calculate the key in this case: Should we only take the folder itself into account or use 'album name from tag + path to folder of file' to group the items?

**Comment by RobertoRiera** [comment]
@adrian-bl I really apreciate that you have this in count man!

Answering your question, I think the normal way to do it is like the other music players(not the ones who show all songs of an artist when you select one), I think it was nice exactly like it was before 1.0.47, when you go to an artist, it shows all albums and when you select one of them it just show the songs belonging to that album(not all the songs that belongs to an album named like that no mater what artist owns it)

I don't know exactly how it works but I think the 'album name from tag + path to folder of file' sounds better than just the folder itself.

I have experience in java but not to much on android itself (I have just made some apps showing things from DB and some functions with buttons) but I would like to make something, is it there any guide through how is it build? I have experience in programming and I think that guide would help me to talk about Vanilla more deeply.

**Comment by adrian-bl** [comment]
Ok, i added an option to change the album grouping to the latest nightly build (See: http://vanillamusic.io/#nightly-builds - you can install it together with the normal release as it shows up as a seperated app)

The default behavior is still to group by $album_name, but if

Settings > Media library > Group albums by folder

is enabled, we will group albums by $album_name+$folder.

**Comment by RobertoRiera** [comment]
Okey, thanks Adrian!
