### ISSUE TITLE
File scanning ignores mp3s with ID3v1 tags

### ISSUE THREAD

**Issue by t-wissmann** [vanilla-music/vanilla#528]
Vanilla Music 1.0.47 seems to ignore mp3 files that have ID3v1 tags (regardless the presence of id3v2 tags). The issue is still present in 1.0.48; it works fine for 1.0.46.

For instance the file [05. Don Edito EI Gruva.mp3](https://github.com/vanilla-music/vanilla/files/742817/unrecognized-mp3-file.zip) is _ignored_ (the file is in the linked zip. Its duration is only 13 seconds, so I hope this is not a copyright violation). Running `id3v2 -l` on it prints:
```
id3v1 tag info for 05. Don Edito EI Gruva.mp3:
Title  : Don Edito EI Gruva              Artist: The Nice                      
Album  : Ars Longa Vita Brevis           Year: 1968, Genre: Progressive Rock (92)
Comment:                                 Track: 5
id3v2 tag info for 05. Don Edito EI Gruva.mp3:
TIT2 (Title/songname/content description): Don Edito EI Gruva
TRCK (Track number/Position in set): 05
TPE1 (Lead performer(s)/Soloist(s)): The Nice
TALB (Album/Movie/Show title): Ars Longa Vita Brevis
TYER (Year): 1968
TCON (Content type): Progressive Rock (92)
```
By 'ignored' I mean that neither the artist 'The Nice' nor the album 'Ars Longa Vita Brevis' is listed in the media browser. I can still play the file via the 'files' tab, however the gui shows `<05. Don Edito El Gruva.mp3>` as the song's title and `<No Artist>` and `<No Album>` as the artist and album name, respectively. (See  screenshot below).

A sample of 10 tests showed, that the pattern is: If a mp3 file has both ID3v1 and ID3v2 tags, then vanilla music fails to read its tags. Interstingly, after downgrading to 1.0.46, the songs appear immediately - it seems it was not necessary to rescan the filesystem.

However, if only ID3v2 tags are present, the tags are read correctly, e.g. this one:
```
id3v2 tag info for 09 - Everydays (Single Version).mp3:
TSSE (Software/Hardware and settings used for encoding): LAME 64bits version 3.99.5 (http://lame.sf.net)
TRCK (Track number/Position in set): 9
TPE1 (Lead performer(s)/Soloist(s)): Yes
TALB (Album/Movie/Show title): Yes
TIT2 (Title/songname/content description): Everydays (Single Version)
TCON (Content type): Progressive Rock (92)
TYER (Year): 1969
TLEN (Length): 383800
09 - Everydays (Single Version).mp3: No ID3v1 tag
```

![playlist-window-screenshot](https://cloud.githubusercontent.com/assets/9048813/22478578/c972c930-e7ea-11e6-832d-d5a812424bc1.jpg)

**Comment by adrian-bl** [comment]
Thanks a lot for this very well written and detailed bug report!

I just tested this on my development device running Android 5.1 and the file gets correctly indexed with Vanilla Music 1.0.47 (.46 used Androids media database while .47 uses our own implementation).

We are using Androids own tag reader to read ID3v1 and v2 tags, so something seems to go wrong on your device in Android itself. What version of Android 4.x are you using? We have a similar strange issue in #515 which also only affects Android <= 4.x


Thinking about it: Maybe we should enable our own tag reader for ID3 tags on Android 4.x - or give the user an option to choose the tagreader implementation.

**Comment by t-wissmann** [comment]
My Android-Version is 4.2.2 (I'm running a _Samsung S3 mini value edition_, and the kernel version is 3.4.5-2824661, but that should be irrelevant for the issue).

**Comment by adrian-bl** [comment]
Hmm.. so it seems that Androids own ID3 Tag reader is (randomly) broken on some Android 4.x releases :-/

But: Could you please give the latest nightly build (See: http://vanillamusic.io/#nightly-builds - you can install it alongside the normal release, it will show up as a seperated app) a try?

It has an option to use its own tagreader for ID3v2 tags which you can enable at Settings > Media Library > Always use builtin tagreader

This should hopefully solve the issue on your device.

**Comment by ffdroid** [comment]
Hello,
I had the same problem using the last stable 1.0.48: not all the ID3 Tags are recognized. The last version that worked well for me with the ID3 Tags has been the 1.0.46 which on the conuntrary doesn't recognise the plugins, so I have two options between which to choose, but both with some problems:
1) To use the 1.0.48 accepting that many of the ID3 tags are no more recognised, so some songs are now difficult to be found into the library;
or
2) To use the older 1.0.46 without the plugins;

Tested already also the last nighlty builds, but it has the same disadvantages of the 1.0.46 -> not working plugins.

Do you think there wll be soon an update which will definitely fix the problem of the ID3 Tag recognition?

Thank you

**Comment by t-wissmann** [comment]
Thank you very much @adrian-bl! If I tick _always use built-in tag reader_ in the nightly-build (ID: Mon Feb 6 15:30:25 EST 2017), then all the tags are recognized correctly again :-). (Without ticking it, the tags are gone as in 1.0.48)

@ffdroid: did you activate the `builtin tagreader`-option in the nightly build?

**Comment by ffdroid** [comment]
@t-wissmann: yes I did, I activated the builtin tagreader-option in the Nightly build version and actually it works, but the Nightly build doesn't give the possibility to activate the Plugins (e.g. Tag Editor, Lyric Search, etc...).

This means that, at the moment, there isn't a version of Vanilla Music which allows at the same time to correctly read the ID3 Tags (fixed only into the Nightly build) and to activate also the Plugins (fixed only into the 1.0.48).

**Comment by adrian-bl** [comment]
@ffdroid: what android version are you using? I am very surprised to see that so many devices seem to have issues with ID3 tagd while AOSP 4.x seems to work just fine.

About the plugins: this is a known issue of the nightly triggered by the different package name. I will release 1.0.49 on f-droid very soon - probably tomorrow.

**Comment by adrian-bl** [comment]
Closing this bug as 1.0.49 is about to be released (Which also contains ID3v1 parsing support!)

**Comment by t-wissmann** [comment]
Thank you @adrian-bl for releasing a new version that quickly!

**Comment by PanderMusubi** [comment]
Follow up on https://github.com/vanilla-music/vanilla/issues/531 I am suspecting something is wrong with ID3 tags on lots of my files. I use easytag to edit them but some (older) MP3 have a problem that is not fixed with triggering an edit from easytag, writing ID3v2(.4) tags.

Easytags shows ID3 tags (no idea which version it is stored in). If I edit the tags, the tags are persistent. But it is not ending up in ID3v2. Does anyone know how to fix the following attempt to do that or what is an alternatieve for this?

    $ id3v2 -l filename.mp3 
    filename.mp3: No ID3 tag

    $ id3v2 -C filename.mp3 
    Converting id3v1 tag to id3v2 in filename.mp3...
    id3v2: Success
    Tags could not be converted

    $ id3v2 -l filename.mp3 
    filename.mp3: No ID3 tag

**Comment by PanderMusubi** [comment]
Apparently id3v2 isn't supporting v2.4 because id3lib isn't yet. So my tags written by easytag are okay. Simply should try to validate or upgrade them with id3v2. Are there other ID3 v2.4 editors out there to investigate my files?
