### ISSUE TITLE
Show complete option's title in the configuration menu

### ISSUE THREAD

**Issue by RobertoRiera** [vanilla-music/vanilla#529]
When I navigate through the configuration I cant see complete name of some options, I mean, if the option name is large it hides behid '...' It would be nice if you hold the option the name rolls and show entirely

**Comment by adrian-bl** [comment]
Android doesn't offer such a functionality for standard preference views - but maybe we should just avoid extremely long translations.

What language do you use on your device and could you give an example of some truncated strings?

**Comment by RobertoRiera** [comment]
I use Spanish, an example would be 'Carpeta de inicio de administrador de archivos'  it appears like ' Carpeta de inicio de administrador de ar...' in a 4.7" device.

If Android doesnt have that functionality I will propose a change in transifex.

Thanks ;)

**Comment by kirbyfan64** [comment]
Closed by accident?

**Comment by RobertoRiera** [comment]
Sorry, I'm not sure when to close an issue, I propose the  translation in Transifex, when should I close it?

**Comment by RobertoRiera** [comment]
@kirbyfan64 Sorry, I'm not sure when to close an issue, I propose the translation in Transifex, when should I close it?

**Comment by adrian-bl** [comment]
Are you already a member of the spanish transifex team?
If yes, (eg: you have edit rights on transifex) i'd say we can close the issue here.

If not: Please send me a join-request on transifex and i'll close this issue after i added you.

**Comment by RobertoRiera** [comment]
Yes, I am a member, I close this.

**Comment by adrian-bl** [comment]
Ok, and thanks for your contribution to the spanish translation! 👍
