### ISSUE TITLE
Unable to sort library by date added, reverse sort.

### ISSUE THREAD

**Issue by ToNIX-** [vanilla-music/vanilla#532]
Date added only works, but with reverse sort, it always resets to name.

Version 1.0.48.

**Comment by adrian-bl** [comment]
Works for me, did you try rebooting your phone? ;-)

Also what do you mean with reset? Does the selection revert itself?

**Comment by ToNIX-** [comment]
Doesn't work with a rebooted phone.

If sort by "Date added", it works.

If I sort by "Date added" and check "Reverse sort", it doesn't work and switches to "Name" by itself. When I re-open the "Sort by" dialog, "Name" is selected.

**Comment by adrian-bl** [comment]
Oh! I assume you are at the album or artist tab?

Looks like Date Added itself isnt the issue: it just happens to whatever item is the last in the sort options.

I think i know where things go wrong, will have a look at this tomorrow.

**Comment by ToNIX-** [comment]
Yes, Artists or Albums tabs. Thanks!

**Comment by adrian-bl** [comment]
Fixed via c0854e27400b884f01a69bc202360b05aa2c72bb , thanks for the bug report!
