### ISSUE TITLE
(album.ogg + album.cue) vanilla-music read album.ogg instead of album.cue

### ISSUE THREAD

**Issue by mrprole** [vanilla-music/vanilla#535]
So the music database is full of albums instead of separate tracks.
![screenshot_2017-02-04-12-24-38](https://cloud.githubusercontent.com/assets/25525606/22617756/2abdbafa-ead5-11e6-90c0-7cb7e79e8464.png)

**Comment by adrian-bl** [comment]
We simply do not support cue files.

If you would like to implement this, feel free to work on a patch - but this is not a feature that i am going to implement
