### ISSUE TITLE
Sorting tracks by name is confusing

### ISSUE THREAD

**Issue by lucamp** [vanilla-music/vanilla#536]
Hi,
my localization is Italian, inside track tab sorting by name "nome" lead to sort it by title. In my opinion name means the file name so it should be replaced with title, "titolo" in my language

Thanks for your app
Luca

**Comment by adrian-bl** [comment]
Thanks for the info - i suppose it was you who requested to join the italian translation on transifex?

I just accepted your request - you should now be able to update the translation - i usually sync them to git a few days before the release, so any changes you make on transifex will 'automatically' show up in the next release.

**Comment by lucamp** [comment]
Hi,
yes, it was me!
I am looking at the Italian translation and the original string is "name" and not "Title". So maybe you should consider to change that string in the main language (english) first. After that other translators could revise it and change accordingly.
Let me know your point of view

Luca

**Comment by adrian-bl** [comment]
I agree, that's also inconsistent in the english translation: I replaced 'name' with 'title' in the source translation (See: 4c59fc24866916a9bba434a5d9c76ea353c918fa)

Transifex syncs with our git-head every ~24 hours, so the new string (title) should show up tomorrow

**Comment by adrian-bl** [comment]
Closing this issue as the string is now available on transifex
