### ISSUE TITLE
scrobble through ScrobbleDroid-API doesn't work after upgrade to 1.0.47/48

### ISSUE THREAD

**Issue by ph13rc3** [vanilla-music/vanilla#537]
Hi,
as I found no open issue for it, I guess it does not affect all configurations:
After upgrading to 1.0.47 (through F-Droid), I've noticed that the Simple LastFM Scrobbler didn't receive any notifications from VM. Same behaviour with 1.0.48 (tested today).
When I install previous version 1.0.46 it immediately works again, so it seems there's something different in the newer versions. 
Let me know what additional information I can provide or if there is anything I can test for myself.

Android: 6.0
Motorola Moto G 2nd Gen LTE

**Comment by adrian-bl** [comment]
1.0.47 was pretty broken, but 1.0.48 should work.

Did you verify that the scrobbling option is actually enabled? (It is off by default)

**Comment by ph13rc3** [comment]
Thanks to your reassuring answer, I have tried it again. This time first uninstalling the 1.0.46, then installing 1.0.48. First it seemed to work. One single "just listened to" (hört gerade) was transmitted and that's it. No new scrobble updates afterwards, even after reboot. 
The "use Scrobble Droid-API"-option was activated by default, btw.
I am using Simple Last.fm Scrobbler v1.5.3.

**Comment by adrian-bl** [comment]
> The "use Scrobble Droid-API"-option was activated by default, btw.

Ah, yes: i mixed this up with the 'emulate stock broadcasts' option (which actually works with sls!)


Anyway: I had a look at this and SLS rejects our message with this stacktrace:

```
02-07 21:17:59.088 30008 30008 W Bundle  : Key id expected Integer but value was a java.lang.Long.  The default value -1 was returned.
02-07 21:17:59.088 30008 30008 W Bundle  : Attempt to cast generated internal exception:
02-07 21:17:59.088 30008 30008 W Bundle  : java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
02-07 21:17:59.088 30008 30008 W Bundle  : 	at android.os.BaseBundle.getInt(BaseBundle.java:873)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at com.adam.aslfms.receiver.ScrobbleDroidMusicReceiver.parseIntent(ScrobbleDroidMusicReceiver.java:105)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at com.adam.aslfms.receiver.AbstractPlayStatusReceiver.onReceive(AbstractPlayStatusReceiver.java:100)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at android.os.Looper.loop(Looper.java:154)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at android.app.ActivityThread.main(ActivityThread.java:6126)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at java.lang.reflect.Method.invoke(Native Method)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-07 21:17:59.088 30008 30008 W Bundle  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

So it expected us to send an Integer while we are sending a Long.
Pre 1.0.47 Versions of Vanilla Music *did* in fact send an Integer - which was wrong: The SDK documentation clearly states that song and album id's are Longs (https://developer.android.com/reference/android/provider/MediaStore.Audio.AudioColumns.html#ARTIST_ID)

But the good news is that the folks at SLS already fixed this:
https://github.com/tgwizard/sls/commit/87136dca27208f1cb5150398e842be6515ed78e5#diff-a1610eb182e1dbcc9e9f2b3bd839ba05R105

So the next release of SLS should work again with 1.0.48 - as a workaround you could also try to enable 'Emulate Stock Broadcasts' until the new version is released.

**Comment by ph13rc3** [comment]
Thanks a lot, yes the "emulate stock broadcasts"-option did work. Also thanks for clearing up why it didn't work. I will now stick with 1.0.48 and keep testing ;-)
Awesome support!

**Comment by adrian-bl** [comment]
Closing this as a new SLS version will probably show up soon
