### ISSUE TITLE
Cover Fetch plugin

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#540]
@adrian-bl , I requested a transfer of my repo to you, pls place it into @vanilla-music repo

**Comment by adrian-bl** [comment]
Done: I clicked on the link github sent me - the repo should show up in a few minutes

**Comment by adrian-bl** [comment]
Ah no: Github moved it to *my* personal account (without even asking. thank you github) - i'll try to transfer it to the vanilla-music organisation

**Comment by adrian-bl** [comment]
Ok, the repo is now part of vanilla-music and you should have admin access to it

**Comment by Adonai** [comment]
Thanks a lot!

**Comment by papafelice** [comment]
Nice plugin. Would it be possible to have the cover image saved as folder.jpg instead of writing it to the tags?

**Comment by Adonai** [comment]
Yes, possible, but that'd require WRITE_EXTERNAL_STORAGE permission for Cover Fetch plugin too. Create an enhancement issue there, we'll have a talk about implementation details.

**Comment by adrian-bl** [comment]
How can it write to the tag without this permission? (Or does it just update the cover blob in androids database?)

**Comment by Adonai** [comment]
It passes artwork to the Tag Reader through the file descriptor.

**Comment by adrian-bl** [comment]
Ah, ok: so it doesn't have direct access to the sdcard.

Another thing: i noticed that edited tags dont show up in vanilla: does the tag editor notify the media scanner about the change?

**Comment by Adonai** [comment]
@adrian-bl , it does. Vanilla picks up the change several minutes after.

But... it works for ordinary tags, artwork change is somehow missed from Vanilla. My guess is that it has something to do with our lru cover cache.

**Comment by adrian-bl** [comment]
Oh, you are right. I was pretty sure that i've seen this fail before, but maybe i had an older version installed. Just recently upgraded stuff on fdroid.

About the cover: yeah: we are currently not purging the cache on file changes, we should probably change that
