### ISSUE TITLE
cannot add to playlists

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#541]
Using 1.0.48 from F-Droid on Nexus 5X with Android 7.1.1.

When adding songs to any playlist (either a new one or an existing one), it says "added 0 songs to playlist blah". Which is true, but ideally shouldn't be :) . Happens with both save as playlist and add to playlist functionality.

**Comment by adrian-bl** [comment]
Does this happen to all songs and are the affected songs indexed?

If you have root, a copy of /data/data/ch.blinkenlights.android.vanilla/databases/media-library.db would help tobdebug the issue

**Comment by adrian-bl** [comment]
Hmm... Looking at the code, this might happen also if the mtime of a song is 0 in the database.

In this case, a full rescan with database flush would solve the issue

**Comment by mathstuf** [comment]
Opening the Media Library panel in Settings shows it doing a scan now. I remember it doing a scan after installation, but does it not run later if interrupted?

**Comment by mathstuf** [comment]
I did a filesystem scan, but that did not help. How do I do a library flush?

**Comment by adrian-bl** [comment]
> but does it not run later if interrupted?

The upgrade from 1.0.47 to 1.0.48 did a 'refresh' scan as i changed how some tags are interpreted.

But looking at the code now, it seems that the trigger-to-refresh left the songs in a bad state by setting their 'mtime' to zero, which equals to 'song does not exist'.

I fixed this in 35833f1c65fb9545edc70096fdfdb54ba64ac74c, but it's too late for your database ;-)

But a flush + scan should bring you back into a good state

> I did a filesystem scan, but that did not help. How do I do a library flush?

Settings -> Media Library

Then tick both 'Scan full filesystem' and 'Flush media database' - then hit 'Scan'

This will re-populate the database from scratch, while (hopefully ;-) ) keeping your playlists alive.

**Comment by mathstuf** [comment]
That seems to have worked, thanks.
