### ISSUE TITLE
Plugins not recognized

### ISSUE THREAD

**Issue by cfabio** [vanilla-music/vanilla#542]
I installed Vanilla Music (ver. 1.0.48) and Vanilla Cover Fetcher (ver. 1.0.0) from f-droid but I can't find any "Plugins" option in the context menu.
The problem also occurs with every other Vanilla Music plugin installed from f-droid.
Android ROM installed on the phone is LineageOS.
Does anyone have any suggestion?

**Comment by Adonai** [comment]
How do you activate plugins?

This is the way I do it:

![screenshot_20170210-001335](https://cloud.githubusercontent.com/assets/863272/22803416/e11d2b38-ef25-11e6-803a-bb0cc21a3141.png)
![screenshot_20170210-001345](https://cloud.githubusercontent.com/assets/863272/22803422/e9943a86-ef25-11e6-86f8-58ebd77f1a66.png)
![screenshot_20170210-001349](https://cloud.githubusercontent.com/assets/863272/22803429/edc99902-ef25-11e6-98a5-022bcf8d9412.png)

**Comment by cfabio** [comment]
Damn, I found it thanks to your help.
Anyway I suggest you to spend a couple more words to explain how to use the plugin because
> Once both player and this plugin are installed, request a context menu from library screen, select "Plugins" and "Cover fetch" afterwards.
is really not clear and ambiguous.
Thanks for the help and for developing such great app.

**Comment by ffdroid** [comment]
Hello everyone,
I had the same problem: cannot find any "Plugins" menu entry into the context menu of the library screen using Vanilla Music (ver. 1.0.48) and Vanilla Cover Fetcher (ver. 1.0.0) from f-droid.
Could you please add some screenshots in which the manu entry is in English please? As me (and many others I guess) are not able to read Cyrillic ;-)
Thank you

**Comment by Adonai** [comment]
Cyrillic text is not relevant, what's important are accents which point out what to click to get there.

Just do the same thing with any song.

**Comment by ffdroid** [comment]
I found it, thank you.
Now the only problem that remains for me is that not all the ID3 Tags are recognized in the last Vanilla Music (ver. 1.0.48 but the same happens also in the 1.0.47).
The last version that worked well with the ID3 Tags, has been the 1.0.46 which on the unfortunately doesn't recognise the plugins, so two options between which to choose, but both with some problems:
1) To use the 1.0.48 accepting that many of the ID3 tags won't be recognised, so some songs will be very difficult to be found into the library;
or
2) To use the older 1.0.46 without the plugins;

Tested also the last nightly builds, but it is actually the same of the 1.0.46 as it doesn't supports the plugins.

**Comment by kirbyfan64** [comment]
Wait, do plugins not work in the nightly?

**Comment by Adonai** [comment]
@kirbyfan64 , no, they don't, see vanilla-music/vanilla-music-tag-editor#4

**Comment by adrian-bl** [comment]
1.0.49 is now on f-droid which contains an option to use the builtin ID3 tag reader

**Comment by Adonai** [comment]
Guess this can be closed now

**Comment by adrian-bl** [comment]
Not sure: plugins don't work for me in the nightly build using gradle

**Comment by Adonai** [comment]
@adrian-bl , ok, I'll check it and fix last bits remaining

**Comment by adrian-bl** [comment]
@Adonai So the nightly builds are now on GCE and won't change the plugin constants:

Nightly builds are now correctly detecting the presence of plugins, but hitting the 'Plugins' button does nothing.

I suspect that's because the package name is hardcoded in the plugins itself, see:

 https://github.com/vanilla-music/vanilla-music-lyrics-search/blob/master/app/src/main/java/com/kanedias/vanilla/lyrics/PluginService.java#L109

**Comment by kirbyfan64** [comment]
As a side note, would it be possible to have a sort of "mini-library" that plugins import in order to communicate with Vanilla? That way, stuff like selecting the proper package name could be handled in the library, and the user wouldn't have to experience all the `Intent` crud.

**Comment by Adonai** [comment]
@kirbyfan64 , I had this option in mind when creating plugin APIs. At least all the constants we have can be moved there. I'm not sure about intents as we'll have to create broadcast receivers and query packages anyway. 

But all the hard work comes not from creating such a library, but from work needed to wire it up. We need to alter (potentially) F-Droid builds, Gradle builds, Ant builds, Travis builds, we need to add this lib as a subproject in vanilla-music and include it as git (and gradle) submodule in all plugins and player itself. Most of this work requires very close collaboration with admins of vanilla-music, thing that I don't have.

@adrian-bl, will try to circumvent this by extracting package name from coming intent, wait a day or two, I'll come up with comment or commits.

**Comment by adrian-bl** [comment]
Closing this as it is not an issue in the nightly itself but plugin specific (eg: plugin using hardcoded package name)

**Comment by Adonai** [comment]
Should be fixed with latest commits in respective repos.
Wait for F-Droid to build them.
