### ISSUE TITLE
Arstist info in the Albums tab

### ISSUE THREAD

**Issue by rqcy** [vanilla-music/vanilla#544]
Hi, it would be useful to have some info about album artist in the Albums tab for each album.

Thanks!

**Comment by adrian-bl** [comment]
...and what kind of information would we display about the artist?

**Comment by rqcy** [comment]
> ...and what kind of information would we display about the artist?

a name ;-)

The thing is that I like the album view the most, because it's how my
music is organized, but sometimes album name by itself is a bit
enigmatic.  I would be more informative to have artists name displayed
next to it, e.g.:


Album A (Artist A)
Album B (Artist B)
Album C (VA)


What do you think?

**Comment by adrian-bl** [comment]
Done in f4d0028176fdf094fbc5c7370076fb4ba18c27a0 - the album view now also includes the artist

**Comment by rqcy** [comment]
cool, thanks!
