### ISSUE TITLE
Save cover image as folder.jpg

### ISSUE THREAD

**Issue by papafelice** [vanilla-music/vanilla#546]
Instead of putting the cover image into the tag of an individual file, the image could be stored as a separate folder.jpg file when a folder contains a set of songs from the same album.

**Comment by kirbyfan64** [comment]
I think you meant to report this at:

https://github.com/vanilla-music/vanilla-music-cover-fetch

**Comment by Adonai** [comment]
Yup, looks like a job for Vesemir

**Comment by Adonai** [comment]
@adrian-bl , please assign me

**Comment by adrian-bl** [comment]
Looks like i can only assign to people with commit privileges to the repo (+ the reporter)

I suggest to close the issue here, re-open a new one at the vanilla-music-cover-fetch repo + mention the url to this issue (so that github will 'link' them together)

**Comment by papafelice** [comment]
Closed for reopening at the vanilla-music-cover-fetch
