### ISSUE TITLE
FR: rational L-R swipe behavior on playback screen

### ISSUE THREAD

**Issue by goldencut** [vanilla-music/vanilla#547]
Heretically, I like to pick and play my music from folder/file view. Left-right swipe just restarts the same song over - that makes no sense. If I start playback from filesystem then obviously I'd like the next-previous gestures to play the next or previous track from that source - the filesystem. Vanilla currently behaves like an idiot savant - plays me the same song over and over.

**Comment by adrian-bl** [comment]
> Left-right swipe just restarts the same song over 

No, it doesn't: it goes to the next item in the queue. If you only have one item in the queue, then it will keep playing the same song over and over.

> Vanilla currently behaves like an idiot savant

Please watch your language (also see your previous bug report).
