### ISSUE TITLE
FR: Option to turn off nonsensical track info

### ISSUE THREAD

**Issue by goldencut** [vanilla-music/vanilla#548]
If there's no album info on current track then what's the point of spamming the UI and printing `<No Album>`? Wouldn't the lack of album title and an empty line inform user as well that there's no album title? An option to turn this info of having no info off would also suffice, as some (with autism? no pun intended) might find it maybe useful.

**Comment by adrian-bl** [comment]
> If there's no album info on current track then what's the point of spamming the UI and printing <No 
Album>

To have it visible in the media library. Displaying an empty row would look even more strange.

> An option to turn this info of having no info off would also suffice

Sorry, but i do not think that this should be a configuration option.
