### ISSUE TITLE
Crash on startup versions 1.0.47-1.0.49 (from f-droid)

### ISSUE THREAD

**Issue by Jaulers** [vanilla-music/vanilla#550]
Running on Android 4.0.4 CyanogenMod 9
When trying to start Vanilla with app icon or by tapping widget, it quickly shows library with only one "Artist" entry showing, then crashes. ("Unfortunately, Vanilla Music has stopped")

[logcat](https://github.com/vanilla-music/vanilla/files/787835/vanillacrash.txt)

**Comment by ToNIX-** [comment]
Could this be related to the new library scanning module? I had to downgrade on an old phone to the version just before the new module.

**Comment by adrian-bl** [comment]
Could you provide a logcat of the crash? (adb logcat, then cooy paste the exception).

My oldest phone is running 4.3, so everything older gets very little testing

**Comment by Jaulers** [comment]
relevant part of logcat:
[vanillacrash.txt](https://github.com/vanilla-music/vanilla/files/787835/vanillacrash.txt)

**Comment by adrian-bl** [comment]
Thanks: we crash while creating the notification as Android 4.0 does not implement the NotificationBuilder.

That should be easy to fix: i'll try to push a fix this week and release 1.0.50 on f droid.

**Comment by adrian-bl** [comment]
Ok, so this should be fixed in https://github.com/vanilla-music/vanilla/commit/7580280ba5f109da88696cdb211f0082b4df98e4 

The latest nightly build (see: http://vanillamusic.io/#nightly-builds) already includes this commit - so feel free to test it there

**Comment by Jaulers** [comment]
It no longer crashes. Thank you very much.

**Comment by adrian-bl** [comment]
Cool, thanks a lot for the feedback!

I'm closing this issue as 1.0.50 should show up soon on f-droid or on the google play store (if you subscribed to the beta channel there)
