### ISSUE TITLE
Nightlies redirects to "403 Forbidden"

### ISSUE THREAD

**Issue by rancidfrog** [vanilla-music/vanilla#552]
Trying to download latest apk redirecting to "403 Forbidden"

Is it possible to include apk in release section?

**Comment by adrian-bl** [comment]
Which link are you using?

http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk works just fine for me.

Are you sure that there is no 'security proxy' MITMing the connection?

**Comment by rancidfrog** [comment]
The link from readme needs updating: https://github.com/vanilla-music/vanilla/pull/553
It used to take you to html with link to apk, now it is forbidden.
Linking directly to apk works

**Comment by adrian-bl** [comment]
Thanks a lot for the pull request!

I am closing this bug as i merged the PR.
