### ISSUE TITLE
Please Support *.mid files.

### ISSUE THREAD

**Issue by Antonbeard** [vanilla-music/vanilla#554]
Please Support Midi format files. Standart music player on Android play them with no problems.

**Comment by adrian-bl** [comment]
Fixed via https://github.com/vanilla-music/vanilla/commit/42cb7979e4bbf7e1e1a150a158c484108138b834 - we are now checking if the file has a midi header

**Comment by Antonbeard** [comment]
I installed the nightly build. But MIDI files still can not be played.

**Comment by adrian-bl** [comment]
Are they displayed in the library?

**Comment by Antonbeard** [comment]
No.

**Comment by adrian-bl** [comment]
Try to start a full rescan (settings > media library)

If the file still does not show up (under <No Artist>), feel free to send me a sample to adrian@blinkenlights.ch

**Comment by adrian-bl** [comment]
Thanks for the sample file: It is correctly indexed on my phone.

Maybe your mediaserver process somehow fails to report it as a valid audio file: try to reboot your phone & force a full scan again.
