### ISSUE TITLE
Links to plugins in GPlay

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#555]
Hi @adrian-bl!

I've uploaded plugins to GPlay as requested, here's the query:

https://play.google.com/store/search?q=vanilla%20music%20plugin

Should we mention them also in README.md or F-Droid description?

**Comment by adrian-bl** [comment]
Thanks, i added links to them in the README.md file.

I don't think that we need to add them in the f-droid description: The f-droid catalog is quite small and users are more likely to find them using the normal search.

But maybe we could add them to the about page (Feel free to send a PR)

**Comment by Adonai** [comment]
Got it, thanks!
