### ISSUE TITLE
Nightly crashes on taborder dialog

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#556]
Nightly builds created by gradle crash while opening the tab order dialog.

Probably a gradle or proguard 'feature' 😕

**Comment by Adonai** [comment]
Assign it to me, I'll have a look at weekend

**Comment by adrian-bl** [comment]
Note that the headset beep is also broken :-/

**Comment by adrian-bl** [comment]
We hit this issue: https://code.google.com/p/android/issues/detail?id=86642

```
E/AndroidRuntime(11633): android.content.ActivityNotFoundException: Unable to find explicit activity class {ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.TabOrderActivity}; have you declared this activity in your AndroidManifest.xml?
```
```
                <intent
                        android:targetPackage="ch.blinkenlights.android.vanilla"
                        android:targetClass="ch.blinkenlights.android.vanilla.TabOrderActivity" />
```


So if gradle is unable to change the package name there (i don't think that <intent> takes non-absolute targets), we have to switch back to the good old sed script.

**Comment by adrian-bl** [comment]
This is fixed as i went back to the 'sed' build: gradle also broke all widgets.

However: the new build script should not touch the constants in PluginUtils.java
