### ISSUE TITLE
Duplicated artists

### ISSUE THREAD

**Issue by NicolasLM** [vanilla-music/vanilla#557]
When I updated to v1.0.50, my library was re-scanned. It seems that the artist name is now case sensitive.

I have duplicated artist `In Flames` and `In flames`. 
Likewise I have duplicated `Moby` and `Moby`, which is probably a whitespace problem.

I'm not sure if it's a bug or a feature, but I definitely liked the previous behavior more.

**Comment by adrian-bl** [comment]
The case sensitivity is a feature: Older releases used to display a random variant which was IMO confusing.

But i agree that we should trim whitespaces (mostly the fault of ID3v1 tags)

**Comment by adrian-bl** [comment]
Fixed via 710398822d2b752b50519ebd90b9e0258bd73aa8 - we are now trimming whitespaces before returning tags.
