### ISSUE TITLE
Add audiobook features

### ISSUE THREAD

**Issue by hgkamath** [vanilla-music/vanilla#56]
There is no open source player dedicated for audiobook as of yet. 
Vanilla player could easily double up as a audiobook player.
Audiobook players are essentially no different from music players except they have the following features, which can be provided and enabled via the settings menu. 

1] Button in the playback interface to enable a 15 second quick-rewind
2] Checkbox to remember last folder/playlist , playlist position and playback position on app close.
3] Checkbox for automatic start play 
4] Checkbox to auto quick-rewind 15 seconds on automatic start play. 
5] With availability of NFC tags and phones that support NFC tags, one feels the need to toggle the state of an audiobook player via a widget, NFC tag or via a smart action based on other profile or proximity detection. 
6] Usually audiobooks are stored as sound files for book chapters under a single folder, recognizing the playing order from filename, tracknumber is nice, and can save time over listening to several books. However, books once listened to are usually not listened-to again and would be deleted, and so a  means to not commit permanently into media index. A good playlist editor can allow a user to sequence the chapters in the right listening order. 
7] fetching book information is nice but not essential. 
8] A book listening history is also nice but not essential

Currently Vanilla music player 0.9.23
* opens the last file played.
* Files in a folder can be enqueued
* only files later than current position in queue can be cleared
* current queue cannot be edited.
* does not automatically start playing
* when play is pressed a file (current position in queue) is played from its start

An open-source app called mort player is advertised. Its source however seems to be not available.  

Some player apps come in both a audiobook version and music version. Though they are basically the same player, they can be installed as separate apps. The apps have different default settings set conveniently to listen to music or books.

**Comment by adrian-bl** [comment]
Closing this bug: We do not intent to build an audio book player.
The 10-sec-skip feature has been implemented in 1.0.20 but adding all features would be overkill (we are a music player after all)

**Comment by dandv** [comment]
> We do not intent to build an audio book player.

Staying focused is good. For those who are looking for an audiobook player, I like the [Material Audiobook Player](https://github.com/Ph1b/MaterialAudiobookPlayer).

**Comment by xeruf** [comment]
There is also AntennaPod, or my current favorite: Tsacdop
