### ISSUE TITLE
Duplicate entries from both /sdcard and /storage/emulated/0

### ISSUE THREAD

**Issue by davidschlachter** [vanilla-music/vanilla#561]
Many of my tracks are appearing twice in the library. When comparing duplicates, one will be in `/sdcard`, and the other in `/storage/emulated/0`:

![screenshot_20170309-140530](https://cloud.githubusercontent.com/assets/8271268/23766501/162d63ac-04d3-11e7-9d3e-8c01c5050dc2.png)

![screenshot_20170309-140543](https://cloud.githubusercontent.com/assets/8271268/23766516/26eaabdc-04d3-11e7-9904-ff7de3b864d2.png)

However, `/sdcard` is a symlink to `/storage/self/primary`, which is a symlink to `/storage/emulated/0`.

![screenshot_20170309-140956](https://cloud.githubusercontent.com/assets/8271268/23766554/4cfc4894-04d3-11e7-8384-b4a212b334f5.png)

I'm running Android 7.1 with adoptable storage. This issue started when I updated Vanilla to a version with the media scanner.

The expected behaviour would be that one of the directories is recognized as a symlink to the other and the tracks not be listed twice.

**Comment by adrian-bl** [comment]
What OS are you using? (Stock? LineageOs?)

Did you by any chance ever do a firmware upgreade after 1.0.46 was installed?

I've seen this on my Moto G3 (falcon) when LOS at one point deceided that the primary storage should now be '/sdcard' instead of '/storage/emulated/0' (..and got quickly reverted back in the next release)

Does '/storage/sdcard1' also exist and if yes: where does it point to?

**Comment by davidschlachter** [comment]
I'm using the latest LineageOS 14.1 nightly on a 2015 Moto G (osprey). I usually update weekly. I can't remember exactly when the duplicates started appearing, but it might have been when I switched from CM to LOS. I've deleted the app data for Vanilla and rebuilt the index, but the issues still occurs. I store my music on an adoptable storage partition of my SD card.

`/storage/sdcard1` doesn't exist. `/storage` is laid out like this:

    /storage
    ├── C06B-0F02 (portable SD card partition)
    ├── emulated
    │   ├── 0 (adoptable storage partition of SD card)
    │   ├── obb (
    ├── self -> /mnt/user/0/primary

Here's the output of `mount` for more details: [mount.txt](https://github.com/vanilla-music/vanilla/files/834355/mount.txt)

**Comment by adrian-bl** [comment]
Hmm, that's odd.

This is where we guess the paths to scan:
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/medialibrary/MediaLibrary.java#L455

I don't see how this would end up in both /sdcard and /storage/emulated.

But looking at the code, another possibility comes to mind:

After a full rescan, we also read androids own native library and index any songs found there:

https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/medialibrary/MediaScanner.java#L329

So if the device reports that '/storage/emulated/0' is its primary storage path BUT the media library contains songs pointing to /sdcard, we then would end up in a situation with duplicate paths.

Could you please give this a try: ?

* Run 'adb logcat | grep "VanillaMusic"'
* Go to Settings > Media Library and check 'flush database' and 'perform full scan' & hit the scan button.

I'd assume that you'd see a 'switch' from /storage/emulated to /sdcard *after* Vanilla Music logged this:
```
 -- starting scan of type 104
 [... /sdcard inserts start]
```

**Comment by davidschlachter** [comment]
That's looks like what's happening,

````
03-16 13:22:43.589  7339  7395 V VanillaMusic: Extracting tags from /storage/emulated/0/Music/Swing/42 Stars Fell On Alabama (1934-09-11).m4a
03-16 13:22:43.705  7339  7395 V VanillaMusic: MediaScanner: inserted /storage/emulated/0/Music/Swing/42 Stars Fell On Alabama (1934-09-11).m4a
03-16 13:22:43.707  7339  7395 V VanillaMusic: Extracting tags from /storage/emulated/0/Music/Swing/Dancing Cheek To Cheek.mp3
03-16 13:22:43.759  7339  7395 V VanillaMusic: MediaScanner: inserted /storage/emulated/0/Music/Swing/Dancing Cheek To Cheek.mp3
03-16 13:22:43.761  7339  7395 V VanillaMusic: Extracting tags from /storage/emulated/0/Music/Swing/Bill.mp3
03-16 13:22:43.817  7339  7395 V VanillaMusic: MediaScanner: inserted /storage/emulated/0/Music/Swing/Bill.mp3
````
…

````
03-16 13:30:29.476  7339  7395 V VanillaMusic: --- starting scan of type 103
03-16 13:30:34.920  7339  7395 V VanillaMusic: --- starting scan of type 104
03-16 13:30:35.035  7339  7395 V VanillaMusic: Extracting tags from /sdcard/Music/Swing/42 Stars Fell On Alabama (1934-09-11).m4a
03-16 13:30:35.221  7339  7395 V VanillaMusic: MediaScanner: inserted /sdcard/Music/Swing/42 Stars Fell On Alabama (1934-09-11).m4a
03-16 13:30:35.227  7339  7395 V VanillaMusic: Extracting tags from /sdcard/Music/Swing/430 Why Don't You Do Right_ (1942-07-27).m4a
03-16 13:30:35.365  7339  7395 V VanillaMusic: MediaScanner: inserted /sdcard/Music/Swing/430 Why Don't You Do Right_ (1942-07-27).m4a
03-16 13:30:35.368  7339  7395 V VanillaMusic: Extracting tags from /sdcard/Music/Swing/Cocoanut Trot.mp3
03-16 13:30:35.476  7339  7395 V VanillaMusic: MediaScanner: inserted /sdcard/Music/Swing/Cocoanut Trot.mp3
````
A quick fix could be to add a toggle in the Media Library settings to disable reading the native library.

**Comment by adrian-bl** [comment]
In the near future (when users have a choice to include/exclude directories), we probably should only scan files which are a child of the reportet storage directories, so we would not be a victim of such a corrupted native media storage.

But until we are there, i would recommend that you just flush the media library on your device as it clearly is in an unsound state.

You can do this via System Settings > Apps > (Show system apps) > Media Storage > Force Stop & Delete Data, then reboot.

This will get rid of the invalid entries and forces a rebuild on next boot. Note that this will also reset your ringtones and delete playlists (not in vanilla but in other players if they use android playlists)

**Comment by davidschlachter** [comment]
Deleting the media library completely resolved the problem — I suspect that Lineage/CM switched the path to primary storage, then reverted the change, but my media library ended up corrupted.
