### ISSUE TITLE
Unable to play mp4/webm files downloaded by NewPipe in v1.0.50

### ISSUE THREAD

**Issue by anlar** [vanilla-music/vanilla#565]
Hi,
I know there was an issue related to files without metadata which is marked as fixed in v1.0.49. Currently I'm using v1.0.50 from F-Droid and when I'm trying to open any file downloaded by NewPipe via Files tab there is a popup saying "0 track playing".

**Comment by adrian-bl** [comment]
* Please provide a logcat
* Is the stock media player of your phone able to play the file?

**Comment by anlar** [comment]
- That's what happening after I'm pressing on webm file: https://gist.github.com/anlar/a22d9e98cae819118c6c382ef6edacc5
- Yes, these files visible/playable in stock Videos app.

**Comment by adrian-bl** [comment]
So does the file contain a video stream?
We will never try to play videos, we only play a file if it contains (only) an audio stream

**Comment by anlar** [comment]
>  We will never try to play videos, we only play a file if it contains (only) an audio stream

Is it always worked that way? I can't get old version from F-Droid already, but I do believe that prior to issues with missing tags (around v1.0.46) I've played videos from NewPipe in Vanilla.

I've tried to download only audio (m4a with single aac track) and it's failing on loading:

```
V/VanillaMusic(16695): Loading coverart for 2199609594610100261 1655987094515250 /storage/emulated/0/Music/NewPipe/RTRT_Mili.m4a failed with exception java.io.FileNotFoundException: No entry for content://media/external/audio/albumart/31
D/MediaPlayer[JAVA](16695): broadcasting MEDIA_CHANGE_PLAYER_STATE : reset
E/LGBluetoothAvrcpManager( 1600): [BTUI] onReceive()... com.lge.intent.action.MEDIA_PLAYER_STATE_CHANGED
D/LGBluetoothAvrcpManager( 1600): [BTUI] checkSendAvailableState
D/LGBluetoothAvrcpManager( 1600): [BTUI]         Received Media Player State: 1 (IDLE)
D/LGBluetoothAvrcpManager( 1600): [BTUI]         Current AVRCP State: 2 (PAUSED)
D/LGBluetoothAvrcpManager( 1600): [BTUI]         Received Uri: null
D/LGBluetoothAvrcpManager( 1600): [BTUI]         mUri is null
D/LGBluetoothAvrcpManager( 1600): [BTUI]         mUriString is null
D/LGBluetoothAvrcpManager( 1600): [BTUI]         return : 2 (1:skip, 2:update)
D/LGBluetoothAvrcpManager( 1600): [BTUI] savePlayStatusData
D/LGBluetoothAvrcpManager( 1600): [BTUI]         uri: null
D/LGBluetoothAvrcpManager( 1600): [BTUI]         state(before): 1 (IDLE)
D/LGBluetoothAvrcpManager( 1600): [BTUI]         state(after): 0 (STOPPED)
D/LGBluetoothAvrcpManager( 1600): [BTUI]         position: 0
D/LGBluetoothAvrcpManager( 1600): [BTUI]         duration: -1
D/LGBluetoothAvrcpManager( 1600): [BTUI]         sys time: 1489601009368
E/LGBluetoothAvrcpManager( 1600): [BTUI] updateAvrcpPlayStatus : com.lge.intent.action.MEDIA_PLAYER_STATE_CHANGED
E/LGBluetoothAvrcpManager( 1600): [BTUI] updateAvrcpMetaData : com.lge.intent.action.MEDIA_PLAYER_STATE_CHANGED
D/LGBluetoothAvrcpManager( 1600): [BTUI] skip update... not playing state
V/MediaPlayer-JNI(16695): reset
```

**Comment by adrian-bl** [comment]
We never attempted to pick up videos and m4a files downloaded by newpipe work fine on my phones.

Your logcat only shows some bluetooth related errors - arent there any MediaPlayer errors? I'd also expect VanillaMusic to log an exception.

Also: Is the stock music player able to play m4a files written by newpipe?

**Comment by anlar** [comment]
When I'm trying to play audio file: https://gist.github.com/anlar/a073e70ae153204b7b1a7b418b9eabf1

It's failing the same way in Music app, only third-party players are able to play it.

**Comment by adrian-bl** [comment]
If the stock app fails, then there is not much we can do as the native media player is unable to play the file.

**Comment by utack** [comment]
@anlar workaround is to get the vorbis audio, you can change that in the NewPipe settings
