### ISSUE TITLE
Vorbis(.ogg) files are not enqueued when using the 'play' button on a folder

### ISSUE THREAD

**Issue by Egam12** [vanilla-music/vanilla#566]
Long-pressing a folder in the 'files' tab, and selecting 'play', 'play next', 'enqueue', or 'add to playlist' will add any .mp3 files in their respective ways, but seems to ignore .ogg files. 

This issue is present in the currently newest release, version 1.0.50, and seems to be present in previous versions as well.

**Comment by kirbyfan64** [comment]
Are you sure they aren't actually OPUS? IIRC there have been a ton of issues filed in the past because Android doesn't support OPUS.

**Comment by Egam12** [comment]
Very sure. I actually transcoded an mp3 to vorbis using ffmpeg to test it.
(used the command: ffmpeg -i track1.mp3 -c:a libvorbis track1.ogg )

To clarify, it plays fine if I just add the individual song, but adding the folder doesn't work.

**Comment by adrian-bl** [comment]
The file is not indexed (= Android missed that the file got added): go to settings > medialibrary and start a scan (use 'scan full filesystem' if the normal scan doesnt help)
