### ISSUE TITLE
[Feature Request] Allow music to be scanned into the library from selected Android/data paths.

### ISSUE THREAD

**Issue by spark4160** [vanilla-music/vanilla#570]
This is regarding my pull request #569.

Since d2c54eeb2a395d74cdd2d02ca277d4ad37a0ad1a (I think), my music has not shown up in the library (I've been using the files tab instead). This is because I use syncthing to get my music onto my phone's SD card, but syncthing can only write within its data folder on removable storage (/storage/6BA1-35CD/Android/data/com.nutomic.syncthingandroid/files/Music in my case). This path is blacklisted so vanilla does not add any files inside to the library.

**Comment by st3rk** [comment]
I'm encountering the exact same issue, /storage/*/Android/data/ seems to be blacklisted. Hopefully it is still possible to use the file navigation, but it is painful to add the tracks one by one.

**Comment by adrian-bl** [comment]
I'll try to finish this during easter holidays.

**Comment by adrian-bl** [comment]
Closing this as the code to select folders to include/exclude in scans has been merged and is already in the latest nightly build:

Go to Preferences -> Media Library -> Edit.

Folders can now be in 3 states:

Neutral (eg: do nothing special)
Included (Start a scan from there)
Excluded (Stop scanning there)

This gives you the ability to 'unblacklist' Android/data or (even better!) keep it blacklisted but include '/storage/6BA1-35CD/Android/data/com.nutomic.syncthingandroid/files/Music'

**Comment by spark4160** [comment]
Thanks, works great.

**Comment by adrian-bl** [comment]
Thanks for the feedback: great to know that it solves the syncthing issue
