### ISSUE TITLE
Slow when choosing folders since 1.0.47

### ISSUE THREAD

**Issue by zenny565555** [vanilla-music/vanilla#571]
Since version 1.0.47 up until the latest nightly, Vanilla Music has been slow. If I try to choose a folder in the Artists or Albums section and it's a large folder it takes 5 seconds to show. I went back to 1.0.46 and it's back to being fast (folders show almost instantly) I noticed that it maybe to do with the new scanner that was built in 1.0.47

Does anyone have a solution?

Huawei Honor 6 
Android 4.4.2
Vanilla Music downloaded through F-droid App, except the nightly builds.

**Comment by adrian-bl** [comment]
So are you using the Folder tab or the normal library tabs?

How big is your library? (How many songs?)

**Comment by zenny565555** [comment]
Normal library and about 1942 songs.

**Comment by zenny565555** [comment]
When I open a small album it's fast. Trouble is with an album of large mp3's range from 30MB to 90MB's

**Comment by adrian-bl** [comment]
1942 songs are not that much: I have about 6'000 songs on my device.

Do you have root on your device? If you do, then a copy of /data/data/ch.blinkenlights.android.vanilla/databases/media-library.db would be helpful.

**Comment by zenny565555** [comment]
No root.

**Comment by adrian-bl** [comment]
Ok, so could you give the nightly build a try? (See http://vanillamusic.io)

Enabled SQL debug there: after installing it, please:

* wait for the initial scan to finish
* start 'adb logcat | grep VanillaMusicSQL'
* Open a few slow items
* Post the output somewhere at gist.github.com

This should give us a clue which queries are so slow on your device.

**Comment by zenny565555** [comment]
I now have the nightly build. The initial scan took a long time(1 hour= number of tracks reads 4768. Now, How do I start 'adb logcat | grep VanillaMusicSQL'
I'm not that familiar with advanced things like this.

**Comment by kirbyfan64** [comment]
@zenny565555 

- Download and extract the [Android platform tools](https://developer.android.com/studio/releases/platform-tools.html).

- Follow [these instructions](https://www.howtogeek.com/129728/how-to-access-the-developer-options-menu-and-enable-usb-debugging-on-android-4.2/).

- Plug your phone in to your computer.

- Go to the folder where you extracted the platform tools, shift+right click on the file browser, hit "Open Command Window Here". 

- Type `adb logcat -e VanillaMusicSQL > logcat.txt` and hit Enter.

- Follow @adrian-bl's other directions:

  > - Open a few slow items

- Close the command window.

- Upload `logcat.txt` somewhere.

**Comment by adrian-bl** [comment]
ping.

**Comment by adrian-bl** [comment]
No reply: closing this.
