### ISSUE TITLE
Wrong cover art for album-less songs, but only on lock screen

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla#572]
**Me:** "Hey, let me listen to this song I wrote a while back!"

[![Screenshot_20170327-203230.png](https://s5.postimg.org/ye94vo4cn/Screenshot_20170327-203230.png)](https://postimg.org/image/fyony9q83/)

*turns off phone, turns back on a few seconds later*

[![Screenshot_20170327-203237.png](https://s5.postimg.org/xd8w6jnd3/Screenshot_20170327-203237.png)](https://postimg.org/image/6fez4t2pv/)

What the...

**Comment by adrian-bl** [comment]
Does this always happen if we switch from a Song with cover to one without a cover while the screen is off?

I know that the firmware on some (Samsung?) Android 4.x devices was buggy where the cover simply would get stuck.

This is the related code:
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/RemoteControlImplLp.java#L144

We either pass the cover bitmap or null to the OS.

**Comment by adrian-bl** [comment]
friendly ping

**Comment by kirbyfan64** [comment]
It...randomly stopped happening?

Here's my guess:

I had part of the Xenoblade X OST on my phone. Later on, I re-ripped the tracks, but the artist name became incorrect without me realizing it (so that there were no cover art matches), although the album name stayed the same. Then I removed all the old tracks.

I'm thinking that, since I removed all the old ones at the same time as getting the new ones, Vanilla got confused. It still had the cover art saved because the album name was the same, but the songs from which it got the cover had disappeared.

FWIW I always change tracks manually, e.g. turn on the screen, select a new track, turn it off again.

Oh, and is it supposed to take anywhere between a few minutes to overnight for cover art changes to appear in the thumbnails?

**Comment by adrian-bl** [comment]
> but the artist name became incorrect without me realizing it

This shouldn't have any effect as we group albums by album string: Multiple Songs by different Artists on the same Album all share the same album_id.

> It still had the cover art saved because the album name was the same, but the songs from which it got 
> the cover had disappeared.

Hmm.. We cache covers in different resolutions - so if there are any changes while we didn't cache both, they may get 'out of sync': eg: the large cover is version A while the small one is version B. But it seems that this also didn't happen here as the lockscreen and the playback view both use the same (large) cover.

I still suspect that this is a strange bug in the lockscreen itself where android got stuck on a cover as both the PlaybackView and the lockscreen-code use exactly the same code to fetch the cover.

> Oh, and is it supposed to take anywhere between a few minutes to overnight for cover art changes to 
> appear in the thumbnails?

Yes: There are two caches:

The in-memory cache which caches up to 15MB (and will get emptied if vanilla music gets evicted from memory) and the on-disk cache which caches covers up to 8 days.

Hint: toggling the checkboxes in 'Cover Art' will flush the on-disk cache, so every cover will get re-read the next time vanilla music starts up.

**Comment by adrian-bl** [comment]
Closing this as i didn't see this on any of my devices and we already know that your phone is possessed :-)

**Comment by kirbyfan64** [comment]
...at this point I'm pretty sure this has to be a bug somewhere. I've noticed it's pretty much always when I make weird changes to song tags after the songs have already been indexed?

Here's a new interesting combo:

![](https://s5.postimg.org/89bufflzb/Screenshot_20170926-200744.png)
