### ISSUE TITLE
[Feature Request] Comment Search

### ISSUE THREAD

**Issue by InstallGentoo11** [vanilla-music/vanilla#573]
Can you make it so comments can be searchable as well?
This is what I am talking about:
![untitled](https://cloud.githubusercontent.com/assets/6108677/24521778/eb7de3a6-1595-11e7-936e-7e6a626a6877.png)

**Comment by Adonai** [comment]
And Vorbis ones too, not only ID3!

**Comment by adrian-bl** [comment]
I do not think that this would be a good feature as displaying search results for a field which we are never showing would be confusing.

**Comment by InstallGentoo11** [comment]
It is the prime place I use for the main tags I use, that don't really fit in any other place. I doubt anyone would be that massively confused. And it will really require me to edit a lot of songs to make them searchable the way I am used to. At the very least can't you put it as something that people can turn on themselves from the option?
