### ISSUE TITLE
Show scanner progress beginnig of the line

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#576]
Please show the scanner progress at the beginning of the line. Now it is at the end of the line and because the file path varies in length, the progress jumps too much from left to right and vice versa to follow the progress with ease. Also use leading zeros in order to keep the progress at exactly the same place on the screen.

Currently it is e.g.:

    /storage/emulated/0/Music/a/b/c.mp3 (9 / 678)
    /storage/emulated/0/Music/a/b/d.mp3 (10 / 678)

Proposal is:

    009/678: /storage/emulated/0/Music/a/b/c.mp3
    010/678: /storage/emulated/0/Music/a/b/d.mp3

**Comment by adrian-bl** [comment]
The numbers are just some debugging leftovers anyway. Commit 
https://github.com/vanilla-music/vanilla/commit/fee64685bd1b33162a24ce36a4002746816c1863 changes the preferences to use the same progress bar as the widget.
