### ISSUE TITLE
Swiping music is laggy

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#578]
I just bought a Samsung Galay S5 4G+ (SM-G901F Kit Kat) and I'm encountering an issue that I had not in my Sony Xperia V (LT25i Jellybean).

When I swipe in now playing screen (to play next or previous song) there is an annoying lag, **especially when vanilla is playing a song** (it's better when paused).

I have tried with several vanilla and vanilla nightly versions since 1.0.40 until 1.0.51, its the same.

Please look at this screen record video to see the issue **https://youtu.be/tf789H_p-Y4**

Do anyone have a similar issue or an idea of the origin of the lag ? (nothing to do with the covers btw)

Thanks

PS : I must specify that on my Xperia V, **I have also this problem, but ony with the last version of vanilla**

**Comment by adrian-bl** [comment]
Hmm.. we are probably doing something which is expensive on your phone in the UI thread while the swipe animation runs. Will be fun to debug this :-/

**Comment by andiandi13** [comment]
That would be quite surprising for a quad-core phone with 2,5ghz and 2GB RAM   :O

And the strangest is that on an old Xperia V from 2013, it's smooth with 1.0.4X versions but not on an S5...

**Comment by adrian-bl** [comment]
> That would be quite surprising for a quad-core phone with 2,5ghz and 2GB RAM :O

We are probably not really CPU bound in this case - and phones can be bad. My Moto X Play takes *seconds* to index some simple ogg files which my old sony phone indexed within 10ms.

**Comment by andiandi13** [comment]
Hmm ok it's interisting to know it...

**Comment by adrian-bl** [comment]
Could you give this version a try please: https://drive.google.com/open?id=0Byx0H5q6Z7OCWEN3cGplWVl6bHM ? (Signed with a debug key, so you must uninstall the existing version first).

This buts some work in a new background thread: Does it make scrolling any better?

**Comment by andiandi13** [comment]
It's still laggy but in a different way. Please take a look : https://youtu.be/h2hkJ8WElcA

Sometime, there is like a "teleportation" effect in the cover (at 7-8 sec for instance).

I think the new one is a **little** less laggy when we compare the two, but that teleportation effect can be quite strange, its like the cover is "late" and then "accelerate".

**Comment by adrian-bl** [comment]
So i played yet again with this - feel free to give this version a try:
https://drive.google.com/open?id=0Byx0H5q6Z7OCenIxdDBoZkdhLUk

Scrolling is much better on my android 4.x device with this (note: this is a NON-nightly build, but signed with my debug key, so it conflicts with the f-droid and play-store version. But it can be installed alongside the nightly build)

**Comment by andiandi13** [comment]
@adrian-bl I tried it and its way better, no more lags.

Before http://youtu.be/4t2dZgE_ojk

After http://youtu.be/y9QqJ20R8X4 (you can see small lags in the video but there isn't any in reality, maybe because of the FPS)

There is just a little thing : Before I was able to fastly swipe songs (with an ugly black background before the cover came back :p), and know I have to wait for the cover to be fully centered (until the animation is over I mean) before the scroll can continue.

Well, Its not a big deal since I can quickly change songs with "Next" button.

**Comment by adrian-bl** [comment]
> I tried it and its way better, no more lags.

Cool, glad to hear that things got better!

> Before, I was able to fastly swipe songs (with an ugly black...

Yeah: the test version didn't allow swiping while the animation is running - the updated version (see below) improves that.

> Edit : I noticed an other "side effect" of the new scroll, bigger than what I just said : when it load 
> songs in Random mode, the duration between you press "Next" and the cover appears is longer 
> than before.

We are now doing more work in the background, so this is a side effect. The updated version at https://drive.google.com/open?id=0Byx0H5q6Z7OCenIxdDBoZkdhLUk (same link as previous) should improve this.

**Comment by andiandi13** [comment]
OK so the random mode is perfect now.

But two I have two thing to say :

The first thing is that in the 2 debug versions, Vanilla also have to wait until the animation of the cover is finished to change the song (display title), look here how the title is delayed :

http://youtu.be/u67Z8JwHIqM

And look how it was before (the tile appeared far before the cover animation was over) : 

http://youtu.be/2jFHrAPTJHk


The other thing(s) is that before, I really felt that the cover was following my finger while swiping, but now its SUPER sensitive + the animation is a bit slow :

http://youtu.be/VfYi7dhoVo4

Just a little swipe and the cover is gone.

I don't know if you fell that, but when I swipe, I feel like "OK I swiped, and now I'm waiting for the animation".

It would be cool if you can somehow synchronize the animation with the movement of the finger.

**Comment by adrian-bl** [comment]
> The first thing is that in the 2 debug versions, Vanilla also have to wait until the animation of the cover 
> is finished to change the song

Yes, this is a trade off we make for the smoother animation: Low end phones turn out to just be to slow to load a new song while the animation is playing.
The only option to avoid this would be to switch to OpenGL, which i kind of don't feel like doing - at least right now :-)

> The other thing(s) is that before, I really felt that the cover was following my finger while swiping, but 
> now its SUPER sensitive (look at the white circle when I touch) + the animation is a bit slow :

I agree: The values were a bit off: i updated the version stored on Google Drive and things should be better now.

> I don't know if you feel it, but when I swipe, I feel like "OK I swiped, and now I'm waiting for the 
> animation".

This should also be fixed in the new version: Aborting the swipe will cause the song to be switched instantly, just like it was before.

**Comment by adrian-bl** [comment]
> When I compare the old and new versions, there is still a little difference. Do you change the 'bounce' 
> or 'deceleration' of the cover in the code ?

No, the animation should be the same. Maybe it just feels different because the old one stalled for a few milliseconds at the beginning?

Maybe i'll play with a different animation at some point, but i merged the code to the master for now as-it-is.

**Comment by andiandi13** [comment]
Ah yeah maybe the lag confuse me. I'll check it on another device one day and I'll let you know if there is difference. 

For now it's good ;)

Nb : The nightly comes today ?

**Comment by adrian-bl** [comment]
Yes, its usually built around 20:00 UTC

**Comment by adrian-bl** [comment]
Closing this: Has been included in the latest release and seems to work fine!
