### ISSUE TITLE
[Feature Request] Comment Search

### ISSUE THREAD

**Issue by InstallGentoo11** [vanilla-music/vanilla#579]
Can you make it so comments can be searchable as well?
This is what I am talking about:
![untitled](https://cloud.githubusercontent.com/assets/6108677/24521778/eb7de3a6-1595-11e7-936e-7e6a626a6877.png)
"I do not think that this would be a good feature as displaying search results for a field which we are never showing would be confusing."
Can't you put it as something that people can turn on themselves from the options? It is the place I put the main tags I use, that don't really fit in any other place. I doubt anyone would be that massively confused anyway.
I am sorry for posting this again, but you could have let it live for a little bit longer so there could be some discussion and not just shut it down.
Regardless, thank you for you work.

**Comment by adrian-bl** [comment]
> Can't you put it as something that people can turn on themselves from the options?

No, because we would end up with 1000 options.

I'm sorry - but this is simply not going to happen.

**Comment by InstallGentoo11** [comment]
Not if you put things that make sense and actually helping people to find their songs seem like one such a thing. As a whole the app seems to lack the option to let you see more detailed info about songs, which is something I doubt people haven't complained about before and I don't see how it could bee seen as not enough important to add. Like being able to make some of the swipes to show you all the metadata.

**Comment by Adonai** [comment]
I doubt BASTP actually can show all the metadata...

The point Adrian tries to make is that each option, each switch exponentially increases count of test vectors. Don't suggest it as an optional feature, or each new one potentially touching this code will have to be tested with each switch turned on and off. All the combinations of these switches will pile up and you'll end up with users complaining about instability and bugs.

**Comment by InstallGentoo11** [comment]
All android players lack this or other basic features. It is honestly frustrating that there is not even one that can do the job of a simple music player on the PC, even if we don't count the editing ones, but just the ones that let you view stuff.
As good as this app is compared to many others this is a big minus for me and it is very unfortunate that there doesn't seem to be the will to improve it in such a way.

**Comment by kirbyfan64** [comment]
Yet, a music player on the PC has significantly more CPU and RAM to burn through in the process...

**Comment by adrian-bl** [comment]
> As good as this app is compared to many others this is a big minus for me and it is very unfortunate that 
> there doesn't seem to be the will to improve it in such a way.

As already explained: If i had implemented every requested feature, we would be a Video Player which also includes a web browser by now. (no joke).

I simply do not see the point in searching content we are not displaying - and indexing comments would come at a cost of having to maintain more code AND putting more stress on the sqlite database.

I am therefore closing this as wontfix.
If you really need this feature, you can always implement it yourself and run your own fork.
