### ISSUE TITLE
When swiping up in the files tab to the queue, the home directory button is still there

### ISSUE THREAD

**Issue by david-sawatzke** [vanilla-music/vanilla#580]
![photo5438456649154144178](https://cloud.githubusercontent.com/assets/11035569/25000704/9823f274-2042-11e7-82a5-e7af0c83b4f1.jpg)

**Comment by adrian-bl** [comment]
Thanks for the bugreport: should be fixed in https://github.com/vanilla-music/vanilla/commit/58068fb9ca6ca05d863c3cde93963855e5660f0b
