### ISSUE TITLE
The mysterious case of the missing .mp3

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla#583]
https://drive.google.com/file/d/0B3RBF3Zy7CAXeTQtNzMycGxoQlU/view?usp=drivesdk

It somehow doesn't appear. I'm using built-in tag scanner. Only track I have that does this...

**Comment by adrian-bl** [comment]
This works for me on Android 4 with the internal tag reader.

Did you try to do a full rescan of the library? Maybe android failed to pick up the file, so we will only find it during a scan of the full filesystem.

**Comment by kirbyfan64** [comment]
Haha, it magically appeared. Even though I did three *full* rescans (one of them was a flush, too)...

At this point, considering that I'm dealing with:

- Swapped cover art (#572).
- mp3 files that literally duplicate themselves (I delete them, couple of days/weeks later, another random batch gets duplicated).
- Colors on the lock screen getting inverted whenever Vanilla is open and I get a cat through Android Neko.

I'm just going to assume that my phone is possessed...
