### ISSUE TITLE
albums with the same name

### ISSUE THREAD

**Issue by trmendes** [vanilla-music/vanilla#584]
When I go to an Artist and click on it Vanilla will show me a list of all the albums from that artist. If that Artist has a album by the name of "Greatest hits" and I click on it Vanilla will show me all the songs from that album plus all the songs from any album or artist that has an album with the same name.

 It would be nice to see the musics from that specific album and artist only.

**Comment by adrian-bl** [comment]
You can configure this in Settings > Media Library > Group albums by folder.

Enabling this will make sure that albums in different folders are not merged.
