### ISSUE TITLE
[Suggestion] Disk image change

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#585]
Hi.

I want to propose a new image for the "no cover" disk, when playing and when scrolling files. 
I mean these two:

https://image.noelshack.com/fichiers/2017/16/1492888100-screenshot-2017-04-22-21-01-40.png

https://image.noelshack.com/fichiers/2017/16/1492887981-fallback-cover.png

There are too "old school" and I want to do a cool and very simple material design-like thing.

I can provide it in svg, svgz, and in png (any resolution).

Thanks

**Comment by andiandi13** [comment]
Ok, so I worked on a "fallback_cover" since my first message, here is how it looks like :

https://image.noelshack.com/fichiers/2017/16/1492904522-fallback-cover192.png

**A before/after picture inside vanilla** : https://image.noelshack.com/fichiers/2017/16/1492904532-screenshot-2017-04-22-23-32-41.png

In my opinion its better like that, there is more space between each disk, its clearer and looks more "modern".

Please give me your opinion about it.

PS : I wonder where is the "now playing" disk image in the apk ? it seems that its not an image but an xml or something like that ?

**Comment by kirbyfan64** [comment]
Looks like an eye staring at you...

**Comment by andiandi13** [comment]
Maybe its better with dilated pupil :smile: 

https://image.noelshack.com/fichiers/2017/16/1492955780-fallback-cover2048x2048-v2.png

I'm waiting for Adrian's view.

**Comment by adrian-bl** [comment]
Hmm.. i played with a similar icon some months ago and it always (and still does) looked .. odd to me.

How about a music note instead of a disc?

Nb: The image in the playback view is dynamically created by CoverBitmap: generateDefaultCover

**Comment by andiandi13** [comment]
It sounds good to me. I saw it in several players and its cool. 
I'll work on it and show you the result.

PS : Ok, and what do you think about straighten up the cover in playback view like that : https://image.noelshack.com/fichiers/2017/17/1493056750-covertest.png

Good ? still odd ?

**Comment by andiandi13** [comment]
So, what do you think of that : 
https://image.noelshack.com/fichiers/2017/17/1493064345-fallback-cover.png
https://image.noelshack.com/fichiers/2017/17/1493064348-screenshot-2017-04-24-21-54-54.png

**Comment by adrian-bl** [comment]
Looks nice: do you have an svg version of it?
How does it look on white (lollipop) background?

**Comment by andiandi13** [comment]
Yes, svg and svgz : 

- https://drive.google.com/open?id=0B7yLYKIM8DZYdGdHR2ozMUtHdE0
- https://drive.google.com/open?id=0B7yLYKIM8DZYeGxFQ1VCR1hLUmM

Actually, I was wondering on the result on Lollipop too, but I'm on Kit Kat...

But I compiled an APK if you (or somebody) can test it : https://drive.google.com/open?id=0B7yLYKIM8DZYaGM4OXltSl9CMzg

**Comment by andiandi13** [comment]
In fact, I matched the background with the action bar as you can see : http://2.1m.yt/9KmggF6.png

So with multiple themes in Lollipop, I'll have to change it, I guess.

**Comment by adrian-bl** [comment]
Well, i guess its ok to have a dark background: the current icon does the same

**Comment by andiandi13** [comment]
Ok fine :)

Concerning the cover in playback view, you said that its dynamically created. But is it possible to create (dynamically) any form, I mean that same music note as it happens ?

**Comment by adrian-bl** [comment]
Yes, i just have to write code to draw the note, its like drawing an svg in a text editor.

Btw: what is the license of the note graphic? Did you draw it yourself?

**Comment by andiandi13** [comment]
Yes, I drew it with Illustrator as always.

And by the way, I'd like to draw others icons as well (like materialize the main icon etc..). 
Is there a better place to talk than this issue topic (why not outside github) since its not "issues" and not really convenient ?

**Comment by adrian-bl** [comment]
> Yes, I drew it with Illustrator as always.

Ok, cool!

I tested our SVG on Lollipop and IMO it looks a little bit too dark (left side), so i changed the colors to material grey 400 & 800 (middle + right):

![image](http://i.imgur.com/biRStCd.jpg)

What do you think?

> Is there a better place to talk than this issue topic (why not outside github) since its not "issues" and 
> not really convenient ?

I don't mind using the issuetracker for this (But maybe open a new issue)

**Comment by andiandi13** [comment]
Yes it seems better. Can you send me the apk too see the result on KitKat ?

**Comment by adrian-bl** [comment]
Sure: https://drive.google.com/open?id=0Byx0H5q6Z7OCRUd6UFBiSmNUYjQ

**Comment by andiandi13** [comment]
Thanks. 
So the color looks good on KK, we can keep it.

**Comment by adrian-bl** [comment]
Ok: i commited this, so it should be included in the next nightly (still need to replace the generated version in the FullPlaybackActivity)

**Comment by andiandi13** [comment]
Ok cool !

**Comment by adrian-bl** [comment]
Finally got around to also replace the cover in the full playback activity - closing this as it will be included in the next nightly (hopefully it looks ok on KK, only tested it on Marshmallow)
