### ISSUE TITLE
New main icon

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#587]
Hi, as planned I opened a new topic.

I worked on two styles of the main icon.

**Icon 1 :**

![style1](https://cloud.githubusercontent.com/assets/19387072/25649778/398c2d08-2f8d-11e7-85af-691f8a23f960.png)

**Icon 2 :**

![style2](https://cloud.githubusercontent.com/assets/19387072/25649780/3c1192a2-2f8d-11e7-8992-87f9e811802b.png)

@adrian-bl : Do you like it ? if so which one do you prefer.

**Comment by ToNIX-** [comment]
I prefer the first one.

**Comment by andiandi13** [comment]
@ToNIX- : Thanks for your opinion

**Comment by Adonai** [comment]
@andiandi13 , kind sir, in case it works out can you also suggest similar icons for plugins?

**Comment by andiandi13** [comment]
@Adonai yeah it'll depend but why not

**Comment by adrian-bl** [comment]
I'd prefer #2, but hiw about making the circle in the middle lighter? It looks kind of a headphone jack to me :-)

**Comment by andiandi13** [comment]
Yeah true, is it better like that :

https://image.noelshack.com/fichiers/2017/18/1493743423-style3.png

**Comment by adrian-bl** [comment]
Yes, i think style #3 looks pretty good.

Did you test it in inkscape/generate_pngs.sh? Do the sizes match the old version?

**Comment by andiandi13** [comment]
As I said in another issue, I don't really know how to use .sh files.
I generate pngs with a .bat file that uses Inkscape though.

And I made the svg of the icon the exact same size (object+artboard) as the original, so it shouldn't be any issues :)

**Comment by adrian-bl** [comment]
> And I made the svg of the icon the exact same size (object+artboard) as the original, so it shouldn't be 
> any issues :)

Ok, so as long as the DPI are the same, the icon size should be fine.

Feel free to upload it (or send a pull request), i'll then add it to the master branch.

**Comment by andiandi13** [comment]
> Feel free to upload it (or send a pull request), i'll then add it to the master branch.
(The SVG is enough, i'll create the pngs locally)

The svgz of the main icon is here :  https://drive.google.com/open?id=0B7yLYKIM8DZYa1RGTzVEeW9EM1k

Also, all the icons of the control bar that I've scaled down are in this zip file : https://drive.google.com/open?id=0B7yLYKIM8DZYdVNtZmRULThaMkE

It'll be cool if you can add them all in the code for the next nightly.

**Comment by adrian-bl** [comment]
Cool, thanks: i pushed them to master

**Comment by adrian-bl** [comment]
Closing this as the new icon is already included in the latest nightly builds.
