### ISSUE TITLE
[Suggestion] Various icons modifications

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#588]
Hi.

First of all I think that it would be nicer and more relevant to change the Previous/Next icon (control bar) with only one "triangle" instead of two. 
The two triangles with a bar is mostly used when the button can fast forward/backward AND skip to next/previous song. Here, its only used to skip and could be confusing at first use.

https://image.noelshack.com/fichiers/2017/18/1493688948-nextpreviousnewicon.png

Then, in most of material designed music apps the play button is bigger than the rest. I thought about reducing others icon and it looks like that :

https://image.noelshack.com/fichiers/2017/18/1493689112-beforeafter.png

That is all for now...

@adrian-bl : What do you think ?

**Comment by Adonai** [comment]
This was supposed to be part of material design icon set modernization (that never happened).
Looks good, many people were waiting for it.

**Comment by samcompz** [comment]
great.

**Comment by adrian-bl** [comment]
LGTM!

**Comment by andiandi13** [comment]
@adrian-bl Fine :) Can I have all the control bar SVG files, so that I can resize them, please.

**Comment by adrian-bl** [comment]
They are in the orig/ folder.

**Comment by adrian-bl** [comment]
And you can regenerate the pngs via ./generate-pngs.sh (requires inkscape)

**Comment by andiandi13** [comment]
Ok, thank you

**Comment by andiandi13** [comment]
Ok so I finished the icons, the svgz are [here](https://drive.google.com/open?id=0B7yLYKIM8DZYdVNtZmRULThaMkE)
And the PNG's [there](https://drive.google.com/open?id=0B7yLYKIM8DZYV3JhTmJtdWZMdTQ)

@adrian-bl I'm not too familiar with coding though, so for the PNG's I used a .bat script which use Inkscape :


> @ echo off
> set INKSCAPE_EXE="C:\Program Files\Inkscape\inkscape.exe"
> 
> echo
> set /p svgFile="Filename (without extension) ? "
> 
> IF NOT EXIST %svgFile%.svgz (
> echo The file %svgFile%.svgz does not exist
> pause
> exit
> )
> 
> echo --------------------------------------
> echo Generating mdpi (32x32)...
> %INKSCAPE_EXE% -f %svgFile%.svgz -e %svgFile%_mdpi.png -h 48 -w 48
> echo Generating hdpi (48x48)...
> %INKSCAPE_EXE% -f %svgFile%.svgz -e %svgFile%_hdpi.png -h 72 -w 72
> echo Generating xhdpi (64x64)...
> %INKSCAPE_EXE% -f %svgFile%.svgz -e %svgFile%_xhdpi.png -h 96 -w 96
> echo Generating xxhdpi (96x96)...
> %INKSCAPE_EXE% -f %svgFile%.svgz -e %svgFile%_xxhdpi.png -h 144 -w 144
> echo --------------------------------------
> echo Finished
> echo --------------------------------------
> pause
_

I don't really know if its the same result, but I compiled the apk and its 100% normal.

![screenshot_2017-05-03-07-05-31](https://cloud.githubusercontent.com/assets/19387072/25648702/9fba57d0-2f83-11e7-905d-c812321958c9.png)
![screenshot_2017-05-03-07-08-51](https://cloud.githubusercontent.com/assets/19387072/25648733/064feb4a-2f84-11e7-9e05-a328dc4eeacd.png)

**Comment by andiandi13** [comment]
Update : 
 
@adrian-bl Is it possible to increase control bar height, so that
it'll be more centered and less stuck to the bottom ? I mean :
![before](https://cloud.githubusercontent.com/assets/19387072/25649574/700e9480-2f8b-11e7-9d01-f5742669f0c8.png)

I will permit me to add a circle to the play/pause icon, for a much
more material design style (I would like to know your opinion on the
result, it looks great to me) :

![final](https://cloud.githubusercontent.com/assets/19387072/25649609/ca1776cc-2f8b-11e7-8ac6-1f6718e667c2.png)

**Comment by adrian-bl** [comment]
Changing the height should not be an issue (the existing code will auto adjust)

But i am not sure about the circle: why does it make things look more 'material' ;-)

**Comment by Adonai** [comment]
Adrian, are you familiar with Material Design? Google proposed it for all > Android 5.0 apps. 

Similar circular feedback can be found also in recent Chromium Aria UI and Qt QML Material-style widgets.

**Comment by adrian-bl** [comment]
A static circle isnt feedback.

I'm actually worried that it will clash with the ripple effect (= thing you see while pressing buttons in material apps)

**Comment by andiandi13** [comment]
Actually I was inspired first and foremost by the music player of Google (for Google is the creator of material design), and by other players that followed the trend of that circle button like Black player, Voltage, Pi, Phonograph, Stellio etc..)

![screenshot_2017-05-07-16-23-45](https://cloud.githubusercontent.com/assets/19387072/25782202/dafe443a-32fa-11e7-9e37-21fd4e46e877.jpg)

However, in my opinion you should never use the material design that Google provide (with all its effects, floating action button etc..) since it will make Vanilla consuming more RAM uselessly. 
Believe me, before choosing Vanilla as my main player, I compared the RAM consumption of hundreds of players from the play store, and Vanilla has the best features-consumption ratio !

Most of material design players have a terrible RAM consumption, even with poors features...

Anyway, all that to say that we should only work on icons and layout to me.


So we keep the normal play/pause button ?

And also, do you think we should use those open source icons that we see in almost every material design music app (for shuffle and repeat at least), Google use them too. ?

![material](https://cloud.githubusercontent.com/assets/19387072/25782355/1d0a3282-32fe-11e7-962a-9cfa78ca55d9.png)

Sorry for this massive post :)

**Comment by adrian-bl** [comment]
> So do we keep the normal play/pause button ?

We can give the circle version a try: having it displayed in the default accent color on Android 5 might actually look nice.

> And also, do you think we should use those open source icons that we see in almost every material 
> design music app (for shuffle and repeat at least), Google use them too.

Not sure: Do you think they look better than what we have now? I kind of dislike them as they look 'cold' to me.

**Comment by andiandi13** [comment]
OK so if I make a circle around play and pause svg, it should be fill with a certain color only or is there a particular svg filter to apply ?

I don't think there are better, they look a little bit too "angular" to me.
I'll make the old one thinner and try others style to see what we can do.

**Comment by adrian-bl** [comment]
> it should be fill with a certain color only or is there a particular svg filter to apply ?

I can apply a filter in code (we already do this to highlight the other two icons on Android >= 5 in custom colors). So the circle just needs to have an unique color (the grey would be ok)

>  I'll make the old one thinner and try others style to see what we can do.

Sounds good!

**Comment by andiandi13** [comment]
I gave a first try, but I can't see the result since eveything is white (because of the code I guess), here are the svg :

Play button : [download](https://drive.google.com/open?id=0B7yLYKIM8DZYbWNYX1JNWmplWGc)
Pause button : [download](https://drive.google.com/open?id=0B7yLYKIM8DZYSHdLRDQtR1BmRGc)

So are you going to change some lines, or I have to do something in particular in the svg ?

**Comment by adrian-bl** [comment]
That's because we handle icons as '1 bit' in the playback view:

The icon is loaded and every non-transparent pixel is replaced by a color, depending on the theme and android version (so we do not end up with 3000 variants of very icon).

This now fails badly with the play icon - we probably have to think about some other approach to style the color at runtime :-/ (i excluded the play/pause icons from the update for now until we have a solution)

**Comment by adrian-bl** [comment]
Hmm.. one solution might be to just have the code draw the circle - this would also make it simpler to use the 'primary color' on Android >= 5.x

**Comment by adrian-bl** [comment]
Also note that i'll be on a business trip for ~2 weeks, so dont expect any reply for me in the next few days

**Comment by andiandi13** [comment]
> Hmm.. one solution might be to just have the code draw the circle - this would also make it simpler to use the 'primary color' on Android >= 5.x

Yes like the playback cover, it seems to be a good idea.

> Also note that i'll be on a business trip for ~2 weeks, so dont expect any reply for me in the next few days

Ok fine :)

**Comment by andiandi13** [comment]
# - Several new modifications:

 ### 1. The "repeat once" number to a more simple thing :

![sans titre 1](https://cloud.githubusercontent.com/assets/19387072/26282120/6f414b14-3dbf-11e7-9d27-6ee224d913da.png)



### 2. The parent folder icon :

![gg](https://cloud.githubusercontent.com/assets/19387072/26282130/bca386c4-3dbf-11e7-88f2-2e1f44d01344.png)

### 3. Shuffle and Repeat icons : 

![sdsdd](https://cloud.githubusercontent.com/assets/19387072/26282187/da914b52-3dc0-11e7-95b0-e9fc96902e45.png)

The Shuffle icon isn't too rounded nor squared and the Repeat icon remains simple but less rounded than before.

The result would look like that (with a higher margin and the circle button as well)


![bbbbbb](https://cloud.githubusercontent.com/assets/19387072/26307624/6289fa10-3eaa-11e7-9124-d33cce4eb620.png)



So what do you think ?

# - Questions:  

### 1. Do you keep the holo icons on purpose for Android < 5.0 ? Isn't it better to put material icons for any firmware ?


![screenshot_2017-05-07-16-17-41](https://cloud.githubusercontent.com/assets/19387072/25783544/86c2e28c-3312-11e7-83af-c08ac49621ae.png)


### 2. It's a little bit off topic but the library screen of vanilla is often too crowed, so :

-> Is there a possibility, on one hand,  to get rid of the separation lines (especially on Holo firmwares !) like that :

![sdsdsd](https://cloud.githubusercontent.com/assets/19387072/26282634/cc288cc0-3dc9-11e7-9ad7-519287edd2a8.png)

-> And on the other hand, to scale down the album/artist text (which is the same size as the title despite that its less important and overloads the screen particularly with long tags) :

![vvvvvvvvvv](https://cloud.githubusercontent.com/assets/19387072/26282827/a898a750-3dcd-11e7-8f8b-4c1715f30d7d.png)

It looks more "modern" and clearer to me.
I choose a random text size, but in any case it'll also permit to have a less cut-off text when album names are long !

**Comment by adrian-bl** [comment]
Thanks a lot for your work: I like the new icons - feel free to upload them!

About the questions:

1: Yes, we keep the holo icons on purpose as we do not try to 'emulate' material design on 4.x devices - I feel that we should use the native icons if possible.


2: This 'crowded' design is only visible on Android 4.x and has been like this since 'forever'. But maybe it would be a good idea to use the same dimensions on 4.x as we do on 5.x (which is feels less 'cramped')

**Comment by andiandi13** [comment]
Its a pleasure to improve Vanilla :)

Ok, so all the icons are in the zip (I've also updated a little bit next/previous icons) : [Google Drive](https://drive.google.com/open?id=0B7yLYKIM8DZYSldVb0VJRzN1U2c).
I look forward to see the result in the next Nightly.

I think we're almost done, you've just to :

- Increase the control bar height
- Make a grey circle around the play/pause buttons
- Use the same dimensions as 5.x (It worth a try)

**Comment by adrian-bl** [comment]
Ok, finally got some time to work on this: I updated all icons from the last zip excluding the widget versions. These are also used in the Notification and having different sizes there looked not so nice IMO.

I also added code to draw the circle (commit: 57992bad25b6ade8a86323c9f3ee924d23c13cb5) behind the play/pause button.

I did some experiments:

These samples use the accent color:

![dark](http://i.imgur.com/Z0PTXr6.png)
![white](http://i.imgur.com/WAVIRCT.png)

And these are using material grey:
![dark](http://i.imgur.com/yxAuSJY.png)
![white](http://i.imgur.com/vUTjat6.png)

I went with the grey version for now as i didn't like the accent color in the white theme.

And this is Android 4.x:

![holo](http://i.imgur.com/I7RdTum.png)

What color did you intent to use for holo? It's probably too dark right now (i used `#f222`)

**Comment by adrian-bl** [comment]
Also made a version with slightly higher buttons (48 -> 52)

![image](https://user-images.githubusercontent.com/568734/26880217-fde270e6-4b93-11e7-9809-a4a0916cdade.png)

**Comment by andiandi13** [comment]
Thanks for your work.

Here are some new Play / Pause icons, centered and smaller, the old ones are really invasive imo : [Google Drive](https://drive.google.com/open?id=0B7yLYKIM8DZYNVB4Tzd1RUFQNVk)

For the colors: I also prefer the grey icon much more, whether in Material design or in Holo design and its indeed too dark in Holo. 
After some experiments I would suggest the **#4A4A4A** grey for holo

Also, I think that you should move all icons a bit more **upper** and **increase the circle size**.

## To sum up all this, it would look like that : 

![sdsdsd](https://user-images.githubusercontent.com/19387072/26906629-ce496122-4bee-11e7-90d4-5af63517adff.png)
![aaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/19387072/26906628-ce48cc8a-4bee-11e7-927b-48ab2cb8b39d.png)



However, I don't know if you have a limit in the margin since the control bar **has** a limit (64px in your image for example) and I would prefer an higher margin in Holo but would it affect the material margin ?

So what do you think.

**Comment by adrian-bl** [comment]
Thanks for the updated icons: But the play/pause button were slightly smaller than the next/prev buttons. Was this intentional? I adjusted them for now to be the same height.

I also added some padding to the buttons and things are now looking like this:

![image](https://user-images.githubusercontent.com/568734/26929223-273385a0-4c59-11e7-9f2c-563cc1858cb5.png)

**Comment by ToNIX-** [comment]
@adrian-bl That last screenshot looks amazing. Everything​ is aligned and centered.

Personally, I'd make the play/pause icon slightly bigger that the others.

**Comment by adrian-bl** [comment]
And this is Holo with the same spacing as Material:

![image](https://user-images.githubusercontent.com/568734/26929421-f06da40a-4c59-11e7-8b5e-a6f9f8dc687e.png)

**Comment by andiandi13** [comment]
It was intentional but ultimately I prefer yours. Is it perfectly centered though ?

Also, I partially agree with @ToNIX : The Play icon should be bigger BUT only if the **circle** also is bigger **as well as the control bar**. If that's impossible (especially because of the control bar) it'd looks too crowded.

I was thinking of something like that, tell me if its possible and what do you think.


![ff](https://user-images.githubusercontent.com/19387072/26942434-55ce3698-4c82-11e7-9212-257057d3bd50.gif)


Nb : The spacing in Holo looks amazing, thanks.

**Comment by adrian-bl** [comment]
> Is it perfectly centered though ?

It should be (unless inkscape fooled me - but it looks OK IMO)

> BUT only if the circle also is bigger as well as the control bar.

We can increase the size of the control bar - but right now it has the same height as a library row.
Making it bigger looks kind of ugly in my opinion (I did some experiments and it just feels odd if you see the library rows at the same time).

But we could also increase the size of the circle: It uses 80% (https://github.com/vanilla-music/vanilla/blob/db02f119638fee2b7db12066ddc5f8d5295c30df/src/ch/blinkenlights/android/vanilla/VanillaImageButton.java#L78) of the available space right now.

**Comment by andiandi13** [comment]
> We can increase the size of the control bar - but right now it has the same height as a library row.
> Making it bigger looks kind of ugly in my opinion (I did some experiments and it just feels odd if you see the library rows at the same time).
> 
> But we could also increase the size of the circle: It uses 80% of the available space right now.

I really think that more than 80% would overload the control bar too much. 
I'd suggest a play/pause icon slightly bigger but not as the one in the after pic of my gif (mid way).

Can you try it ?

**Comment by adrian-bl** [comment]
Yepp, i'll play around with the size this evening

**Comment by adrian-bl** [comment]
![image](https://user-images.githubusercontent.com/568734/26993563-f424d464-4d63-11e7-8385-42e4ef2794d9.png)

How about this?

**Comment by andiandi13** [comment]
It looks perfect. Can you please send me an apk to try it.

**Comment by adrian-bl** [comment]
You can try the latest nightly build: http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk

(Note that this will install as a different application, called 'Vanilla Nightly')

**Comment by andiandi13** [comment]
Yeah I know I often try the new features in the nightly, I didn't know that the icon were already updated though.

Well, in KK its also cool ! : 

http://i.imgur.com/W2mS8dH.png

**Comment by andiandi13** [comment]
Also I wonder, is it svgz for widget previews ? 
(those : http://i.imgur.com/A7SyAP6.png)


nb : btw the nighlty icon is a little bit pixelated, I make a new svg with the #006666 color [Google Drive](https://drive.google.com/open?id=0B7yLYKIM8DZYUzd5WEk2YlBOSUU)

**Comment by adrian-bl** [comment]
> Also I wonder, is it svgz for widget previews ?

No, they are just plain screenshots. I'll updated them when i have time (also have to update the screenshots for the play store)

> nb : btw the nighlty icon is a little bit pixelated, I make a new svg with the 006666 color Google Drive

Thanks, but we create this dynamically during the nightly build using imagemagick.
I don't mind if the nightly icon doesn't look that nice as it's only used for debug builds ;-)

**Comment by adrian-bl** [comment]
Ok, updated the widget previews in commit 124a24e9b1d09cbef5313d6152cc5d319757e670

@andiandi13 Thanks again for all your work - would you like to have your name added to the 'About' page? (And if yes, which name?)

**Comment by andiandi13** [comment]
> @andiandi13 Thanks again for all your work - would you like to have your name added to the 'About' page? (And if yes, which name?)

You're welcome it was a pleasure :p
And yes why not, my name is Yacine Krouri.

**Comment by Adonai** [comment]
Amount of anime-loving people in Vanilla contributors starts steadily grows :)

**Comment by adrian-bl** [comment]
@andiandi13 great: i added you in commit 64d0325a7d3529ce97d1c9701c011f640e630fca and tagged release 1.0.53, so it should soon show up on f-droid (and i'll probably start the rollout in the play-store next week)


@Adonai I wonder how/why Vanilla Music attracts this 'demographic' - maybe because all streaming services suck for OSTs.

**Comment by kirbyfan64** [comment]
Streaming services suck in general for anything coming out of Japan... I mean, Spotify only has like 4 Sawano OSTs...

**Comment by andiandi13** [comment]
Ok cool !

**Comment by adrian-bl** [comment]
Closing this as 1.0.53 has hit f-droid and the play store (beta).

Thanks again for all your hard work!
