### ISSUE TITLE
Songs not being added to playlist

### ISSUE THREAD

**Issue by fmorato** [vanilla-music/vanilla#590]
For some reason, when I clicked add a song from Files view or songs from queue to a playlist it or they weren't added. 

For a song I see a toast saying '0 songs added to playlist' or in a certain queue only 2 out of 10 songs were added.

All my files are mp3 in an sdcard and play as expected.

Seems like a bug.

**Comment by adrian-bl** [comment]
This indicates that the file is not indexed.

Go to Settings > Media Library & tick the 'scan full filesystem' option and start a scan.

(Tl;dr: Android failed to index the file)
