### ISSUE TITLE
Auto play when Bluetooth headset plugged

### ISSUE THREAD

**Issue by StefDotmailer** [vanilla-music/vanilla#598]
Would be nice if the headset plugged detection worked also with Bluetooth. After disconnecting it stops, but when the headset is reconnected I have to play manually (not really comfortable on motorcycle with BT helmets as you have to stop).

**Comment by adrian-bl** [comment]
Not sure if this is possible without requesting scary permissions (eg: telephone status).

I've opened a bug at the 'headphone detector' repository to track this: https://github.com/vanilla-music/vanilla-headphone-detector/issues/8

**Comment by StefDotmailer** [comment]
Thanks. I will subscribe there.
