### ISSUE TITLE
Bluetooth next track without specific buttons

### ISSUE THREAD

**Issue by StefDotmailer** [vanilla-music/vanilla#599]
Would be nice if the Bluetooth controls were configurable. I have only three buttons: VOL+ VOL- ON (on/pairing button). Would be nice if I could set "go to next track" using the ON button or maybe double press on volume buttons.
Thanks.

**Comment by adrian-bl** [comment]
I'm not sure if we actually receive VOL+ and VOL- events - i'd guess we don't.

Do you have the Android SDK installed? It would be interesting to see which events your headset sends: You could add some logging to 'MediaButtonReceiver' -> processKey()

(Also see: https://developer.android.com/reference/android/view/KeyEvent.html)

**Comment by StefDotmailer** [comment]
Thanks, I will try; there might be an easier way, too (some app detecting key events). Will give feedback.

**Comment by StefDotmailer** [comment]
Great news, I run `getevent` on my device and tried using the Bluetooth keys and no event was recorded. it looks like the buttons don't send any event to the device so no way to achieve this for me. Maybe I could suggest to implement voice commands, but I guess that's quite a massive piece of work. Shall I leave the issue open? Same feature might be useful to other users who actually send something to the device from the Bluetooth device.

**Comment by adrian-bl** [comment]
> Maybe I could suggest to implement voice commands, but I guess that's quite a massive piece of 
> work.

That's not feasible for us to implement - Maybe Google Now reacts to some keywords? (Dont know, i've never really used it - but if it sends media events, we would work with it out of the box)

> Same feature might be useful to other users who actually send something to the device from the 
> Bluetooth device.

In this case we likely do catch it: The device is supposed to send some specific keycodes which are handled by us.

**Comment by StefDotmailer** [comment]
I shall (at some point in a far future) try the Google Now/similar to send next/prev events. Thanks.

> In this case we likely do catch it: The device is supposed to send some specific keycodes which are handled by us.

I presume this will work only if the event is actually "next/prev", if it's a different one I don't think there is a way of mapping it to next/prev in Vanilla, correct?

**Comment by Adonai** [comment]
> Maybe Google Now reacts to some keywords?

Wen I tried to implement "hold-to-fast-forward" feature for Vanilla Music, this thing interfered, both when using wired and bluetooth headset. And afterwards I coudn't get any events at all.

**Comment by adrian-bl** [comment]
> I presume this will work only if the event is actually "next/prev", if it's a different one I don't think there is 
> a way of mapping it to next/prev in Vanilla, correct?

Yes, we only catch media keys which are identified as next/prev.

**Comment by adrian-bl** [comment]
Closing this for now as i do not think there is much we can do.

Feel free to repoen if you have any news.
