### ISSUE TITLE
temporary removal of removable storage not handled

### ISSUE THREAD

**Issue by ericjs** [vanilla-music/vanilla#601]
I plugged an SD card with my music collection into my phone. I told Vanilla where it was and had it scan it. All was good. Later I ejected the card to use it elsewhere.

Then I opened up Vanilla, forgetting that I did not have the card in. Vanilla forgot everything it had indexed. Plugging the card back in did not bring it back.

It ought not forget info it has indexed from removable storage simply because that storage gets removed (the ability to come and go is a basic property of such storage). One might even want to have music spread across several cards and have the player remember it all. It would have to report that the device is unavailable if one tried to play a song and the device is not there, but it ought not assume it is gone forever and forget it.

**Comment by adrian-bl** [comment]
> It ought not forget info it has indexed from removable storage simply because that storage gets 
> removed 

So what should we do? I don't feel that keeping unplayable songs in the media library is a good idea.

**Comment by ericjs** [comment]
I do. For the use case of a music collection spread across several SD cards it is not just a good idea, it is necessary. 

I suppose it is similar to the case of a user deleting things from their stored music (even on the internal drive). I can imagine a number of ways of handling it. Prompt the user when music "disappears", or have a global option. I lead toward the latter as there are probably several overall usage patterns users fall into. Users like me who want this player to catalog their collection would select the behavior of "do not delete music from the catalog when files are unavailable". Users who temporarily move a subset of their music to their phones and frequently change it might want "automatically delete music from catalog...". There may be some usage patterns where the user might want to be prompted on a case by case basis.

**Comment by adrian-bl** [comment]
I was planning to add an option to the media library to let users choose automatic scan intervals (right now we are only scanning if android notifies us of changes).
I could very well add an option to never-ever scan automatically - but this wouldn't work with multiple storages, as a scan always performs a cleanup - and i really think it should. Vanilla Music was just not made to deal well with missing files (eg: we stop after failing to play ~3 indexed files)

**Comment by adrian-bl** [comment]
closing this as WAI/Wontfix.
