### ISSUE TITLE
files tab - enqueuing, playing or adding folder to playlist ... uses old folder content

### ISSUE THREAD

**Issue by eternalbit** [vanilla-music/vanilla#602]
Somehow when I add a folder to a playlist (via context menu) old folder content seems to be used. Files will then be in the playlist which are actually no longer present. When just browsing the folder (using the files tab) I get the correct (up to date) list of files.

This also seems to be true for _enqueuing_ and _playing_ a folder.

**Comment by adrian-bl** [comment]
Your library is out of date.

Go to settings > media library and start a rescan.

**Comment by eternalbit** [comment]
> Go to settings > media library and start a rescan.

This doesn't fix it. Neither when I check **Scan full filesystem (Slow)**.

The list of files (which aren't there anymore) that get equeued is at least two weeks old. I've rebooted my phone like at least ten times since then.

**Comment by adrian-bl** [comment]
Please start adb logcat, launch a scan and upload the logcat output.

**Comment by eternalbit** [comment]
Sorry to have wasted your time :-/

I actually didn't have the respective folder set to be indexed at all. Misunderstood the UI of the activity for editing the indexed directories. Damn.

**Comment by adrian-bl** [comment]
Which part confused you?

Maybe we can improve the UI.

**Comment by eternalbit** [comment]
Well, somehow I didn't get that I have to use the context menu rather than navigating into the directory :-| but I don't think there's anything wrong with the UI ... rather my head :D

When I had navigated into the correct dir (the one I wanted indexed) which has no sub dir, there was only the save button. So I thought saving would set this dir to be indexed.

I then wondered why the dir wouldn't show up in the list ... but figured that as the app found at least some files in this directory it must have worked anyway and it just wasn't showing up in the list.
