### ISSUE TITLE
progress indicator / seek slider - incorrect 

### ISSUE THREAD

**Issue by eternalbit** [vanilla-music/vanilla#603]
I couldn't yet figure out under which circumstances exactly this occurs. Might have to do with VBR encoded files, but I'd be surprised if seeking within these was a general issue.

Sometimes the progress indicator / seek slider gets screwed up. The total playing time of the track on the right shows a much smaller number than the actual total playing time (like 12 mins instead of 61).
While playing, the slider will stay at the end of the bar while the total playing time increases - somewhat similar to playing a network stream.
While dragging the slider to jump to some specific time the bar seems to behave like the playing time is recognized correctly. Sliding to half way results in a jump to roughly half of the playing time. Yet only roughly, like up to 1-2 minutes off. The slider then jumps right back to the end like before.

**Comment by adrian-bl** [comment]
This is for sure an issue with the file: the MP3 probably has an invalid header, causing android to report/calculate an invalid duration.

The only way to fix this is to fix the broken file.
