### ISSUE TITLE
Jump to song in the queue

### ISSUE THREAD

**Issue by UnoSD** [vanilla-music/vanilla#604]
A nice feature would be to able to jump to a specific song in the queue/playlist. Sometimes queues can be quite big and you might want to listen to a song first and then carry on as usual in the playlist. Currently if you jump to a song then you can't go automatically back to the queue/playlist.
I do not have mobile app development experience (only web/desktop) but I am happy to help implementing it if I can.
Thank you.

**Comment by adrian-bl** [comment]
Could you elaborate in more details how this would work?

Where would the user select the song to 'jump' to?

**Comment by UnoSD** [comment]
Sure, something along this line:

![Jump to](http://i.imgur.com/WXXkqJ7.png)

So in the options from the queue screen.

Once you select the option you can just type using the regular search but restricted to the current queue.

Once selected, it will play that song and then either resume from the previous track of the queue when we jumped or continue from that selected song on in the rest of the queue (maybe with user settings, but I wouldn't overcomplicate it).

**Comment by adrian-bl** [comment]
So in the end this would be like a search feature in the queue?

**Comment by UnoSD** [comment]
Pretty much, yes. Without dropping the whole queue when you search and pick a song.

**Comment by Adonai** [comment]
I think another option for this could be the possibility to add one song as currently playing but without shattering the whole queue. Clicking on a single song doesn't necessarily mean we want to create a queue with only this song. What's the point of this anyway, we can do this with "Repeat one" mode already.

Now if we want to listen to one particular song we should look it up through "search" in library view, right-click on it, then hit "add as next to queue", then hit "play next".

But this all can be done in one click on a song! @UnoSD, what do you think? I can prepare a patch for that.

**Comment by UnoSD** [comment]
> I long thought about an option to add one song as currently playing but without shattering the whole queue. Clicking on a single song doesn't necessarily mean we want to create a queue with only this song. 

Totally agree, unlikely people would want a single song playlist.

> Now if we want to listen to one particular song we should look it up through "search" in library view, right-click on it, then hit "add as next to queue", then hit "play next".

Sorry, I can't try this now, but does this mean the song gets added potentially again to the queue? Let's imagine a like a lot a song and I want to listen to it often, would this mean that I end up with that song 20 times in my playlist and then I have to remove it when I get sick of it (and the shuffle play might play it many times in a row)? Don't get me wrong, I would still be really glad with this option, but I'm not sure it's the best option in my opinion.

Thanks again for the attention for my request.

**Comment by Adonai** [comment]
> Sorry, I can't try this now, but does this mean the song gets added potentially again to the queue? Let's imagine a like a lot a song and I want to listen to it often, would this mean that I end up with that song 20 times in my playlist and then I have to remove it when I get sick of it (and the shuffle play might play it many times in a row)? Don't get me wrong, I would still be really glad with this option, but I'm not sure it's the best option in my opinion.

hmm, how about that: If you click on a single song, we search for this song in queue and delete all occurencies (there's usually only one) of it before adding it as current and playing?

**Comment by UnoSD** [comment]
> hmm, how about that: If you click on a single song, we search for this song in queue and delete all occurencies (there's usually only one) of it before adding it as current and playing?

Sounds good, would it be then inserted in the queue after the current playing song?

I am not 100% sure everyone would like removing all occurrences, but I personally do like it. I could suggest asking for confirmation in a pop up dialog, but of course it's just a suggestion considering other users, if it was just for me I would be perfectly happy with your implementation.

**Comment by adrian-bl** [comment]
> we search for this song in queue and delete all occurencies (there's usually only one) of it before 
> adding it as current and playing?

That sounds like a quite uncool user experience.

But the 'Play' option indeed doesn't make that much sense for single files (It does for artists and tracks as it gives you a quick way to have only a single album/artist, etc in the queue).

So how about changing the Play-action for tracks to:

* Check if the song exists in the queue, if yes, jump to it
* If not, do the same as 'Play as next' (= enqueue after the current song) and jump to it.

**Comment by Adonai** [comment]
@adrian-bl , but what happens if user then clicks "Play Previous", expecting it will be the same song he played before picking this one?

**Comment by adrian-bl** [comment]
That would play a different song if the picked song was already in the queue.

But thats still better than what we have right now.

**Comment by Adonai** [comment]
Hmm, doesn't sound very intuitive to me...

Still, I'll prepare the patches for this feature by weekend. Let's see how it rolls.

**Comment by Adonai** [comment]
Here's your cake, go get it ;)

**Comment by UnoSD** [comment]
Thank you guys, that was really nice, do you use a donation platform?

**Comment by Adonai** [comment]
@UnoSD you're early, wait for it to be reviewed and merged by @adrian-bl 

Adrian has donation addresses in player's [Readme](https://github.com/vanilla-music/vanilla/blob/master/README.md), I have a Patreon page linked in plugins respective Readme's

**Comment by adrian-bl** [comment]
As @Adonai mentioned: We link to GratiPay and a Bitcoin address in the Readme: All money sent to these accounts goes into my pocket and stays there ;-) (Well: I use it to pay the vanillamusic.io domain and the nightly-build server (which is now dead cheap after migrating from AWS to GCE: The monthly bill went from 4$ to 0.02$)

**Comment by UnoSD** [comment]
Thanks, I will do. Wow did not realise GCE was that cheaper; I appreciate it mostly just has IaaS and not much else compared to Azure and AWS.

I'll follow the status of the PR; how often do the changes get pushed into a release into the Google Play store? (apologies if it's written already somewhere)

**Comment by adrian-bl** [comment]
> Thanks, I will do. Wow did not realise GCE was that cheaper;

The difference also depends on your use case: Our build-server-use-case is:

* Boot the VM
* Build
* Copy file to some webserver
* Shutdown

The large $$ difference is due to the fact that AWS bills you per hour while GCE bills per minute.

> How often do the changes get pushed into a release into the Google Play store?

Whenever i feel that a new release should be done - this is usually about once per month.
You can sign-up for a beta tester to get new builds sooner.

**Comment by Adonai** [comment]
@adrian-bl , why d oyou even need GCE if you can build (and even autotest) your nightlies with Travis CI?

**Comment by kirbyfan64** [comment]
FWIW [Travis has docs specifically for setting up Android projects](https://docs.travis-ci.com/user/languages/android/). If you want to keep nightly builds in addition to (or instead of) per-commit ones, you can use [cron jobs](https://docs.travis-ci.com/user/cron-jobs/).

Also @adrian-bl

> (Well: I use it to pay the vanillamusic.io domain and the nightly-build server (which is now dead cheap after migrating from AWS to GCE: The monthly bill went from 4$ to 0.02$)

[You're killing me here.](https://xkcd.com/859/)

**Comment by adrian-bl** [comment]
Closing as this has been merged
