### ISSUE TITLE
Funny BT behaviour, lock screen widget empty

### ISSUE THREAD

**Issue by mindforger** [vanilla-music/vanilla#606]
since some update in the younger past i had an issue that after linking to my car, the music won't play
when i activated my phonne, i notiecd the symbol in the task bar but it' wont respond to bt-keys unless i open the player manually

then i noticed when i woke my phone, the widget is there, but it is empty! hitting the empty widget brought up the player and everything worked okay then

also for some unknown reason the player does not respond to BT connection very well anymore ... my car linking takes up to 10 seconds and hitting the play button almost every time worked, but now after i started my car and hit the play button several times, i have to stop to activate the player manually

something must have changed or maybe broken by the update

how can i save my playlist so i can reinstall the app properly without loosing my playlists again ?

**Comment by adrian-bl** [comment]
Reinstalling wont help: Bluetooth and media button routing is handled by the operating system - we are just a consumer of events passed down to us.

So your ROM is most likely to blame.

**Comment by mindforger** [comment]
This time i did not use any custom, samsung is at fault or maybe amazon music dropped an update that is disturbing the intent routing

but how about the issue with the widget beeing blank and unresponsive except for opening the app on the lock screen? i want to clear all cache and reinstall vanilla music but i do not want to loose my playlists again, it was quiet a PITA since i added ALL my music lately and organized it

**Comment by adrian-bl** [comment]
A blank widget indicates that your Launcher AND Vanilla Music got killed by Android at some Point. Most likely to free Memory.

Android tries very hard to not kill the launcher, but will still do as a last resort if it has to.

**Comment by mindforger** [comment]
ooookay i will double check the optimize exception for vanilla music

**Comment by mindforger** [comment]
guess what ... you were right ... how the heck did that happen? i haven't had any system updates before that issue, just a whole bunch of app updates and a new google play ... i blame samsung :p
stupid power reduction turning on by itself ... not just vanilla, several other applications too
