### ISSUE TITLE
Scanning and indexin' music files on sdcard is not possible!

### ISSUE THREAD

**Issue by mehakimz** [vanilla-music/vanilla#607]
I use the F-droid version of Vanilla Music and want to thank you here for the great job.

The thing is, after upgrading to v1.0.52 and some change(s) in Media library section (I think,) I can't add my external sdcard in INDEXED DIRECTORIES and MEDIA SCANNER [Scan full filesystem] seems doesn't work on ext_card.
I can see my ext_card in EDIT browser but selecting the music folder (or any others) and saving, make no change in INDEXED DIRECTORIES!

_Storage permissions is granted; 
ext_card formated as ext4;
older version still works fine;
and new version works with older indexed file._

![001](https://cloud.githubusercontent.com/assets/15959574/26761545/a8546bce-4946-11e7-9d07-f6245b9be085.jpg)

**Comment by adrian-bl** [comment]
You are aware of the fact that you neee to long-press on a folder to change the state?

**Comment by mehakimz** [comment]
I was not. 
It works perfectly like always, thx again.
