### ISSUE TITLE
A single track is duplicated, but Vanilla treats both as one (?)

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla#609]
I just downloaded the nightly build of Vanilla to try the fix for #608.

The good news: It works!
The bad news: I have another freaking weird metadata bug.

The track in question: https://drive.google.com/file/d/0B3RBF3Zy7CAXN1p0RldhTE0xYzg/view?usp=drivesdk

It appears *twice* in the media database (I also tried flushing to no avail):

[![Screenshot_20170607-100905.png](https://s5.postimg.org/zeqon0oef/Screenshot_20170607-100905.png)](https://postimg.org/image/3v0ncxi83/)

If I tap on either one, Vanilla says that *two* tracks are playing, and puts both in the queue:

[![Screenshot_20170607-100845.png](https://s5.postimg.org/lmc9rdxmv/Screenshot_20170607-100845.png)](https://postimg.org/image/amr2fs77n/)

However, tapping on either one in the queue does absolutely *nothing*, as if they were the same track.

Regardless of which one I selected first, the details view shows the same file path:

[![Screenshot_20170607-100322.png](https://s5.postimg.org/cep37sww7/Screenshot_20170607-100322.png)](https://postimg.org/image/73a6n3atf/)

Even weirder is that the tag editor shows the file as having metadata:

[![Screenshot_20170607-101351.png](https://s5.postimg.org/cfz117ypz/Screenshot_20170607-101351.png)](https://postimg.org/image/nsbmj07er/)

but, as seen above, Vanilla doesn't pick up the title, album, *or* artist.

...please tell me my phone isn't possessed again...

**Comment by adrian-bl** [comment]
Do you have root?

A copy of /data/data/ch.blinkenlights.android.vanilla/databases would be interseting.

**Comment by kirbyfan64** [comment]
https://drive.google.com/file/d/0B3RBF3Zy7CAXSHNtM1BHV1BsY2c/view?usp=drivesdk

**Comment by adrian-bl** [comment]
Thanks a lot:

So this is interesting: Your database has 3 entries with duplicate artists:

```
sqlite> select title,album,artist from _songs_albums_artists  where _id IN(SELECT _id FROM _songs_albums_artists GROUP BY _id HAVING count(_id) > 1); 
L'Oscurità dell'Ignot|KINGDOM HEARTS Dream Drop Distance Original Soundtrack DISC 3|ä¸æé½å­
L'Oscurità dell'Ignot|KINGDOM HEARTS Dream Drop Distance Original Soundtrack DISC 3|下村陽子
GaMetal - Masked Dedede.mp3|<No Album>|GaMetal
GaMetal - Masked Dedede.mp3|<No Album>|<No Artist>
09-tabun-lastboss-gata-kokonotsubosh.mp3|<No Album>|Hiroyuki Sawano
09-tabun-lastboss-gata-kokonotsubosh.mp3|<No Album>|<No Artist>
```
While each of these songs only exists once (this is why the queue treats them as equal), the track view will display each song in each possible combination: in this case, twice: once with the correct and once with a faulty artist.

I wonder how this happened... Are you running a nightly build or the regular releases?

To fix your database, you can either:

* Delete these 3 songs and re-add them (or just change the path, as this is used for the id calculation). The re-indexed version(s) should then be fine.
* Try the latest nightly build with commit  981b22764f3b5da35c602351d6e52c71af4350f1: This will delete such invalid entries during cleanup: You can trigger this by running a re-scan with 'flush database' enabled - after this, run a regular scan to have the songs re-indexed. (As the flush will just delete these 3 song entries during the 'final' cleanup)

**Comment by kirbyfan64** [comment]
Well...

I had actually never used the nightly before. The dups appeared on my very first scan.

The latest build seems to have worked...sort of. Now, none of the duplicated songs are showing up *at all*...

**Comment by adrian-bl** [comment]
Oh, i just realized how this happens:

Turns out that we failed to handle tag updates correctly since about 2 months :-/
Commit 46a8d0b60229c3b460fb00b2fda5a65bb9e4668d broke this.

I just pushed https://github.com/vanilla-music/vanilla/commit/d6b1da50fb61cde29144be4947e88934f8ecaeab which should fix this issue for good.

**Comment by adrian-bl** [comment]
About the file: This is an ID3v2.*2* file which we fail to parse.

I've never seen an ID3v2.2 file before and turns out that the standard is even worse than v2.3 (http://id3.org/id3v2-00) - i'd strongly recommend to just re-tag the files.

**Comment by kirbyfan64** [comment]
@adrian-bl Thanks!!

If ID3v2.2 isn't supported by Vanilla, shouldn't the tag editor always write v2.3? Right now, the tag editor picks up the tags, which is part of the reason I found it so weird...

**Comment by Adonai** [comment]
Tag Editor is its very own beast and uses sophisticated jaudiotagger library that I adapted for Android usage. Vanilla itself uses BASTP parser that Adrian wrote, it's more convenient for scanning large amounts of files at once.

You can file a enhancement issue against Tag Editor, maybe it's a good idea to retag 2.2 into 2.3.

**Comment by kirbyfan64** [comment]
@Adonai I just filed https://github.com/vanilla-music/vanilla-music-tag-editor/issues/13!

**Comment by adrian-bl** [comment]
> If ID3v2.2 isn't supported by Vanilla, shouldn't the tag editor always write v2.3?

It kind of is if you are not using the internal tag reader. But 'upgrading' ID3v2.2 tags to 2.3 wouldn't be a bad idea (VLC does this for example).

I created https://github.com/adrian-bl/bastp/issues/6 - Maybe i'll have a look at it at some point.
