### ISSUE TITLE
Add and sort into the queue by folders names

### ISSUE THREAD

**Issue by Solitary** [vanilla-music/vanilla#61]
Lot of people is sorting their collection of music by folders in "../band/year - album/" type of deal. 

But if you add music (whole band directory with it's discography in subdirectories) into the queue it sorts the albums alphabetically by id3 tag album and not by name of the directory (in case of "year - album" that means from oldest to the newest album)

So, it would be nice if in case of using directories it would add them by their names. I actually have my music tagged properly, but still prefer dealing with my music in directories and files type of manner.

**Comment by adrian-bl** [comment]
This should be fixed via 95cd3b3329c756c9b85f0bb722d4af6a0b254ad3
