### ISSUE TITLE
Bluetooth Song/Artist Titles Missing

### ISSUE THREAD

**Issue by Sortova** [vanilla-music/vanilla#611]
Howdy. Please forgive me if I missed this in the fine manual, but after a bit of searching I was unable to find an answer.

I run Vanilla via F-droid on CopperheadOS. It plays fine through bluetooth but it does not display the artist and song title nor any controls. If I run the stock music player I do get this information. Is there a setting I am missing?

Under Settings -> Audio I do have "Headset/Bluetooth controls" enabled.

Vanilla 1.0.52

**Comment by adrian-bl** [comment]
Well, we are using the standard media api of android to send this information & to receive key presses.

Is any other 3th party (VLC?) app able to handle keypresses & send title information?

This smells like a feature/bug of copperhead.

**Comment by Sortova** [comment]
You're right. I knew that it worked with the default music app and not Vanilla, but just now I went to test it and it didn't work with either.

I turned off bluetooth and then turned it back on and titles and controls started working again. Sorry to bother.
