### ISSUE TITLE
Transfer of plugins-commons to vanilla

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#614]
@adrian-bl , need your help again in moving common plugin repo here.

All plugins already have this as git submodule.
Please take a look at it and bless me.

https://github.com/Adonai/vanilla-music-plugin-commons

**Comment by adrian-bl** [comment]
Did you already start the transfer? (https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/)

I didn't get a mail/notification from github yet.

**Comment by Adonai** [comment]
No, I was waiting for your blessing :)

**Comment by Adonai** [comment]
@adrian-bl , when I'm trying to transfer to vanilla-music organization it says I have no rights to create repos there. So I requested a transfer to you personally as we did it last time, just move it to vanilla-music.

**Comment by adrian-bl** [comment]
No problem: The transfer is done and you should be an admin of the repo:

https://github.com/vanilla-music/vanilla-music-plugin-commons

**Comment by Adonai** [comment]
@adrian-bl , thanks a lot!
