### ISSUE TITLE
General slowdown since 1.0.47 update

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#615]
I kept this issue aside for a time, but several people encountered it since the .47 update (in github as well as around me). 
I guess that it's obviously because of the new media database engine that was implemented.

Concretely, when we use the "Play all" function (the single "play" does not affect the speed) the time laps between we press it and the songs are playing is longer than before.
Also, when we open Vanilla the first time, the songs with their covers are slow to appear.

It's quite annoying that each time I press the title of a song, I have to wait until it start (around 2 seconds !)

It seems that the more songs you play, the higher the time lapse is (maybe because of the large amount of files to enqueue)

Please look at the delay at the opening (songs, covers...) and the time lapse between the pressing of "Play all" and the display of the blue popup at the bottom (XXXX tracks playing) :

Vanilla 1.0.46 (old media db, fast) : https://youtu.be/7PvKoglAlUM

Vanilla 1.0.47 (new media db, slower) : https://youtu.be/m-IVC4OD1Oc

Vanilla 1.0.53 (time lapse greater or equal to .47) : https://youtu.be/WRg66Iqsz8M

I really hope I'll be able to experience the smooth sensations of Vanilla again, I'm quite frustrated when using it since then.

Thanks.

**Comment by adrian-bl** [comment]
> Please look at the delay at the opening (songs, covers...) and the time lapse between the pressing of 
> "Play all" and the display of the blue popup at the bottom (XXXX tracks playing) :

I think this is mostly due to the pretty old SQLite version which is used in Android 4.x - Version 1.0.47 is often faster than the old one on Android >= 5.x (at least that's my feeling).

* Which Sort option do you have selected? Some sort options are not using an index and can be somewhat slow
* If you have the SDK installed, you could try to recompile with DEBUG = true set in src/ch/blinkenlights/android/medialibrary/MediaLibraryBackend.java. This would cause VanillaMusic to print all issued SQL queries (including timing information!) to the android log.

**Comment by andiandi13** [comment]
I tried every sort option and its the same.

I'm not familiar with SDK , compile etc..

Can you explain me quickly how to proceed step by step (I'm rooted if it can helps)

**Comment by adrian-bl** [comment]
> I'm not familiar with SDK , compile etc..

You'd need to install the official Android SDK, build instructions are at https://github.com/vanilla-music/vanilla/blob/master/README.md#building-from-command-line-2

..but i just imported an existing database (~5000 songs) to an Android 4.x device - and wow: this is *really* slow. Seems that JOIN operations are abysmally slow on 4.x:

```
select COUNT(*) FROM _songs_albums_artists;
```

takes like 10 seconds to finish :-/

**Comment by andiandi13** [comment]
Could you try the same operation with 1.0.46 ?

**Comment by adrian-bl** [comment]
1.0.46 uses a completely different schema, but it turns out that sqlite on Android 4.x simply fails to use an index:

Android 4.x:
```
sqlite>  EXPLAIN QUERY PLAN select * FROM _songs_albums_artists;
0|0|0|SCAN TABLE songs (~1000000 rows)
0|1|1|SEARCH TABLE albums USING INTEGER PRIMARY KEY (rowid=?) (~1 rows)
0|2|2|SEARCH TABLE contributors_songs USING COVERING INDEX sqlite_autoindex_contributors_songs_1 (role=?) (~2 rows)
0|3|3|SEARCH TABLE contributors AS _artist USING INTEGER PRIMARY KEY (rowid=?) (~1 rows)
```

Android 5.x
```
sqlite> EXPLAIN QUERY PLAN select * FROM _songs_albums_artists;
0|0|0|SCAN TABLE songs
0|1|1|SEARCH TABLE albums USING INTEGER PRIMARY KEY (rowid=?)
0|2|2|SEARCH TABLE contributors_songs USING INDEX idx_contributors_songs (song_id=? AND role=?)
0|3|3|SEARCH TABLE contributors AS _artist USING INTEGER PRIMARY KEY (rowid=?)
```

On Android 4.x, SQLite fails to use `idx_contributors_songs` as an index, this causes it to do an almost full table scan on each song, which is quite catastrophic.

Fortunately, we can force SQLite to use the index it forgot about:

So if you are root, you could try the following:


- Kill Vanilla Music
- Login via adb and change to the database directory
```
adb shell
cd /data/data/ch.blinkenlights.android.vanilla/databases  # or vanillanightly if you are using the nightly
```

Then launch sqlite via:

```
sqlite media-library.db
```

...and copy'n'paste this:

```
DROP VIEW _songs_albums_artists;
CREATE VIEW _songs_albums_artists AS SELECT *, _artist._contributor AS artist,_artist._contributor_sort AS artist_sort,_artist._id AS artist_id FROM songs LEFT JOIN albums ON songs.album_id = albums._id LEFT JOIN contributors_songs INDEXED BY idx_contributors_songs ON contributors_songs.role=0 AND contributors_songs.song_id = songs._id LEFT JOIN contributors AS _artist ON _artist._id = contributors_songs._contributor_id ;

DROP VIEW _songs_albums_artists_huge;
CREATE VIEW _songs_albums_artists_huge AS SELECT *, _albumartist._contributor AS albumartist,_albumartist._contributor_sort AS albumartist_sort,_albumartist._id AS albumartist_id, _composer._contributor AS composer,_composer._contributor_sort AS composer_sort,_composer._id AS composer_id FROM _songs_albums_artists LEFT JOIN contributors_songs AS  __albumartists  INDEXED BY idx_contributors_songs ON  __albumartists.role=2 AND __albumartists.song_id = _songs_albums_artists._id LEFT JOIN contributors AS _albumartist ON  _albumartist._id = __albumartists._contributor_id LEFT JOIN contributors_songs as __composers INDEXED BY idx_contributors_songs ON  __composers.role=1 AND __composers.song_id = _songs_albums_artists._id LEFT JOIN contributors AS _composer ON  _composer._id = __composers._contributor_id ;
```

This will re-create two SQL views, now forcing the use of an index.

After this, Vanilla Music should be much faster.

**Comment by andiandi13** [comment]
Ok i'll try, you mean on pc or on android terminal emulator ?

**Comment by adrian-bl** [comment]
I'd try it on a PC.

**Comment by andiandi13** [comment]
It seems that I've not sqlite on my device : http://i.imgur.com/Er2xacf.jpg

I'm lost right now

**Comment by kirbyfan64** [comment]
https://stackoverflow.com/questions/17427948/how-can-i-install-the-sqlite-executable-on-an-android-device

**Comment by adrian-bl** [comment]
...Or just wait a few days: i'll push a commit which does the upgrade automatically when i have time (maybe this evening)

**Comment by andiandi13** [comment]
@adrian-bl And so you mean that .47 will become as fast as before without any manual workaround ?

**Comment by adrian-bl** [comment]
1.0.53 would only become faster if you tinkered with the SQLite database as described.

But anything with commit b9f0d2db880078dbd525312729b1cce77fec72fd should give Android 4.x a nice speed up: On my test device, the track list went from ~25 seconds (!) to ~1 second.

The commit is already included in the latest nightly, so feel free to give it a try and report back!

And as a bonus: Here is a (potato quality, no screenrecord on Android 4.2) video of old-vs-new:

https://www.youtube.com/watch?v=EEHoV-Kb7gU

The fixed version gets installed at 0:55

**Comment by andiandi13** [comment]
I just managed to solve the sqlite error with an adb push solution and its wonderful (as fast as your video obviously)

It was so crazy with your amount of songs, I'm in shock :O

And I tried the nightly and its also perfect !

So, I guess that everyone that will install the next update in (as well as this nightly) will not encounter slowdowns anymore ? No manual root-SQL tinker needed at all ?

**Comment by adrian-bl** [comment]
> I just managed to solve the sqlite error with an adb push solution and its wonderful (as fast as your 
> video obviously)

Ah, so you did the update on the PC and pushed the file? That would work too.
How is the speed compared with 1.0.46? Do you still feel that it is slower?

> It was so crazy with your amount of songs, I'm in shock :O

That was a library with > 5'000 songs, and yes: it was *really* bad - i was also amazed at how slow it was :-). The problem with the missed index is that sqlite had to do a full table scan on the 'contributors_song' table, which lists the artist/composer+co for every song. This table grows at the same speed as the songs table itself: So: 'many songs = many queries to contributors_songs = query to contributors_songs gets slower.'


> So, I guess that everyone that will install the next update in (as well as this nightly) will not encounter 
> slowdowns anymore ? No manual root-SQL tinker needed at all ?

Yes: Upgrading to a version with the fix will automatically perform the required database changes.

**Comment by adrian-bl** [comment]
I also wonder if i should just release 1.0.54 early.

https://github.com/vanilla-music/vanilla/commit/7612febbabcad3466dda814ef55f8c3963d4871e and https://github.com/vanilla-music/vanilla/commit/b9f0d2db880078dbd525312729b1cce77fec72fd are both quite nice fixes.

**Comment by andiandi13** [comment]
> The problem with the missed index is that sqlite had to do a full table scan on the 'contributors_song' table, which lists the artist/composer+co for every song. This table grows at the same speed as the songs table itself: So: 'many songs = many queries to contributors_songs = query to contributors_songs gets slower.'

Oh yeah its like deactivate index in windows search, its horrible :)

> I also wonder if i should just release 1.0.54 early.

I mean, it would be quite soon since .53 has just been released, a .54 version with other new fixes is better IMO.

But it would be cool if you can provide me a "non-nightly" apk because it's the one I use, and it takes me some time to configure dit, with all the playlists and stuff..

**Comment by adrian-bl** [comment]
> But it would be cool if you can provide me a "non-nightly" apk because it's the one I use, and it takes 
> me some time to configure it, with all the playlists and stuff..

Well, if you manually fixed the sqlite database there would not be much reason to upgrade.

Also: i could only build an upgradeable non-nightly compatible with the version downloaded from the play store. If you downloaded the app from f-droid, there is nothing i could do as these releases are signed with the private key owned by f-droid

**Comment by andiandi13** [comment]
> How is the speed compared with 1.0.46? Do you still feel that it is slower?

It feel the same in 46 and 47, and after some test with a stopwatch, I'm around 900ms for both versions when I play all my songs, good news.

> Well, if you manually fixed the sqlite database there would not be much reason to upgrade.
> 
> Also: i could only build an upgradeable non-nightly compatible with the version downloaded from the play store. If you downloaded the app from f-droid, there is nothing i could do as these releases are signed with the private key owned by f-droid

Yes you're right, its just that the fix is inside the media-library.db file, if I recreate one (just to test), its slow again, it is less secured.

But I'll wait until the .54 release then, I'll just have to install it above .53 to keep my settings ;)

**Comment by adrian-bl** [comment]
> It feel the same in 46 and 47, and after some test with a stopwatch, I'm around 900ms for both versions
> when I play all my songs, good news.

Ok, cool: glad to see that we are now as fast as the old version on 4.x :-)


Closing this bug as the fix has been commited.
