### ISSUE TITLE
The in-app search button should open the search bar and make appear the soft keyboard.

### ISSUE THREAD

**Issue by TgA22** [vanilla-music/vanilla#618]
- Vanilla Music Version (Settings -> About): from at least 1.0.47 (very possibly way before this) to 1.0.53
- Android Version: Tested on Omnirom (Android 4.4.4) and Resurrection Remix (Android 7.1.2)
- Phone vendor / model: Samsung Galaxy S III i9300 international
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

The in-app search button should open the search bar and make appear the soft keyboard. Currently, it only shows the library screen.

## Steps to reproduce the issue

Assign the function "in-app search" to a double tap to the physical home button for example (you can do this in Cyanogen Mod, Omnirom, Resurrection Remix, etc.). Press it while in Vanilla Music.

**Comment by adrian-bl** [comment]
That sounds like a good thing to do, didn't know that KEYCODE_SEARCH was still a thing :-) (I assumed it wasn't used much when the hardware-search button went out of style).

94b7566881d66f4459ffb61b817636bf207ed592 fixes this: Hitting the search button in the library view will now start the search dialog.

Hitting search in the playback activity will still go back to the library (Going back seems to be androids default if the search keycode is not handled) which makes IMO sense as we do not have a search dialog there (yet - but might in the future when we add search to the queue)

**Comment by Adonai** [comment]
It's used a lot on custom ROMs. On LOS I always activate "hold-to-search" on menu/recents button.

**Comment by adrian-bl** [comment]
Never noticed it - and long-press on menu/recents brings up the split-screen mode on my LOS 14 device

**Comment by TgA22** [comment]
If KEYCODE_SEARCH only works in the library screen, it makes it almost useless since I can juste tap the magnifying glass icon, I think it would be very practical that it worked from the playback screen because it's less frustrating press KEYCODE_SEARCH than to press back, wait for the library screen to come and then tap the magnifying glass. Plus Vanilla Music only has one search bar. (If you implement another search for the queue, you can remove that or make it an option).

Anyways, thanks for the quick reply!

**Comment by adrian-bl** [comment]
Implemented in 345e45533cd949540677f8cef2c35f757859bdb6
