### ISSUE TITLE
Songs in <No Album> ALL have the same cover.

### ISSUE THREAD

**Issue by TgA22** [vanilla-music/vanilla#619]
- Vanilla Music Version (Settings -> About): 1.0.53 (I think it appeared around 1.0.49)
- Android Version: happened on OmniRom 4.4.4 and Resurrection Remix 7.1.2
- Phone vendor / model: Samsung Galaxy S III i9300 international
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

Songs which don't have an album tag (\<No Album>) all have the cover which is embedded in one of the songs which don't have an album tag, I don't know how the song is choosed, it seems to be random (it happened with different songs with almost the same library in android 4 and 7). The cover can only be seen in the playback screen and not the songs list on the library screen (but you can see it in the bottom bar), so this issue is already half-fixed.

I can understand having the same cover for \<No Album> for one artist, but this happens with any artist, and even \<No Artist>.

## Steps to reproduce the issue

Start using Vanilla Music with default settings and a library with several songs which have different artists and don't have an album tag, with one of the songs with no album having a cover. Play another song with no album, and the cover of the other song would appear (even if the song has its own cover).

Disabling "Load artwork from Android" in the "Cover art" section of the settings fixes this, but it disables all covers embedded for all songs.

(Please also check my last comment on the other issue I posted)

Thank you very much

**Comment by andiandi13** [comment]
I'm on KitKat 4.4.4 and I have the exact same "issue", I can't remember if I had it in the past though (I don't think so..).

**Comment by adrian-bl** [comment]
> Songs which don't have an album tag (<No Album>) all have the cover which is embedded in one of the 
> songs which don't have an album tag

This works as expected: We only cache a single cover per album id, and by default, albums are grouped simply by their name.

You can change the grouping in Settings -> Media Library -> Album grouping.

This causes us to create an album id per $album-name+$folder, so untagged songs in different folders will not all share the same album id.

**Comment by kirbyfan64** [comment]
IMO it would be a little more intuitive if `<No Album>` tracks *always* used the folder name, too...

**Comment by TgA22** [comment]
I ticked this box, it rescanned, I had to restart the application to see the changes, it's much better now. I failed to understand what was "Group albums by folder"

**Comment by adrian-bl** [comment]
> I ticked this box, it rescanned, I had to restart the application to see the changes, it's much better now. I 
> failed to understand what was "Group albums by folder"

That's because they were still cached. We should probably flush the cache if scanner options changed.
