### ISSUE TITLE
Incorrect Bitrate for VBR files

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#620]
- Vanilla Music Version: 1.0.53
- Android Version: 4.4.4
- Phone vendor / model: Samsung Galaxy S5 Plus (SM-G901F)
- Application was downloaded from :
  - [ ] Play Store
  - [x] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

The Bitrate shown in playback view for Variable Bitrate files (for example MP3 "V0") is always of 128kbps. 

In most music players (Poweramp, Black Player ...) the displayed Bitrate for this type of file is an average of the various Bitrate variations of the song. For example, it would show ~264kbps or 264kbps.

128kbps is not an average at all here, but a number by default. 
It would be useful to know if a song is in VBR or not. 128kbps isn't that good and I may delete a song because of that and look for a better quality while its already fine.

## Steps to reproduce the issue

Play a song with a variable Bitrate, go to playback view and long-press the name of the song to display metadata.

## Screenshot

![screenshot_2017-06-21-04-44-20](https://user-images.githubusercontent.com/19387072/27367887-33420182-5604-11e7-9e1d-17795a431b17.jpg)

Thank you.

**Comment by adrian-bl** [comment]
The bitrate we display is the bitrate reported by Androids media framework - which *most likely* reads it from the header of the MP3 - so the information stored there by the encoder is most likely simply wrong.

But feel free to send me a sample to adrian@blinkenlights.ch ..

We could probably calculate a 'better' bitrate by stat()'ing the file and divide it by the duration - but i feel like this is an ugly hack.

**Comment by andiandi13** [comment]
I just sent you a song.

The thing is that I never saw 128kbps in any players, in Android or Windows (well in android the other players may calculate it by themselves I guess).

> We could probably calculate a 'better' bitrate by stat()'ing the file and divide it by the duration - but i feel like this is an ugly hack.

Yeah but its worth a try if its the only way and if the result is realistic.

**Comment by adrian-bl** [comment]
> The thing is that I never saw 128kbps in any players, in Android or Windows (well in android the 
> other players may calculate it by themselves I guess).

Displaying VBR bitrates of MP3s has always been a challenge :-)
I did a quick test and only `ffmpeg` showed a correct value:

`file` reports an 128 kbps MP3 (that's the number present in the ID3 header)
`vlc` also report 128kbps
`ffmpeg` reports 243kbps
`mpg123` report VBR (thank you...)

So IMO, our 128kbps isn't *that* bad - as it is the value reported by the encoder (did you encode the file yourself? If yes, which parameters did you pass to `lame`?)


> Yeah but its worth a try if its the only way and if the result is realistic.

The problem is that we don't really know how much of the space is actually used by the file:
Almost all media formats (including MP3) have the option to include binary data, such as a cover picture.

**Comment by andiandi13** [comment]
> So IMO, our 128kbps isn't that bad - as it is the value reported by the encoder (did you encode the file yourself? If yes, which parameters did you pass to lame?)

Oh didn't know it was I the file, I thought the others player displayed the right bitrate from the file.

I used mostly GUI programs like Audacity and DBPoweramp, I just choose MP3 VBR and quality V0, I'm not really aware of what happens on the encoder.

If you say that the bitrate is an ID3 tag, is there a way to change it manually as I would change Album or Year tag without re-encoding ?

**Comment by andiandi13** [comment]
EDIT : After several searches, I found that you can only 'fix' the nitrate with some software but it displays bitrates even worse than 128 (as 64 or 80..).

So I would like to know if there is any possibility of at least displaying the word 'VBR' in the tag screen of Vanilla even if its still 128kbps (so that we know what we're dealing with).

For instance 'format MP3 128kbps VBR'.

**Comment by andiandi13** [comment]
Fine, Vanilla isn't guilty for that after all.

**Comment by andiandi13** [comment]
I've asked some developers how they managed to display an average bitrate for MP3s VBR (BlackPlayer, Phonograph etc..) and they are in majority using [JAudiotagger](http://www.jthink.net/jaudiotagger/) which is a free tagging library.

As far as I know it display the same average bitrate as FFMpeg, Mediainfo etc. which is pretty cool.

Here is the source code from Phonograph to illustrate it (at line 98) [Source code](https://github.com/kabouzeid/Phonograph/edit/master/app/src/main/java/com/kabouzeid/gramophone/dialogs/SongDetailDialog.java#L98).

It don't understand anything, its beyond me :p 
I hope this could help though.

**Comment by Adonai** [comment]
> JAudiotagger

Tee-hee, that's the one I use in Tag Editor plugin.

**Comment by andiandi13** [comment]
> Tee-hee, that's the one I use in Tag Editor plugin.

Cool, If Vanilla implement that library, you could maybe make the tag editor more lightweight or even incorporate it to Vanilla if Adrian want so (well, I doubt it since I think he wanted to keep the app light, which is its main advantage imo).

**Comment by adrian-bl** [comment]
Thats nice, but i still blame LAME for writing a nonsense bitrate value in the header.

Maybe things will improve once/if we switched to ExoPlayer.

**Comment by andiandi13** [comment]
>Thats nice, but i still blame LAME for writing a nonsense bitrate value in the header.
And the others VBR encoders (that I tried). AFAIK the bitrate in the header come from the first frame (So that Vanilla can also display 32kbps and 64kbps depending on the first frame of a song). When I think that they just have to put the average bitrate in the first frame and it would be OK for every players, its just stupid.

> Maybe things will improve once/if we switched to ExoPlayer.

If/once you switch to ExoPlayer, I hope the app will still be as lite as Vanilla and not become like these performance and battery-draining music players though :p

> jaudiotagger wont happen: the library is almost as big as vanilla music and wont solve the issue: there will always be cases where we need to fallback to the media framework to extract info (eg: jaudiotagger does not support midi) - also note that bastp was written to be super fast, so it skips expensive stuff (such as reporting a duration for Ogg) on purpose.

I thought you could use a "part" of the library, but you're right as I said above whatever happens, Vanilla should remain lightweight.
