### ISSUE TITLE
1.0.53 shuffle and repeat buttons have the same color activated and deactivated with greyish theme

### ISSUE THREAD

**Issue by TgA22** [vanilla-music/vanilla#621]
In Android 7.1.2, with the greyish and dark.greyish themes, the repeat and shuffle buttons are always white wether they are activated or deactivated.

**Comment by adrian-bl** [comment]
Works for me on 3 different Devices running 7.1.2.

- Which part of the UI is affected?
- Which device / rom are you using? (Please use the template to report bugs)

**Comment by TgA22** [comment]
Thank you. Please also consider [https://github.com/vanilla-music/vanilla/issues/618#issuecomment-309536018](url)

**Comment by adrian-bl** [comment]
This is fixed in the latest nightly:

The greyish theme now (again) uses a grey color for the controls, while black/white are used to indicate active items.

Not super happy with the contrast, but it's now as good as it was before.
