### ISSUE TITLE
Bad scrollbar numbers when sorting by Date Added

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#622]
- Vanilla Music Version: 1.0.53
- Android Version: 4.4.4
- Phone vendor / model: Samsung Galaxy S5 Plus (SM-G901F)
- Application was downloaded from :
  - [ ] Play Store
  - [x] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

When I sort my songs by Date Added, instead of displaying the date while I'm scrolling, it shows some numbers that does not make any sense. 
If it's sorted by date or playcount (to take numbers based sorting as example), there isn't any problem.

## Steps to reproduce the issue

Just sort by Date Added and scroll the sidebar, for example in the tracks tab.

## Screenshots

![mobizen_20170621_200417 mp4_snapshot_00 21_ 2017 06 21_20 27 49](https://user-images.githubusercontent.com/19387072/27400491-1624122c-5675-11e7-8308-02ef8923f24d.jpg)
![mobizen_20170621_200417 mp4_snapshot_00 19_ 2017 06 21_20 27 30](https://user-images.githubusercontent.com/19387072/27400492-162666b2-5675-11e7-9d01-2f0ebf4f243d.jpg)

Thank you.

**Comment by adrian-bl** [comment]
Well, it's Unixtime :-) The information is correct, just not very convenient :-)

**Comment by andiandi13** [comment]
Oh so it makes sens :smile: Wouldn't it be possible to convert it in a more convenient thing then.

I mean Unix time is too accurate  --> 1498023651 = Wed, 21 Jun 2017 05:40:51 GMT 

We could keep only daymonthyear, with a list like that :

21062017
21062017
21062017
21062017

**Comment by andiandi13** [comment]
Oh so it makes sens :smile: Wouldn't it be possible to convert it in a more convenient thing then.

I mean Unix time is too accurate  --> 1498023651 = Wed, 21 Jun 2017 05:40:51 GMT 
To me, the day and the exact time is not useful (to me, again).

We could keep only day/month/year, with a list like that :

21062017
21062017
21062017
21062017
18062017
18062017
17062017
15062017
19052017
...

Since Android is based on Unix I don't know if its doable, but if it is would you agree or you prefer Unix Timestamp ?

**Comment by adrian-bl** [comment]
> Wouldn't it be possible to convert it in a more convenient thing then.

Sure, just never bothered to do it until now :-)
ab91bda772a6e12bea7a22a776141a506118638b (already included in the nightly) displays the date as YYYY-MM-DD.

Not sure how great this looks (only tested it on my kitkat device where it looks odd), maybe something like '-5d' would be better (?!)

**Comment by andiandi13** [comment]
You mean that you've already change it in the Nightly ? I updated it and there is NOTHING (neither Unix time stamp nor yyyymmdd).

**Comment by adrian-bl** [comment]
Yes.

Did you do a rebuild of the media library?
The timestamp corresponds to the time when a song was found: Doing a full db result would cause all songs to have the same date, so the fast scroller wont display anything

**Comment by andiandi13** [comment]
You're right I copy a new file and it works great.

It display 2017-06-21.

> Not sure how great this looks (only tested it on my kitkat device where it looks odd), maybe something like '-5d' would be better (?!)

Why is it odd to you ? And what do you mean by -5d ?

**Comment by Adonai** [comment]
(like, it takes half the screen. -5d = like, added 5 days ago)

**Comment by kirbyfan64** [comment]
Is there a reason for the negative sign then, since you're never going to get a positive one unless you used a time machine?

**Comment by andiandi13** [comment]
In my opinion, DD-MM-YYYY is clear to anybody, its multilingual, while "-5d" or "5d", at first glance can be confusing, plus if I want to know what I copied on my phone on January 2017 for example, and Vanilla shows me "-147D" I have to calculate to know the exact date, which is kind of boring.

**Comment by adrian-bl** [comment]
I think we will stick with YYYY-MM-DD for now - it looks less odd on my 'real' phone than it does on my old crappy 4.x device :-)

**Comment by andiandi13** [comment]
Cool :) 
BTW @adrian-bl, I post a reply on issue #391, which is closed so maybe you are not notified.
