### ISSUE TITLE
No Play all function for non-indexed files

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#623]
- Vanilla Music Version: 1.0.53
- Android Version: 4.4.4
- Phone vendor / model: Samsung Galaxy S5 (SM-G901F)
- Application was downloaded from:
  - [ ] Play Store
  - [x] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

There are some audio files that are not musics, so that I don't want them to be mixed with my songs. Thus I exclude those folders from the scanner.

Then, I use the "FILES" tab to play those files but I encounter ~~two~~ an issue : 

--> ~~There isn't any metadata displayed (but of course they appear as soon as they are indexed into the media db)~~
--> The play all function doesn't work (for the same reason I guess), it only _says_ that 1 file is playing but nothing happens.

Since Vanilla isn't a file explorer it seems that it only relies on its media library.

So could it be improved by one of these two ways? :

- Add a feature to "hide" or "ignore" certain songs everywhere in Vanilla despite the fact that they _are_ indexed in the media library. So that in my case, I would include my folder to be scanned to Vanilla's db , which will permit to make ~~tags appear as well as the~~ "play all" function working, like any indexed songs. But it will avoid playing those audio files while I'm randomly playing musics.

**or**

- ~~Read tags _directly_ from the audio file and display them~~, just playing all files from a folder without any request from the media library (more complicated I think)

_EDIT_ : I just figured out, reading #528 that it could be an ID3 error, and it is : 

My files were in **ID3v2.3  ISO-8859-1** (8 bit). So I convert them using _MP3Tag_ to be in ID3v2.3 UTF-16 (16 bit) and it works (non-indexed files as always). It also works in ID3v2.4. (an FAQ within the new the Help page we've talk about would be great to explain those little issues)

So is there still a hope to use the Play All function with non-indexed files ?

## Screenshot

![screenshot_2017-06-24-20-23-22](https://user-images.githubusercontent.com/19387072/27510965-709e6e3e-58d0-11e7-9576-83e5d23650b4.jpg)

**Comment by adrian-bl** [comment]
> Since Vanilla isn't a file explorer it seems that it only relies on its media library.

Yes, and the ability to play a single non-indexed file is actually a horrible hack:
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/SongTimeline.java#L714

We really should get rid of this hack but i'm not sure how feasible it is to make play-all for files work in all cases: Scanning and indexing multiple files while adding them to the queue is a definitive no-no as this simply takes too much time.

**Comment by andiandi13** [comment]
Hmm yeah its understandable... 

But in that case how feasible is it to hide indexed songs from Tracks/Album/Artist/Genre/etc... so that it not plays there, but plays in "File" tab only (with play all function thanks to the library).

I know it seems contradictory..

**Comment by adrian-bl** [comment]
> But in that case how feasible is it to hide indexed songs from Tracks/Album/Artist/Genre/etc... so that it 
> not plays there, but plays in "File" tab only (with play all function thanks to the library).

That won't be possible with the current code: The Queue doesn't have enough context to know what exactly happened  (and there are things such as the 'Random' mode, which automatically appends songs to the queue without any 'source', so it would be hard to guess which type of songs it should use)

**Comment by andiandi13** [comment]
Ok as expected, thanks anyway :)

**Comment by nazar-pc** [comment]
I've probably stumbled uponbthe same issue. I have Music directory where my music is stored and it is in Vanilla'slibrary. However, I also have a directories with a lot of small files that are parts of audiobooks. I'm wondering wh I can play single files from those folders, but can't play the whole directory as single playlist. I definitely do not want to have audiobooks being mixed with the rest of music.

If this is the same issue as described here, could you reopen it, please?

**Comment by andiandi13** [comment]
Its the same issue if I understood correctly but as adrian-bl said, either you include those files in the library and they are mixed with the others, or you exclude them from the scan and since they are not indexed in the .db file, Vanilla can't play them all or add to playlist and so on.

**Comment by nazar-pc** [comment]
If it is not possible right now, consider it to be a feature request. If we can play single file already, here should be a way to play all of them from specific directory.
