### ISSUE TITLE
Filenames with quotes are ignored

### ISSUE THREAD

**Issue by Exagone313** [vanilla-music/vanilla#626]
- Vanilla Music Version (Settings -> About): 1.0.53
- Android Version: 7.1.2 / LineageOS 14.1
- Phone vendor / model: private
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

Filenames containing a quote (') are ignored in the library scan.

## Steps to reproduce the issue

Get a music that has a filename that contains a quote (or rename) in a directory that will be scanned by the player.

## Screenshot / Video (If applicable)

File in Amaze (quote is on PC'86): https://ewd.xyz/Screenshot_20170627-231555.png
Search in Vanilla Music: https://ewd.xyz/Screenshot_20170627-231609.png (with flushed and rescanned library)

**Comment by Exagone313** [comment]
It's odd, it may not be the problem, I have other files with quotes that are in the library.

**Comment by Exagone313** [comment]
I converted the file from mp3 to ogg-vorbis and now it's there.

**Comment by adrian-bl** [comment]
This works for me.

Did you try a full scan? (No need to drop the database, we probably should remove the option anyway)

**Comment by Exagone313** [comment]
It wasn't working for an mp3, but the exact same filename with .ogg (file converted to ogg-vorbis) was ok.
