### ISSUE TITLE
[Feature Request] A shuffle button.

### ISSUE THREAD

**Issue by claiire** [vanilla-music/vanilla#628]
There needs to be a shuffle button on any screen that lists tracks (the all tracks list, the album list, artist track list, etc).

The current method of shuffling (start playing a song, put it into shuffle mode (which looks indistinct from the non-shuffle mode because the icons are the same), then click play all) is too unintuitive and confusing. 

Pretty much anyone who wants their music shuffled just wants a button they can click.

**Comment by adrian-bl** [comment]
> start playing a song, put it into shuffle mode (which looks indistinct from the non-shuffle mode because 
> the icons are the same

Please post a screenshot of these indistinct icons, i don't know what you exactly mean.

**Comment by claiire** [comment]
![No Shuffle Mode](https://user-images.githubusercontent.com/15915950/27708489-f7b2fb6e-5ccd-11e7-870c-0ca35cc5916d.png)

![Continuous Shuffle Mode](https://user-images.githubusercontent.com/15915950/27708506-0a0bb71a-5cce-11e7-8880-2e0c688be501.png)

![Unclear Functionality](https://user-images.githubusercontent.com/15915950/27708581-48d31f38-5cce-11e7-8a7b-75b65dbfa682.png) (perhaps shuffle one song and play the rest in order? it changes from sccreen to screen.)

Those pictures are in the order you press them.

**Comment by claiire** [comment]
Erm. hold on let me crop those, those came out bigger than I intended.

**Comment by claiire** [comment]
Okay, 

First Icon

![No Shuffle mode, plays music in normal order](https://user-images.githubusercontent.com/15915950/27708877-19d423ac-5ccf-11e7-910f-6a12af28d7df.png)

Second Icon

![Apparently Shuffle Mode](https://user-images.githubusercontent.com/15915950/27708895-2a51cd92-5ccf-11e7-8bdf-ca17031659cf.png)

Third icon

![Unclear functionality.](https://user-images.githubusercontent.com/15915950/27708919-3b6afd1a-5ccf-11e7-939a-4f8e343c7eb7.png) Apparently choses one song at random and plays the rest in order, but only sometimes?

Those are in the order that they come up as you press them.

**Comment by kirbyfan64** [comment]
The first two icons being the same was a bug (#621) that was recently fixed (the second and third are supposed to be blue to show that the shuffle mode is activated).

**Comment by ToNIX-** [comment]
I'm using the latest f-droid version and confirm that the icons turn blue in second and third.

**Comment by adrian-bl** [comment]
This is a bug in the current f-droid build which only affects the grey theme.

Any other theme OR any other build (nightly / play store) will work correctly.

(F Droid did not (yet?) pick up the patched 1.0.53 version automatically)

**Comment by claiire** [comment]
This thread is not about the graphics bug, it's a request for a shuffle button to be implemented. Keep that in mind 😉

**Comment by adrian-bl** [comment]
Adding songs to the queue while shuffle is active will shuffle them.

You can always reshuffle by exiting & re-entering shuffle mode.

What kind of new functionality would a shuffle button add?

**Comment by claiire** [comment]
A shuffle button is a very common feature in every other music player I've used. It's just a button that you click once to shuffle-play-all your tracks/an album/an artist's tracks.

Any other method, like dealing with a queue is too much. Most people are accustomed to a frictionless single button to shuffle their songs

**Comment by adrian-bl** [comment]
Well, a queue is a very essential part of a music player.

As already said: You can have exactly the same effect by hitting 'Play All' in any screen while the shuffle mode is active.

I dont think that we need an extra button for this.

**Comment by claiire** [comment]
You do. Otherwise you have to
1) play a song
2) pause it
3) change the shuffle mode
4) go back and hit play all again
5) remember to turn off shuffle mode when you're done

That is an objectively inferior UX to just hitting a button and not having to think about it again.

A shuffle button is absolutely important because people don't wanna have to start a song or go to the player screen to enable a whole other mode and THEN have to go back to what they wanted to shuffle. They don't want to have to remember to turn shuffle on so the next time they play their favorite album the tracks are in the right order. They don't want to have to go long pressing and tapping and digging around for a shuffle button only to find none exists and then have to go through the very unobvious process you have to do.

Shuffle-and-forget, so to speak, is vital.

**Comment by andiandi13** [comment]
> You do. Otherwise you have to

>play a song
pause it
change the shuffle mode
go back and hit play all again
remember to turn off shuffle mode when you're done

No, you don't have to do all that, just swipe on the queue bar anywhere and activate/deactivate shuffle.
Please look at this screen recorded video : [YouTube](https://youtu.be/_vtAs_ghKms)

**Comment by claiire** [comment]
Again though, that's more friction than a "shuffle all" button

And you still have to remember to disable shuffle afterwards, which is not something people wanna worry about.

**Comment by andiandi13** [comment]
Yes, people doesn't have the same criterions though :)
But I think an easy way to do it would be adding an SQL button :

![screenshot_2017-06-30-19-53-16](https://user-images.githubusercontent.com/19387072/27748758-73f7ea2e-5d85-11e7-97bf-cb26b7de3d8f.png)

**Comment by adrian-bl** [comment]
I am closing this as WONTFIX as there is no point in a discussion about what people want and what they do not want:

I am 'people' and i do not think that we need an extra button for this as the current workflow is IMO not bad and far more flexible as it works in any context.
