### ISSUE TITLE
icons for "repeat" and "don't repeat" are virtually indistinguishable

### ISSUE THREAD

**Issue by majewsky** [vanilla-music/vanilla#631]
I have v1.0.53 from F-Droid. On the "Now playing" view , the "repeat" and "don't repeat" icon are basically the same, except for colors which are virtually indistinguishable in a bright environment.

It would be nice if both icons could be differentiated further, e.g. by adding a diagonal slash over the cyclic arrow to signify "don't repeat".

Current icons:

<img width="40%" src="https://user-images.githubusercontent.com/24696/27801278-6cd61a96-601d-11e7-9e21-50c3a346737c.png" /> <img width="40%" src="https://user-images.githubusercontent.com/24696/27801280-6f72e9e6-601d-11e7-8b7d-1134caee4be3.png" />

**Comment by kirbyfan64** [comment]
Dup of #621, and fixed in the nightly version.

**Comment by adrian-bl** [comment]
#621 was about the grey theme - the button colors work in the standard 'olive' theme.

I agree that the colors arent't that great on some screens / light conditions, but i'd recommend to simply switch to another theme (such as the blue one - which i consider to make the default anyway)

**Comment by majewsky** [comment]
I didn't know that there is a design choice. I just looked at the settings, and I seem to have selected the "Standard" design (so that's what you see in the screenshots above). I switched to "Orange" now, and the active icon now stands out better.
