### ISSUE TITLE
Index music on SD-Card

### ISSUE THREAD

**Issue by reno-a** [vanilla-music/vanilla#633]
- Vanilla Music Version (Settings -> About): 1.0.53
- Android Version: 7.1.2
- Phone vendor / model: Moto G 2015
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ X] F-Droid
  - [ ] Other (Nightly Build)

## Description
Hello,
Thanks for this application, simple and efficient. (and vorbis/replaygain compatible)
Just a suggest, for select music on SD-Card it's not easy. (finding in indexed directories).
Maybe think more simple solution.. (user friendly?).
....

...

**Comment by adrian-bl** [comment]
Using non standard directories is an advanced feature. It doesnt need to have a stellar UI.
