### ISSUE TITLE
[BUG] Can't play music

### ISSUE THREAD

**Issue by teod0r** [vanilla-music/vanilla#634]
Recently I updated from version 1.0.46 to latest. Added my /storage/sdcard1/Music to library. And everything was fine.
Today I played several downloaded music tracks from file manager with Vanilla. Then I tryed to play again music from /storage/sdcard1/Music with vanilla selecting directory from Vanilla's interface by holding the directory and pressing  Play. Vanilla didn't played it  saying "0 tracks playing". It only can play a single track from that directory. I tryed to clean cache and data. Even to reinstalling back to 1.0.46: nothing helpes.
I already had problem with playing music after updating from 1.0.46 to several newer versions, so I didn't updated it for some tome. Recently I tryed latest version, and it played my music, so I thought it became good, and I stayd with the latest. But today I realised that the problem didn't gone, so now I have to restore my /data from back-up to make my music playable again!

**Comment by adrian-bl** [comment]
The files are probably not indexed by Android, so we can't find them.
Try a full scan in Settings -> Media Library.


Also: Please use the template next time.

**Comment by teod0r** [comment]
@adrian-bl, you did not carefuly read my post

**Comment by teod0r** [comment]
Which template?

**Comment by Adonai** [comment]
@teod0r , when you create new issue there's a pre-filled form that you can complete.
