### ISSUE TITLE
<noalbum>, <no artist> on album, despsite showing correctly in tag edditor

### ISSUE THREAD

**Issue by AlexKraak** [vanilla-music/vanilla#635]
- Vanilla Music Version (Settings -> About): 1.53
- Android Version: 7.1.2
- Phone vendor / model: Samsung gs3
- Application was downloaded from:
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description
With one specific album (unstoppable power by condor, if thats relevant) vanilla music does not show its tags and marks it as <No album> <No artist> and the song name is just the file path. What's odd is that vanilla shows the correct tags in the tag editor and mpd/ncmpcpp and quodlibet all show the correct tags on their end.
....

## Steps to reproduce the issue
I can provide the album mp3s if nessecary but i dont know if github allow that. If you do indeed need it just adding it to the library should be enough 
...

## Screenshot / Video (If applicable)
Vanilla: http://i.imgur.com/EnXxL1r.png
Correct: http://i.imgur.com/eBLh35g.png
...

**Comment by kirbyfan64** [comment]
Might be related to: https://github.com/vanilla-music/vanilla/issues/609#issuecomment-307056273

**Comment by adrian-bl** [comment]
Are you using the intern tag reader? (If you dont know what i am talking about, then you are probably not using it).

But feel free to send me a sample to adrian@blinkenlights.ch

**Comment by adrian-bl** [comment]
closing due to lack of reply.
