### ISSUE TITLE
OGG Opus files don't play (unless the device supports it?)

### ISSUE THREAD

**Issue by oyvinds** [vanilla-music/vanilla#638]
- Vanilla Music Version (Settings -> About): 1.0.53
- Android Version: 5, 6, 7
- Phone vendor / model: Various
- Application was downloaded from (use `[x]`):
  - [x] F-Droid
- Did this work in a previous version?
  - [x] No

## Description
Apparently not all Android devices will play Ogg Opus files (musicfile.oga). I have a Android 6 phone that will play any Opus files in both Vanilla music and the stock music player on that device. I also have a tablet with Android 5 and a phone with Android 7 and none of these will play Ogg Opus files in Vanilla music or the stock music player.

Some software that bundles it's own ffmpeg library (like MX Player) will play these music files on the devices that won't play in Vanilla music. This would be one way of allowing Vanilla music to play more audio formats than the device supports. 

Searching gave me a few pages that claim Opus is supported by Android since Android 5 which does make me wonder how come it works on my 6 device but not my 5 or 7.

## Steps to reproduce the issue
Try playing a Ogg Opus audio file.

**Comment by adrian-bl** [comment]
Android >= 5.x should indeed have opus support (using mka or the opus container).

If your device somehow doesnt support it, then there is not much we can do as we use the builtin media framework.
