### ISSUE TITLE
Duplicate tracks (five times)

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#641]
- Vanilla Music Version : 1.0.53
- Android Version: 4.4.4
- Phone vendor / model: Samsung Galaxy S5 Plus SM-G901F
- Application was downloaded from :
  - [x] Play Store
  - [x] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

I once had duplicate tracks but I didn't care at that time. When I was trying to reproduce the issue to add it to FAQ, I realized that you just have to include folders that share the same files but with a different path.

Prior to Android 4.0, there wasn't that amount of symlink folders, and its worse since 4.2+, with the multi users feature added. This post sum it up well : https://android.stackexchange.com/a/39546.

The thing is that I added the maximum "same" folders to indexed directories, namely :

/sdcard
/mnt/sdcard
/storage/emulated/0
/storage/emulated/legacy
/storage/sdcard0

And you can see the result on the screenshot below, five tracks that are in fact the same.

I don't know how feasible it is to make Vanilla know that all these paths are the same and just take it one in consideration.

That issue has been dealt a little bit here #561 but the root of the problem hasn't been solved.

The thing is that I don't know if you consider it to be an "issue" since you've added the include/exclude feature. At least, I could put that warning in the FAQ.

## Steps to reproduce the issue

Just add at least two folders that lead to the same content (symlink)

## Screenshot

![screenshot_2017-07-24-22-16-39](https://user-images.githubusercontent.com/19387072/28542833-03696624-70be-11e7-8c76-eb009ac10e95.jpg)

**Comment by adrian-bl** [comment]
> I don't know how feasible it is to make Vanilla know that all these paths are the same and just take it 
> one in consideration.

This 'works as expected': Vanilla Music doesn't really have a way to know that these folders are the same. We could do some nasty hacks and check the fsid + inode, but this would only work to detect bind-mounts and symlinks and would fail for fuse-mounts.

**Comment by andiandi13** [comment]
Hmm I got it, I think I'll just explain that well in FAQ but I still have one question :
On my device the default included folder is /storage/emulated/0. What would it be on an older device/firmware where the path where e.g "mnt/sdcard". ? Do Vanilla recognize the sdcard path whatever its name is and including it to be indexed ?

**Comment by adrian-bl** [comment]
> Do Vanilla recognize the sdcard path whatever its name is and including it to be indexed ?

Yes, we use whatever the system reports to be the 'media' directory.

**Comment by andiandi13** [comment]
Great, I close the issue then.

**Comment by Adonai** [comment]
@adrian-bl , Hm-m-m, but we can achieve some kind of "deduplication", no? Just by comparing BASP tags and file size, for example?

**Comment by adrian-bl** [comment]
We could also compare a sha1 hash, but i consider thus to be a non issue as the default settings will not index a folder twice.

If an user changes advanced settings, i assume that he knows what he is doing.

**Comment by k3b** [comment]
My photo-app-media scanner had the same issue with duplicate items due to directory symlinks.

I fixed this by only storing the CanonicalPath of a file (File.getCanonicalPath()) instead of the AbsolutePath

For details see 

http://stackoverflow.com/questions/813710/java-1-6-determine-symbolic-links

**Comment by adrian-bl** [comment]
This would help with symlinks but still fails if the user has a mix of fuse and non-fuse mounts selected.
