### ISSUE TITLE
No songs on previously created playlists

### ISSUE THREAD

**Issue by bobolea** [vanilla-music/vanilla#642]
- Vanilla Music Version (Settings -> About):
- Android Version: 1.0.53
- Phone vendor / model: Nokia 6
- Application was downloaded from (use `[x]`):
  - [x ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x ] NA / Don't know.

## Description
The playlists that were created on my previous Blackberry 10 phone do not show any tracks on them, these show correctly on Google music.
....

## Steps to reproduce the issue
Open playlists
...

## Screenshot / Video (If applicable)

...

**Comment by bobolea** [comment]
Thats great, it worked perfectly. Thanks for the quick response.

**Comment by andiandi13** [comment]
You're welcome.

**Comment by andiandi13** [comment]
@bobolea You can close the issue :)

**Comment by adrian-bl** [comment]
Closing this, also kind of a duplicate of #643
