### ISSUE TITLE
Doesn't index aac files

### ISSUE THREAD

**Issue by IwraStudios** [vanilla-music/vanilla#644]
So I've added some aac files to my music collection recently. But when I looked to find them in vanilla they were nowhere to be found

I've tried deleting all .nomedia files, clearing data, force filesystem and flush media database, and specifically including the folder containing the files but to no avail.

How do i fix this?

**Comment by IwraStudios** [comment]
Oh yea, and i can manually click the files in the file explorer and they play, but aren't indexed

**Comment by kirbyfan64** [comment]
What version of Android are you on?

**Comment by IwraStudios** [comment]
Nougat(7.1.1?), nexus 5X

**Comment by adrian-bl** [comment]
Are the files tagged?

**Comment by IwraStudios** [comment]
@adrian-bl I do not know  what you mean so probably not

**Comment by adrian-bl** [comment]
I mean: do they have a title, artist or album tag/metadata set? We skip completely 'naked' files.

Feel free to send me a sample to adrian@blinkenlights.ch

**Comment by IwraStudios** [comment]
Ahh, that would probably be it, haven't tested it yet but I'm gonna close this issue for now

**Comment by adrian-bl** [comment]
But wait: are you actually talking about raw .aac files or normal .m4a?

I wouldnt be surprised if fail to pick up raw .aac files

**Comment by IwraStudios** [comment]
Raw .aac files

**Comment by andiandi13** [comment]
@adrian-bl I was curious about it and I found out that .aac files (not m4a) which have an MPEG4 'header' (codec ID iso-m/3gp4 etc etc.) are indexed.

However .aac with an ADTS header are ignored by Vanilla.

Its curious because aac ADTS seems to be read by Android since 3.1+ :

https://developer.android.com/guide/topics/media/media-formats.html#audio-formats

And stock music player read it too.

**Comment by adrian-bl** [comment]
I pushed b308b9788043d80a6e6ab5a130e1ee1dd13bb723 - With this commit, we will also pick up ADTS files (as produced by ffmpeg -i foo.mp3 out.aac).

However: The files will be untagged - that's a feature. (As raw ADTS files don't support tags ;-) )

**Comment by IwraStudios** [comment]
Thanks, I'll check it out later
