### ISSUE TITLE
Add tracks and album duration

### ISSUE THREAD

**Issue by steve95** [vanilla-music/vanilla#647]
It would be very useful to have the duration of each track in the queue and tracks views, at the moment the only way to know it is playing the track which is somewhat annoying...
Also, displaying the total album duration and the remaining total queue duration could be nice, although not so needed.

**Comment by CreamyCookie** [comment]
I agree. Especially when using Vanilla for things other than music (audiobooks, for example), it is great if one can check easily the duration before selecting the track. Sometimes one, wants to select a track that is a certain length and not too long.

**Comment by adrian-bl** [comment]
This was implemented via https://github.com/vanilla-music/vanilla/commit/b847279578be51e4938df276b1319a0d42628612

**Comment by CreamyCookie** [comment]
Thanks @adrian-bl and especially @tobyhs for implementing it!

@adrian-bl Regarding closing this: If I understood right, the pull request doesn't address the other half of this feature request, which is about displaying individual track durations in views other than the queue.

**Comment by adrian-bl** [comment]
There were a few follow up commits: the duration is now displayed for tracks in all situations (library, queue, playlists).

You can give it a try by installing a nightly build from http://vanillamusic.io (installs as different app, so no need to uninstall the normal version)

**Comment by CreamyCookie** [comment]
Ah, that's great to hear. Thank you again! :)

**Comment by andiandi13** [comment]
@adrian-bl : I think it has been talked somewhere but I don't know where so I'll comment here : **display duration of albums.**

When we're on a trip, we just downloaded a new album (or we played an old one whatever) and we wanna know how much time it'll play.

It quite useful.

I don't see it hard to implement, it's basically an addition of track durations ?
