### ISSUE TITLE
[Files tab] Add all songs to playlist crash

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#648]
- Vanilla Music Version : 1.0.53
- Android Version: 4.4.4
- Phone vendor / model: Samsung Galaxy S5 (SM-G901F)
- Application was downloaded from :
  - [x] Play Store
  - [x] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

Since the implementation of "Play all" in file view (1.0.51), I can't add indexed tracks to playlist, it instantly crashes. It's bothering, particularly when you creates playlists from folder content.

## Steps to reproduce the issue

Go to Files tab, long press Play all, then add to playlist.

**Comment by adrian-bl** [comment]
Good catch, fixed in a44dca0d1b2165c4c7dbad407de2b61529b5244d
