### ISSUE TITLE
Add previous-track button to lock screen notification.

### ISSUE THREAD

**Issue by dseomn** [vanilla-music/vanilla#650]
- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: LineageOS 14.1 / Android 7.1.2
- Phone vendor / model: HTC One M9 US AT&T
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

It would be nice if the notification on the lock screen had a previous-track button in addition to the play/plause and next-track buttons.

**Comment by andiandi13** [comment]
I have it on a galaxy s5 KitKat, maybe its your ROM.

**Comment by dseomn** [comment]
I don't think it's Lineage, though the Android version matters, I think. If I understand cab1dc8fdd6235d1ade4733a627b870187190806 correctly, lock screen notifications on Lollipop and above don't have a previous button.

**Comment by adrian-bl** [comment]
You can expand the notification: the big version has a back button.

But adding one to the small notification wont hurt.

**Comment by andiandi13** [comment]
Ah I thought he spoke about stock lockscreen widget :)

**Comment by dseomn** [comment]
Maybe I'm missing something obvious, but how do I expand the notification on the lock screen? (I do see a bigger notification with a previous button when the phone is unlocked, for what it's worth. Also, I've only been a smartphone user for a few weeks now, so it's entirely possible I have no idea what I'm doing.)

**Comment by kirbyfan64** [comment]
Drag downwards on the Vanilla notification?

**Comment by dseomn** [comment]
That didn't work. I did some googling, and read a bit of the developer documentation for notifications. As far as I can tell, it's not possible to expand notifications from the lock screen when the OS is configured to hide sensitive notification content on the lock screen. So, having a previous button in the publicVersion notification would be nice.

**Comment by adrian-bl** [comment]
Yeah, expanding doesnt work for sensitive notifications. I'll add a back button when i have time to do so. (But a PR would also be welcome)

**Comment by adrian-bl** [comment]
Fixed in https://github.com/vanilla-music/vanilla/commit/fa65bc393b2d41642a4eec78f95cbeb8fe11c5f7
