### ISSUE TITLE
Option to invert notification colour

### ISSUE THREAD

**Issue by deepu2** [vanilla-music/vanilla#654]
An option to invert the color of the notification text and icons would be great for phones with transparent notification bar. Take a look at this screenshot 
![](http://i.imgur.com/tHmU4Ur.jpg)

**Comment by adrian-bl** [comment]
Phones with transparent bar are unlikely to pass the Android CTS - we can not support any custom modification and do not think that we should offer an option to change this.

I'd be happy to include a patch which automatically detects the background color - feel free to send me a PR for this.
