### ISSUE TITLE
Shuffle mode does not function in playlists

### ISSUE THREAD

**Issue by inspector71** [vanilla-music/vanilla#656]
1. Please take a moment to check if the same Bug has already been reported.
2. Please use our subreddit for general questions: https://www.reddit.com/r/vanillamusic/
3. Please provide all relevant information below.

**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: 6.0.1
- Phone vendor / model: ASUS ZE601KL
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

See issue title.

## Steps to reproduce the issue

1. Create a playlist
2. Select playlist tab
3. Long press playlist entry
4. Select play from dialog
5. Choose random / shuffle (dice) mode
6. Tap next

**Comment by adrian-bl** [comment]
The dice is *not* shuffle mode: the dice keeps filling the queue with random songs.

To activate shuffle mode, use the button in the left corner.

**Comment by inspector71** [comment]
Thanks. That explains some inexplicable behavior, though I hate that
behavior, personally 😀

I don't have a bottom left button unless you're referring to a cross fade
suggested button but I think you're referring to a hardware menu button
that doesn't exist on newer phones or perhaps non-Samsung phones, not sure.

**Comment by adrian-bl** [comment]
I am talking about the shuffle button on the left side of the control bar.

See https://github.com/vanilla-music/vanilla-music.github.io/wiki/User-guide#2-shuffle-and-random-modes

**Comment by inspector71** [comment]
Ahh!

Never seen that icon used for shuffle. Thanks for the clarification!
