### ISSUE TITLE
Crash when opening playback screen

### ISSUE THREAD

**Issue by Jaulers** [vanilla-music/vanilla#657]
- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: 4.0.4 CM9
- Phone vendor / model: Sony Ericsson / Arc S
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes (1.0.53)
  - [ ] No
  - [ ] NA / Don't know.

## Description
When opening the playback screen, vanilla Music crashes.
I can open the playback screen when no song is currently playing/paused(to see the message "No tracks selected. Pick some from the library ...")

## Steps to reproduce the issue
Open the playback screen.

Logcat of the event:
[logcat_playbackscreencrash.txt](https://github.com/vanilla-music/vanilla/files/1251060/logcat_playbackscreencrash.txt)

**Comment by adrian-bl** [comment]
Oh, seems like 4.0 doesn't support 'postInvalidateOnAnimation' (but 4.1 - which is running on my test device does).

Fixed in 1ad2a6fb8b8d307f3a8cebf7aed2776a080b7a86 - thanks for the report!
