### ISSUE TITLE
Share broken in Android 8

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#661]
Exposing file:// uri's is not supported anymore.

```
android.os.FileUriExposedException: file:///storage/emulated/0/Music/foo exposed beyond app through ClipData.Item.getUri()
```

We can probably just fall back to the content resolver Uri for now, as using the Fileprovider would force us to copy the item to private storage first (which is .. ugly)

**Comment by adrian-bl** [comment]
..or just use getUriForFile()

**Comment by adrian-bl** [comment]
Fixed as good as we can by using the FileProvider.

**Comment by Adonai** [comment]
Can you share commit?

**Comment by adrian-bl** [comment]
a104b68201a7c569c1358b1602d7083d6abf226d

**Comment by adrian-bl** [comment]
Closing: This works on my N5X with Android 8
