### ISSUE TITLE
Media Library statistics

### ISSUE THREAD

**Issue by ashed** [vanilla-music/vanilla#664]
1. Please take a moment to check if the same Bug has already been reported.
2. Please use our subreddit for general questions: https://www.reddit.com/r/vanillamusic/
3. Please provide all relevant information below.

**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: 4.4.2
- Phone vendor / model: Lenovo K910 (Vibe Z)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
Media Library statistics info panel do not show tracks qty number full field
....

## Steps to reproduce the issue
Rescan Library
...

## Screenshot / Video (If applicable)
https://get.google.com/albumarchive/117896947742496959787/album/AF1QipMU3nQboYGiWuI1LP5sEVukxswWzNVynklYVUpZ/AF1QipM5mVLdB7AlG0jWHX3RTMG0ozaC6WuOZ_sY8Hwt
...

**Comment by adrian-bl** [comment]
I'm sorry, but i dont know what this report is about exactly.

The screenshot link leads to a 404.

**Comment by adrian-bl** [comment]
Closing: no reply, invalid link to image.

**Comment by ashed** [comment]
I am sorry. Album with this screenshot unavailable

    Vanilla Music Version (Settings -> About): 1.0.54
    Android Version: 4.4.2
    Phone vendor / model: Lenovo K910 (Vibe Z)
    Application was downloaded from (use [x]):
        Play Store
        F-Droid
        Other (Nightly Build)
    Did this work in a previous version?
        Yes
        No
        NA / Don't know.

Description

Media Library statistics info panel do not show tracks qty number full field
....
Steps to reproduce the issue

Rescan Library
...
Screenshot / Video (If applicable)
![screenshot_2017-09-05-14-51-26-499_marked](https://user-images.githubusercontent.com/6615946/30415248-152588ee-9949-11e7-9b05-2391df33cfb3.jpg)
