### ISSUE TITLE
Hidden track title and artist when locked

### ISSUE THREAD

**Issue by Almtesh** [vanilla-music/vanilla#666]
- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: 5.1.1
- Phone vendor / model: Sony D2303 (Xperia M2)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

Track name an artist is not displayed when I lock the phone.

## Steps to reproduce the issue

Add a code, schemas or password to lock your phone, than, hide sensible informations on notification when locked, and then, start the player and lock the phone

## Screenshot / Video (If applicable)

![screenshot_2017-09-06-12-21-25](https://user-images.githubusercontent.com/8816946/30107181-447b8db0-92fe-11e7-8cbe-6f552d1f1281.png)

**Comment by mindforger** [comment]
i have exactly the same issue now and then, i also reported it earlier with another bug but the dev mentioned it beeing caused by power reduction functions ... i removed all apps that tried to save power, set it on the exception list for android power optimize and even disabled the deepest options depening on power that i could find in the system ... but it still happens now and then but not as often as in the past

bluetooth control still works normally and the display on my car radio also works fine so i did not bother to call out on this issue again ... i thought i am just one in a million with this bug

**Comment by Almtesh** [comment]
That funny, because I don't have any power reduction application or functions since I don't need any.
The Bluetooth controls work here too, even the ones in the notification, and I even have the background that is replaced by the cover (when there's one), like I asked in the settings.

**Comment by mindforger** [comment]
there is always a, default on, power optimize function, as far as i know since android 7 at least
you may find it somewhere around your battery settings

**Comment by Almtesh** [comment]
When you say "android 7 at least", do you include android 5.1.1?

**Comment by ToNIX-** [comment]
As stated by Adrian on Reddit, 1.0.54 started to mark notifications as sensitive, so no content will be shown if you configured android to hide sensitive information on the lockscreen.

https://www.reddit.com/r/vanillamusic/comments/6wornk/missing_song_info_on_lock_screen_v_1054/

**Comment by Almtesh** [comment]
Yes, it's that, will it be solved?

**Comment by mindforger** [comment]
uh okay, i will give that a shot ;D

**Comment by adrian-bl** [comment]
This change was introduced by https://github.com/vanilla-music/vanilla/commit/cab1dc8fdd6235d1ade4733a627b870187190806

We now consider the notification with the playback information to be 'sensitive' and will not show the contents if the user has choosen to hide sensitive information (which is not the default).

I don't have a strong opinion on this, so i'm OK with reverting it if many people feel that this is not the right thing to do. The only thing i do not want is to add an option to toggle the feature on and off: We can not have an option for every little detail.

**Comment by Almtesh** [comment]
@adrian-bl, yes, you can add an option for every little detail, it's just very hard to sort them the way we find them all, and the sensitiveness of notification is not a "little detail", you have a whole section for notification, with three settings, you could add this fourth without making it heavy.

If you don't want to add this option, I have no problem with it, but don't make the notification sensitive by default.

@mindforger, for me, it's in "Ton & Benachrichtigung", and the option is called "Bei gesperrtem Gerät", with three choices: "Gesamten Nachrichteninhalt anzigen" (show all notification), "Sensible Nachrichteninhalte ausblenden" (hide sensitive content, the one I set) and Benachrichtigungen nich anzigen" (don't show any notification). It could help.

**Comment by mindforger** [comment]
it's a bit different in arrangement (i blame samsung) and i noticed i do not have all notifications enabled globally but per app and vanilla music is allowed to do everythign regarding notifications, no limits and no privacy for the player

**Comment by Almtesh** [comment]
Pearhaps, but on some phone (Sony D2303, for instance), that's not available.

**Comment by kirbyfan64** [comment]
IMO what you're listening to isn't really *sensitive*; anyone could probably pop your earbuds out if they can't hear it already (e.g. in the case of open-back headphones or Apple earpods).

**Comment by adrian-bl** [comment]
So the common consens seem to be that we do not want this feature (Some people also complained in the play store).

I reverted it via 073896639a6d71e3811e34ff554f4c040af225d6
