### ISSUE TITLE
Tracks present in Files view, but missing in album view

### ISSUE THREAD

**Issue by eggsgent** [vanilla-music/vanilla#667]
- Vanilla Music Version: 1.0.54
- Android Version: 7.0
- Phone:amsung SM-G930F
- Application was downloaded from (use `[x]`):
  - [ x] Play Store
- Did this work in a previous version?
  - [x ] NA / Don't know.

## Description

Tracks present in Files view, but missing in album view

## Steps to reproduce the issue

No clear steps, but I have this issue  currently, so I can provide logs when needed. 

Just started noticing some months ago that tracks would be missing when I was playing back whole albums. No other music players installed show this issue. The file can be played from the Files view, but is hidden in Album view and cannot be played through Vanilla Music from the Samsung file manager (selecting Vanilla Music as playback option results in nothing played, no playback UI). 

...

## Screenshot / Video (If applicable)

...

**Comment by andiandi13** [comment]
Maybe they are in non indexed folders.

See https://github.com/vanilla-music/vanilla-music.github.io/wiki/FAQ#media-library-media-scanner-missing-tracks

**Comment by eggsgent** [comment]
Hi, I dont think so, the files are located in the same folder as the other, viewable and playable files.
I can see that the file exists in the correct folder in the Files view.

**Comment by adrian-bl** [comment]
Did you try to trigger a scan via settings > media library?

**Comment by eggsgent** [comment]
Full file system scan resulted in files showing up again in the Album view. Last time around i had to do a clean install of the app to get the files back.

**Comment by adrian-bl** [comment]
> This time full file system scan resulted in files showing up again in the Album view.

In this case, the files were not indexed by Android itself.

We probably should run some periodic background scans, i created #670 to track this.
