### ISSUE TITLE
opus support in plugins

### ISSUE THREAD

**Issue by jcgruenhage** [vanilla-music/vanilla#668]
None of the plugins (cover fetcher, lyrics and tag editor) can read opus files, even though they show up just fine in the media library with correct tags and everything. Afaict, this should only require reading and writing tags, so it should be not too hard to implement.

Thanks for this simple and great Player :+1:

**Comment by Adonai** [comment]
In fact we depend on [jaudiotagger](https://bitbucket.org/ijabz/jaudiotagger/commits/all) for that.
It has tracking issue from looong ago: [#65](https://bitbucket.org/ijabz/jaudiotagger/issues/65/add-support-for-ogg-opus-format)

**Comment by jcgruenhage** [comment]
thanks for the info :smile:

**Comment by adrian-bl** [comment]
Closing this as this affects a different repo (plugins) and will be fixed once/if jaudiotagger implements opus support.
