### ISSUE TITLE
File sharing fails since .55

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#669]
- Vanilla Music Version : 1.0.55
- Android Version: 4.4.4
- Phone vendor / model: Samsung Galaxy S5 G901F
- Application was downloaded from :
  - [x] Play Store
  - [x] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

Description

When I try to share a file there is a popup saying "Failed to share file". I assume its linked with #661.

**Comment by adrian-bl** [comment]
Where is the file located?

The new fileprovider can only share files which are stored on the internal storage.

**Comment by andiandi13** [comment]
External, so that's it ...

It's a pretty serious loss for the app :/

I used to share files a lot with media info app etc...
Do you intent to fix it ?

For now I'll come back to .54

**Comment by adrian-bl** [comment]
The alternative would be to copy the file to our app cache before sharing, but i'm not sure how we would do the cleanup.

**Comment by andiandi13** [comment]
Plus I guess the waiting time would be long to cache big files.

Why not add an option to activate sharing for android 8 (and untick it would be like before) ?

**Comment by adrian-bl** [comment]
> Why not add an option to activate sharing for android 8 (and untick it would be like before) ?

I strongly prefer to share as much code between Android releases as possible.

But looking at the FileProvider.java code (https://android.googlesource.com/platform/frameworks/support/+/android-support-lib-19.1.0/v4/java/android/support/v4/content/FileProvider.java#309), there *is* an option to share from the filesystem root.

I pushed 33697741583a5c7bb783ff5b4f3dcb6ad65a106f which uses this undocumented configuration, which seems to work fine on Android 8 running inside the emulator.

The latest nightly + the alpha-version from the playstore both include this commit.

**Comment by andiandi13** [comment]
Thanks. I give the nightly a try and it works for both internal and external storage now :D

**Comment by adrian-bl** [comment]
Cool, thanks for the feedback! I will release .56 soon.

**Comment by andiandi13** [comment]
You're welcome :)

**Comment by Adonai** [comment]
Isn't there a threat that the undocumented feature will be removed in future releases and we'll have to rewrite this again? Or maybe it's not present on some phones and present on others?

**Comment by adrian-bl** [comment]
Could you link to the thread? Havent seen this mentioned anywhere.

But we use our own copy of fileprovider.java, so the feature should keep working until Android forbids to expose URIs outside of the external storage directory.
