### ISSUE TITLE
Lockscreen background is replaced with launcher background when playing a song

### ISSUE THREAD

**Issue by Ezile** [vanilla-music/vanilla#671]
- Vanilla Music Version (Settings -> About): 1.0.55
- Android Version: 5.1.1
- Phone vendor / model: Sony Z1Compact
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description
The lockscreen background image is replaced with the launcher (home) background image when playing a song. The setting "Show artwork on lockscreen" setting is OFF.
I have a personal background image on my home screen (after unlocking the phone) and a "safe" image on the lockscreen. When playing any music with vanilla the personal image is shown on the lockscreen.

## Steps to reproduce the issue
Set different background images for the launcher (home) and the lockscreen.
Set the setting "Show artwork on lockscreen" in vanilla music to off.
Play music, lock the screen (I have a lock pattern set), observe that the launcher image is now shown on the lockscreen (together with the vanilla widget).

**Comment by adrian-bl** [comment]
What launcher are you using? I'm pretty sure that's actually a bug of the launcher and we are just triggering it:

https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/RemoteControlImplLp.java#L144

So we are setting the artwork to `null` if there was either no artwork OR displaying it was disabled.
I don't see what we could do different to tell the launcher to not display artwork anymore.

**Comment by adrian-bl** [comment]
Closing due to lack of reply.
