### ISSUE TITLE
[Request] Sort by Filename

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#672]
- Vanilla Music Version : 1.0.55
- Android Version: 4.4.4
- Phone vendor / model: Samsung Galaxy S5 G901F
- Application was downloaded from :
  - [x] Play Store
  - [x] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

Description

The sorting by filename actually exists in File tab, but it would be very useful to add it in the library view. 

I have an OST which is a compilation of 3 games, the tracks name are like 100..101... to 300..301.. according to the game.

As for the "Track number" tag which could've been a solution, many tracks share the same track number (e.g track 100 = track nb 1, and track 200 = track nb 1 too).

So its a complete mess to listen in library view in a similar case and not very convenient to go find the folder manually in File tab to have the right sorting...

**Comment by adrian-bl** [comment]
That should be pretty easy to implement.

I'll have a look when i have time - but if someone feels like digging into the code: this would be a good fit: The relevant code is in `MediaAdapter.java`
