### ISSUE TITLE
Vanilla doesn't seem to support embedded cover art.

### ISSUE THREAD

**Issue by DervishD** [vanilla-music/vanilla#673]
- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: 7.1.2
- Phone vendor / model: BQ/Aquaris V
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

I have cover art embedded in my music files (Ogg and FLAC), but currently Vanilla only seems to read cover art from external image files, not from the embedded cover art. Is this at all possible? Thanks a lot!

....

## Steps to reproduce the issue

Just use Ogg or FLAC files with embedded cover art. It is ignored.
...

## Screenshot / Video (If applicable)

...

**Comment by kirbyfan64** [comment]
Well, it definitely works with MP3s. OGGs and FLACs seem to be a totally different beast:

http://blog.magnatune.com/2012/06/cover-art-in-oggflac-files-now.html

**Comment by andiandi13** [comment]
@DervishD You should be aware that if 'Load artwork from cover' is checked in settings, then external image files will be preferred over embedded cover art.

Try to uncheck this box or delete/move your external jpg/png files.

**Comment by DervishD** [comment]
Thanks for your reply @andiandi13 :)

I don't have any external image files for the cover art, and anyway I tried with all options checked (as they are by default) and unchecked (just in case unchecking them forced the embedded cover art to be used).

**Comment by adrian-bl** [comment]
We will pick up embedded cover art IFF the file was indexed by Android (and androids tagreader was able to extract an image).

For files which are not present in Androids media database, we will fail to load the embedded cover artwork as our internal tag reader does not support that (https://github.com/adrian-bl/bastp)

**Comment by DervishD** [comment]
Thanks a lot for the information @adrian-bl :)
