### ISSUE TITLE
Allow the user to ignore .nomedia files

### ISSUE THREAD

**Issue by DervishD** [vanilla-music/vanilla#674]
- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: 7.1.2
- Phone vendor / model: BQ / Aquaris V
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

I have my entire music library on a directory in the device's internal storage, masked with a `.nomedia` file so it is neither accessed nor processed by Android's Media Storage component, because it doesn't read metadata correctly (it ignores encoding for Ogg files metadata). With PowerAmp (for example) I can choose this directory and it is processed by the player, but it is still ignored by Media Storage. Vanilla seems to always honor `.nomedia` files. Could this please be made optional for people who have their libraries hidden from Android's Media Storage? Thanks a lot!

I understand that the purpose of `.nomedia` is exactly that: ignore media in directories. But, IMHO the purpose is to ignore media by the Media Storage component, not by user installed apps. Those should allow the user to honor `.nomedia` or not, as MX Player or PowerAmp do (just two examples, there are more). Of course, my personal and very subjective opinion ;)

## Steps to reproduce the issue

Select a directory with music on it and a `.nomedia` file. It is ignored.

## Screenshot / Video (If applicable)

N/A

**Comment by andiandi13** [comment]
I have an album folder with a .nomedia file too. It is ignored but every music player but if I include that folder on Vanilla's media scanner it is added to its library.

**Comment by DervishD** [comment]
Not in my case, @andiandi13. I have a /Music folder, with a `.nomedia` in it, and it contains folders, one per artist, and those folders contain other folders, one per album. It is completely ignored by Vanilla, but not by PowerAmp, for example.

To make things clear, my hierarchy is more or less /Music/[ARTIST]/[ALBUM]/[SONG].ogg

**Comment by adrian-bl** [comment]
We always honor .nomedia files and will abort scanning if a directory contains such a file: So if Music/.nomedia exists, no subfolders will be scanned.

However: you can cheat (as andiandi13 suggested) by creating a subfolder in Music:

Eg: `/sdcard/Music/data/$artist/`

* Place the `.nomedia` file in `/sdcard/Music`
* Add `/sdcard/Music/data` to Vanillas indexed directories and run a full scan.

**Comment by DervishD** [comment]
Again, thanks for the information, @adrian-bl I'll do it that way, it's not a big deal :)
