### ISSUE TITLE
The fallback cover in widgets is ugly

### ISSUE THREAD

**Issue by meskobalazs** [vanilla-music/vanilla#676]
- Vanilla Music Version (Settings -> About): 1.0.55
- Android Version: 5.1
- Phone vendor / model: Sony Z1 Compact
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description
In one of the previous build, the fallback images were replaced in Vanilla. This works well in the app itself, but in the widgets, the new image looks ugly.

## Steps to reproduce the issue
Put one of the widgets onto your home screen.

## Screenshot / Video (If applicable)
Screenshot on my phone. Look at the edges of the note, very blurry.
![vanilla-widget](https://user-images.githubusercontent.com/9340769/30771827-2c7a0e9e-a050-11e7-95ec-bfde5db9c04c.png)

**Comment by adrian-bl** [comment]
That's indeed uncool: We should either increase the size of the normal fallback cover bitmap or provide a hires version for widgets.

**Comment by adrian-bl** [comment]
https://github.com/vanilla-music/vanilla/commit/4d39a912f7ad3e51a306ac19413fb09b2ec720c3 should fix this: We now include a hires version of the placeholder image and use it in certain widgets.
