### ISSUE TITLE
[Feature request] Notification style

### ISSUE THREAD

**Issue by regagain** [vanilla-music/vanilla#678]
- Vanilla Music Version (Settings -> About): 1.0.55
- Android Version: Oreo 8.0.0
- Phone vendor / model: Nexus 6P
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [X] NA / Don't know.

## Description

It would be cool if the notification style could change according to the current song, like [AntennaPod](https://github.com/AntennaPod/AntennaPod) does:

![img_20170926_171443](https://user-images.githubusercontent.com/1060371/30981094-89f815de-a483-11e7-9e11-3fa40a48546f.jpg)

**Comment by adrian-bl** [comment]
So why is Antenna pods notification green?

**Comment by Adonai** [comment]
@adrian-bl , that's because song cover is green... I guess?

**Comment by adrian-bl** [comment]
Ah, didn't spot that in Forkdroid on mobile (forkdroid truncated the image).

But i do not think that this is a feature we should add.
