### ISSUE TITLE
Add Dutch translation

### ISSUE THREAD

**Issue by cornelisbb** [vanilla-music/vanilla#679]
I would like to help translate vanilla into Dutch. This does not exist yet, can you add it, please.

**Comment by adrian-bl** [comment]
We use transifex to manage all translations:

Sign up to transifex and request the language at https://www.transifex.com/vanilla_music/vanilla-music-1/

The new translation will automatically be included once it reaches about 80% completeness

Thanks in advance for your contribution!

**Comment by cornelisbb** [comment]
Thanks, have done do.

You may want to change the readme, because it says there to open an issue if an language is not present yet.

**Comment by cornelisbb** [comment]
My request to join the Dutch language still awaits approval.

**Comment by adrian-bl** [comment]
Oh sorry - must have forgotten to hit the submit button in transifex: Your request should now be approved.
