### ISSUE TITLE
Song plays / occurs in "FILES" view but not in "TRACKS" view;

### ISSUE THREAD

**Issue by ecanja** [vanilla-music/vanilla#680]
- Vanilla Music Version: 1.0.55
- Android Version: 5.1
- Phone vendor / model:
- Application was downloaded from:
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

I've only experienced this with a few songs (but I haven't recognized a pattern yet): When I try to play the song in the usual library view under the view tab "TRACKS", I get a toast message that says

> Failed to load track «FILEPATH». It may be corrupt or missing.

I've observed the `adb logcat` output, but it doesn't produce any logs there.
However, when I search for the song in the "FILES" explorer and start playback of the song from there, it works perfectly fine.

Moreover, there is another song (from the same album) that is on the file system, visible and playable in the "FILES" tab, but I cannot find the song in the library (neither under the album it should belong to, nor in the global "TRACKS" list by searching it).

## Steps to reproduce the issue

Actually, I don't see a pattern of the songs and the files, so I have no clue how to reproduce this with arbitrary songs.

## Screenshot / Video (If applicable)

Wouldn't add any information, I guess.

**Comment by adrian-bl** [comment]
Are you sure that the path is exactly the same in both cases?

I suppose that the file just was somehow renamed and the library failed to pick up this change.
A rescan of the Media Library (in settings) should help.

**Comment by ecanja** [comment]
I checked the path, but it was a long one, so I might have missed a small difference.

You're correct, a rescan of the media library did help. Now everything seems fine. Does this mean that I have to do a rescan everytime I add new songs to the file system?

**Comment by adrian-bl** [comment]
No, this should not be required: But sometimes Android itself fails to pickup a file or just 'forgets' to notify us.

Bug #670 tracks a feature where we would do a full filesystem scan in the background - this would solve such issues.
