### ISSUE TITLE
Add the possibility to add to the library a manually typed path

### ISSUE THREAD

**Issue by TgA22** [vanilla-music/vanilla#683]
- Vanilla Music Version (Settings -> About): 1.0.56
- Android Version: LineageOS 14 (7.1.2)
- Phone vendor / model: Samsung Galaxy S3
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

I use adoptable storage with my external SD, I make it accessible to apps as a readable/writable folder with the command 'sm mount emulated:xxx_xx', which creates a folder in /storage which has the form of a UUID e.g. '123e4567-e89b-12d3-a456-426655440000'. This folder then contains a '0' folder which is accessible to apps with the SD Card permission. Problem: the UUID-named folder is not (owned by root and d-rwx--x--x), so I can't see 0 when I tap on it (having gone up two times from the default beginning in /storage emulated/0 in the file explorer for adding a new folder to the library).

## Suggestion

I suggest turning the label at the left of the 'SAVE' button in the file explorer into a text box, or simply add a button "Manually type path", which opens a new screen with a text entry and 3 buttons: "Include", "Neutral" and "Exclude". I would gladly have edited a config file or a database in /data/data, but it seems this is stored in files/prefs-v1.obj in a bizarre format.

**Comment by adrian-bl** [comment]
This was implemented in commit feed3100be5deae0bf20447d797e5540adf5262b - the view displaying the current path is now editable, so you can enter any path you like.

btw: prefs-v1.obj is a serialized java object - but yeah: this thing isn't really supposed to be edited by users.
