### ISSUE TITLE
[enhancement] Gapless Playback

### ISSUE THREAD

**Issue by bastianilso** [vanilla-music/vanilla#684]
The Android media framework supports Gapless Playback since Android 4.1[1]:

"You can now perform gapless playback between two separate MediaPlayer objects. At any time before your first MediaPlayer finishes, call setNextMediaPlayer() and Android attempts to start the second player the moment that the first one stops."

This is particularly interesting for playback of albums where tracks segue into each other, for example live recordings and in some classical, electronic and rock albums.[2]

[1] https://developer.android.com/about/versions/android-4.1.html
[2] https://en.wikipedia.org/wiki/Gapless_playback

**Comment by adrian-bl** [comment]
We already support gapless playback since ages.

Could you provide more details on what is missing?

**Comment by mindforger** [comment]
and it's working like a charm!

**Comment by bastianilso** [comment]
hmm interesting, I can see that you do use this in PlaybackService.java and VanillaMediaPlayer.java. When I was writing this report I was assuming it wasn't implemented because I could hear gaps between the songs in practice (in any case, the API docs does say "attempts to start"). Might be a hardware limitation im hitting then? I tried FLAC and M4A, and also enabling readahead (although, from looking at the code probably doesnt do a difference). If it's any help, the included music player neither does gapless playback for me (I dont have the code to say if its supposed to, though).

If it's any help, here's some device info:
- Vanilla Music Version (Settings -> About): 1.0.54
- Android Version: 6.0
- Phone vendor / model: HUAWEI MYA-L22
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ X ] F-Droid
  - [ ] Other (Nightly Build)

**Comment by mindforger** [comment]
well i can only tell from an galaxy a5 (2016 - stock ROM) with android 7 that it is working with MP3 totally gapless ...
i included a few songs in my lists that can be played back to back for about an hour and you won't even notice the gap if you didn't watch the display

**Comment by bastianilso** [comment]
Let's leave it at that then, thanks for the help!
