### ISSUE TITLE
Poor mpc support

### ISSUE THREAD

**Issue by hasufell** [vanilla-music/vanilla#687]
You can play mpc files via the file browser, but albums are not automatically created and you cannot even create a playlist from musepack files, no matter how hard you try.

Note that mpc uses APEv2 tags.

**Comment by adrian-bl** [comment]
We do not have any support for musepack or any APE tags.
I'm actually surprised that your phone plays such files: are you using lineageos?

**Comment by hasufell** [comment]
I am on stock Android 7.0.

**Comment by adrian-bl** [comment]
I opened a bug report (for myself) on the 'bastp' project (the tag reader we are using internally): https://github.com/adrian-bl/bastp/issues/7

Closing this issue here as fixing the issue in bastp would solve the issue.
