### ISSUE TITLE
Show file-name when metadata is not exist

### ISSUE THREAD

**Issue by TerkiKerel** [vanilla-music/vanilla#688]
Hi,

On the music playing screen I can not see the file list. Because I had clear my songs metadatas. If the metadatas are undefined, please show the file name.

Thank you

**Comment by Adonai** [comment]
> Because I had clear my songs metadatas

![But why?](http://www.reactiongifs.com/r/but-why.gif)

**Comment by TerkiKerel** [comment]
:)

Is this important for this feature request?

Most of the metadatas were wrong.. I remove most of them manually.. Most of them does not include metadatas already... bla bla..

But I fixed all my music archive file names properly. Some media players automatically changes the metadatas (find metadatas from internet)... I don't trust metadata info. Thats why I use file-names.

Thank you

**Comment by Adonai** [comment]
IIRC Vanilla can show filename if metadata doesn't exist, but you have to be sure that you deleted the metadata tag, not set it to empty string or space. I hope Adrian can shed more light on this.

**Comment by adrian-bl** [comment]
We already show the filename as title for untagged files, but as already pointed out: this will only be done if the file does not contain any title tag. (We obey blank tags).

I'd recommend to scan your library via picard and let it tag all files.

**Comment by adrian-bl** [comment]
For the record: This is where it happens:
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/medialibrary/MediaScanner.java#L474

So if title is null (= there was no title tag), the filename is used.
