### ISSUE TITLE
Crash when importing in Android Studio!!

### ISSUE THREAD

**Issue by kumar23rahul** [vanilla-music/vanilla#689]
The app is crashing when opening the app after importing and installing it. Below is the screenshot of logcat, if someone could address this it would be of great help!!
![vanilla](https://user-images.githubusercontent.com/32873244/31986117-d92ced80-b984-11e7-93ca-b7c3e8768840.png)

**Comment by adrian-bl** [comment]
Looks like getPendingJob is API26, fixed in head.
