### ISSUE TITLE
No themes on Android Kitkat

### ISSUE THREAD

**Issue by nicd23** [vanilla-music/vanilla#690]
- Vanilla Music Version (Settings -> About): 1.0.56
- Android Version: 4.4.4
- Phone vendor / model: Samsung Tab E
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x ] No
  - [ ] NA / Don't know.

## Description
On my other device running Android 7.1 I can choose light and dark themes with various colors, on my KitKat device there is no option to do that.
....

## Steps to reproduce the issue
Open Vanilla Music, go to Settings.
...

## Screenshot / Video (If applicable)
https://imgur.com/a/cZBPl
...

**Comment by andiandi13** [comment]
Themes are only available from android 5.x. Older firmware have holo theme.

**Comment by adrian-bl** [comment]
This works as expected: Themes are only available when we are using material design which requires Android 5.x

**Comment by nicd23** [comment]
Tnx for clearing that out.
