### ISSUE TITLE
Album split in two parts, one with a strange char in its name

### ISSUE THREAD

**Issue by Massedil** [vanilla-music/vanilla#694]
- Vanilla Music Version (Settings -> About): 1.0.57
- Android Version: 7.1.2 LOS
- Phone vendor / model: GT-I9305
- Application was downloaded from :
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

In Vanilla Music, I have a case where, in an album with all musics with the same album name "La fête est finie" (Image 1), the album is cut in 2 parts, one with the good album name, the other with a strange char (Image 2).

3 songs are in the "bad named" album. The others are in the "well named" album.

Do you know what happens ?

## Screenshot / Video (If applicable)

Image 1 :

![1](https://user-images.githubusercontent.com/20357783/32657794-ed12a132-c60e-11e7-8c0a-7fe77b6d3e0d.png) 

Image 2 :

![2](https://user-images.githubusercontent.com/20357783/32657931-8cdcf5e6-c60f-11e7-8b45-cbe64b42f7b1.png)

**Comment by adrian-bl** [comment]
So the file you showed in the screenshot is part of the album with the wrong title?
Are you using the internal or androids tagreader? (If you don't know, you are probably using Androids tagreader).

You could try to switch to the internal tagreader in Settings -> Media Library.
Then perform a full rescan with DB-Flush enabled (this will take some time depending on the size of your music library)

**Comment by Massedil** [comment]
> So the file you showed in the screenshot is part of the album with the wrong title?

In the first screen shot, it's a properties window of the all 14 files of the album. To show that the Album name is the same and you can see "(Valeurs multiples)" for the title.

> Are you using the internal or androids tagreader?

Not the internal

> You could try to switch to the internal tagreader in Settings -> Media Library.

Yes, and it solves the problem. Thanks !

So, what's the difference between both mode ? And why keep both ?

**Comment by adrian-bl** [comment]
> Yes, and it solves the problem. Thanks !

Cool: nice to hear that it solved your problem!

> So, what's the difference between both mode ? And why keep both ?

The 'internal' Tagreader uses a library a wrote some years ago which supports MP3, OGG and Vorbis while the non-internal tagreader uses the one which is included in the firmware of your phone (well: Android)

Android has a bad habit of guessing encodings of tags while my library respects whatever is set by the file (which is pretty often - correct.).

Androids tagreader is the default because it was there since $forever and is *supposed* to be more stable. But given the fact that already quite a few people use the internal tagreader (with better results), it may make sense to enable it by default, at least for new installations.

**Comment by Massedil** [comment]
> Android has a bad habit of guessing encodings of tags

So do you know where is the right place to inform about this bug ?

> But given the fact that already quite a few people use the internal tagreader (with better results), it may make sense to enable it by default, at least for new installations.

Yes, may be, if no one complains ! :)

**Comment by adrian-bl** [comment]
> So do you know where is the right place to inform about this bug ?

You could report it to AOSP, but there area already multiple open bugs, such as:
https://issuetracker.google.com/issues/37013213

It seems that the Android team thinks that there are many files with incorrect encoding information, so guessing the right encoding seems to make sense for them.

However: Users of Vanilla Music tend to have correctly encoded files, so this might do more harm than good for us.

Given the fact that Bastp seems to work for most users, i changed the default value of it via commit 7ad4b59cf642bab76089a10e158268d47742d9d3.
This will automatically enable Bastp for new installations (while not affecting existing installations)
