### ISSUE TITLE
Crash when clicking playing song name or singer

### ISSUE THREAD

**Issue by qwertyuser1983** [vanilla-music/vanilla#696]
Advan i5e, 

Always crash when clicking now playing song name or singer, in the lower bar.

:sob:

**Comment by adrian-bl** [comment]
Please provide a logcat and the version you are running. (As requested in the template)

**Comment by qwertyuser1983** [comment]
Err, the template did not show on mobile, 

- Vanilla Music Version (Settings -> About): 1.0.57
- Android Version: 5.1
- Phone vendor / model: Advan i5E
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
When playing my music, I click 

## Steps to reproduce the issue
1. Play an ogg song
2. Click either song or singer name

## Screenshot / Video (If applicable)
[TO BE UPDATED}

**Comment by adrian-bl** [comment]
https://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat

**Comment by Adonai** [comment]
@qwertyuser1983 , you don't use Gapps, do you? If you have root, you can get logcat directly from OSMonitor, but be aware that Android spams tons of logs each second. If you see a crash, try to filter output by log level ERROR/FATAL and "vanilla" as a keyword.
```
And please use markdown backticks (like this)
to post long log output or it will become unreadable mess
https://daringfireball.net/projects/markdown/syntax#precode
```

**Comment by qwertyuser1983** [comment]
[Still have problem setting the logcat, would update after this]

**Comment by adrian-bl** [comment]
You could also install the version from the play store, let it crash and choose to send the crash report.

I'd then be able to see the required log/stacktrace in the developer console.

**Comment by qwertyuser1983** [comment]
@adrian-bl thanks, this much easier.

I sent several report with my tag. :)

**Comment by adrian-bl** [comment]
Thanks, i searched the developer console but didn't find your bug (i haven't seen any crash reports from Advan i5e devices).

Could you try to get a logcat again?
Note that you don't need to have the full sdk installed: Just 'adb' is enough.

**Comment by qwertyuser1983** [comment]
@adrian-bl ok, 

I have downloaded the whole sdk though, so, 

I hope I can report the logcat asap.

Btw, just find report with tag "qwerty_user1983" or "Renan Prasta Jenie".

That would be mine. ;)

**Comment by adrian-bl** [comment]
Does the crash still persist? Were you able to get a logcat?

**Comment by adrian-bl** [comment]
closing due to lack of reply
