### ISSUE TITLE
[Feature Request] Auto update Playlist if directory is source

### ISSUE THREAD

**Issue by Mannshoch** [vanilla-music/vanilla#697]
- Vanilla Music Version (Settings -> About): 1.0.57
- Android Version: 6.0.1
- Phone vendor / model: Fairphone 2
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [X] No
  - [ ] NA / Don't know.

## Problem to solve:

If you use a Folder as Source of Music, you have to refresh the Playlist every time you change the content.

## Feature Request

If a folder was used as source for playing music (and only if so), do automatically recheck the containing Media and Remove/add Media from this Folder. Do this after every new start of the app.
I use Syncthing for data transferring and have a cron-job on a computer at home that fill a Music folder all day with a set of new files. These files get synced to my Mobile phone.

## How the App Maybe could Work

The app Vanilla got Started  (I do it by pressing Play Button on Bluetooth Headset). 
Two processes starting. The first try to play Music already Present in playlist. The second check the directory for contend and update the playlist and send the detected files also to Android media-scanner.
If the first process was not able to find media in playlist, it waits for the result for Process two and take the first media from there.

...

**Comment by adrian-bl** [comment]
I'm not sure if i understand your request correctly.

How do you define 'playlist' ? In Vanilla Music (and most other players), a playlist is a fixed (but user editable) list of songs. I assume that you actually mean the Queue? (= The list of played and soon-to-be-played songs)

If you just want to automatically add new songs to the queue once they are on the device, wouldn't the random mode be sufficient?

**Comment by Mannshoch** [comment]
sry. Until now, I did not  differ between playlist and Queue. In my Opinion a directory is also a playlist. A playlist that could get changed by an external influence. In my situation a syncing tool is manipulating the playlist called '/storage/456-695/music/' .
The Problem at moment is, that random mode is not able to detect new music in a Folder. It only use, as far I know, the files in queue and play it in mixed order.

**Comment by adrian-bl** [comment]
> In my Opinion a directory is also a playlist.

This is not how Vanilla handles folders. In Vanilla Music, a Folder is just like a 'filter' for the media database.


> The Problem at moment is, that random mode is not able to detect new music in a Folder.

No: Random mode (= the dice) will always pull whatever it finds in the media library.
Maybe the new contents didn't get indexed yet, but this is would mostly be SyncThings fault for not notifying Android about new media data. (However: We run a some background scans once in a while (if the phone is idle and charging), so we would eventually pick up all changes)

**Comment by Mannshoch** [comment]
That's interesting. Thanks for the information about the Dice.

**Comment by eggsgent** [comment]
Hi, I second the feature request. This is something I miss in Vanilla Music as I use it as the only sorting method on desktop through "autoplaylists" in Foobar2000.

Having a large library, I keep music in folders like "archive", "incoming", "from family" etc. The "playlist" is updated once files are added and removed.
