### ISSUE TITLE
No music found when scanning

### ISSUE THREAD

**Issue by stephenjsweeney** [vanilla-music/vanilla#699]
- Vanilla Music Version (Settings -> About): 1.0.57
- Android Version: Android 8.0.0 (Oxygen 5.0)
- Phone vendor / model: OnePlus 3T
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

I have my music stored on my phone, under a folder called Music, that lives in:

/storage/emulated/0

The structure of the Music folder is simple:

Music/Albums/<artist>/<album>/01 - Song.ogg
Music/Albums/<artist>/<album>/02 - Song.ogg
etc.

Overall, there are some 3700 files, 400 subfolders, and 21GB of data.

However, when I set the folder as one of the Index Folders in Media Library in Settings, and press Scan, I see only two files, both of which are sounds from Hangouts.

Have I done this wrong? I can see all the music files when browsing internal storage, and both PowerAMP and VLC are able to see the files.

....

## Steps to reproduce the issue

Copy music to internal storage, under a Music folder.
Open Vanilla Music.
Go to Settings.
Got to Media Library.
Add the Music folder to the Indexed Folders section.
Click Scan.

...

## Screenshot / Video (If applicable)

![screenshot_20171128-184738](https://user-images.githubusercontent.com/11473973/33338608-739c076c-d46e-11e7-93e5-e1ba25369bb1.jpg)

![screenshot_20171128-184747](https://user-images.githubusercontent.com/11473973/33338617-7d876fe6-d46e-11e7-8617-d64bd8c7457a.jpg)
...

**Comment by adrian-bl** [comment]
That is odd, haven't seen this before.

Our initial scan only queries Androids internal media database - maybe none of your songs is indexed?
Did you try to tick the 'Full scan' option before starting a manual scan? This should walk trough the whole filesystem and pickup any audio file.

**Comment by stephenjsweeney** [comment]
Ah, after some investigation I discovered a .nomedia file in my Music folder. Scanning is working fine now (not sure how that file got there..!).

**Comment by adrian-bl** [comment]
Ah, that explains everything: We stop as soon as we hit a .nomedia file.

Glad that it is now working for you ! :-)
