### ISSUE TITLE
[Feature Request] Add entire albums when in random mode

### ISSUE THREAD

**Issue by stephenjsweeney** [vanilla-music/vanilla#700]
- Vanilla Music Version (Settings -> About): 1.0.57
- Android Version: Android 8.0.0 (Oxygen 5.0)
- Phone vendor / model: OnePlus 3T
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

When playing songs in random mode (the 'Dice' mode) a new song is pulled at random from the media library and added to the playlist for continuous playback. It would be nice if there was an option to random pull in entire albums, too.

....

## Steps to reproduce the issue

The user could select an option to enqueue whole albums during random playback. This album could be pulled in by selecting from the albums data and appending all the tracks from that album to the playlist, in track order. Essentially, it's just random album playback; anything that can appear in the Album tab would be a candidate for adding to the playlist, regardless of the number of tracks.

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
Hmm.. we could probably 'tie' this to the current shuffle mode:

If the user is in album-shuffle, we would pull random albums. Otherwise we would grab random songs to add them to the queue.

**Comment by adrian-bl** [comment]
I hacked up a prototype at https://gist.githubusercontent.com/adrian-bl/a82fab2d3ac7155708ea04317e1c5d1e/raw/7dd9a0a44975748ab4625714635563533451bb66/gistfile1.txt

Seems to work reasonably well so far.

**Comment by stephenjsweeney** [comment]
Just tried this (took a while to get my Intellij and all that set up to give it a go) and it works very well!

One thought: would it be better to enqueue the entire album in one go, rather than the individual tracks? This would mean that if you enqueue an unrelated song while in album shuffle mode, the new song would play after the entire album has finished, rather than immediately after the current track.

Otherwise, this is great!

**Comment by stephenjsweeney** [comment]
I just had a go at this myself, and I think I've managed to get it working. A gist of the diff can be found here:

https://gist.github.com/stephenjsweeney/ef78725f7376122823091fb5782539ee#file-albumshuffle-txt

Now, when in album shuffle mode, the entire album will be added to the playlist at once. In addition, when an album has been added, anything else that is queued will follow afterwards (so, while listing to one album selected at random, one could queue up another song or album to play when that album is finished).

It appears to all work fine (not tested on a real device, though).

**Comment by adrian-bl** [comment]
That looks reasonable, but i feel that this could be simpler.
Maybe we also just want to get rid of the getRandomSong() and always have it return a list, so that SongTimeline doesn't have to care that much about the different modes. Also not sure if we really need to increase the queue shrinking (If i remember correctly, it only removes songs which have a lower queue position than the currently playing song, so it wouldn't do any harm even if we enqueue a 40 song album).

Btw: I commited my initial patch to head as https://github.com/vanilla-music/vanilla/commit/7f1e0791392b21dd42737241fe6914a58dc55b9d

**Comment by adrian-bl** [comment]
Oops - wrong button :-)

**Comment by stephenjsweeney** [comment]
I've updated the gist, removing getRandomSong() and replacing it with getRandomSongs(). Also restored the shrinkQueue() to 20.

https://gist.github.com/stephenjsweeney/ef78725f7376122823091fb5782539ee

**Comment by adrian-bl** [comment]
Could you rebase against the current head so that your diff only includes your changes? (Will make it simpler to read) or/and consider doing a pull request.

**Comment by stephenjsweeney** [comment]
No worries. I've created a pull request based on the current HEAD and my own additions.

**Comment by adrian-bl** [comment]
marking this as fixed as the PR has been merged and seems to work fine.

Thanks again!
