### ISSUE TITLE
USB Type C Headphones not working while "External Output only" is checked

### ISSUE THREAD

**Issue by gitwah** [vanilla-music/vanilla#702]
- Vanilla Music Version (Settings -> About): 1.0.57
- Android Version: 7.0
- Phone vendor / model: Xiaomi Note 2
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

I'm using USB Type C headphones. When the "External output only" setting is on, I don't get any audio / the player is behaving like there are no headphones conncted. As soon as "External output only" is deactivated, everything is just fine.

## Steps to reproduce the issue

- connect USB Type C headphones
- check "External output only"
- congratulations, you got no audio

Just an oversight I guess, should be an easy fix :) Thank you for this great music player btw

**Comment by adrian-bl** [comment]
Related code:
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/PlaybackService.java#L984

We probably should migrate this to use the new getDevices() code which can report USB Headsets:
https://developer.android.com/reference/android/media/AudioManager.html#getDevices(int)

**Comment by adrian-bl** [comment]
Pushed 9c6c18912f8fa98ff286fb2f1769034ec4e89f65 - still need to test it on a real device, but i suppose that this should work out.

**Comment by adrian-bl** [comment]
gitwah@ could you give the latest nightly build a test and confirm that it solves the issue? You can download the APK from http://vanillamusic.io - you can install the nightly alongside the normal version (it will show up as a different app)

**Comment by gitwah** [comment]
Just tried it, still not working. Got the nightly apk from your link, installed it, checked "external output only", plugged my headphones in - no sound. As soon as I disable the setting it's working again.

**Comment by adrian-bl** [comment]
Hmm.. that's annoying :-/

Could you re-download & re-install the (latest) nightly build?

I also added TYPE_USB_DEVICE to the list of external outputs, so this might now catch the connected device.

If this still doesn't work: could you get me a logcat?

Run
```
adb logcat | grep AudioDeviceInfo
```

and then hit the play button with the 'external output only' setting enabled.
It should print a list of all seen audio devices which would be helpful to debug the issue.

**Comment by gitwah** [comment]
Tried the latest nightly, it's fixed! Thank you.

**Comment by adrian-bl** [comment]
Great to hear! Thanks for the feedback!
