### ISSUE TITLE
The application is not showing some photo album embedded in the music files instead it's picking up an another photo from internal storage. 

### ISSUE THREAD

**Issue by philiparniebinag** [vanilla-music/vanilla#706]
This bug I found is for **Vanilla Music**.

This mentioned open-source application is somewhat very amazing tool in playing music but there are few bugs still exist in the application.

This bug I found recently in the application is that, **the application is not showing some photo album embedded in the music files instead it's picking up an another photo from internal storage**.

Please see it in the photo below:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513266732/qasn81ovkxuy1hcbctni.png)

> As you can see in photo above, please focus on the highlighted part where the photo icon of the album **Memories...Do not Open** by *The Chainsmokers & Coldplay*, the icon photo shows Naruto picture but that was not really the original embedded photo in the music files.

The application just picked up Naruto photo from my phone storage and not showing the original photo embedded on the file. But in the built-in music application in my Android Smartphone, the built-in app does show the correct embedded photo found in the files. The proof was shown below.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513267385/uvieaktjw6vykxzmva8l.png)

The photo that it picked up is stored in my Smartphone internal storage. Seen in the follows photo.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513267646/jejicuui2aed44ianpzv.png)

As I said, this bug is found in some music album and not all media files are affected by this bug. But there are many files in fact that was affected by this kind of bug. Please see the follows photo where another files was affected.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513269626/ifxny4viv6ju2jbiq5eg.png)

In the file as opened in the built-in music application of my Smartphone, the files doesn't have embedded photo yet it has in **Vanilla Music**.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513269813/itwwuyjh0me6npvpd1zp.png)

### My Smartphone details where I used to found this bug
**Phone Brand:** Vivo
**Model:** V5
**RAM:** 4GB
**OS:** Android 6.0.1

That's all. I hope the developer will hear this kind of bug found in the current application version.

I hope this bug will be fix soon as it picks personal photo from the user which is a privacy to be considered from the first place.

Edit from adrian: linkspam removed.

**Comment by adrian-bl** [comment]
This WAI: we always prefer image files found in the same folder as the audio file over the embedded artwork.

You can disable this by going to Settings > Cover Art ; then untick the 'Load artwork from folder' and restart/kill the app (to flush the in-memory cache)
