### ISSUE TITLE
Gratipay has closed down

### ISSUE THREAD

**Issue by regagain** [vanilla-music/vanilla#707]
See [The end of Gratipay](https://gratipay.news/the-end-cbfba8f50981?source=collection_home---5------0----------------).

You might want to update [README.md](https://github.com/vanilla-music/vanilla/blob/master/README.md#donations).

[Liberapay](https://liberapay.com/) seems to be a good alternative.

**Comment by adrian-bl** [comment]
Thanks for the notice: I removed them from the README.

I don't think we need a new service as vanilla-music costs me about $0.50 per year. (Google Cloud instance costs for the nightly builds)
