### ISSUE TITLE
WMA files not indexed

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#708]
- Vanilla Music Version : 1.0.58
- Android Version: 4.4.4
- Phone vendor / model: Samsung Galaxy S5 Plus SM-G901F
- Application was downloaded from :
  - [x] Play Store
  - [x] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

WMA files can be played inside the file explorer but are not indexed in media library. Why is that ? 

(Nothing do to with #238)

**Comment by adrian-bl** [comment]
That's odd: I don't have any WMA files myself but this should work.

Could you send me a sample to adrian@blinkenlights.ch?

**Comment by andiandi13** [comment]
After some test with other wma files, they are indexed normally. 

Actually the wma file that won't index has been converted from an .m4a when I copied it to my Samsung, which ask me to convert it to wma.

It's just that file, I don't know maybe the metadata are corrupted in the m4a because if I convert it first to another format and then to wma there isn't any issue.

Anyway, sorry for the waste of time but wma files are completely OK :)
