### ISSUE TITLE
*linkspam removed*

### ISSUE THREAD

**Issue by nilfanif** [vanilla-music/vanilla#709]
1. Please take a moment to check if the same Bug has already been reported.
2. Please use our subreddit for general questions: https://www.reddit.com/r/vanillamusic/
3. Please provide all relevant information below.

**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About):
- Android Version:
- Phone vendor / model:
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

....

## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by kirbyfan64** [comment]
For starters, I can't seem to even view that without an account, besides the fact you put the everything in the issue title and disregarded the template. Also, Vanilla recently changed its icon anyway...

**Comment by adrian-bl** [comment]
Closing this - yet another utopian linkspam attempt.

**Comment by adrian-bl** [comment]
Yes, thats the 3th "bug" linking to this site.

I wouldn't be bothered if the site was public, but i consider links to sites where you need to sign up to see any contents to be spam - i'd also delete links to private facebook groups.

**Comment by mktcode** [comment]
I would like to apologies for the inconvenience. We know about this issue and we are working on making the Platform public as soon as possible.

**Comment by diegopucci** [comment]
Utopian is not spam. It is a decentralised platform that rewards contributions to Open Source projects. The site was closed to public due to technical issues and will be open back in a few days.

**Comment by mktcode** [comment]
Indeed, not our brightest moment. We are now public again.
