### ISSUE TITLE
Database isn't created with recursive search for music files in indexed directories.

### ISSUE THREAD

**Issue by doronbehar** [vanilla-music/vanilla#710]
I've just installed the app on a new phone and I'm having trouble creating the database.

I have one directory with all the albums in it in the external SD card, in the albums there are music files and I've set the indexed directories to include only this folder.
When I hit the `start scan` button in the app's settings, it doesn't add anything to the database. But, if I tell it to include a directory which right inside it there are music files in depth level of 1, it does add those files to the database.
I think it would be correct to say that the scan function doesn't look for music files recursively.

When I had the app in the previous phone with a previous version I haven't had this problem.

I hope it can be fixed because I have a **lot**  of music directories and it will be a lot of work to include all of them.

Thanks for making this app :)

**Comment by Adonai** [comment]
Do you have a `.nomedia` hidden file in this folder?

**Comment by doronbehar** [comment]
Yes, I do, I removed it and it fixed it. I know what is this file's
purpose. I haven't noticed/thought about this option when I opened this
issue so thanks for reminding me to check this.

**Comment by adrian-bl** [comment]
closing this issue as stopping at .nomedia WAI

**Comment by kirbyfan64** [comment]
This seems to happen a bit...what if Vanilla showed a warning if the user manually adds a directory containing a .nomedia file to the search path?

**Comment by Adonai** [comment]
Yeah, at least toast would be nice
