### ISSUE TITLE
add language switcher

### ISSUE THREAD

**Issue by verdulo** [vanilla-music/vanilla#711]
Please add possibility to change the language of the user-interface, so it will be possible to select languages which are not selectable on Android (for example Esperanto).

**Comment by adrian-bl** [comment]
Sorry, but i do not think thats a feature we should implement.

One can always recompile vanilla music and force the language to whatever is needed.

**Comment by verdulo** [comment]
Vanilla Music is currently in English which is very hard to understand, I'm offering to translate it to Esperanto. The only thing I need is option to change the language.

**Comment by adrian-bl** [comment]
Send me a patch which implements the feature and i may consider merging it.

**Comment by verdulo** [comment]
Could you at least allow translating the application on Transifex? I will use external tool to change language of the application.

**Comment by Adonai** [comment]
It's on Transifex for a very long time actually

**Comment by adrian-bl** [comment]
Just accepted your request on transifex to translate to esperanto.

**Comment by verdulo** [comment]
Could you make my translation available in Nightly versions?

**Comment by adrian-bl** [comment]
Done: i pushed it via https://github.com/vanilla-music/vanilla/commit/008ed50fcd997ecc05598799d72b1b4565f22035 - the next nightly build will include this change.

**Comment by adrian-bl** [comment]
@Adonai what is missing?

@verdulo thanks for the translation - it is unfortunate that Android doesn't offer Esperanto as a selectable language.

**Comment by Adonai** [comment]
@adrian-bl I meant the "thanks" part but you just ruined the joke :D thanks!

**Comment by adrian-bl** [comment]
Ah ;-p
