### ISSUE TITLE
RemoteControlImplICS sends incorrect metadata

### ISSUE THREAD

**Issue by abn-volk** [vanilla-music/vanilla#712]
- Vanilla Music Version (Settings -> About): 1.0.58
- Android Version: 4.4.4
- Phone vendor / model: Genymotion emulator
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
In `RemoteControlImplICS.java`, artist and album are stored in the wrong field of MetadataEditor. The field METADATA_KEY_ALBUM contains "artist - album" and METADATA_KEY_ARTIST contains nothing. In line 143:
`	editor.putString(MediaMetadataRetriever.METADATA_KEY_ALBUM, artist_album);`

Meanwhile on Lollipop, `RemoteControlImplLP.java` stores the information correctly. 

I'm writing a lyrics finder app that retrieves information from RemoteController.MediaMetadataEditor and because the artist field is always blank, the app can't find any lyrics.
...

## Screenshot / Video (If applicable)
My app displays a notification when the song changes (using `NotificationListenerService` and `RemoteController.OnClientUpdateListener.onClientMetadataUpdate()`. It retrieves `METADATA_KEY_TITLE` and `METADATA_KEY_ARTIST` from the `RemoteController.MetadataEditor`. However, the artist field is blank.

[Imgur](https://i.imgur.com/H5IZvT1.png)
...

**Comment by adrian-bl** [comment]
We did that for 'historical reasons' because 4.x devices never displayed KEY_ALBUM.

I don't have a strong opinion on this - any 4.x users who care about the cururent behavior?

**Comment by abn-volk** [comment]
Oh, I didn't know that. I guess we can leave it as it is to fix that bug.
