### ISSUE TITLE
Widget used in Overlays closes current app

### ISSUE THREAD

**Issue by mcwieger** [vanilla-music/vanilla#715]
- Vanilla Music Version (Settings -> About): 1.0.58
- Android Version: 6.0.1
- Phone vendor / model: Joying car radio
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
I use the Overlays app (https://play.google.com/store/apps/details?id=com.applay.overlay) to show the music control widget (any size), to be able to skip to next song when using a different app (use case: show the music control widget on top of the navigation app).
When I press one of the buttons on the widget, the current app is closed and I'm taken to the home screen. The widget does perform the action corresponding to the button.
Expected result: current app remains on the foreground.

## Steps to reproduce the issue

1. Install Overlays.
2. Create scenario showing the music control widget on top of an app (e.g. Google Maps)
3. Open app. Widget is displayed on top of other app
4. Press any button on the widget

**Comment by adrian-bl** [comment]
I don't see how this is a bug on our side: Isn't that something that the Overlay app is handly poorly?

**Comment by mcwieger** [comment]
I think that depends on what Vanilla does when the button is pressed: does it only perform the action it's asked to do (e.g. Pause), or is another action triggered (e.g. close widget, go to home screen).
Poweramp's widget does not show the same behaviour.

**Comment by Adonai** [comment]
I don't see what we're doing different from other apps... Widget handles just single clicks and that's all.

FourSquareWidget
FourWhiteWidget
FourLongWidget

**Comment by abn-volk** [comment]
This is just a guess, but I think that's because widget clicks launch `ShortcutPseudoActivity`, which has these flags 
```
Intent.FLAG_ACTIVITY_NEW_TASK 
| Intent.FLAG_ACTIVITY_CLEAR_TASK 
| Intent.FLAG_ACTIVITY_TASK_ON_HOME
```
One of these flags must be closing the current app when `ShortcutPseudoActivity` is launched - perhaps `CLEAR_TASK` or `TASK_ON_HOME` is the culprit here.

**Comment by adrian-bl** [comment]
Thats possible: We use the same code in our widgets as we use in the shortcuts.

Can you recompile with these two flags removed to see whether it works?

**Comment by abn-volk** [comment]
Hm, adding `Intent.FLAG_ACTIVITY_MULTIPLE_TASK` seems to solve the problem for me (removing the flags didn't help). I only tested it on an emulator running 5.1 though.

**Comment by adrian-bl** [comment]
That wont work: a widget click should not start a new activity stack.

Maybe we would be forced to go back to the old widget launcher code...

**Comment by adrian-bl** [comment]
Closing this as i do not see what we are doing wrong.
Also: the app in question is closed source / commercial and i do not have the time to reverse engineer it.

**Comment by mcwieger** [comment]
That's too bad, I had the idea you guys were making progress. I'll have to move on then ☹
