### ISSUE TITLE
Change default sorting

### ISSUE THREAD

**Issue by cauebs** [vanilla-music/vanilla#717]
One thing I loved about this app is that I can have a "Composer" tab instead of "Artist", which is great for classical music. The problem is that when I filter an album, the default sorting takes the artist as the first field, which leaves everything out of order. The ability to change the default sorting (ideally, per tab) would be wonderful. I just don't want to have to put the composer in the artist tag.

**Comment by adrian-bl** [comment]
The sorting should be saved: If you go to the Album tab and change the sorting to 'Title', it should stick to this.

Or doesn't this work for you?

**Comment by cauebs** [comment]
If I close and reopen the app, the sortings are reset. But indeed, if they were saved it would be enough for me :)

**Comment by adrian-bl** [comment]
Oh: Turns out that we never restored the (saved) sort-order if the limiter changed while we are running (restore would have worked if we got restarted).

Commit c898969de16554fc59f96de1d7147bbd754fc487 should fix this.

**Comment by adrian-bl** [comment]
Closing as this is included in the latest release.
