### ISSUE TITLE
Correctly recognize more that one participating artist per song

### ISSUE THREAD

**Issue by ddv239** [vanilla-music/vanilla#718]
## Description
When an MP3 file contains more than one contributing artist in the Artist tag, separated with the slash character(s), as specified in the format (http://id3.org/id3v2.3.0#Text_information_frames_-_details), ideally, the media library implementation should recognize that and find the songs with participation of each of the artists listed. The current implementation does not do that.

## How to address
We should change the implementation of the media library scanner and database schema to have every song have 2 types (roles) of artist-related contributions:
- the "artists list" contribution - the contents of the original "Artists" tag, including its "/" separators. This value should be shown anywhere in the UI where the song's properties are shown.
- 1 or more "individual artist" contributions. These values would be used to find all the songs/albums where each individual artist participates.

I realize there are somewhat substantial changes across the Java sources and SQL code to be made to accommodate this design change.

**Comment by adrian-bl** [comment]
Related to #725

It seems that this is only true for ID3v2.3 (and lower?) and does not apply to v2.4?
But in any case this should be fixed in our tag reader: https://github.com/adrian-bl/bastp/issues

**Comment by adrian-bl** [comment]
Closing as a dup of #718
