### ISSUE TITLE
Missing genres in MP3s

### ISSUE THREAD

**Issue by dseomn** [vanilla-music/vanilla#725]
- Vanilla Music Version (Settings -> About): 1.0.58
- Android Version: Android 7.1.2 / LineageOS 14.1
- Phone vendor / model: HTC One M9
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

I have many MP3 files with ID3v2.4 tags that include multiple genres per file. I think the text is encoded as UTF-8 and the files additionally have ID3v1 tags. When I expand a genre from the library screen, then go to the "tracks" tab, some (or all, I'm not sure) of the MP3 tracks that I know are tagged with that genre are missing from the list.

**Comment by adrian-bl** [comment]
ID3v2.4 is a horrible format and we do indeed have issues parsing it sometimes.

Feel free to send me a sample to adrian@blinkenlights.ch

**Comment by dseomn** [comment]
Here's a 2 second sine wave tagged like one of the files that I have an issue with: [multi-genre.zip](https://github.com/vanilla-music/vanilla/files/1691999/multi-genre.zip)

**Comment by adrian-bl** [comment]
The sample file has one single TCON tag:

```
<TCON> = [added/2017dance/by-name/branleremark/catchy]
```

So this value should show up in the genres tab (if not: make sure to have 'Always use internal tag reader' checked in the media library settings.

So i'm not sure what to do here:
https://hydrogenaud.io/index.php/topic,61317.0.html suggests that SOME ID3v2 versions use / as a seperator, but 2.4 does not (your file is 2.4 tagged) - so we seem to do the right thing in this case.

**Comment by dseomn** [comment]
> &lt;TCON> = [added/2017dance/by-name/branleremark/catchy]

I think the TCON value in that file has some null bytes that aren't showing up here. I couldn't find anything in the specification that describes the use of null bytes to separate values in TCON, but http://id3.org/id3v2.4.0-frames (search for "TCON") gives this example with two values in a TCON frame: "21" $00 "Eurodisco" $00

**Comment by adrian-bl** [comment]
No: there are no NULL bytes: I cross-checked this with hexdump:

```
00000090  34 2d 30 34 2d 30 31 00  54 43 4f 4e 00 00 00 2f  |4-04-01.TCON.../|
000000a0  00 00 03 61 64 64 65 64  2f 32 30 31 37 00 64 61  |...added/2017.da|
000000b0  6e 63 65 2f 62 79 2d 6e  61 6d 65 2f 62 72 61 6e  |nce/by-name/bran|
000000c0  6c 65 00 72 65 6d 61 72  6b 2f 63 61 74 63 68 79  |le.remark/catchy|
000000d0  00 54 44 4f 52 00 00 00  06 00 00 03 32 30 30 36  |.TDOR.......2006|
000000e0  00 54 49 50 4c 00 00 00  01 00 00 03 54 4d 43 4c  |.TIPL.......TMCL|
```

But nevertheless, we should support such tags (and be relexed about the use of / or NULL)

**Comment by dseomn** [comment]
> So we have added/2017, dance/by-name/branle, remark/catchy.

Yup, that's correct.

> where are the added/remark strings defined? What kind of software did write such a tag?

ID3v2.4 and vorbis comments both support more-or-less arbitrary genres stored as free-form text. I use the tags to store a bunch of information that I find useful for finding what I'm looking for in my collection. In terms of software, I [add the tags to MusicBrainz](https://musicbrainz.org/user/dseomn/tags) and use [Picard](https://picard.musicbrainz.org/) to put the tags in the files.

**Comment by adrian-bl** [comment]
Ah: so the strings such as added/2017 are your text? I somehow assumed that some tagging software tried to put additional metadata into the TCON field.

**Comment by dseomn** [comment]
> Ah: so the strings such as added/2017 are your text?

Yup.

**Comment by adrian-bl** [comment]
This issue should be fixed in https://github.com/vanilla-music/vanilla/commit/b3c11e6549c7917a37b66100fdf790b852cf8f6d

We now split (known) values by \0 and add all found items.
I tested this with your sample file which now works as expected.
