### ISSUE TITLE
Genres not "translated"

### ISSUE THREAD

**Issue by joesse** [vanilla-music/vanilla#726]
- Vanilla Music Version (Settings -> About): 1.0.59
- Android Version: 6.0.1
- Phone vendor / model: Fairphone 2
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

In my genre list there are genres like (1).
When I look into the files tagged with (1) using the vanilla tag editor I find that this genre is translated as "Classic Rock".
In my Genre list I find both, (1) and Classic Rock.
Some of these files I have tagged myself using Picard.
## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
That should be fixed in https://github.com/vanilla-music/vanilla/commit/1a61c7f8b6d5c1f3aaf98a541c8cc6e3a005d5ef

Note that this only has an effect on newly scanned files - so you might want to do a full scan + flush the database to forcefully re-index all files.
