### ISSUE TITLE
Play All button broken

### ISSUE THREAD

**Issue by sakuramboo** [vanilla-music/vanilla#727]
- Vanilla Music Version (Settings -> About): 1.0.59 Released Jan. 30, 2017
- Android Version: 6.0.1
- Phone vendor / model: Motorola G Play
- Application was downloaded from (use `[x]`):
  - [X] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [X] Yes
  - [ ] No
  - [ ] NA / Don't know.

When doing a long press on a folder and selecting "Play" is supposed to load all the files in that folder into a play queue, but instead will either load no songs or a small selection of them will get loaded and usually picks a song somewhere in the middle of the directory listing. But, not all the files in the directory.

Also, if you go into the folder and click "Play All" it has the same behavior.

This was working fine yesterday, but there was an update over night which broke this feature.

....

Go to a folder, long press and select "Play" or go into the folder and press "Play All."

...

**Comment by adrian-bl** [comment]
The skipped files are probably not indexed.
Did you try to do a rescan?

**Comment by sakuramboo** [comment]
I thought the same thing so I hit "Start Scan" but it's still not working.

This is affecting every directory, not just a few select directories.

I can go into each directory and play each song without any issue, but when I try to "Play All" it doesn't

**Comment by adrian-bl** [comment]
Try to tick the "Scan full filesystem" checkbox: by default, we just sync with Androids DB, which seems to be hosed in your case.

**Comment by sakuramboo** [comment]
I did the full scan and it seems to be working as expected now.

Thanks.
