### ISSUE TITLE
Playlists now missing songs

### ISSUE THREAD

**Issue by bobolea** [vanilla-music/vanilla#729]
- Vanilla Music Version (Settings -> About): 1.0.59
- Android Version: 7.1.2
- Phone vendor / model: Nokia 6 Ta-1025
- Application was downloaded from (use `[x]`):
  - [x ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description
Since updating to this version my playlists have lost most of their songs, although the playlists still show, These are playlists that have been created in vanilla. This also affects another phone with the same model and version of software. I have tried doing a Full scan and a flush media database but this makes no difference.
....

## Steps to reproduce the issue
Go into any previous created playlist.
...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
There is no backup of playlists: if an entry is gone, it is gone.

Your phone probably reported that some of the songs were unavailable, so vanilla purged them from the playlist.

**Comment by bobolea** [comment]
Can I ask why there is no backup of playlists? 

The songs all seem available so I dont know why they arent showing on the playlists now.

I have checked in google music and I can still see some of the playlists in there that I must have previously created with play music but these are still showing correctly, is there no way I can import these again somehow?

Thanks

**Comment by adrian-bl** [comment]
> Can I ask why there is no backup of playlists?

Because such a feature is simply not implemented.

> I have checked in google music and I can still see some of the playlists in there that I must have previously 
> created with play music but these are still showing correctly, is there no way I can import these again 
> somehow?

Yes - if Android still (or again) knows them, you can:
 * Delete the Playlist(s) in Vanilla Music
 * Settings -> Media Library
 * Select full scan and database drop
 * Hit the Scan button

This will take a while - and the last step will be to import system playlists (which are not present yet, hence the deletion first)
