### ISSUE TITLE
Give option to only use cover art stored in the same folder

### ISSUE THREAD

**Issue by yaomtc** [vanilla-music/vanilla#730]
- Vanilla Music Version: 1.0.59
- Android Version: 8.0
- Phone vendor / model: Moto X4
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

Sometimes Vanilla Music will show album art from a completely different folder and artist.

## Steps to reproduce the issue

I haven't figured this out yet.

## Screenshot / Video (If applicable)

![screenshot_20180215-164426](https://user-images.githubusercontent.com/5534045/36282678-ef2fbf6a-126f-11e8-9abb-0871f212de47.png)

![screenshot_20180215-164949](https://user-images.githubusercontent.com/5534045/36282782-4ad0bf22-1270-11e8-8ac4-9a913fc331bb.png)

**Comment by adrian-bl** [comment]
If the image is not in the folder, it is either present in the tag or set as cover in Androids media Db.

Uncheck the 'Load artwork from Android' option to disable this.

(Note: you must kill vanilla for this to take effect)

**Comment by yaomtc** [comment]
I have that unchecked, and after restarting the phone, that incorrect cover art is still being shown. It may have something to do with the fact that both lack an album title. I just noticed if I go to speder2 in "artists", it shows "<No Album> by JerryTerry", and the tracks within are a collection of all the files in my music folder that don't have album information... Oh wow, there's a lot in here. And all albums called "Greatest Hits" (Huey Lewis, Queen...) are all grouped together under Earth, Wind & Fire... WTF?

**Comment by adrian-bl** [comment]
Ah, yeah: Album covers are shared between album names.

Selecting the 'Group albums by folder' in the media library may help.

**Comment by yaomtc** [comment]
That seems like quite an imprecise method... well, that explains my issue. I'll let this scan go, and I'll let you know if the problem is fixed in the morning.

**Comment by yaomtc** [comment]
That fixed it, thanks!
