### ISSUE TITLE
Small gaps between songs in playback

### ISSUE THREAD

**Issue by SilentFlyBy** [vanilla-music/vanilla#734]
- Vanilla Music Version (Settings -> About): 1.0.59
- Android Version: 7.0
- Phone vendor / model: Huawei P10 lite
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [ X] NA / Don't know.

## Description
When playing a playlist, there is a small gap (about 200ms) between the songs

## Steps to reproduce the issue
- make a playlist with songs that fade into each other
- forward to the end of one song

The problem seems to be specific to my phone because it seems to haven't been reported before and it works flawlessly on the Android emulator

**Comment by adrian-bl** [comment]
Your phone seems to lack gapless support and there is not much we can do about: you could try a different format (ogg and opus usually work).

**Comment by SilentFlyBy** [comment]
Apparently it works in Poweramp, but I don't know if it uses the same mechanic to implement gapless playback.

**Comment by kirbyfan64** [comment]
I believe Poweramp decodes and processes the audio by itself, whereas Vanilla uses Android's normal playback system.

**Comment by adrian-bl** [comment]
Yes, Poweramp uses its own sw-decoder while we depend on the media framework of your phone.
