### ISSUE TITLE
Add feature to be able to save favorites playlist to a file

### ISSUE THREAD

**Issue by lenzj** [vanilla-music/vanilla#735]
- Vanilla Music Version (Settings -> About): 1.0.59
- Android Version: 8.1.0
- Phone vendor / model: Nexus 6p
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
I enjoy using vanilla music player and have added quite a few music files to my "favorites" playlist using the star icon while a track is playing.  I would like to be able to export my favorites so that I can use them on my other devices.  It would be great to be able to export the favorites play list (or any other playlist) to a m3u file or equivalent.

**Comment by adrian-bl** [comment]
Yes, we really need a way to import and export playlists to M3U.

We already have #643 which talks about M3U support, so i'm closing this as a duplicate for now.
