### ISSUE TITLE
Replaygain not applied after audio focus gain

### ISSUE THREAD

**Issue by stephenjsweeney** [vanilla-music/vanilla#737]
- Vanilla Music Version (Settings -> About): 1.0.59
- Android Version: 8.0.0
- Phone vendor / model: OnePlus 3T
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

If the audio focus is lost, such as when a phone call comes in, Vanilla will stop playing (as expected). However, when the focus returns, the volume of the current track (or the one following) does not appear to have the replaygain applied and the volume can end up being very loud. This can be fixed by changing the current track.
....

## Steps to reproduce the issue

Play any track with replaygain applied. Lose the focus (by receiving a call on the phone, for example). Note the volume change (which may not be until the track that follows).
...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
Hmmm.. that works for me: tested by having VLC steal the audio focus.

Does this always happen or only under some circumstances?

**Comment by stephenjsweeney** [comment]
I'm thinking this could actually be (another) issue with OnePlus' Oxygen OS. There are other problems, such as the notification always forcing ducking, and the media scanner not working correctly until there's a reboot.

Since you're not able to recreate this, I'm going to close it for now.
