### ISSUE TITLE
With an update in 2018, suddenly, more than half of everything is no longer indexed properly /  no longer shows up

### ISSUE THREAD

**Issue by JonasT** [vanilla-music/vanilla#739]
- Vanilla Music Version (Settings -> About): `1.0.59 Released Jan. 30, 2017` (latest on f-droid)
- Android Version:
- Phone vendor / model:
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [X] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

With an update from f-droid in early 2018, suddenly, more than half of everything is no longer indexed properly /  no longer shows up. In the "Files" tab, everything is there, but when browsing "Albums", while albums are there, a quarter to more than three quarters of the songs of each album are missing (it seems to be quite random which ones, I couldn't find an obvious pattern like music file format or something). It worked fine before, it's just broken since that particular update.

## Steps to reproduce the issue

1. Index your library

**Comment by adrian-bl** [comment]
Did you try a rrscan in the media library settings?

**Comment by JonasT** [comment]
I tried Settings > Media Library > Media Scanner "Start Scan" with [x] Flush Media Library enabled.

I am just trying now again, but the telltale sign of some albums having appeared with only 2 to 8ish of 16-20 songs has already started (with nothing new popping up while other albums are already being scanned).

For what it's worth, I might be wrong, but all the affected albums seem to be mp3. I haven't found an ogg or FLAC album yet which is affected.

**Comment by JonasT** [comment]
For what it's worth, since a lineageos change a few months ago, Vanilla Music started to crash. I observed that the crash happened in most cases when 1. Entering an album with Covers, 2. Clicking play on a song without the cover having loaded yet, 3. During playback in the first seconds, there used to be a medium probability of a crash.

Since this Vanilla Music update with now some songs not being listed at all, I haven't seen this crash once. I don't know if it's just a coincidence, but I wanted to mention it in case it's related.

**Comment by JonasT** [comment]
Oops, seems like I made the ticket too early. "Flush Media Library" actually fixed it and the other album pieces just took a while to turn up. Whatever it was that interrupted a previous scan and made things go missing, now everything is back :-) :+1:

**Comment by adrian-bl** [comment]
> For what it's worth, since a lineageos update a few months ago, Vanilla Music started to crash.

That's interesting, do you happen to have a logcat of such a crash?
It may be that you have a file which crashes mediaserver and therefore we crashed during a library update (which left the library in a funny state).

**Comment by JonasT** [comment]
Sadly I don't, I planned to get one but it had the unfortunate coincidence of usually happening when I was on the way to a work event where I had other things to think about. However, if it ever happens again I'll collect one.

Have you ever considered built-in crash reporting? If there was an easy way to send you the crash with a single button press (if that opened up an e-mail with an attachment that would be fine as well) that doesn't require me to use adb and a laptop, I'd much more likely find the time to do this on the run when it happens again.

**Comment by adrian-bl** [comment]
Not really: We already have crash reporting from the google play store (I'd assume to see most/all f-droid crashes reflected in crashes of the play store version).

However: in such specific cases, the crash is issue is likely to happen somewhere in android itself - and we would not be able to read such log info without using some ugly permissions.
(By default, the app can only read it's own logs, so we wouldn't see any mediaserver issues)
