### ISSUE TITLE
Music List Fails to Refresh On Vanilla-Music when New songs are added On Device

### ISSUE THREAD

**Issue by gutzygwin** [vanilla-music/vanilla#740]
#### Expected behavior
Vanilla-Music is an open source music player widely used by andriod users. As expected by the music player, the music playlist is supposed to be refreshed or reloaded to show any new changes done on the application when new songs are added on the Mobile Device.

#### Actual behavior
When New songs are added on mobile device, the vanilla-music application fails to refresh playlist to highlight or show "Last added" songs to device.
* *As a test run, I decided to add songs from another mobile device using the xender application. After the songs had been added to the phone, the playlist was refreshed but songs weren't added.*

#### How to reproduce
* Download Vanilla music player from Google Playstore
* Open the Application and allow app to read phone storage to access music on device. 
* Add new songs to Mobile Device.
* Return to Vanilla music player and refresh Playlist. 
* Music Playlist fails to add or display new songs. 

* Browser: Google playstore/Vanilla-Music
* Operating system: Android 7.0. Infinix Note 4

#### Recording Of The Bug

https://youtu.be/6bdrjlXWQ98
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/music-list-fails-to-refresh-on-vanilla-music-when-new-songs-are-added-on-device">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by adrian-bl** [comment]
The app used to store the file did not broadcast the new file.

Start a manual full library scan in settings.
