### ISSUE TITLE
unable to send music from file to playlist

### ISSUE THREAD

**Issue by celizstine** [vanilla-music/vanilla#741]
#### Expected behavior
After getting a particular music from file folder, you wont want to go to file again to get the music, so i decided to add it to a playlist, but i was unable.

#### Actual behavior
showing zero music was added, tried different playlist  and created also, but couldnt adda song

#### How to reproduce
- download the vanilla app
- launch it
- goto file
- goto the directory path of the musc
-try adding the song to playlist

* Browser:  infinix note 4 pro
* Operating system: android 7.0

#### Recording Of The Bug
https://youtu.be/3CLWhuCKIak
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@celizstine/unable-to-send-music-from-file-to-playlist">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by adrian-bl** [comment]
The file is not indexed.

Go to settings and start a medialibrary rescan.
