### ISSUE TITLE
Typo in the google store description text?

### ISSUE THREAD

**Issue by neunmalelf** [vanilla-music/vanilla#743]
...  Ogg und FLA**G** Dateien ... Shouldn't it be:  ... Ogg und FLA**C** Dateien ...  ?
       

Good work btw.
rgds
NeunMalElf

**Comment by adrian-bl** [comment]
Oh, das war im deutschen Text wirklich falsch.

Danke für den Hinweis! Habs korrigiert (dauert einige Zeit bis es im Playstore auftaucht)
