### ISSUE TITLE
Bluetooth pause button not working

### ISSUE THREAD

**Issue by topas-rec** [vanilla-music/vanilla#747]
- Vanilla version: 1.0.59
- Android Version: 7.1.2 (lineageOS 14.1)
- Phone vendor / model: LG G4 (H815)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [X] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

I'm using vanilla often together with a Bluetooth car radio. This JVC radio has got a play/pause button.
Since the mentioned version above this button only works for play, not for pause (stop) anymore. (Music continues playback after pressing play/pause button even after pressing it twice) It worked in the version 1.0.58. For testing I reinstalled the app in the previous version. In version 1.0.58 music stops playing when pressing the play/pause button. I reinstalled the current (1.0.59) version to verify the issue persists after reinstall (and app data wipe) and found out that it is still present.
The same happened about one or two years ago. It didn't worked in some version and then after updating to some other version it worked again. (I thought - nice someone fixed it)
I also use non Bluetooth headphones with a button placed on the wire. This button works with both functions. Play and pause (stop).

## Steps to reproduce the issue

Start playing music to a Bluetooth device which has a button for at least stop (play / pause is mostly found on devices I think) Press the button during playback. Expect the music playback to stop.

I like the app - thanks for development!

**Comment by adrian-bl** [comment]
We did have some remote-control related changes in 1.0.59. One suspect commit would be
https://github.com/vanilla-music/vanilla/compare/1.0.58...1.0.59#diff-a3a9f3b34875d927590616febfbd31e2

Do you have the SDK installed?
If yes then you could try to revert commit https://github.com/vanilla-music/vanilla/commit/07a21c5d99458662de96d9d63dcf28a30a7f3782 to see if it helps.

**Comment by topas-rec** [comment]
Hey ho,

I'm sorry I have no android dev tools installed. I'm afraid I have no time go deep into this. If someone could provide an apk I'll try it out.

Can you revert the mentioned and build a test version for me?

**Comment by adrian-bl** [comment]
Sure:

I uploaded a test build at:
https://drive.google.com/open?id=1CcP5gCe2e6JWEue_o6khHqTnAhiiFtXa

(Note that this is signed with a different key, so you need to uninstall any other version you have installed)

**Comment by topas-rec** [comment]
Tested this and it brought back the pause/stop functionality

**Comment by adrian-bl** [comment]
Cool: thanks for the feedback!

Committed https://github.com/vanilla-music/vanilla/commit/8584299c76ca1ea19695dda404b4bc230fa23fc7 which undoes this change, so the next release should start to work again for you.

**Comment by topas-rec** [comment]
Thank you!

**Comment by topas-rec** [comment]
Tested in version 1.0.60 and the pause function is back.
Again - thank you.
