### ISSUE TITLE
Music stopping randomly in playlists and albums.

### ISSUE THREAD

**Issue by bobolea** [vanilla-music/vanilla#749]
- Vanilla Music Version (Settings -> About): 1.0.59
- Android Version: 8.0
- Phone vendor / model: Nokia 6 Ta-1025
- Application was downloaded from (use `[x]`):
  - [x ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x ] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

The music seems to stop playing after a random amount of time, doesnt seem to happen before about 10 tracks,  this happens on both playlists and albums. This issue has happened on two separate phones of the same model but believed to have happened on Android 7.1.2 as well as Oreo 8.0

....

## Steps to reproduce the issue
Play an album or playlist and leave phone unatteneded.
...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
This is most likely a firmware issue: tipping over a 'bad' mediafile can cause the mediaserver to stop.

A logcat may give some clues on what happened.

**Comment by bobolea** [comment]
Sorry, what is a logcat? This doesnt seem to just happen on specific albums or playlists though, it seems random.

**Comment by adrian-bl** [comment]
A snapshot of the system log:

https://developer.android.com/studio/command-line/logcat.html

**Comment by mindforger** [comment]
did you have amazon music installed by chance? and maybe those songs were part of the "offline" titles? they added DRM to their offline tracks a few weeks ago that prevented them from playing in vanilla for me and i had to skip those songs until i got them sorted out and replaced by DRM free versions

**Comment by bobolea** [comment]
No I dont have amazon music installed. As I am just a normal user of vanilla music I assume that logcat isnt really for me and there isnt really any way to understand what is happening?

**Comment by abn-volk** [comment]
Sorry for commenting on an old-ish issue, but I believe this is a Nokia 6 bug. On Reddit and Nokia's support forums many have encountered this issue with various music players. I've got a TA-1021 and the problem seems to happen on my device as well. I think this issue should be closed.

**Comment by adrian-bl** [comment]
Ok, thanks for the notice!
