### ISSUE TITLE
Keeps adding a different version of the same song to the playlist over and over again, without informing the user that song already exists

### ISSUE THREAD

**Issue by zinonweke** [vanilla-music/vanilla#750]
#### Expected behavior
When the user adds a song to a playlist, and the song  already exist in the playlist; the application is supposed to inform the user that song already exists, without adding a different version of the same song. 
#### Actual behavior
The music player keeps adding different versions of the same song to the playlist, without informing the user that the song already exists.
#### How to reproduce
1. Download Vanilla Music Player;
2. Launch the application ;
3. Create a new playlist and add a particular song to the playlist;
4. Go and add the same song over and over again. It will keep adding different versions of the same song without informing the user that the song already exists in the playlist. 

* Browser: Android 7
* Operating system: Tecno Camon CX
* Application Version: Version 1.0.59 

#### Recording Of The Bug

https://youtu.be/Oix43dTDjF4

**Comment by adrian-bl** [comment]
This is not a bug: this is the expected behavior.
