### ISSUE TITLE
unable to delete music from file 

### ISSUE THREAD

**Issue by kr-nahid** [vanilla-music/vanilla#751]
#### Expected behavior
After listening  a song, if the song does not look good then you definitely do not keep the song in your folder ? so i decided to delete it , but i was unable.

#### Actual behavior
showing zero tracks deleted , tried different songs also, but couldnt deleted song

#### How to reproduce
 -  download the vanilla app
 -  launch it
 -  goto file
 -  goto the directory path of the music try deleting  the song 

* Browser:  symphony v75
* Operating system: Android M OS 6.0

#### Recording Of The Bug
https://www.youtube.com/watch?v=7BDwVGNeWD4
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kr-nahid/unable-to-delete-music-from-file">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by adrian-bl** [comment]
We are not accepting reports from utopian.io.

**Comment by sserkez** [comment]
Same problem

**Comment by torvaldmain** [comment]
Same problem
