### ISSUE TITLE
track s order by artist name

### ISSUE THREAD

**Issue by zyf0330** [vanilla-music/vanilla#753]
- Vanilla Music Version (Settings -> About): newest
- Android Version: 8.1
- Phone vendor / model: pixel 2 xl
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

....
tracks is ordering by artist name not track name，is it expected？
## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
Yes?

The default sorting is Artist, Album, Tracknumber.

You can change the sorting in the menu.

**Comment by zyf0330** [comment]
I mean tranks item order, not tab in the top.

**Comment by adrian-bl** [comment]
Tap the menu button and select 'Sort By'.

**Comment by zyf0330** [comment]
Thanks a lot. I just ignore that button.
