### ISSUE TITLE
[Proposal] ACRA reporting?

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#754]
Hi Adrian.
I see there are lots of issues where no logcat is available.
We could actually help people out on these using [ACRA](https://github.com/ACRA/acra) framework.

It has wiki page on logcat collection: [here](https://github.com/ACRA/acra/wiki/AdvancedUsage#adding-logcat-eventlog-or-radiolog-extracts-to-reports)

And to show logcat to user we can use menu option with handler like [this](https://github.com/ACRA/acra/wiki/AdvancedUsage#sending-reports-for-caught-exceptions-or-for-unexpected-application-state-without-any-exception).

I know you don't like additional dependencies but please consider.
This could potentially make your life as a maintainer much easier.

**Comment by adrian-bl** [comment]
I already get stacktraces and crashes from the play store, so for general crashes (affecting multiple users), we are well covered.

The cases where i ask for a logcat on github are usually somewhat different:
These are mostly device specific issues which, even after the logcat was provided, will need more work, such as installing a nightly build or sending some test files.

I have the feeling that users who are not willing to install (or learn how to use) `adb` would also not be able/willing to install test builds.

Also note that 'ACRA' can only get the logs of VanillaMusic itself on Devices >= 4.1 which makes it somewhat useless as we won't be able to collect any output from the mediaserver by using it.

**Comment by Adonai** [comment]
Ok, seems it would be overkill for now.
I'll close the issue then but will reopen it if any features in ACRA will become more appealing for us.
Thanks!
