### ISSUE TITLE
Last song will switch between this and last 

### ISSUE THREAD

**Issue by zyf0330** [vanilla-music/vanilla#755]
- Vanilla Music Version (Settings -> About): newest
- Android Version: 8.1
- Phone vendor / model: pixel 2 xl
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

I use edge sensitive to send last song signal to switch song. When it is playing song A and it can change to last song B, then when send signal again, it changes to song A but not last song of song B.

## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
Sorry, i do not understand this bug report: could you provide more details? Maybe a screen recording?

**Comment by zyf0330** [comment]
Sorry, after my another test, it is my fault.
