### ISSUE TITLE
Replaygain does not work with some tracks

### ISSUE THREAD

**Issue by Nojevah** [vanilla-music/vanilla#759]
- Vanilla Music Version (Settings -> About): 1.0.59
- Android Version: 7.1.2 (LineageOS)
- Phone vendor / model: Moto X Play
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

With some tracks, ReplayGain is ignored. I can see it is not detected because if I change setting "ReplayGain > Tracks without ReplayGain tag", it affects this problematic track.

The track has nothing particular, it's a Flac file. ReplayGain has been applied by Foobar2000 (like all my tracks). Foobar2000 can read ReplayGain info without problem.
It's not the only track, there are a few.
I can send track by pm if needed.

**Comment by adrian-bl** [comment]
Could you post the output of `metaflac --list` for one of the affected tracks?

**Comment by Nojevah** [comment]
```
METADATA block #0
  type: 0 (STREAMINFO)
  is last: false
  length: 34
  minimum blocksize: 4096 samples
  maximum blocksize: 4096 samples
  minimum framesize: 14 bytes
  maximum framesize: 14633 bytes
  sample_rate: 44100 Hz
  channels: 2
  bits-per-sample: 16
  total samples: 7996212
  MD5 signature: 60c4bc6d56b265be889e7641e9ba7609
METADATA block #1
  type: 3 (SEEKTABLE)
  is last: false
  length: 342
  seek points: 19
    point 0: sample_number=0, stream_offset=0, frame_samples=4096
    point 1: sample_number=438272, stream_offset=812701, frame_samples=4096
    point 2: sample_number=880640, stream_offset=2021787, frame_samples=4096
    point 3: sample_number=1318912, stream_offset=3226655, frame_samples=4096
    point 4: sample_number=1761280, stream_offset=4608182, frame_samples=4096
    point 5: sample_number=2203648, stream_offset=5996929, frame_samples=4096
    point 6: sample_number=2641920, stream_offset=7257884, frame_samples=4096
    point 7: sample_number=3084288, stream_offset=8638076, frame_samples=4096
    point 8: sample_number=3526656, stream_offset=10033568, frame_samples=4096
    point 9: sample_number=3964928, stream_offset=11312793, frame_samples=4096
    point 10: sample_number=4407296, stream_offset=12539506, frame_samples=4096
    point 11: sample_number=4849664, stream_offset=13912395, frame_samples=4096
    point 12: sample_number=5287936, stream_offset=15330052, frame_samples=4096
    point 13: sample_number=5730304, stream_offset=16589300, frame_samples=4096
    point 14: sample_number=6172672, stream_offset=17877329, frame_samples=4096
    point 15: sample_number=6610944, stream_offset=19164969, frame_samples=4096
    point 16: sample_number=7053312, stream_offset=20543837, frame_samples=4096
    point 17: sample_number=7495680, stream_offset=21940668, frame_samples=4096
    point 18: sample_number=7933952, stream_offset=23021240, frame_samples=4096
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 204
  vendor string: reference libFLAC 1.3.1 20141125
  comments: 7
    comment[0]: ARTIST=Jonas Blue
    comment[1]: DATE=2017
    comment[2]: GENRE=Pop
    comment[3]: Rating2=7
    comment[4]: TITLE=Mama (Feat. William Singe)
    comment[5]: replaygain_track_gain=-9.72 dB
    comment[6]: replaygain_track_peak=0.908142
METADATA block #3
  type: 1 (PADDING)
  is last: true
  length: 8156
```

**Comment by adrian-bl** [comment]
That does indeed look fine.
Could you send me the problematic file to adrian@blinkenlights.ch?

**Comment by adrian-bl** [comment]
Thanks for the sample file:
The Flac file you sent contains both an ID3v2 tag AND a vorbiscomment - unfortunately, they are not really the same:


```
$ id3info Jonas\ Blue\ -\ 2017\ -\ Mama\ \(Feat.\ William\ Singe\).flac 

*** Tag information for Jonas Blue - 2017 - Mama (Feat. William Singe).flac
=== TIT2 (Title/songname/content description): Mama
=== TPE1 (Lead performer(s)/Soloist(s)): Jonas Blue feat. William Singe
=== TALB (Album/Movie/Show title): We Love Summer 2017
=== TYER (Year): 2017
=== TRCK (Track number/Position in set): 04/23
=== COMM (Comments): ()[eng]: Track 4
=== TCON (Content type): Pop
=== TENC (Encoded by): Exact Audio Copy   (Burst Modus)
=== COMM (Comments): (ID3v1 Comment)[XXX]: Track 4

....
$ metaflac --list Jonas\ Blue\ -\ 2017\ -\ Mama\ \(Feat.\ William\ Singe\).flac 
METADATA block #2
  type: 4 (VORBIS_COMMENT)
  is last: false
  length: 204
  vendor string: reference libFLAC 1.3.1 20141125
  comments: 7
    comment[0]: ARTIST=Jonas Blue
    comment[1]: DATE=2017
    comment[2]: GENRE=Pop
    comment[3]: Rating2=7
    comment[4]: TITLE=Mama (Feat. William Singe)
    comment[5]: replaygain_track_gain=-9.72 dB
    comment[6]: replaygain_track_peak=0.908142
```

As you can see, the replay gain information is only stored in the vorbiscomment part of the file - the ID3 tag has no such information.

Our tag reader does not expect to find more than one metadata format per file and just goes with the first one it found (ID3 in this case).

I don't think there is much we can do - your best bet is to simply remove the ID3v2 tags and have the file just contain the vorbiscomment metadata (Side note: My Android 5.1 test device can not even play such files)

**Comment by Nojevah** [comment]
Ok then. I heard about these tags (ID3 or vorbis_comment) but I did not know it could bother this much a player.
I used mp3tag to find these flac files wrongly tagged, and I converted them to the right tag.
For those interested, I removed track in mp3tag, then I pressed the "undo" button, and when undoing, mp3tag puts the right tag.
Confirmed working with Vanilla Player.
Thanks for the precious analyse. I think you can cloture this ticket.

**Comment by adrian-bl** [comment]
> ... but I did not know it could bother this much a player.

This isn't just some additional metadata: The ID3 tag is actually at the beginning of the FLAC file, making the whole structure of the file quite different.
I'm actually surprised that metaflac (and your phone) are able to read such files. As a side note: oggenc fails to read such flac files.
