### ISSUE TITLE
[Request] Widget with album art only

### ISSUE THREAD

**Issue by tmknight** [vanilla-music/vanilla#764]
Would be appreciated to have a widget with album art only. Similar to white widget though without the image of the vinyl record. Keep up the good work!

**Comment by adrian-bl** [comment]
Could you maybe draw a mockup for what you had in mind?

**Comment by tmknight** [comment]
See attached. Bear in mind the widget is transparent, showing device
wallpaper. Also, the album art would look better as square vs round.
However the over all availability of player functionality presented with
just the basics of track info and album art is what I'm proposing.

**Comment by tmknight** [comment]
Also, if you point me to the widget code, I'd be willing to take a swag at
it. Not a C dev by trade, but I know my way around abit of .Net code.

**Comment by tmknight** [comment]
I'll take a look and see what I can do this week.  Transparent example below...
![capture _2018-04-14-09-53-46](https://user-images.githubusercontent.com/548588/38772856-793c86ae-400e-11e8-9f27-c8f7faa21f82.png)

**Comment by adrian-bl** [comment]
Did you make any progress on this? Let me know if you need help!
