### ISSUE TITLE
Uptade automatically playlists

### ISSUE THREAD

**Issue by justanidea** [vanilla-music/vanilla#765]
I often set one of my folder as a playlist. But when I add a music to it I have to delete the first playlist and replace it by creating a new one with the folder updated. Thats quite boring, and imagine that I have more than 10 folders...
I know it is related to #744 but it would be important to update playlist's content automatically, as the same time as scanning everything.

Ps : Great job,  love your app!

**Comment by adrian-bl** [comment]
That feels like the same issue as described in https://github.com/vanilla-music/vanilla/issues/640, closing this as a duplicate.
