### ISSUE TITLE
Shuffle adds new tracks rather than shuffling through the queue

### ISSUE THREAD

**Issue by KonomiKitten** [vanilla-music/vanilla#766]
I find the shuffle play mode to be quite odd, it seems to randomly add songs to the queue rather than randomly playing through the queue, I don't know of any other audio player that does this and I think it should be changed to only randomly play through the queue and not add new songs to the queue.

**Comment by KonomiKitten** [comment]
Oh there are two playlist mode buttons I never noticed, I really think this needs to be cleaned up and random should be removed or put somewhere else. No other queue setting modifies the queue as far as I can see, it's really inconsistent with the other options. I think it should be in the three dots menu instead.

**Comment by adrian-bl** [comment]
It may be confusing at first but i think that the current way is pretty good after you got used to it.
