### ISSUE TITLE
WebView disappear after exiting app and re-entering

### ISSUE THREAD

**Issue by calbee633810** [vanilla-music/vanilla#767]
- Vanilla Music Version (Settings -> About): 1.0.60
- Android Version: 23
- Phone vendor / model: Nexus 4
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
In Settings, click About, then pressing home button and re-enter the app, About disappear. But it should persist there.

## Steps to reproduce the issue
1. Click Settings
2. Click About
3. Press home button
4. Re-enter app

## Screenshot / Video (If applicable)
![bug0-before](https://user-images.githubusercontent.com/38213896/39096036-ae667442-467c-11e8-9fb8-4a1d927c869a.png)
Screenshot before pressing home button

![bug0-after](https://user-images.githubusercontent.com/38213896/39096037-b537fa84-467c-11e8-9b0e-9ba7afc3c0fd.png)
Screenshot after re-entering app

**Comment by adrian-bl** [comment]
Hmmm.. i tested this on two devices running 7.1 and 8.0 and everything works there.

Are you running a custom rom or the stock nexus image?

**Comment by adrian-bl** [comment]
Ah: just realized i misread your report: i understood that you ended up with an empty webview, but you get taken to the library view.

This works as expected: when launching the app, we always go back to the library or playback view (depending on the settings)
