### ISSUE TITLE
[Request] Android auto support 

### ISSUE THREAD

**Issue by Arzza** [vanilla-music/vanilla#770]
- Vanilla Music Version (Settings -> About): 1.0.60
- Android Version: 7.0
- Phone vendor / model: LG g6
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
It would be great if there was support for Android auto!
Also while I was checking version number it said 2017 not 2018 🤷

**Comment by adrian-bl** [comment]
We already do have mirrorlink support, which looks almost the same as the Android Auto samples.
Maybe someone more familiar with it knows what needs to be done to be compatible with android auto?

Thanks for the note about the year, fixed it in commit fcd42ae6206988f32189f4b178dca4d61274c4a0

**Comment by Arzza** [comment]
This is Google's info on setting up an app to support Android auto https://developer.android.com/training/auto/audio/

**Comment by GitKalle** [comment]
I add the Android Auto support, see on my fork [https://github.com/GitKalle/vanilla/commit/8a62ec5f7bda34d24a18c9d517c69c771a0a0ffb](url). You have to build it by yourself.

Up to now the notification and the album cover is missing. I try to add this features and make a pull request to the original repository after that.

**Comment by adrian-bl** [comment]
Thanks for the Pull Request, but i'm concerned about the review process and that Android Auto is only supported for apps installed from the play store (making the f-droid version inferior): https://developer.android.com/docs/quality-guidelines/auto-app-quality

**Comment by GitKalle** [comment]
@adrian-bl

I know, but why did you label the issue "patches-welcome"? In my opinion, it's better to close the issue with this explanation.

**Comment by adrian-bl** [comment]
I run vanilla music in my spare time and do not have time to investigate every feature request: I simply didn't realize this requirement/limitation at the time when the request was made.
I only discovered it this morning while skimming trough the documentation.

**Comment by GitKalle** [comment]
OK, I got it. Good job.
