### ISSUE TITLE
.opus files are not included in a directory "Play all"

### ISSUE THREAD

**Issue by Benny-** [vanilla-music/vanilla#774]
- Vanilla Music Version (Settings -> About): `1.0.61 Released Mai. 8, 2018`
- Android Version: `8.0.0`
- Phone vendor / model: `TA-1032`
- Application was downloaded from:
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
.opus files are not played when pressing "Play all" in a directory view.

## Steps to reproduce the issue
- Go to a directory with .m4a files and .opus files.
- Click "Play all" at the top.

## Expected behavior:
All .m4a files and all .opus files will played

## Actual behavior:
Only all .m4a will be played.

## Notes:
The .opus files are visible in the directory and playing a .opus file directly (by selecting it) works just fine.

## Screenshot / Video (If applicable)
N/A

**Comment by adrian-bl** [comment]
Android doesn't index .opus files, so we only pick them up during a full scan (which we trigger every few days in the background, at very low priority).

You can speed up the process by running a full scan yourself: Settings -> Media Library -> Scan full filesystem ; start
