### ISSUE TITLE
Changelog link on f-droid do not work

### ISSUE THREAD

**Issue by Mannshoch** [vanilla-music/vanilla#775]
On the App overview in f-droid ther is a Link to the Changelog. It seems that it Point to [https://cdn.rawgit.com/vanilla-music/vanilla/HEAD/assets/about.html](https://cdn.rawgit.com/vanilla-music/vanilla/HEAD/assets/about.html) which does not work.

**Comment by adrian-bl** [comment]
Thanks for the heads up: I submitted a merge request: https://gitlab.com/fdroid/fdroiddata/merge_requests/3179

**Comment by adrian-bl** [comment]
Closing as the merge request got merged
