### ISSUE TITLE
The played mp3 file has no title in file browser mode

### ISSUE THREAD

**Issue by anahuj** [vanilla-music/vanilla#777]
- Vanilla Music Version (Settings -> About): 1.0.60  (automatically updated from play store May 20, 2018)
- Android Version: 4.0.4
- Phone vendor / model: samsung trend  GT-S7560
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

In the file browser mode: when I press an mp3 file, the file plays but the title info is completely empty. The empty title is in all 3 places: in topbar notification, in bottombar of the file browser, and in the player view (time-line + cover art page).

This bug appeared when the player was automatically updated May 20, 2018. Now I don't know what is playing and in what folder.

In previous version, I saw the mp3 filename and the foldername. I prefer the mp3 filename and the foldername - please give them back, or an option.

## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
This is usually due to bad tagging: Your files may have an empty ID3v2 tag (but a non-empty ID3v1 tag)

Feel free to send me a sample to adrian@blinkenlights.ch

**Comment by anahuj** [comment]
An add to this issue: when I press and hold the empty title area of the player view, I get detailed information: the file path shows what mp3 file is playing and in what folder.

Looks like this is not a bug, but a feature. I would like to have an option to show the mp3 file name and the folder name (not complete folder path).

**Comment by anahuj** [comment]
Yes they have an empty ID3v2 tag. I never add them when I make mp3 files with Audacity. I simply use Audacity labels and export the labels as mp3s. The mp3 file names have the info I need.

**Comment by adrian-bl** [comment]
It would probably make sense to pick up some data from the filename if all tags are completely empty.

**Comment by anahuj** [comment]
SOLVED. The name title shows ok after running the media library search. This media library search was not required in an earlier version. Apparently the media search filled the Name field which was empty.
