### ISSUE TITLE
Playing all mp3 files does not work in the file browser mode

### ISSUE THREAD

**Issue by anahuj** [vanilla-music/vanilla#778]
- Vanilla Music Version (Settings -> About): 1.0.60
- Android Version: 4.0.4
- Phone vendor / model: samsung trend GT-S7560
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

In the file browser mode, playing all the mp3 files of the folder does not work.

In a previous version, I pressed and hold folder, then selected menu to play all. This does not work anymore.

In this new version, there is the "play all" button inside the folder. This is new feature to me, but it does not work.

## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by anahuj** [comment]
A detail on this: when I press and hold on a folder - and select "play all", the player notifies "0 songs playing" (or so). Exactly the same notification when I press the "play all" button inside the folder.

When I press and hold on a folder - and select "add to playlist", the player notifies "0 added to playlist".

**Comment by adrian-bl** [comment]
Looks like these files are missing from the index: Did you try to run a manual scan? (Settings -> Media Library)

**Comment by anahuj** [comment]
That solved the problem. Previously there was no need to scan separately in the file browser mode. I don't exactly understand why not read the folder when I select "play all", specially if the songs are not yet in the media library.

**Comment by adrian-bl** [comment]
We were never able to "play all" from a folder for non indexed files. Looks like we somehow missed a library update event from the OS.

The reason for requiring the files to be indexed is thst we need some metadata to enqueue songs (tags, length) and reading them can be quite expensive - and therefore slow.
