### ISSUE TITLE
Feature request: recording the headphones button to a file

### ISSUE THREAD

**Issue by anahuj** [vanilla-music/vanilla#780]
- Vanilla Music Version (Settings -> About):
- Android Version:
- Phone vendor / model:
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

Would be nice if the pressings of the headphones button are recorded to a file.
E.g., Pause "filepath"  "playhead position", and maybe "wall clock time".

I listen to music when I exercise walk or jog. I don't want dig out the mobile phone to see what good song is playing. I have only one remote button - I use it to pause and continue the playing. Would be nice if I could mark the good songs by pausing and continuing. Then later at home, I could read the log-text to find the good songs again.

Note: I don't know what mobile bluetooth remotes are available, do they work with Vanilla Music, or do they have extra buttons to mark positions in songs.

Note: Later would be nice to have a proper marking system. I could rewind to begin of the good song, mark the playhead position, then later I would find this mark in a list and play starting from the mark. But I have not yet polished this feature idea; I have some special use for it, need to think over.

## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
The headset button already has 3 functions:
1 press = play/pause
2 presses = skip song
3 presses = go back

One thing we could do is to make 2 & 3-presses configurable in the same way as the swipe up/down & long-press actions: All that would be missing would be a 'add/remote to favorites' action so you could configure vanilla to add a song to the favorites with 2 presses and remove it with 3 presses.

Would that sound like an useful feature?

**Comment by anahuj** [comment]
Seriously suggesting I should switch the player? Is there equivalent open source music player, which also is useful for audiobooks?

YouTube implements positions too, by having additional timestamp. Maybe you could check how easily they do it. And why they find the feature useful.
https://www.youtube.com/watch?v=bUy1TlZUL4o
https://www.youtube.com/watch?v=bUy1TlZUL4o&feature=youtu.be&t=1952

I don't know details on how Vanilla implements links to songs, but adding timestamp to the link should be easy. Timestamp = 0 for regular use.

How about this baby-steps plan:

(1) Add the timestamp to the song links.

(2) Add new menu entry "Add this place to playlist"  (there is already "Add to playlist")

(3) The playlist view should show the timestamp if it is different from 0. New menu entry "Set timestamp to begin" (timestamp becomes 0).

(4) Make headphone button presses configurable, with list of choices: "skip song", "add to favourites", "add this place to favourites".

(5) I don't know what this favourites list is but YouTube has "watch later" list which is very useful; videos can be added to it by single mouse click. Its content can be copied to a new playlist later.

**Comment by adrian-bl** [comment]
We can not implement every feature request: if we did, we wouldnhave become a videonplayer with email capability long time ago.

Vanilla Music is opensource, so you can implement whatever feature you want in your own private fork
