### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by mansya** [vanilla-music/vanilla#782]
- Vanilla Music Version (Settings -> About): 1.0.60 (and 1.0.61)
- Android Version: 7.1.1
- Phone vendor / model: Samsung J5 Pro
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [y] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [y] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description
Hi @ vanilla-music, I am a graphic designer, I want to help others in graphic design.

After I reviewed the project logo on this project is too simple and colorless. Therefore I would like to contribute to this project by creating a more interesting new logo / icon

**Comment by anahuj** [comment]
The current icon is nice and clear. We are talking about the speaker icon?

Complex icons are not the trend. For example, Instragram switched from complex to simple, and the change looks great.

In my phone, most relaxing icons are Vanilla Music and OsmAnd (open street map viewer, they switched to simple icon too).

**Comment by adrian-bl** [comment]
Feel free to upload a suggestion.
Note that the logo should work well with multiple icon shapes to support adaptive icons

**Comment by mansya** [comment]
I've designed the logo. What do you think? do you like it ?
![vanila](https://user-images.githubusercontent.com/33461607/40787129-0e2a726c-6517-11e8-9a78-bbf042a83132.png)

**Comment by adrian-bl** [comment]
Thanks for the proposal - but i have to say that i'm not too thrilled about it.

However: I'd love to hear the opinion of other users.

**Comment by mansya** [comment]
yes. I will wait for information from others

**Comment by andiandi13** [comment]
I don't really like it either, but you have good skills for sure.

And I don't say that because I did the actual logo, but IMO its too flashy and there is too much details for the eyes : big strokes, many colors for the colored version, and a hesitance between a music note and a play button that looks strange to me.

**Comment by kirbyfan64** [comment]
It looks nice, but nothing about it feels like it fits Vanilla.

**Comment by andiandi13** [comment]
@adrian-bl : Currently, Vanilla Music has a visual identity. You recognize its icon among hundreds on the Play Store.

Using a common icon, e.g. with a play button, would, IMO, drown the app among the others and it's popularity with it.

It's good to change the icon, to create a new adaptative icon, but I think it really should be unique as Phonograph, Pulsar, Google Play Music etc...

**Comment by adrian-bl** [comment]
> Currently, Vanilla Music has a visual identity. You recognize its icon among hundreds on the Play 
> Store.

I agree - i don't like my new icon either - and as you can see i'm not a good artist ;-)

> It's good to change the icon, to create a new adaptative icon, but I think it really should be unique as 
> Phonograph, Pulsar, Google Play Music etc...

Yes: I just don't see a way to make a nice adaptive icon :-/
Phonograph and Pulsar both don't have one (still using older SDKs) and Play music just uses the default (auto-created) adaptive icon

**Comment by kirbyfan64** [comment]
Ok, so this is a random prototype idea that I put together in like 5 minutes, but...

![vanilla](https://user-images.githubusercontent.com/1690697/40893661-b83bc384-6768-11e8-968b-e22b954df006.png)

If the outer circle is adaptive sized, then it would (in theory) look fine as a square or whatever else, and the inner circles would still look like a speaker inside. The V is for...well, vanilla.

**Comment by andiandi13** [comment]
The Vinyl icon is quite a good idea.
But its hard to recognize the vinyl, and the V is too muched cropped.

I thought about changing the name of the app and make a brand new logo according to it, what do you think @adrian-bl

**Comment by adrian-bl** [comment]
A vinyl like logo could actually work quite well:
The round shape could be the vinyl while the background (which is only visible for non-round icons) would could be the turntable.

> I thought about changing the name of the app and make a brand new logo according
> to it, what do you think @adrian-bl

I'd rather like to avoid that: Not only do i like the current name - a name change would also create a lot of 'administrative' overhead (change github repo names, website, etc)

**Comment by andiandi13** [comment]
@adrian-bl Oh yes I see

**Comment by TacoTheDank** [comment]
How about maybe making it white like vanilla ice cream? :D

**Comment by andiandi13** [comment]
@adrian-bl About that, why is it called Vanilla ? Is it a way to say "original version" in the software/hardware field,  or does it refers to the flower ?

**Comment by adrian-bl** [comment]
Honestly: I don't know :)

The original author (kreed@) renamed the project from "Tumult" to "Vanilla Music" via commit 44ebddbc1452d6437af69a981b821d6ceb212491

For me, the name always indicated that we are a simple player which does one thing well: playing music.

(The adjective "Vanilla" stands for: "...having no special or extra features; ordinary or standard." - one could argue whether or not we have 'no special or extra features')

**Comment by andiandi13** [comment]
Yes I understood it that way too, as I've seen this adjective everywhere (video games, apps etc...), I wanted to be 'sure' before suggesting an actual vanilla flower as an icon :')

**Comment by FichteFoll** [comment]
I was just thinking of the usual "play" icon but rotated by 90 degrees to the right so it reads like a "V" (for vanilla). Could also be merged with the vinyl idea since a solid triangle shape would be easier to recognize, I suppose, and the rotation would work well with with a vinyl.
