### ISSUE TITLE
[SUGGESTION] Add lockscreen seekbar

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#789]
Vanilla Music Version : 1.0.60
- Android Version: 4.4.4
- Phone vendor / model: Galaxy S5
- Application was downloaded from :
  - [X] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [X] No
  - [ ] NA / Don't know.

## Description

Some music players can work with android stock lock screen to display a seekbar. It's very useful IMO to quickly navigate through a song without having to unlock / open vanilla / seek / relock.

For example, AIMP do this ![ https://image.noelshack.com/fichiers/2018/26/6/1530355184-screenshot-2018-06-30-12-35-24-540x960.png ]( https://image.noelshack.com/fichiers/2018/26/6/1530355184-screenshot-2018-06-30-12-35-24-540x960.png)

I don't know If its related to a library that is heavy (like jaudiotagger or stg) but it'd be so good to have that on vanilla.

**Comment by adrian-bl** [comment]
That looks indeed nice, but which android version is that?
I installed AIMP on my Oreo device where this doesn't seem to work.

**Comment by andiandi13** [comment]
Hmm maybe it depends on the device..

It's on KitKat (4.4.4) on a Samsung galaxy s5.
It can be a Samsung thing...

BTW Musicolet player also has it so try with it.

**Comment by adrian-bl** [comment]
Musicolet also doesn't work on my Android 8 device - i don't think that lockscreen customizations are possible on anything >= 5.0

From https://developer.android.com/guide/topics/appwidgets/

"Only Android versions lower than 5.0 support lock-screen widgets. For Android 5.0 and higher, only home_screen is valid."

And i don't really want to implement any new feature which would only work on 4.x devices

**Comment by andiandi13** [comment]
I see, thanks for the explanation. I guess >5.0 devices prefer lockscreen notifications than widget..

Well I can workaround this with a media control lock screen.
