### ISSUE TITLE
[Request] Android Auto support

### ISSUE THREAD

**Issue by gena01** [vanilla-music/vanilla#794]
Please add support for Android Auto.

Here is a link to another open source project (podcast player with code changes/docs/etc): https://github.com/AntennaPod/AntennaPod/pull/2053

**Comment by GitKalle** [comment]
See #770

**Comment by adrian-bl** [comment]
This is not going to happen: i do not have time to go trough some qualification process and the feature would only be available in playstore builds - which would make fdroid builds inferior.

**Comment by gena01** [comment]
I am maybe missing something here, but the linked project in the ticket is open source project which is also listed in fdroid. Also as far as i know it's just a code change to implement the feature.

**Comment by adrian-bl** [comment]
See:
https://developer.android.com/docs/quality-guidelines/auto-app-quality

"Apps will not work on Auto in vehicles unless they are installed from the Play Store."

**Comment by gljones2001** [comment]
> See:
> https://developer.android.com/docs/quality-guidelines/auto-app-quality
> 
> "Apps will not work on Auto in vehicles unless they are installed from the Play Store."

This is not true anymore. Check vinyl music player. I downloaded that from f droid, and it works perfectly on Android auto. I don't exactly know how he's implemented it, but he did do it.

https://github.com/AdrienPoupa/VinylMusicPlayer
