### ISSUE TITLE
[FR] show albums in grid

### ISSUE THREAD

**Issue by ildar** [vanilla-music/vanilla#806]
Currently albums are shown in list. Many people find the grid view with album art as more natural.

**Comment by adrian-bl** [comment]
Sorry, but this will not happen. I don't think the grid view is a good way to represent larger music libraries.

**Comment by ildar** [comment]
Wow, very tough.

BTW the feature may be opt-in for those who think differently

**Comment by ildar** [comment]
Re triage?
