### ISSUE TITLE
[FR] Android Oreo Volume Long Key Press

### ISSUE THREAD

**Issue by sgratzl** [vanilla-music/vanilla#813]
- Vanilla Music Version (Settings -> About): 1.0.70
- Android Version: Oreo
- Phone vendor / model: Galaxy S9
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

According to https://www.xda-developers.com/android-oreo-volume-key-long-press/ Oreo now or will allow to listen to long press volume presses. While custom roms out of the box support skip to next track on long press, stock ones (like the on on my S9) doesn't. It would be great if Vanilla music could try to request this permission and mimic the same behavior (or even a customizable one) when available.

**Comment by adrian-bl** [comment]
That would be a nice feature, but i doubt that we could get this working:

Looking at the diff shows that the new permission is defined as:

```
<permission android:name="android.permission.SET_VOLUME_KEY_LONG_PRESS_LISTENER"
--
  | android:protectionLevel="signature\|privileged\|development" />
```

That means that we either need to be signed with the firmware signature or installed in /system, which will not be the case (without root)

**Comment by sgratzl** [comment]
I know so far it is not an official api. I don't say that this feature would work out of the box atm but requires some manual intervention. But for the longer run or the ones who know a workaround it would be nice to have it integrated.

**Comment by adrian-bl** [comment]
Both the fact that the API is only available via reflection and requires permissions which can never be granted to a normal app (on an unrooted phone) are a strong sign that this API should simply not be used (yet) by any 3th party app and must be considered unstable:

Using this feature in an app which is shipped with a ROM (like: the builtin media player) would be fine, as such an app only needs to run on one API-Version.

But we are a 3th party app which runs on a wide range of API-Versions, using an hidden API is just not a good idea in such a case.
