### ISSUE TITLE
Folder actions broken in Files Tabs

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#815]
@adrian-bl : You have fixed that issue for files in #809, but there still is a problem with every action done on folders :

- Play
- Add to Playlist
- Enqueue...

0 tracks are managed...

**Comment by adrian-bl** [comment]
Yeah, you are right.

Not sure what i was thinking (not much) when i was changing the file picker code.

https://github.com/vanilla-music/vanilla/commit/4bd4fb700a93ebb6db2b61b6f0c4f3e3376505a2 should fix it once and for all.. hopefully.

**Comment by andiandi13** [comment]
Thanks I'll check that on the nightly.

**Comment by rafiberlin** [comment]
@adrian-bl : thanks, that works for me!
