### ISSUE TITLE
Pressing "Play" or "Play Next" returns a message "0 tracks playing."

### ISSUE THREAD

**Issue by sakuramboo** [vanilla-music/vanilla#816]
1. Please take a moment to check if the same Bug has already been reported.
2. Please use our subreddit for general questions: https://www.reddit.com/r/vanillamusic/
3. Please provide all relevant information below.

**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About): 1.0.71
- Android Version: 7.1.1
- Phone vendor / model: Motorola G Play
- Application was downloaded from (use `[x]`):
  - [X] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [X] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

When I long press on a directory and press either "Play" or "Play Next" I get a message that says "0 tracks playing." instead of loading the files in the directory into the queue.

I had a similar issue a few years ago and was instructed to do a full scan of the media, which resolved the issue. I did it this time and the issue still persists. I even did a "Flush media database" and did a full scan and still no go.

....

## Steps to reproduce the issue

Long press a folder and press "Play" or "Play Next."

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
That should be fixed in 1.0.72: https://github.com/vanilla-music/vanilla/commit/4bd4fb700a93ebb6db2b61b6f0c4f3e3376505a2

I'll push this to the play store in the next few days.

**Comment by adrian-bl** [comment]
Pushed it to 100% in the play store - f-droid builds should also be available by now.

Therefore, marking this as fixed.
