### ISSUE TITLE
Scroll to track title in queue broken since 1.0.71 

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#818]
It seems that when you have fixed the "0 track playing" issue, it made another issue : the queue isn't jumping to the current playing song when the option is activated.

**Comment by adrian-bl** [comment]
That works for me. Hmm..

But note that we only scroll if the playing track is outside of the current view.

**Comment by Adonai** [comment]
Oh that was me! it was #812, I guess.
Glad you like it :)

**Comment by andiandi13** [comment]
Thanks @Adonai I usually don't read Pull Requests, too many complicated comments for a mortal like me :)
