### ISSUE TITLE
Random cover for <no album> tag

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#819]
Vanilla pick the same random cover for every files that has no album tag since it's the same 'ID'.

However I think you should tell Vanilla not to pick any cover when there is no tag at all.

IMO it's _ugly_ to see the same cover everywhere and it confuses me.

**Comment by ildar** [comment]
enhancement? no, it's a UI bug.

**Comment by andiandi13** [comment]
Not really a UI bug, it's just how Vanilla works with album IDs.

But it's really really annoying

**Comment by adrian-bl** [comment]
And it's fixed in https://github.com/vanilla-music/vanilla/commit/1a6c9018e10fdcb79fbbd33ffe0a47648e951fd9

Note that this only works for songs which have the correct bit set in the database, so you'd have to do a 'flush database' scan to set it on existing songs.
