### ISSUE TITLE
Add 'Show Details' shortcut

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#820]
I can see that displaying song details by long pressing the top area isn't clear for many people.

I think you should add a 'Show Details' button (and Hide details when it's on) just below 'Show Queue' in the 3-dot menu on now playing screen.

**Comment by n2j3** [comment]
I agree. Current implementation is very counter-intuitive. I came across it by accident - thought it was an easter egg.

**Comment by andiandi13** [comment]
An easter egg haha

Yeah this should only be a shortcut for 'advanced' users.

**Comment by adrian-bl** [comment]
That thing is actually more like a debug feature :-)

Bug #506 talks about a generic 'details' view

**Comment by andiandi13** [comment]
Too useful to be only a debug feature IMO...

Why not adding that #506 co text menu _and_ a shortcut to the 'debug' details in the 3-dot menu on playing screen ?

I mean, if Im playing a song and I want to see details, I won't have to find it in the library if I scrolled for example.
