### ISSUE TITLE
Duplicate songs and extension

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#826]
I just discovered a bug by accident regarding track duplication.

I downloaded a song named XXXXX.MP3.

Yes, with capital letters. Vanilla duplicate the paths :

/SDCard/XXXXX.MP3
/SDCard/XXXXX.mp3

I have to rename it to .mp3 and to flush the entire library to (possibly) make one of them disappear.

I saw some users complain about duplicate tracks but it wasn't symlink, maybe it's that strange behavior.

Vanilla should simply ignore letter case for extensions..

**Comment by kirbyfan64** [comment]
OTOH this is kind of fundamental behavior of Unix file systems...

**Comment by andiandi13** [comment]
@kirbyfan64 I didn't know that.

But how come the song isn't duplicated in other players ?

You can try : just rename any mp3 of your library to MP3. There will be two of them in Vanilla, and only in Vanilla.

**Comment by kirbyfan64** [comment]
Not sure... They might just detect it based on identical metadata or identical file contents?

**Comment by andiandi13** [comment]
Hmm strange. You think they _all_ work the same way ?

The easiest thing for them would be not to mind about letter case of extensions

**Comment by kirbyfan64** [comment]
:man_shrugging: A lot of them import their metadata from Android's own system, which would probably handle something like this in one place. It's just that making solely the extension case-sensitive seems REALLY odd to me...

**Comment by andiandi13** [comment]
I see what you try to say. It's beyond me though tbh.

As long as @adrian-bl find a workaround to avoid that strange behavior it's OK :p

**Comment by adrian-bl** [comment]
closing this as wontfix: while i see that this can be confusing, that's just how unix system works:

/some/Path and /some/path are completely different files - unix also doesn't really have a concept of file extensions.
