### ISSUE TITLE
Can't play some folders (but can play individual files)

### ISSUE THREAD

**Issue by joshtriplett** [vanilla-music/vanilla#839]
- Vanilla Music Version (Settings -> About): 1.0.72
- Android Version: 9
- Phone vendor / model: Google Pixel XL
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

With some folders, I can long-press on the folder and choose "Play", or open the folder and choose "Play All", and all the music in that folder will play. With other folders, however, doing so produces "0 tracks playing". (Likewise, choosing "Enqueue" or "Play next" results in "0 tracks enqueued".) In all cases, I can play the individual files directly.

I don't know what's different between the folders that work and those that don't. Happy to do further debugging as needed. (I do have a shell on the device if that helps.)

**Comment by joshtriplett** [comment]
A further detail that might help: for the songs that play individually but not as a folder, if I look at the "Show Queue" view or the widget, their metadata does not display at all. Nothing appears where the title would, and just a single `,` displays where the album and artist would.

**Comment by andiandi13** [comment]
Are you sure those folders are indexed  ? (Make sure that they are included in media library settings by long pressing on them, or that their parent folder is included)

Also, look at the file tags to see if it's id3v2 and not v1 only.

Look here https://github.com/vanilla-music/vanilla-music.github.io/wiki/FAQ#media-library-media-scanner-missing-tracks

**Comment by joshtriplett** [comment]
> Are you sure those folders are indexed ? (Make sure that they are included in media library settings by long pressing on them, or that their parent folder is included)

Yes, I'm sure; my top-level music folder is included and no subfolders of it are excluded.

> Also, look at the file tags to see if it's id3v2 and not v1 only.

`file` says `Audio file with ID3 version 2.3.0, contains:MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo`

Also, I've tried telling Vanilla Music to rescan, and this issue remains.

**Comment by adrian-bl** [comment]
Vanilla doesn't index files with missing tags: Do other applications show tags? If they do, it's a bug in our tagreader.

**Comment by adrian-bl** [comment]
closing due to lack of reply.
