### ISSUE TITLE
Feature request: Make the directory/file list remember the scrolling position

### ISSUE THREAD

**Issue by kaipoethkow** [vanilla-music/vanilla#84]
I prefer to browse files to albums/artists/... but whenever I enter a directory by mistake and go back the list is reset to the topmost position (scrolled up). Please make the lists remember their last scrolling position, i.e. make it persistent. Without this feature I am forced to scroll down time and time again...

Thanks, and keep up the good work.

**Comment by kaipoethkow** [comment]
This issue has been re-introduced in version 1.0.37. When I switch between "Now playing" screen and the file list everything is fine: scroll position is persisted. But when I go back a directory (using back button or breadcrumbs) then the previous scrolling position is not remembered and I have to scoll down again and again.

**Comment by kaipoethkow** [comment]
Can wee re-open the issue?

**Comment by adrian-bl** [comment]
I suspect that https://github.com/vanilla-music/vanilla/commit/3067e592236eaac012520b4355d17c4b8ddc783b broke it.

Maybe getCount is not implemented in the files adapter :-/

**Comment by adrian-bl** [comment]
Fixed via https://github.com/vanilla-music/vanilla/commit/86c6a3b32657c95d78bebd2968b74b92e606cbc7

The adapter was broadcasting data invalidation, so the view never updated and returned 0 (until it was forced to display data)
