### ISSUE TITLE
Scroll to track title issue

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#844]
- Vanilla Music Version (Settings -> About): 1.0.72
- Android Version: 4.4.4
- Phone vendor / model: Galaxy S5 Plus
- Application was downloaded from :
  - [X] Play Store
  - [X] F-Droid
  - [X] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [X] No
  - [ ] NA / Don't know.

## Description

When I change tracks outside of Vanilla, with notification buttons and I come back to the app (library screen), the scroll to track option often act crazy by scrolling super quickly to "catch up" the current playing track from the initial position.

The thing is that, it never catches the track, and it's so strange seeing a player act like this.

I'm pretty sure most of users are familiar with that issue.

## Steps to reproduce the issue

I tried to make a way to reproduce it easily, and I think I found one : 

1- Kill Vanilla
2- Open Vanilla
3- Tap "Play all" to play the entire library (the bug is more common with many song, I guess)
4- Exit Vanilla with Home button (and not back key !)
5- Open notifications and skip many songs (like 15-20)
6- Open Vanilla again, the bug should happen.

## Video

Here is a screen record for a better understanding : 

https://youtu.be/xHXcdQVduas

**Comment by Adonai** [comment]
That has something to do with my code but sadly I'm on a vacation till next weekend, will have a look once home

**Comment by andiandi13** [comment]
@Adonai I see. I'm looking forward to see a fix

**Comment by andiandi13** [comment]
@Adonai bump

**Comment by Adonai** [comment]
Not home yet, sorry. Will post here an update when done
