### ISSUE TITLE
Ignore dot folders (hidden)

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#846]
Vanilla index files located in dot folders (for example .recycle .thumbnails etc..).

In use Mixplorer as my main file explorer, and I often delete musics by sending them to recycle bin, but Vanilla continue loading them since it consider dot folder as any other folders (it's quite annoying).

So I suggest adding an "Ignore hidden folders" box in Media Scanner Option (below always use internal tag).

**Comment by adrian-bl** [comment]
We probably should do that by default and also for files: This would prevent us from picking up tmp-files from SyncThing (and other things).

**Comment by andiandi13** [comment]
True, I guess it wouldn't bother anyone if Vanilla doesn't index those files.

**Comment by adrian-bl** [comment]
Fixed via https://github.com/vanilla-music/vanilla/commit/c6fedb9e172d3a943e50598889a0c5d51d398332

We will now always skip dotfiles.

**Comment by andiandi13** [comment]
Thanks i look forward to test
