### ISSUE TITLE
How to omit/hide icons left of each song?

### ISSUE THREAD

**Issue by bsto** [vanilla-music/vanilla#850]
When I launch Vanilla Music then on the left side of each song entry there is an icon.

How can I omit/hide these icons?

Instead more of the song title should be shown.

Furthermore the space gap between the song lines could be shrinked to show more songs at a time on the dispaly (without scrolling).

Ben

**Comment by andiandi13** [comment]
The icon is the album cover, it's quite useful to quickly identify songs.

But an additional option to remove it for those who want, I mean why not...

For the gap between songs, it was like you said, in the past, but IMO it was ugly and confusing. Plus it really depends on the device screen.

If you are rooted, you can take app settings to change DPI of Vanilla and display everything smaller.
