### ISSUE TITLE
Please provide built-in equalizer alernative [request/not bug]

### ISSUE THREAD

**Issue by JonasT** [vanilla-music/vanilla#854]
In my years with cyanogenmod and later lineageos, AudioFX has NEVER worked reliably. Sometimes it just does nothing, sometimes it works for one song and not for the next,...

Now I have a phone with some vendor room that doesn't come with an EQ at all, and manually downloaded AudioFX just does nothing on it - although it seemed to work for a very brief moment and now the entire sound is stuck dull.

Or summed up: the EQ situation on Android has always been a mess for me, and somehow I don't think I'm the only one...? So it would be nice to have an alternative, even if it uses more CPU or whatever, that is guaranteed to work.

**Comment by kirbyfan64** [comment]
Vanilla relies on the system media player, so I don't think it can really do anything here. 

For AudioFX, you'd likely have to install it as a system app.

**Comment by JonasT** [comment]
Is there absolutely no interest in changing this though? E.g. I'm using the PI audio player right now, which I find pretty awful in almost every regard, but it actually does this.

Wouldn't it be possible to package something like FFmpeg and OpenAL or similar (not sure which audio libs have android support) as an optional alternative backend, at least in theory?

Of course if AudioFX always works fine for you, I suppose it's just my personal problem not worth any dev time. I just assumed it's similarly buggy and unreliable at least for *some* other people.

**Comment by adrian-bl** [comment]
> Is there absolutely no interest in changing this though?

We depend of the media framework provided by the ROM you are running:
If it is buggy, vanilla will be buggy - if it lacks proper EQ support, vanilla won't be able to enable the EQ, there is nothing we can do.

> Wouldn't it be possible to package something like FFmpeg and OpenAL or similar (not
> sure which audio libs have android support) as an optional alternative backend, at least
> in theory?

In theory: Yes, but this would be a huge amount of work.
Given the fact that i'm mostly working alone on Vanilla Music and have a day job (net income from Vanilla Music: 0.00$), this just won't be happening.

**Comment by JonasT** [comment]
> If it is buggy, vanilla will be buggy -

For what it's worth, I haven't had an Android system for years (and that includes LineageOS) where AudioFX wouldn't just randomly stop working on a Vanilla Music played song. Sometimes even requiring a restart to get it back enabled.  Maybe I just have incredibly bad luck, and I don't know if the problems lie in the core Android code, AudioFX or Vanilla - but it doesn't seem to be ROM-specific, which would make it pretty much unavoidable unless the system EQ is simply not relied upon in the first place.

Would you be open to a pull request or something like that, if I ever got around to taking a look at this? (Probably not happening soon, but I'm considering it for when I happen to have the time)

**Comment by adrian-bl** [comment]
Yes: if you find a way to mitigate this issue, i'd be happy to merge it.
