### ISSUE TITLE
Be able to disable jumping if the song is already in the queue

### ISSUE THREAD

**Issue by Exagone313** [vanilla-music/vanilla#862]
- Vanilla Music Version (Settings -> About): 1.0.73
- Android Version: 7.1.2 (LineageOS 14.1)
- Phone vendor / model: irrelevant
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

Sometimes I want to play a sound and it happens that it already played some time ago and it is present in the queue. When paused and selecting that sound (I selected the action `Enqueue if playing; Play if paused`), it will say `Song is already in queue, jumping...` instead of emptying the queue and playing the selecting sound (`1 track playing`) like when the selected sound isn't in the queue.

## Steps to reproduce the issue

* Have a sound X in your queue
* Select the action Play on that sound X
* See that it jumped to that sound instead of clearing the queue

**Comment by adrian-bl** [comment]
f1b7d241fedec2f85362c9788a5525a65c9a733e makes this a config option

**Comment by Exagone313** [comment]
Thanks! What was the `onRestart` method for?

**Comment by adrian-bl** [comment]
`onRestart` is part of the app activity lifecycle:
https://developer.android.com/guide/components/activities/activity-lifecycle

I moved `loadTabOrder()` to `onStart()` to make the code simpler (the drawback is that it gets called twice during a fresh startup, but it's a cheap function, so that won't hurt much)
