### ISSUE TITLE
"0 tracks deleted" unable to delete songs

### ISSUE THREAD

**Issue by StaticSignal** [vanilla-music/vanilla#865]
Problem: dele song option fails to delete songs. Open song to show album art, song details and play/pause/skip options, selecting the options button > delete will load the "delete file [Song Title]?" message. However, selecting yes will result in message "0 tracks deleted". This used to be inconsistent but would work on some songs only, now it doesn't work at all.

- Vanilla Music Version (Settings -> About): 1.0.73
- Android Version: 8.0.0
- Phone vendor / model: Samsung galexy S9+ SM-G965U
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

**Comment by adrian-bl** [comment]
Are these songs stored on an external sdcard?
Apps usually do not have write (and hence: delete) permission on sdcards.

**Comment by StaticSignal** [comment]
I think you're right adrian-bl. They are stored on my SD card. So I need to find a way to grant vanilla music rights to modify content on my SD card

**Comment by cubetronic** [comment]
I can't delete from SD either. Under App permissions, show all, the permissions include read, and "write and delete"... but if i click on the latter for more info, it just says "allows to write"..

HAL 9000: "I'm sorry Dave, I'm afraid I can't do that"

**Comment by adrian-bl** [comment]
Write access to external storage (without SAF) depends on your ROM:
If your rom does not give applications permission to do so, we won't be able to write.

To fix this, we would need to implement SAF support: #691
