### ISSUE TITLE
How to play following songs after start of one song in playlist? Usage description?

### ISSUE THREAD

**Issue by pstein** [vanilla-music/vanilla#869]
Assume I tap on a song in one of my playlists and let it play.

After finishing I want Vanilla Music the directly play the following song in the current playlist.
When reaching the end of the current playlist VM should start over with the first song.

How can I achieve this?

Currently VM is jumping after the end of the current song arbitrarily to another song in another playlist.

Is there a Wiki or manual of the App handling with all the icon descriptions?

Thank you
Peter

**Comment by adrian-bl** [comment]
Closing this as it was already answered in https://www.reddit.com/r/vanillamusic/comments/9wcaec/how_to_play_following_songs_after_start_of_one/
