### ISSUE TITLE
Feature request: time for albums and playlists

### ISSUE THREAD

**Issue by ElektroVirus** [vanilla-music/vanilla#870]
How about showing the total time of albums and playlists in the same position where the duration of individual songs is shown? Analogous to individual songs, but left to the small arrow on the playlists or albums element.

It would also be neat if the total time is shown in all the "Play all" buttons.

Also the time left in currently playing  playlist would be nice to know.

**Comment by andiandi13** [comment]
It's already done for albums but it will be for the next update.

For now, you can download the nightly http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk.

Which contains all new features that will be in the next update.

But for Playlist I agree, it'd be great.

**Comment by ElektroVirus** [comment]
All right, great.

**Comment by adrian-bl** [comment]
Yeah: we should also do this for playlists (will need a small SQL update)

**Comment by adrian-bl** [comment]
Finally fixed via 4d074d52ad856bc254cd98980e3eaf6a19a9d963
