### ISSUE TITLE
Transfer of vanilla-music-metadata-fetch to vanilla

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#872]
Hi Adrian.

I requested a transfer of a new plugin to you.  
It retrieves file fingerprint and fetches metadata from AcoustID if match is found.  
After that one can persist the metadata to the file tag.

Please accept transfer request and add it to vanilla-music repo.  
Wanted to do it before publishing to GPlay and F-Droid.

**Comment by Adonai** [comment]
Thanks. Adrian! That was really fast !

Btw I remember nearly identical conversation about previous plugin. GitHub still doesn't allow transferring directly to organizations :)

**Comment by Adonai** [comment]
Um, @adrian-bl  can you please make permissions for it the same as for other plugins? Can't change any settings currently.

**Comment by adrian-bl** [comment]
That should hopefully be fixed: You are now listed as an admin for the repo (and the settings look the same as what the cover-fetcher has configured)

**Comment by Adonai** [comment]
Yep, all works!
