### ISSUE TITLE
typo in German localisation

### ISSUE THREAD

**Issue by ksaerdna** [vanilla-music/vanilla#875]
This:

In Bibliothekslisten zum aktuell wiedergegeben Titel/Album/Interpreten scrollen

should better be this:

In Bibliothekslisten zum gerade wiedergegebenen Titel/Album/Interpreten scrollen

Generally the word "aktuell" as adverb has been overused epidemically since the last years. Note the difference between "Der Stau ist aktuell drei Kilometer lang" and "Der Stau ist drei Kilometer lang" --there is none.

**Comment by adrian-bl** [comment]
I agree: your version sounds much better.

I updated the string at transifex (https://www.transifex.com/vanilla_music/vanilla-music-1 - you can request to join the 'german translation team' if you would like to contribute more changes).
The change will make it to the git repo on the next sync (done once in a while, but usually before a release)
