### ISSUE TITLE
Context menu and keyboard conflict

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#877]
- Vanilla Music Version : 1.0.80
- Android Version: 4.4.4
- Phone vendor / model: SM-G901F
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [X] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [X] NA / Don't know.

## Description

When searching something in Vanilla, and opening the context menu while the keyboard is still open, the context menu is cut to at the top of the keyboard, however if I touch the menu (scroll...) it immediately overlap the keyboard.

**Comment by adrian-bl** [comment]
Ugh: that seems to be an Android 4 bug: We set the height to wrap_content but for some strange reason it thinks that the space used by the keyboard can be occupied.

The real fix would probably be to set a fixed height, like we do on 5.x and above - but i haven't figured out a way to correctly measure the height on 4.x:
https://github.com/vanilla-music/vanilla/blob/master/app/src/main/java/ch/blinkenlights/android/vanilla/ui/FancyMenu.java#L223

**Comment by adrian-bl** [comment]
Oh - that's odd: i didn't see that on Android 6 - i'll try to reproduce it on 5.x

**Comment by adrian-bl** [comment]
This should be solved in the latest nightly. we now use the bottomSheet instead of a popupmenu.
