### ISSUE TITLE
[Suggestion] Move seek bar to the bottom

### ISSUE THREAD

**Issue by SandBlock4** [vanilla-music/vanilla#880]
- Vanilla Music Version (Settings -> About): 1.0.80
- Android Version: 8.0.0
- Phone vendor / model: MHA-L29
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
Move seek bar to the bottom for better one hand operation. Hard to reach the top section with one hand especially for large phones.

#### Original
![o](https://user-images.githubusercontent.com/30970698/49336817-255f1f00-f644-11e8-9563-5717ab5642a9.jpg)

#### Suggestion
![s](https://user-images.githubusercontent.com/30970698/49336820-2b550000-f644-11e8-961e-afe22612b93b.jpg)

**Comment by andiandi13** [comment]
I agree, even on a 5 inches screen it's hard with one hand... But imo there should be an option, as for infos position, to let users choose.

**Comment by adrian-bl** [comment]
I'm tempted to move it to the bottom for all themes (without having an option).

It is already (fixed) at the bottom in the library view, so doing the same in the playback activity would just be consistent.

**Comment by andiandi13** [comment]
I suggested and option for people who prefer it at the top, but I'm 100% for the bottom seekbar

**Comment by adrian-bl** [comment]
pushed 66bebc87091841e4b88b2d1e49a8ea91a8258be9 which moves the seek bar to the bottom.

**Comment by andiandi13** [comment]
Just run the nightly, its so nice !

I think info below cover should be the default view, it fit perfectly with the new seekbar.

**Comment by adrian-bl** [comment]
marking as fixed
