### ISSUE TITLE
Flag app as a media player

### ISSUE THREAD

**Issue by blackwind** [vanilla-music/vanilla#882]
- Vanilla Music Version (Settings -> About): 1.0.80
- Android Version: 8.1
- Phone vendor / model: Samsung Galaxy S5
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

Since Android Auto support apparently isn't going to be added (as an aside, I say just let the dev who made the pull request deal with the certification process, as he's clearly motivated to get this done), I'd like to request the next best thing: Flag the app, however that's accomplished, as a media player that can be set as a default in Android.

## Steps to reproduce the issue

In [Google Maps](https://play.google.com/store/apps/details?id=com.google.android.apps.maps) (Settings > Navigation settings > Show media playback controls):

![maps](https://user-images.githubusercontent.com/889881/49836483-0b1df300-fd60-11e8-9ccd-860a0545602c.png)

In [AutoMate](https://play.google.com/store/apps/details?id=com.bitspice.automate) (Settings > Media > Choose default media player):

![automate](https://user-images.githubusercontent.com/889881/49836497-14a75b00-fd60-11e8-8df9-8a38c371972f.png)

Currently, neither app is capable of choosing Vanilla as its default media player, so I therefore can't control Vanilla through their interfaces.

**Comment by adrian-bl** [comment]
> however that's accomplished...

So how is this done? I have no idea how to do this.

**Comment by 239** [comment]
Adding `<action android:name="android.intent.action.MUSIC_PLAYER" />`
to `intent-filter` works for me but it's deprecated since API 15 so I'm not sure if it's the best way to achieve it.

**Comment by adrian-bl** [comment]
I wouldn't mind adding this deprecated intent action, but we *do* already set the non-deprecated version called `Intent.Category.APP_MUSIC` in our manifest:

https://developer.android.com/reference/android/provider/MediaStore#INTENT_ACTION_MUSIC_PLAYER

**Comment by adrian-bl** [comment]
So i added this to the manifest in
https://github.com/vanilla-music/vanilla/commit/2e5791ef875697db43709ea6de01644284ac60e7

Should be in the latest nightly, so let's see how that goes.

**Comment by adrian-bl** [comment]
Did someone have a chance to test this?

**Comment by 239** [comment]
**AutoMate** 👎 No Vanilla

![vam](https://user-images.githubusercontent.com/7075008/51528803-c47be800-1e37-11e9-8de9-05110b9f2794.png)

**Google Maps** 👎 Deezer is also missing here

![vgm](https://user-images.githubusercontent.com/7075008/51528804-c47be800-1e37-11e9-9334-403659c731fb.png)

**Smart Launcher** 👍 This is what I tested myself

![vsl](https://user-images.githubusercontent.com/7075008/51528805-c47be800-1e37-11e9-96c1-3bf475cd19ee.png)

I wonder why every app lists a different set of media players and Maps only finds Spotify.

**Comment by 239** [comment]
I think Google Maps looks for Android Auto support:
[https://developer.android.com/training/auto/audio/#config_manifest](https://developer.android.com/training/auto/audio/#config_manifest)

**Comment by adrian-bl** [comment]
Closing this as i think this is as good as it gets (we won't add android auto support).

Note that the manifest change finally (?) made vanilla music become an option for me in google assistant (or was it just slow to pick up the change?)
