### ISSUE TITLE
Multi Select of items in Library

### ISSUE THREAD

**Issue by thigg** [vanilla-music/vanilla#883]
IIt would be nice if multiple items in Library view could be selected.
On such a selection actions such as 
 - Add all to playlist (for example only a few songs of an album)
 - Edit tags of selection

could be performed.

My usecase is the second one. It is really annoying to edit the tags of an artist per song.

It would be possible to have a menu item which says enable multi select, which enables the feature and then provides an action based on the selection.
Actions must depend on what is selected (folder, artist,album,file,song).
When the action is performed multi select could be disabled again and on long press the current context menu would appear.

This would enable a more intuitive and faster handling of libraries.

**Comment by andiandi13** [comment]
It's #792
