### ISSUE TITLE
[Suggestion] Custom theme for 5.x

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#885]
I tried Vanilla on a Lollipop device and I found that default themes are quite limited.

Grey theme for example, has text and controls too much dark IMO and library background too much bright. It's only my preferences and I prefer the AMOLED theme for a black theme, despite we lose many shades.

Anyway, I just wanted to point out that we can't satisfy everybody with basic themes, and it would be very cool to have a "Custom" entry below AMOLED theme, where we would be able to choose a color for each element of the UI.

**Comment by adrian-bl** [comment]
We use the 'standard' (static) theming-mechanism to provide themes (that is: styles.xml).

The way this is done requires the theme to be present at compile time - while it would *theoretically* be possible to change the theme at runtime (and therefore give users total controll), i think that this will be brittle and a lot of work to maintain between multiple android versions.

Given the vast amount of work and little gain, i don't think that we should do that (however: i'm always happy to receive new theme suggestions: feel free to send me a modified theme-*.xml file (or just some RGB codes)

**Comment by andiandi13** [comment]
@adrian-bl I'll do that then, but Im wondering : what are those 8 decimals colors on the XML ?
