### ISSUE TITLE
Micro-stutter with usb-c audio dongle (digital/external soundcard with integrated DAC) - can I increase buffer size?

### ISSUE THREAD

**Issue by JonasT** [vanilla-music/vanilla#890]
- Vanilla Music Version (Settings -> About): 1.0.80 (f-droid)
- Android Version: 7.1.1 (vendor supplied)
- Phone vendor / model: Planet Computers / Gemini PDA
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [X] NA / Don't know.

## Description

I recently got the Razer Usb-C audio soundcard (it's an active usb to 3.5 inch jack dongle with integrated digital-to-analog converter, not one of the simpler analog-only ones that expect the DAC to be in the phone). It works almost perfectly, except that as long as the phone is unlocked & screen enabled, I get micro-stutters: every few seconds the sound just hangs for a tiny moment leading to a not-very-loud but audible click & delay. As soon as I lock the screen and it goes black, it works fine.

Of course this might be mostly a system / driver issue, but my guess is that the latency of the usb connection is just a tad higher than the system expects, so if it's not super super idle, it sometimes just comes in a little too late supplying the audio (hence the stutter).

Therefore I'm wondering: is there some way in vanilla to just request a larger audio buffer? I haven't found any such option, but I suspect that it might get rid of my micro stuttering if something like that was possible

## Steps to reproduce the issue

1. Attach Razer USB-C to jack adapter / soundcard - use the left-hand USB-C socket (the Gemini PDA has two)
2. Attach any headphones
3. Open Vanilla Music and play a song. Keep the interface open, don't lock the screen

-> occasional noticeable small stutter

**Comment by kirbyfan64** [comment]
Outside of Enable Readahead, Vanilla relies on Android itself to play audio, and there's not much you can do about it.

**Comment by JonasT** [comment]
neat! I hadn't actually readahead enabled, maybe that will help a little.

I was aware of that, I just assumed maybe Android has some options for tweaking this vanilla could use - if not, feel free to just close the ticket

**Comment by adrian-bl** [comment]
As kirbyfan64 said: there isn't anything we could do about the buffer size as we use the native framework for playback: Enabling readahead (which just helps with slow storage) is the best we could offer.
