### ISSUE TITLE
Below cover details bad padding

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#892]
- Vanilla Music Version: Last nightly
- Android Version: 4.4.4
- Phone vendor / model: Galaxy S5
- Application was downloaded from :
  - [ ] Play Store
  - [ ] F-Droid
  - [X] Other (Nightly Build)
- Did this work in a previous version?
  - [X] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

Since b812373 and ba2f722 the text of tags is overlapping the bottom of the cover.

I guess that the padding is relative to the very bottom of the screen (behind controls), because when I change Vanilla's DPI in App Setting  (an Xposed module), and so virtually changing device screen size, the text _can_ be well aligned :

### Normal galaxy S5 screen :

<details><summary>Click to show</summary>

![normal galaxy s5](https://user-images.githubusercontent.com/19387072/50575857-2aabb700-0e06-11e9-8e4e-cdc629396e87.png)

</details>

### Bigger screen :

<details><summary>Click to show</summary>

![bigger](https://user-images.githubusercontent.com/19387072/50575858-2aabb700-0e06-11e9-86e0-7ea4063076d8.png)

</details>

### Way bigger screen :
<details><summary>Click to show</summary>

![huge](https://user-images.githubusercontent.com/19387072/50575859-2aabb700-0e06-11e9-8edc-e0ac127ebd2a.png)

</details>

**Comment by adrian-bl** [comment]
Oh, removing the top-padding broke that.
We historically aligned to the bottom as the cover sizes could differ between albums, but this is not needed anymore as the code started to use createZoomedBitmap.

c7605a58d5624f4ccb26e9698f19e1c7db92f4ab changes how we calculate the offsets - the code now always tries to (vertically) center the text if there is enough available space.
