### ISSUE TITLE
Plugins popup not showing

### ISSUE THREAD

**Issue by basile-laderchi** [vanilla-music/vanilla#899]
- Vanilla Music Version (Settings -> About): v1.0.81
- Android Version: v6.0
- Phone vendor / model: Sony Xperia XA
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

I have installed Vanilla Music v1.0.81 (upgraded from v1.0.80), Cover Fetch v1.4.4, Metadata Fetch v1.0.4 and Tag Editor v1.3.0 and when I try to access the plugins it just doesn't work.

## Steps to reproduce the issue

Go to any song and try to open the Plugins popup. It just doesn't open. With or without Internet connection. I only managed to get it opened once, but when it did it opened the window as many times as I had clicked. Haven't managed to get it reopened.

**Comment by adrian-bl** [comment]
- Did you try to restart your phone?
- Could you provide a logcat?

@Adonai any idea?

**Comment by basile-laderchi** [comment]
I did a phone restart and it worked. Unfortunately only temporarily.

This is the logcat (from Android Studio with "vanilla" as filter):
```
01-22 09:43:15.658 10667-10667/? I/Vanilla:Plugin: Received query intent!
01-22 09:43:15.664 1143-1164/? I/WindowManager: Focus moving from Window{e2f88fd u0 PopupWindow:ef6723b} to Window{6db0314 u0 ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity}
01-22 09:43:15.664 1143-1164/? I/WindowManager: Gaining focus: Window{6db0314 u0 ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity}
01-22 09:43:15.667 10680-10680/? I/Vanilla:Plugin: Received query intent!
01-22 09:43:15.671 1143-1157/? W/BroadcastQueue: Unable to launch app com.kanedias.vanilla.coverfetch/10323 for broadcast Intent { act=ch.blinkenlights.android.vanilla.action.REQUEST_PLUGIN_PARAMS flg=0x1000030 }: process is bad
01-22 09:43:15.694 352-1171/? I/BufferQueueProducer: [ch.blinkenlights.android.vanilla/ch.blinkenlights.android.vanilla.LibraryActivity](this:0x7f90f8bc00,id:27,api:1,p:9493,c:352) queueBuffer: fps=0.83 dur=31279.79 max=30910.61 min=7.71
```

I reverted back to 1.0.80 (had to uninstall v1.0.81 prior to downgrading)

I might have a clue to what is causing it.
I have been trying to launch the "Cover Fetch" plugin and it crashes.
After the crash on v1.0.81 there is this line, on v1.0.80 it doesn't exist
```
01-22 09:42:02.143 1143-1153/? W/ActivityManager: Process com.kanedias.vanilla.coverfetch has crashed too many times: killing!
```

**Comment by Adonai** [comment]
@adrian-bl works on my devices. My guess is some android versions may refuse to send intents to newly installed apps.

@basile-laderchi try deleting cover fetch for now and try again.

**Comment by basile-laderchi** [comment]
I did uninstall v1.4.4 of Cover Fetch and installed v1.4.5 and now it looks like the plugin popup is working just fine.

@Adonai for some reason my Cover Fetch plugin did crash upon being called. Do you think I should test it again with v1.4.4?

**Comment by Adonai** [comment]
If it works with 1.4.5 then cover fetch was the reason, I reckon. You can close this bug.

Adrian, I think we should indicate somehow if one of plugins fails to answer. Should I prepare a PR for this?

**Comment by maverick74** [comment]
@adrian-bl @Adonai This is not working for me! I'm already on the latest cover fetch and it does not work. I've also tried with just lyrics search and with just tag editor and I never get the pop-up showing.

I've removed all and reinstalled everything again with no luck...

**Comment by Adonai** [comment]
OK, will try to solve this within Vanilla itself

**Comment by maverick74** [comment]
Thanks! :)

Since the change for 1.0.81 that they don't work and I've been waiting for a fix for them. :)

Hope it'll be easy

**Comment by maverick74** [comment]
@Adonai This still doesn't work.

I see the fix has been merged but has it been released?

**Comment by Adonai** [comment]
@maverick74 no, it hasn't been released yet. WIl be there in 1.0.83

**Comment by maverick74** [comment]
Any ETA?

**Comment by Adonai** [comment]
No idea, release cadence of the player itself is in hands of Adrian

**Comment by adrian-bl** [comment]
I uploaded 1.0.83 to the beta track in the play store and pushed a tag, so it should show up soonish on f-droid.
