### ISSUE TITLE
[Feature Request] Long press headset control play/pause button (3000ms) to delete current track

### ISSUE THREAD

**Issue by anaggh** [vanilla-music/vanilla#900]
- Vanilla Music Version (Settings -> About): 1.0.80
- Android Version: 9
- Phone vendor / model: OnePlus 6
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

Currently long pressing goes to the previous track. Could we have a "Miscellaneous feature" to change it to delete the current track instead.

**Comment by adrian-bl** [comment]
Thanks for the suggestion, but i don't think that we should allow the deletion of files using the headset button.
