### ISSUE TITLE
update

### ISSUE THREAD

**Issue by M1Aston** [vanilla-music/vanilla#906]
1.0.81
Android 8
Xperia X
f-Droid

This version still has problems updating the file list at app launch. Files that were deleted ""outside"" the app still show up. Oddly enough, using the ""Start Scan"" menu option works perfectly well, so I don't understand why it can do a reliable scan at start up.

**Comment by adrian-bl** [comment]
Whatever you use to delete this files fails to notify the operating system, so vanilla wouldn't know about it.
