### ISSUE TITLE
Android 4.0 support at Play store / disable updates

### ISSUE THREAD

**Issue by anahuj** [vanilla-music/vanilla#907]
Play store has planned dropping Android 4.0 support. When the drop goes on, Android 4.0 support requires separate installation package. Maybe not worth the effort.

So, please make sure automatic updates does not delete the last working version for Android 4.0 from my mobile phone.

I'm puzzling if the update first deletes the Vanilla Music, and then does not install the new version because Android 4.0 is not anymore supported. Anyway, please think before applying updates: some updates have broken software in my PC - VLC Media Player, Origin, GOG. For example.

**Comment by kirbyfan64** [comment]
Wouldn't you simply never get the update?

**Comment by adrian-bl** [comment]
Thats not what is happening: Google will stop supporting the play store on 4.0.

That means that at some point the store will stop working and you wont get any updates.
