### ISSUE TITLE
File browser should support play all

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#909]
Unlike views using the MediaAdapter, the file view does not support 'Play All' - but should.

**Comment by adrian-bl** [comment]
Fixed via https://github.com/vanilla-music/vanilla/commit/e312d41874262bdcafc948d058f6d5786984d7f5

**Comment by andiandi13** [comment]
I don't get it. Does it mean that now we can play all non-indexed files in file tab ?

I still got the "0 tracks playing" popup with the last nightly

**Comment by adrian-bl** [comment]
Long-pressing a file now shows the 'Play All' option like we do for other views.

Files still need to be indexed.

**Comment by andiandi13** [comment]
Oh I see. Alright :)
