### ISSUE TITLE
BASTP chokes on some mp3 files

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#911]
1. Please take a moment to check if the same Bug has already been reported.
2. Please use our subreddit for general questions: https://www.reddit.com/r/vanillamusic/
3. Please provide all relevant information below.

**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About): **Today's build from master branch**
- Android Version: 9 (Pie)
- Phone vendor / model: OnePlus 6 (enchilada)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [x] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description
Looks like BASTP is broken on master. Many files don't get parsed.
Stable version from F-Droid shows all these files correctly.

## Screenshot / Video (If applicable)

Vanilla

![screenshot_20190214-001122](https://user-images.githubusercontent.com/863272/52744364-95e3ce00-2fed-11e9-8ed7-529f2fcb6e0e.jpg)

Tag Editor shows it ok:

![screenshot_20190214-001132](https://user-images.githubusercontent.com/863272/52744367-99775500-2fed-11e9-96fa-6c9e5c3c69ec.jpg)

**Comment by adrian-bl** [comment]
Interesting: i didnt touch the tag parsing code since the last release.

Is this for *all* mp3 files on the device?

**Comment by Adonai** [comment]
No, more like 5-10% of all. Should I attach sample file that wasn't parsed?

**Comment by adrian-bl** [comment]
Just mail me a sample to adrian@blinkenlights.ch

**Comment by Adonai** [comment]
Sent

**Comment by adrian-bl** [comment]
Thanks for the sample: This file contains an 'extended header'.

Bastp never supported this, so if vanilla previously was able to read the file, the extended header either wasn't there (yet) - or your media framework was able to extract the tags. (Which works on my device running LOS16, but doesn't seem to be the case with the (current?) firmware you are running).

Anyway: Looking at the spec, it is safe to just skip over the header which i implemented in https://github.com/adrian-bl/bastp/commit/4ca495f763bdcf82a9814f6367909a8d3eb24467

With this commit, bastp is able to read the tags of the sample file:

```
<FILE> t/09 - Fortress.mp3
<_hdrlen> = 76132
<duration> = 236
<ARTIST> = [Rage]
<ALBUM> = [End of All Days (Remaster)]
<TITLE> = [Fortress]
<TRACKNUMBER> = [09]
<GENRE> = [137]
<COMPOSER> = [Peter Wagner]
<type> = MP3/ID3v2
```
