### ISSUE TITLE
Support m3u relative paths

### ISSUE THREAD

**Issue by petko10** [vanilla-music/vanilla#917]
It's been mentioned in the discussion of #643 and I'll try to implement it. I just need some pointers as to where the m3u import/export happens and what to watch out for.

**Comment by Adonai** [comment]
It's here:

https://github.com/vanilla-music/vanilla/blob/9f65fb3f8418149208d3b9d31b2df6cf9d29d63f/app/src/main/java/ch/blinkenlights/android/vanilla/PlaylistObserver.java#L304

**Comment by petko10** [comment]
Wow, someone actually implemented that already, it's just not gotten to the store version yet, #908 . FOSS is amazing.
