### ISSUE TITLE
Add an option to sort the library by album artist

### ISSUE THREAD

**Issue by sbraz** [vanilla-music/vanilla#92]
Hi, it would be great if you could add an option to group albums by album artist instead of grouping them by artist on the first tab. This is useful when a library contains many compilations or soundtracks containing tracks from different artists.

**Comment by PanderMusubi** [comment]
So, lets create a feature request at Android to have this information made available in its API. Who has experience with creating such issue?

**Comment by rejhgadellaa** [comment]
Well there is a good chance you'll get the usual "works as intended" or similar answer from Google but it's worth a shot, I guess. 

Also, it will take quite some time for this feature to roll out to a significant user base. Like 1yr after a release for 10℅ of active devices if the past is any indication

**Comment by PanderMusubi** [comment]
You have also a url where to create feature requests for Android?

**Comment by PanderMusubi** [comment]
If I am not mistaken, this is supported by media scanner, see https://android.googlesource.com/platform/frameworks/base/+/master/media/java/android/media/MediaScanner.java#658 Can someone confirm this please that it can be read from within Vanilla Music?

**Comment by adrian-bl** [comment]
Please see: https://developer.android.com/reference/android/provider/MediaStore.Audio.AudioColumns.html

**Comment by PanderMusubi** [comment]
Okay, reported bug for Android at https://code.google.com/p/android/issues/detail?id=221203 Please, give a _star_ to this issue.
