### ISSUE TITLE
Requested language not added

### ISSUE THREAD

**Issue by jony0008** [vanilla-music/vanilla#920]
I have requested Swedish on Transifex a while ago. Please add it so that it can be translated. Thanks.

**Comment by adrian-bl** [comment]
I really hate the transifex UI: Found your request and accepted it - sorry for the delay!

**Comment by jony0008** [comment]
@adrian-bl Please also accept my request to join the Swedish team on Transifex

**Comment by adrian-bl** [comment]
done

**Comment by jony0008** [comment]
@adrian-bl I have translated the strings. Please merge them.
