### ISSUE TITLE
[META] Milestones?

### ISSUE THREAD

**Issue by Adonai** [vanilla-music/vanilla#927]
Hi @adrian-bl, GitHub has Milestones that issues can be assigned to, can we adopt this? I think it'd be nice for us to see what features are you working on and what is planned for the future.

@kirbyfan64 and @andiandi13 have been waiting for some features for months, this would also help to roughly estimate when some specific feature will be done.

What do you think?

**Comment by Adonai** [comment]
I found some old milestones here: https://github.com/vanilla-music/vanilla/milestones

Any word on why were they abandoned?

**Comment by adrian-bl** [comment]
No special reason: I kind of just stopped doing this, mostly because i didn't have too much time to work on vanilla anyway recently.

Happy to start using milestones again.

**Comment by Adonai** [comment]
Glad to hear that! I kind of have some debts with file change detection, so I'll chime in from time to time too.
