### ISSUE TITLE
Don't add songs from start of album to queue when playing from middle of album

### ISSUE THREAD

**Issue by n-o-o-b** [vanilla-music/vanilla#937]
If I press, say, track 8 of an album, it doesn't just add the tracks after track 8 to the queue, it also adds tracks 1-7. This didn't used to be the case. If you are not going to change this as default behaviour could you please at least add an option to change it to how it used to be.

- Vanilla Music Version (Settings -> About):1.0.81
- Android Version: 8.0
- Phone vendor / model: LG G6
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

**Comment by adrian-bl** [comment]
Not sure why you think that this behaviour is new: Thats how Vanilla works since forever - and thats how it is supposed to work.

**Comment by n-o-o-b** [comment]
Will you consider adding an option to customise this behaviour?
