### ISSUE TITLE
How to auto-add songs to Playlist when MP3 added to corresponding folder?

### ISSUE THREAD

**Issue by pstein** [vanilla-music/vanilla#939]
I setup Vanilla App so that each Playlist contains all songs of a certain folder.

E.g. playlist "plaaa" contains all files form folder \data\mp3\aaa\

In playlist "plaaa" I just change the order of the songs.

Now when I add a *.mp3 file to that folder "aaa" I want Vanilla to AUTOMATICALLY add the new files to the end of the playlist "plaaa"

How can I achieve this?

Similarly when I remove a mp3 file from folder Vanilla App should AUTOMATICALLY remove it from playlists.

The song order of all remaining MP3 should be kept!

If this is currently not possibe:
Can this feature be added?

Peter

**Comment by adrian-bl** [comment]
Automatically adding files to a playlist is not supported.

Vanilla will drop removed files from the playlist once the media scanner notices that they are gone.

**Comment by pstein** [comment]
> Automatically adding files to a playlist is not supported.

Hmm, thats pity.
Can you add this feature?

**Comment by adrian-bl** [comment]
Vanilla Music is open source: feel free to send me a patch
