### ISSUE TITLE
How to export/backup all playlists to file?

### ISSUE THREAD

**Issue by pstein** [vanilla-music/vanilla#940]
Assume I setup 5 or more playlists in Vanilla App.

How can I export/backup all the playlists to one ore more backup files?
I want to copy them to WinPC over USB connection.

Where are the Vanilla playlists originally exactly stored in Android?

Peter

**Comment by refi64** [comment]
There's an option in the settings to sync playlists to the SD card.

**Comment by pstein** [comment]
Is it possible to sync it with file in "normal" Android SmartPhone memory?
