### ISSUE TITLE
Hide "<No Album>"  text  (and/or (if present) album information) in Playlists/Track lists

### ISSUE THREAD

**Issue by pstein** [vanilla-music/vanilla#941]
I remove almost all album info from my MP3s.
Nevertheless "<No album>" is always displayed in Playlists and Tracks tab.

Vanilla App should AUTOMATICALLY hide the text string "<No album>" if no album info exists.
This way the artist/interpret could be display completely.

Even better: Vanilla App should introduce an  option to let the user ALWAYS hide the album info (regardless if album filled is filled or empty).

Thank you
Peter

**Comment by adrian-bl** [comment]
> Vanilla App should AUTOMATICALLY hide the text string "" if no album info exists.

Sorry, i don't understand this report: What do you mean with '""' ?
Are you saying that your files are not tagged? How would vanilla figure out the album of such a file?

**Comment by pstein** [comment]
Sorry, github forum software interpreted the tag between the double quotes as HTML and omitted it.

I meant:  "&lt;No Album&gt;"

(hope this time it will be displayed)

All my files ARE tagged but the album field is empty.
So I don't want to see the album info in Vanilla as well.

**Comment by adrian-bl** [comment]
I don't think that vanilla should hide the album (if empty) in all possible UI elements.

So closing as wontfix.
