### ISSUE TITLE
PlaylistObserver.sendUniqueMessage() order of operations bug in message fingerprint creation

### ISSUE THREAD

**Issue by withthelove** [vanilla-music/vanilla#942]
**You MUST delete the content above including this line before posting, otherwise your issue may be closed as 'invalid'.**

- Vanilla Music Version (Settings -> About):
1.0.82
- Android Version:
any
- Phone vendor / model:
any
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [ ] F-Droid
  - [x ] Other (Nightly Build)
Built from source retrieved from GitHub.
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

PlaylistObserver.java, line 291

private void sendUniqueMessage(int type, Object obj) {
		int fprint = type << 10 + obj.hashCode();
...

fprint is used as the 'unique' fingerprint for each message.  Messages with matching fingerprints in the msgDedupe array are discarded.

I believe the intent of this code is to shift type by 10 bits and then add it to obj.hashCode().  This would produce a quasi-unique value for each message.

However, in Java the operator '+' takes precedence over the '<<' operator (see https://introcs.cs.princeton.edu/java/11precedence/).  So the result of this code is that 10 is added to the obj.hashCode and then type is shifted the resultant number of bits, that is fprint = type << (10 + obj.hashCode()).  

Since the fprint is a 32-bit int, this makes for only 32 possible unique message finger prints.  The net result is that numerous unique messages are erroneously discarded.

I discovered this bug when I tried to import a collection of 500+ playlists and noticed that every run of PlaylistObserver.fullSyncScan() would never result in more than 32 playlists being imported (sometimes fewer were imported).  Tossing some extra log messages in around sendUniqueMessage() confirmed that no more than 32 MSG_IMPORT_M3U messages were ever identified as 'unique' despite the accompanying filenames being unique.

Simple fix is to add parenthesis like such:

		int fprint = (type << 10) + obj.hashCode();

However, it seems likely this method would also produce collisions.
Better solution might be to use a 2D array for the msgDedupe array, with the first index being the message type and 2nd being the fingerprint.  This would at least dedicate the full 32 bits of the fingerprint to the message contents.   To ensure no collisions, the unique fingerprint should probably just be the actual string filename for MSG_IMPORT_M3U type messages.
I'd be happy to implement either of these solutions and submit a patch.

....

## Steps to reproduce the issue
Attempt to import more than 32 playlists.

...

## Screenshot / Video (If applicable)

...

**Comment by adrian-bl** [comment]
Thanks: great catch and great bug report!

I fixed the shifting via 6ab52195b5dd01d3808c4421925f611fb9c58c43, i think that should be sufficient for now: While this still has the potential to hit collisions, the likelihood should be rather small in practice.

**Comment by withthelove** [comment]
No problem.
I can confirm that adding the parenthesis as in 6ab5219 resulted in all 502 of my playlists being loaded without any collisions.  Also since playlists ignored due to collisions are picked up again on subsequent scan(s), just adding the parenthesis does seem like a reasonable 'simplest possible change' solution.
Love the app, thanks for all your hard work on it!
