### ISSUE TITLE
Unable to make playlist from excluded scan folders

### ISSUE THREAD

**Issue by InstallGentoo11** [vanilla-music/vanilla#944]
- Vanilla Music Version (Settings -> About):
- Android Version: 1.0.81
- Phone vendor / model: Tried several phones - Huawai, Nokia, Motorola, Lenovo. Two of them brand new with newest Android, the other two older.
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

You can't add to playlists songs from folder excluded from scanning. Would be nice if you can.

**Comment by andiandi13** [comment]
It's totally normal, excluded songs aren't stored into Vanilla's library so you can't do actions like add to playlist, play all, add to queue etc...

**Comment by InstallGentoo11** [comment]
To be more exact it can't from neutral folders either. But doesn't it make sense to have playlists of songs or others that you don't want in the tracks tab?

**Comment by adrian-bl** [comment]
Playlists can only include tracks which are part of the media library.

> To be more exact it can't from neutral folders either.

A 'neutral' folder inherits from the parent: If the parent folders are not included in the scanner, a neutral folder won't be included either.

> But doesn't it make sense to have playlists of songs or others that you don't want in the tracks tab?

No, i don't think it does: A playlist is a part of your music library - that's just how vanilla is supposed to work.
