### ISSUE TITLE
Ogg indices support

### ISSUE THREAD

**Issue by hamakei** [vanilla-music/vanilla#945]
It would be nice if Vanilla Music supported Ogg indices correctly. They are often used to create "subsongs" for albums, kind of like an embedded CUE sheet, but just with "chapter marks"

VM plays the file, but always stops after the first song in the file, no matter how much content there is.

**Comment by hamakei** [comment]
Sorry.. It seems the correct term for what I have is a "chained stream Ogg", which is literally multiple Ogg files concatenated together.

This was apparently the de facto standard for a long time before vorbis chapter marks became a thing.. And apparently almost nobody supports them.

Chained Ogg files can be played correctly, but it requires the player to scan the file before playback to determine the length, breakpoints and metadata

**Comment by adrian-bl** [comment]
Thanks, but i really don't think that we should support that feature.

Ogg indices seems mostly to be a hack for non-streamed files: Vanilla music (and ogg) supports gapless support, so you'd rather split up the files.
