### ISSUE TITLE
[FR] Add option for m3u playlist sync to use relative paths

### ISSUE THREAD

**Issue by gappleto97** [vanilla-music/vanilla#948]
My current workflow is to sync a folder on my devices using SyncThing. This means that I have a directory tree that looks like

- Music
  - Artist1
  - etc
  - Playlists
    - filename.m3u

What would be great is if the playlist sync would save such that all paths were relative to the playlist file. Then Clementine and Rythmbox would also understand the playlists, as it would not reference Android-specific directory structures.

This was brought up during the initial implementation, and at the time it was said that it would be a relatively simple change, but I forgot to file a ticket at the time to track that separately.

**Comment by adrian-bl** [comment]
The latest version (1.0.83) has an option to use relative paths

**Comment by gappleto97** [comment]
Oh hey, what do you know! I never saw it in the changelog, so I didnt realize. Thank you!

**Comment by adrian-bl** [comment]
Oops: looks like i forgot to mention it :)
