### ISSUE TITLE
"Clear queue" doesn't behave as intended

### ISSUE THREAD

**Issue by psyren89** [vanilla-music/vanilla#95]
When in the Now Playing screen, if I select "Clear queue", it only clears items after the currently selected item.
For example, if my playlist is 20 items, and I am on item 15, selecting "Clear queue" will set the queue size to be 15. If I move back to item 5 and select "Clear queue", it will set the queue size to 5.

**Comment by Allanitomwesh** [comment]
I have this issue as well. Clear queue does not clear the whole queue

**Comment by adrian-bl** [comment]
Closing as dup of #149
