### ISSUE TITLE
Equalizer option shows nothing [Vanilla music version ]1.0.83

### ISSUE THREAD

**Issue by chrisbarth01** [vanilla-music/vanilla#951]
**Expected behavior**
- I expected the equalizer option to open an equalizer so I can fine-tune the music to my taste

---

**Actual behavior**
- The equalizer option opens nothing but a blank page

---

**How to reproduce**
- Download and install the latest version of the Vanilla Music app
- Launch the app
- Wait for your tracks to load then click on the 3 vertically arranged dots at the bottom of the screen 
- Select 'Settings' among the pop up options
- Select 'Audio' (the first option)
- Select 'Equaliser' (the first option) 
- See error

---

- App Version: 1.0.83
- Device: Gionee f100s 
- Operating System: 6.0

---

**Recording of the bug**
https://youtu.be/p-LsSyFftvg

**Comment by adrian-bl** [comment]
Your phone lacks an builtin equalizer.

Also note that i consider anything related to utopian / busy.org spam.

**Comment by chrisbarth01** [comment]
I'll take the first sentence..... I didn't ask you what you think of utopian / busy.org.

**Comment by adrian-bl** [comment]
Neither did i ask you to spam github.
