### ISSUE TITLE
Opus Gain with replaygain seems broken

### ISSUE THREAD

**Issue by david-sawatzke** [vanilla-music/vanilla#952]
- Vanilla Music Version (Settings -> About): 1.0.82
- Android Version: Android 8.1.0 (LineageOS 15.1)
- Phone vendor / model: Xiaomi Redmi Note 5
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

Some opus audio files have completely different volume, when compared to foobar2k (with replaygain calculated by [r128gain](https://github.com/desbma/r128gain)). I think it may have something to do with opus header gain, maybe it gets applied twice.

Unfortunately i haven't been able to find a player that 
## Steps to reproduce the issue

With track replaygain activated, play both attached audio files (gpg passphrase "opustest") in vanilla music and foobar2k. While they have the same loudness in f2k, in vanilla audio `03 - Saisyuu Ressya Ha 25 Ju.opu` is barely audible when compared to `12 - Hörma!.opus`.

[testaudio.tar.gpg.txt](https://github.com/vanilla-music/vanilla/files/3125079/testaudio.tar.gpg.txt)
## Opusinfo
```
$ opusinfo *
Processing file "03 - Saisyuu Ressya Ha 25 Ju.opus"...

New logical stream (#1, serial: 76eb0c3f): type opus
Encoded with libopus 1.2.1
User comments section follows...
	ALBUM=Koibito e
	ARTIST=Lamp
	TITLE=Saisyuu Ressya Ha 25 Ju
	TRACKNUMBER=3
	R128_ALBUM_GAIN=-77
	R128_TRACK_GAIN=-179
Opus stream 1:
	Pre-skip: 312
	Playback gain: -15.8008 dB
	Channels: 2
	Original sample rate: 44100 Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:   1000.0ms (max),  999.5ms (avg),  860.0ms (min)
	Total data length: 3360814 bytes (overhead: 0.841%)
	Playback length: 4m:23.839s
	Average bitrate: 101.9 kbit/s, w/o overhead: 101 kbit/s
Logical stream 1 ended
Processing file "12 - Hörma!.opus"...

New logical stream (#1, serial: 14d63f19): type opus
Encoded with libopus 1.3, libopusenc 0.2.1
User comments section follows...
	ALBUM=Vom Vintage Verweht
	ARTIST=Dendemann
	TITLE=Hörma!
	TRACKNUMBER=12
	R128_ALBUM_GAIN=-3891
	R128_TRACK_GAIN=-3610
Opus stream 1:
	Pre-skip: 312
	Playback gain: 0 dB
	Channels: 2
	Original sample rate: 44100 Hz
	Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	Page duration:   1000.0ms (max),  996.7ms (avg),  300.0ms (min)
	Total data length: 2531642 bytes (overhead: 0.76%)
	Playback length: 3m:30.280s
	Average bitrate: 96.32 kbit/s, w/o overhead: 95.58 kbit/s
Logical stream 1 ended
```

**Comment by david-sawatzke** [comment]
Enabeling replaygain really seems to apply the output gain twice.

According to opusinfo, R128_TRACK_GAIN of is `03 - Saisyuu Ressya Ha 25 Ju.opus` (if i didn't make a mistake while converting Q7.8) -0.6 dB, so enabling replaygain shouldn't make much of a difference, but in vanilla music it does decrease the volume by a lot.

**Comment by david-sawatzke** [comment]
So, according to https://github.com/vanilla-music/vanilla/issues/245#issuecomment-167294449 there shouldn't be a need for vanilla music to do anything with the output gain, but [here](https://github.com/vanilla-music/vanilla/blob/11dde262ee13b572391852ff72f8d38668dca829/app/src/main/java/ch/blinkenlights/bastp/OpusFile.java#L68) it's added to the replay gain. 

If android does apply the output gain, it's applied twice and if android doesn't, the output gain is only applied with replay gain (afaict), which is also wrong.

**Comment by adrian-bl** [comment]
Yes, that behavior is indeed broken.

https://github.com/vanilla-music/vanilla/commit/c57d256a1c37eaf566d5845bdbf5762332b3b98e should make things better (still need to test it on a real device)

**Comment by david-sawatzke** [comment]
Thanks, seems to work in the latest nightly (although i needed to turn down the ReplayGain pre-amp a bit to make it completely adjusted). 

I'm not sure why songs with only opus gain are handled the same way as ones with replay gain, since the opus gain doesn't mean it's adjusted to anything. Ignoring "R128_BASTP_BASE_GAIN" completely seems like the "proper" thing to do.

**Comment by Ceremony64** [comment]
I tried the latest build at http://android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk but my opus files are still a lot quieter compared to different encodes with identical replay gain.

Here is a collection of Flac, MP3, OGG Vorbis and Opus for testing with a fixed track gain of -10db written with foobar2000: https://storage.superconnected.org/random/ReplayGain.zip (14.5MiB)
Source: https://archive.org/details/mmm016
