### ISSUE TITLE
Vanilla Music keeps playing while calling with Signal Private Messenger

### ISSUE THREAD

**Issue by breversa** [vanilla-music/vanilla#953]
- Vanilla Music Version (Settings -> About): 1.0.83 Released 2019-04-21
- Android Version: 8.1.0 (LineageOS 15.1)
- Phone vendor / model: LG G4 H815
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
For privacy reasons, I've been using Signal Private Messenger to make calls.
Hoewever, Vanilla Music keeps playing while calling with Signal Private Messenger, while it pauses when calling with Android's default dialer app.

## Steps to reproduce the issue
1. Install Vanilla Music
2. Install Signal Private Messenger
3. Play music using Vanilla Music
4. Make a call using Signal Private Messenger
-> Vanilla Music pauses for a fraction of a second, then keeps playing while the call is being established, and also once it is established.
Workaround : pause the music before making the call.

## Screenshot / Video (If applicable)
N/A

**Comment by mindforger** [comment]
i noticed that too with telegram, but i did not test if the default music app on my phone does the same

i am only rarely using the messsenger to call somebody

**Comment by adrian-bl** [comment]
Does that work with any other app? (VLC?)

Pretty much sounds like Signal fails to claim the audio focus

**Comment by mindforger** [comment]
Just tested the preinstalled Player on my zte axion 7 mini, it does stop, vanilla wont

**Comment by adrian-bl** [comment]
Ok, thanks for testing:

Could someone get a logcat while this is happening?

* Run 'adb logcat | grep "audio focus change:"'
* Play music in Vanilla Music
* Get a call from Signal / Telegram

Looking at the code in PlaybackService.java:2222, i don't really see what could go wrong, unless we miss some focus case.

**Comment by breversa** [comment]
This issue popped up again yesterday, and while I couldn' grab a log at that time, here are some more info :
- I had an audio plug in the headphone jack.
- The music actually kept playing while the call was being established. I paused it before the call was established, but I'm pretty sure it should have paused before already.

**Comment by breversa** [comment]
I haven't noticed the problematic behaviour for a while now. I'll close this issue for now.
