### ISSUE TITLE
Use ALBUMARTIST tag instead of ARTIST for sorting library

### ISSUE THREAD

**Issue by sylvainsab** [vanilla-music/vanilla#954]
- Vanilla 1.0.83
- Android 9 Pie
- Phone Sony Xperia XZ2 Compact
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

Albums constituted by tracks of various artists render the Artist view in the library bloated/over-loaded with multiple artists. This is unpractical for a library with compilations, movie soundtracks albums, etc.

Seems more or less a duplicate of :
#950
#953 
#801 
#742 
#663 
#652

## Steps to reproduce the issue

Have in your library an album such as a compilation/collaboration, soundtrack, etc.
Setting the ALBUMARTIST and ALBUMARTISTSORT tag to "Various Artists" (in my language "Artistes Divers") does not change the behavior.

## Screenshot / Video (If applicable)

![Screenshot_20190504-163529](https://user-images.githubusercontent.com/34339895/57180583-6b860c00-6e8a-11e9-843e-f0e826c7bb7f.png)

**Comment by adrian-bl** [comment]
Sounds like enabling the album artist tab in Settings > Library > Tab Order would do what you want to do?

**Comment by sylvainsab** [comment]
Indeed it seems it would.

I thought I had gone over such a simple parameter long ago, so I didn't bother to check it. Apologies.
Now that I remember though, the reason why I put "Artiste" instead of "Artiste de l'Album" was that the latter has such a long name that it hides the other sections on my small-sized screen.

I use the following tabs :
Genres | Artist (or Album Artist) | Albums | Tracks | Files

I can still swipe the screen, but I prefer to click especially while searching for tracks.
