### ISSUE TITLE
Enquening directory with .flac files inside results in "0 tracks enqueued."

### ISSUE THREAD

**Issue by Chewie9999** [vanilla-music/vanilla#956]
- Vanilla Music Version (Settings -> About): 1.0.83
- Android Version: 6.0.1
- Phone vendor / model: FairPhone 2
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] NA / Don't know. - This is the first time I've tried playing .flac files.

## Description

When enqueuing directories containing certain .flac files, no files are added to the queue.

## Steps to reproduce the issue

Go to the "Files" tab, select an album directory containing .flac files.
Either tap "Enqueue all" at the top of the list when in a directory, or long-press on the directory and select "Play", "Play all", "Play next" or "Enqueue".
With directories containing just mp3 files, the files are added to the queue.
With all the .flac files I have bought through bandcamp, it results in "0 tracks enqueued."
However, the files are valid, as if I go into the directory and long-press on each .flac file in turn and select one of the choices, the files are added to the play list and play successfully.

1 directory of .flac files (unknown origin) does seem to enqueue as expected. These files have cover art, whereas the bandcamp files do not, but not sure if this is significant.

Files can be provided privately if required.

**Comment by adrian-bl** [comment]
That has nothing to do with .flac: the files were just not picked up by the media scanner (because android is pretty buggy when it comes to broadcasting such changes to applications).

You can solve this by running a manual rescan:

Settings -> Media Library -> Tick the 'full scan' checkbox and start the scan.

**Comment by Z3NOX** [comment]
I have the same problem. For me, also the tags for the files in the directory are garbage. Therefore, I don't want to add the folder to the Media Library. Is there a solution playing the files from the directory without adding it to the Media Library?
