### ISSUE TITLE
hello friend, I love your project, I would like to contribute with some documentation, it could be with privacy policies even if you do not take data from users or contribution guidelines, or a small start guide, you could add or remove the information you want, What do you think of my proposal?

### ISSUE THREAD

**Issue by IntenselyMichell** [vanilla-music/vanilla#957]
Hi. I found your project today while I was surfing the internet. It is an incredible project and I am already putting it into use. I praise the incredible work you have done so far. 

I want to contribute to your project by creating some copies. 

For the declaration of the privacy policy, for example this is very necessary for the cases in which the data collection is carried out and to give confidence to the users. I do not think it collects user information when using the software. 

However, I realized that the application has full networking capabilities and things like that always make people skeptical. 

A concise statement of the privacy policy will put an end to all that skepticism, generating more confidence and leaving things clear and thus boosting the use of the application. 

This document could be modified later as many times as necessary, you could also make a guide to contribute to your project, something very basic but well structured or just a small guide to the beginning of the application. 

 You can answer me if you agree on something or all, or if you do not agree I would also like you to write me. 

Greetings.

**Comment by adrian-bl** [comment]
Closing due to spam being spam.

**Comment by IntenselyMichell** [comment]
what madness

**Comment by adrian-bl** [comment]
So how is this not spam?

You opened (almost) the same kind of bug report on various other projects.

You also seem to have never used Vanilla or looked at it: i have no idea why you claim that Vanilla uses/has network access.

**Comment by IntenselyMichell** [comment]
forget it, this is how a project opensource is managed
