### ISSUE TITLE
Feature request: Disable screen rotation

### ISSUE THREAD

**Issue by yaomtc** [vanilla-music/vanilla#959]
- Vanilla Music Version: 1.0.83
- Android Version: 9.0
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

I never use Vanilla in landscape mode, so an option in settings to disable rotation would be useful for me. I sometimes put Vanilla into landscape mode without meaning to, when the accelerometer acts unexpectedly. Is this feasible to implement?

**Comment by adrian-bl** [comment]
I don't think that we should implement this:
Vanilla obeys the system setting for screen rotation: If one wants to disable screen rotation, it can be done on the OS level.

**Comment by M1Aston** [comment]
Well, I agree with the requester. While it can be useful for other apps, landscape mode is awkward for an audio player. Having to change the system settings is not really a good option. 

Why not add this option and let the user decide whatever he or she prefers?
