### ISSUE TITLE
"Removing" from the statistical auto-playlists is ineffective

### ISSUE THREAD

**Issue by ildar** [vanilla-music/vanilla#968]
- Vanilla Music Version (Settings -> About): latest
- Android Version: 7
- Phone vendor / model: BQ
- Application was downloaded from (use `[x]`):
  - [x] F-Droid
- Did this work in a previous version?
  - [x] No

## Description
If I open my _100 top tracks_ playlist and want to reset one track's counter (kicking off the track from the list) I cannot do that. "Removing" is ineffective as the playlist is frequently regenerated.
Please fix.

Optionally: it would be great to improve the PL' presentation. I'd suggest adding the play counter and PL position (e.g. # 1 track is 1 etc.), like a chart.

**Comment by adrian-bl** [comment]
As the setting says: These are auto *generated* playlists - they are not supposed to preserve any of your changes:

Once they are updated, they are regenerated from scratch, that's just how it works.

**Comment by ildar** [comment]
I know. This is exactly what I wrote in the Description, did you read?
The issue is not that it gets regenerated but that UI option "Remove" is
ineffective and misleading. You should either implement different process
for that or completely delete the popup menu option.

**Comment by Adonai** [comment]
I think this needs to be reopened
