### ISSUE TITLE
[enhancement] Add simple ringtone selector for Android setttings, etc.

### ISSUE THREAD

**Issue by MVoloshin** [vanilla-music/vanilla#972]
I think, built-in Vanilla ringtone/track selector for Android settings, upload buttons in other apps (if we need to choose audio files), etc. might be very useful because it can give us an opportunity to completely replace stock music app with Vanilla. I mean activity which can handle audio track selection

**Comment by adrian-bl** [comment]
Sorry, that is not a feature i want to implement.
