### ISSUE TITLE
Selected performer is not taken into account if <No album> is chosen after that

### ISSUE THREAD

**Issue by MVoloshin** [vanilla-music/vanilla#973]
- Vanilla Music Version (Settings -> About): 1.0.83
- Android Version: 6.0
- Phone vendor / model: ZC451TG
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
When I select some performer and then choose an entry with "No Album", performer's name changes automatically for some reason (and I see ALL tracks with no album specified instead of only performer I've chosen). It's uncomfortable for me. For example, if I select Dire Straits and then "no album", I would like to see only Dire Straits tracks with such a tag. 
....

## Steps to reproduce the issue
See video
...

## Screenshot / Video (If applicable)
http://sbornik-obrazov-dlya-bochs-i-qemu.ru/pub/20190724_132258.mp4
...

**Comment by adrian-bl** [comment]
I can see that this is confusing but this is just how things are working:

Vanilla always only filters for the 'last' selected element: If you pick an Album with multiple artists from an artist view (such as 'no artist'), vanilla will only filter for 'no artist'.

The navigation at the bottom then just picks one random artist while displaying an album with multiple artists.
