### ISSUE TITLE
Significant apk size increase

### ISSUE THREAD

**Issue by MVoloshin** [vanilla-music/vanilla#975]
Vanilla_Music_1.0.81.apk was 1,27 МB
Vanilla_Music-1.0.82.apk is already 2,38 МБ (+ 87% !!!)
What could cause such a growth?

**Comment by mindforger** [comment]
just a quick look into the apk file (unzipped) shows a few hints but i have no idea

classes.dex grew 300%
resources.arsc grew 30%
res folder grew 100%
android.sf and manifest.mf grew 120%

according to the changelog a new context menu was added but it also looks like an graphic overhaul with higher res textures

**Comment by Adonai** [comment]
9ce0975d41fb676d0be50393f92a11422ba0b63b

**Comment by adrian-bl** [comment]
As Adonai pointed out: this is due to dependencies.

I avoided some of the for a long time, but have finally given up.
However: 2.38MB is still very small for an Android app in 2019.
