### ISSUE TITLE
[Bug] Vanilla mistakenly reports the format of Ogg Opus files as Ogg Vorbis

### ISSUE THREAD

**Issue by opusforlife2** [vanilla-music/vanilla#992]

**Comment by adrian-bl** [comment]
That's a bug in your firmware: We fetch the media format using

```
https://github.com/vanilla-music/vanilla/blob/master/app/src/main/java/ch/blinkenlights/android/medialibrary/MediaMetadataExtractor.java#L333
```

**Comment by opusforlife2** [comment]
@adrian-bl What does firmware mean here?

Also, I noticed this line just below the one you've linked:
`// ...but we are using bastp for FLAC, OGG and OPUS as it handles them well`
and the code that follows seems to validate this.

So isn't it possible there is a bug in bastp?

**Comment by opusforlife2** [comment]
@adrian-bl I checked on a Nokia 6.1 running Android 10. The format of an opus audio is reported as 'audio/ogg'.

**Comment by opusforlife2** [comment]
@adrian-bl Ping.

**Comment by opusforlife2** [comment]
Also tested on a Pixel 5a with Android 12. That's 3 different phones with the same result.

Both Vorbis and Opus audios are identified as `audio/ogg` in the `format` field.
